### ISSUE TITLE
Lady Palanseer - (12792)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1007]
> The only PvP necklace this NPC currently sells is a caster spell damage one.
`.go xyz 1659.280000 -4194.240000 56.155500 1 1.938540`

> For priest it sells the mage set, not the pvp dps one.
`.go xyz 1659.970000 -4193.880000 56.154400 1 1.610810`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7977 related

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6554
