### ISSUE TITLE
Ribchaser - (14271)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1031]
> Didn't drop anything
`.go xyz -9529.130000 -1909.230000 74.885200 0 2.517110`

> No special loot dropped
`.go xyz -9772.190000 -2271.160000 59.416400 0 5.851230`

> no loot
`.go xyz -9518.900000 -1924.410000 75.784400 0 5.893610`

**Comment by Bennylavaa** [comment]
beta
