### ISSUE TITLE
Snarlflare - (14272)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1032]
> Drops no green item tho it is a rare
`.go xyz -9084.190000 -2494.810000 122.301000 0 5.912920`

> Rare mob no loot
`.go xyz -9080.950000 -2612.540000 126.356000 0 3.232780`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8249

**Comment by Shadownflame** [comment]
Fixed
