### ISSUE TITLE
Boulderheart - (14273)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1033]
> Only dropped some silver
`.go xyz -9403.320000 -3453.940000 95.478600 0 0.225738`

> no drops beside money, also feels like his health is too low
`.go xyz -9498.150000 -3486.030000 122.652000 0 3.615780`

> Health seems too low to every other rare in the area, or their health bars are too big?
`.go xyz -9426.180000 -3465.200000 103.092000 0 0.028836`

> no special loot
`.go xyz -9389.450000 -3454.970000 93.565100 0 2.982010`

> rare no loot
`.go xyz -9526.540000 -3493.390000 126.859000 0 0.421049`

> Didn't drop any loot as a rare spawn.
`.go xyz -9504.390000 -3487.350000 123.387000 0 5.305900`

> No loot other then 64 Copper
`.go xyz -9508.490000 -3491.190000 124.264000 0 0.301554`

**Comment by Bennylavaa** [comment]
on purpose for beta
