### ISSUE TITLE
Olm the Wise - (14343)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1038]
> I can see the mobs level when I'm only level 10.  Seems all avians level are shown in Felwood as Tauren.
`.go xyz 4900.130000 -733.207000 356.388000 1 3.101310`

> is it SUPPOSED to be unattackable? 
curiosity and intrigue have struck...
`.go xyz 5910.520000 -1242.110000 401.285000 1 3.142610`

**Comment by zana244** [comment]
neutral mob, so you can see his level
affiliated with cenarion circle, intended, need to set at war with them to attack it (but you need to have spoken with someone from CC before to have it in rep panel...)
