### ISSUE TITLE
Gilmorian - (14447)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1045]
> any time it gets aggrod it just instantly evades
`.go xyz -10347.400000 -4380.280000 4.892800 0 4.659390`

> evades all the time. My pet can't even target it and run to it.
`.go xyz -10466.600000 -4396.700000 3.815910 0 5.434040`

> no loot
`.go xyz -10298.800000 -4396.100000 0.619038 0 5.304980`

**Comment by zana244** [comment]
solved by SoS coast line fixes and vmangos update
