### ISSUE TITLE
Rippa - (14490)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1053]
> Rippa is walking through the sand underneath the world map.
Reproduce: Stay and wait at the boat containing the bloodsail orders. Paths right beneath you - does not aggro
`.go xyz -14705.800000 454.975000 0.134452 0 4.507630`

> This rare did not drop anything other than a gray when killed.
`.go xyz -14403.000000 455.098000 -1.786740 0 4.100800`

> This mob patrols into terrain and cannot be interacted with.
`.go xyz -14664.300000 569.069000 -9.782170 0 4.190440`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by zana244** [comment]
Confirmed on internal. The loot was solved by the vmangos loot update.
However, it paths through the sand where the bloodsail pirates are and it evades if you try to pull it.
