### ISSUE TITLE
Verifonix - (14492)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1055]
> This rare mob didn't drop any loot other than 1 silver, 16 copper and 2x mageweave cloth. Not sure if intended.
`.go xyz -13563.600000 -16.720000 49.041300 0 0.524333`

> 2 of this rare mob were spawned in at the same time, i just killed both
`.go xyz -13525.900000 -85.556000 41.862300 0 5.091050`

**Comment by Bennylavaa** [comment]
has loot is only spawned once.
