### ISSUE TITLE
Artorius the Amiable - (14531)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1057]
> Categorized as Demon? Spoiler or error?
`.go xyz 7485.750000 -4760.240000 666.418000 1 5.399940`

> After talking to this NPC he stopped his route. He's still in the same place after >5 minutes.
`.go xyz 7570.120000 -4415.340000 604.140000 1 1.693150`

> shouldn't be a demon in his humanoid form
`.go xyz 7351.910000 -4565.190000 591.103000 1 5.699520`

**Comment by zana244** [comment]
https://www.wowhead.com/classic/npc=14531/artorius-the-amiable
the speaking to NPCs definitely is wonky, it feels like an eternity, but they start moving after some time...
