### ISSUE TITLE
Vilebranch Kidnapper - (14748)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1064]
> Not despawning from the previous quests
`.go xyz 404.518000 -4786.280000 12.080600 0 4.939470`

> They do not despawn
`.go xyz 405.948000 -4786.270000 12.042900 0 5.135810`

> Many many quest mobs stack in 1 and one shot every hero
`.go xyz 391.116000 -4792.490000 5.070700 0 5.844100`

> dont despawns
`.go xyz 401.205000 -4829.330000 8.555090 0 0.911725`

**Comment by zana244** [comment]
#7971
