### ISSUE TITLE
Inspector Tarem - (23567)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1073]
> Hoofprints do not appear to give a quest, I am level 34, quest should be level 30.
`.go xyz -3702.260000 -2534.230000 68.744600 1 5.483170`

> Nothing seems to happen once he spreads the reflective dust in the quest ... the 3 areas get highlighted but then nothing further? They are not interactable
`.go xyz -3701.190000 -2535.760000 69.028900 1 3.588960`

> The "Suspicious footprints" don't get revealed. One quest is missing
`.go xyz -3703.200000 -2518.300000 68.806400 1 4.507980`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2424
