### ISSUE TITLE
Aponi Brightmane

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1096]
> In the first Tauren Racial Knowledge quest chain called "Aponi's Request", I went to this NPC to start it. But I couldn't
`.go xyz -1054.560000 -299.343000 159.030000 1 5.073490`

> The night elf racial quest "Aponi's Request" doesnt work as a tauren, aponi has no turn in or dialogue that completes the quests objective.
`.go xyz -1057.560000 -297.254000 159.030000 1 5.006700`

> Upon accepting Aponi's Request(as an undead), we are supposed to talk to her. The only option selectable on her is "Who is An'she?", which doesn't really resolve the quest. As such, at the moment, APoni's Request is unable to be completed.
`.go xyz -1053.520000 -300.636000 159.030000 1 5.181880`

> cannot interactr with her for the quest Aponi's Request
`.go xyz -1051.990000 -300.216000 159.030000 1 4.684740`

> Can't turn in quest "Aponis's Request" to NPC
`.go xyz -1054.770000 -298.496000 159.030000 1 4.592880`

> An'she is a male, this npc says he's a female.
`.go xyz -1051.060000 -299.879000 159.030000 1 4.252390`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7711
