### ISSUE TITLE
Matron Darcy

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1098]
> In the starting text of the quest "Spider Elixir", a space is missing after the dot: "fast.I've"

In the last sentence could probably use better punctuation, I suggest:
"And please, [name], if you see any miners, will you release them so they can get to me?"

In the objectives, the name of the item that needs to be looted is usually capitalized in WoW, while in this quest it's not ("spider madibles")
`.go xyz -9488.160000 80.652700 57.016500 0 4.035480`

> Looks like a white and blue cube
`.go xyz -9490.420000 81.977800 57.054500 0 4.604770`

**Comment by zana244** [comment]
#2171
Looks fine to me on internal?
