### ISSUE TITLE
Lorkiz Quietbit

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1104]
> Ths NPC walks up to Marshal Dughan in Goldshire and says "We have been requesting help for weeks Marshal. Please for Azeroth sake send help to the Tower of Azora to hunt the foul beast we accidentally unleashed."

Should put a comma before "Marshal".
More importantly - for Azeroth's* sake, not just Azeroth sake
`.go xyz -9581.070000 -174.398000 57.415200 0 4.410210`

> In the start text of "Wanted: Big Blue":

In the 2nd paragraph there's a typo: master' -> master's

In the last paragraph, "[...] bring it's wing [...]" should be "[...] bring its wing [...]
`.go xyz -9543.560000 166.095000 58.260300 0 4.084790`

> not appearing
`.go xyz -9616.870000 -310.785000 57.622800 0 1.848390`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6642
