### ISSUE TITLE
Mosh'Ogg Warmonger - (709)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#111]
> These mobs are Using their Thunder Clap ablity from farther then normal.
`.go xyz -11910.700000 -848.696000 30.107700 0 0.407156`

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/e06c84a8-520e-427e-94d3-7e3eb0275555)
seems blizlike to me, they use it every 10-12 seconds.
