### ISSUE TITLE
Kul Tiras Admiral

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1125]
> Same issue with their deckhand counterparts, weird pathing and targeting. It may be related to the cannon windows size on the sunken ships as i also notice alot of clunkyness when i try to go in and out of a ship through them.
`.go xyz 19.272700 -5369.020000 -2.324820 1 1.843080`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
