### ISSUE TITLE
Kul Tiras Deckhand

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1126]
> Weird creature pathing and targeting issues
`.go xyz -23.089100 -5223.800000 -2.326190 1 0.256430`

> Pathing is really bad on these mobs
`.go xyz -4.787770 -5241.080000 -1.834330 1 1.286610`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
