### ISSUE TITLE
Wizzle Nimbledigit

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1136]
> Did the assist quest for this guy but after finishing it there was a server disconnect and now I cannot do the q again so I cannot finish the Ironforge Airfiled Quest.
`.go xyz -4705.460000 -1700.390000 503.324000 0 3.521130`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2197
