### ISSUE TITLE
Engineer Cobalt

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1147]
> Ironforge Airfighter he is fixing is missing
`.go xyz -4746.090000 -1641.930000 503.326000 0 5.256730`

> The quest does not seem to work / complete
`.go xyz -4746.960000 -1640.920000 503.333000 0 5.085860`

> The Plane is invisible. Quest wont complete.
`.go xyz -4742.670000 -1646.800000 503.353000 0 1.361090`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1149
