### ISSUE TITLE
Nightbane Tainted One

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1162]
> Quest name: Riders In The Night.

Quest text typo: the name Mardigan is written without capital M. It's the quest that takes you to Rolands Doom cave.
`.go xyz -10371.800000 -1242.450000 29.387500 0 5.135640`

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
