### ISSUE TITLE
Zurka

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1169]
> The rare mob feels like it's an elite mob. Does too much damage and has high HP.
`.go xyz -5258.740000 -109.821000 414.333000 0 5.568730`

> Does to much damage with abilities!
`.go xyz -5226.100000 -79.248700 394.581000 0 0.913513`

**Comment by zana244** [comment]
669 hp at lvl 10, maybe mark him as rare elite and tone down hp a bit. Gives a ring, so maybe it is intended for 2 people to duo at least?
