### ISSUE TITLE
Marsh Inkspewer - (750)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#119]
> pathing is bugged.
`.go xyz -10991.500000 -4047.370000 17.222900 0 4.117950`

> Murlcs pathing is glitched also they evade randomly
`.go xyz -10803.600000 -4198.370000 19.528900 0 2.687190`

> all mobs on the coast evade and dont move/follow/attack
`.go xyz -10865.100000 -4195.640000 5.117620 0 2.531890`

> couple of these are just enough in the ground they evade if not in melee range, or even able to run away when in fear
`.go xyz -10790.500000 -4250.320000 2.631700 0 5.412840`

> Constantly evading
`.go xyz -10696.900000 -4318.330000 -0.018111 0 6.011520`

> all murlocks on coast of swamp of sorrow extremly bugged. when aggro from distance they just evade
`.go xyz -10668.700000 -4293.770000 21.344600 0 5.466820`

**Comment by Bennylavaa** [comment]
This seems fixed.
