### ISSUE TITLE
Stelx

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1203]
> this vendor have Impact Shot which is level 55 bullet from burning crusade, very powerful bullet that stack to 1000 instead of 200.
`.go xyz -6926.790000 -4721.480000 12.429800 1 2.363220`

**Comment by zana244** [comment]
Noooo why did you have to report it.
Confirmed on internal.

**Comment by Bennylavaa** [comment]
This still stacks to 1000 not sure if the fix is testable yet

**Comment by Bennylavaa** [comment]
still stacks to 1000 in your bags, vendor sells in stacks of 200

**Comment by kaytotes** [comment]
A mistake was made, next deploy should actually resolve this and another vendor that was selling em.
