### ISSUE TITLE
Binkle Screwsnip

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1208]
> The quests lines regarding the Shadowforge Excavation sites could use some reworking on how the quests are obtained.

The initial "Excavation Investigation" quest, asks me to go accross the map and back just to initialize the questline with low rewards. 

When picking up "Ore for Gapple" I jumped of the edge of the cliff to get back to the site faster and when I returned to the main entrance, I can just now see that "Binkle's Justice" is now able to be picked up since I completed the first quest
`.go xyz -7054.670000 -3772.680000 310.375000 0 4.031920`

**Comment by Bennylavaa** [comment]
Excavation Investigation is the pre req for both Ore for Gapple and Binkle's Justice. Instead of jumping off cliffs its good to explore the easier traveled route.
