### ISSUE TITLE
Gynna Vaststone

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1216]
> We done all quest's in this zone, but 1 quest reclaiming-the-eggs dosent work, so we left 500 rep to get exalted and there is no other way to get this 500 rep, necklesss quest is not repitable - trolls do not give any rep by killing them etc. I hope there was also a bit leftover quests or ways to get a bit more rep or any other way to get more of this rep would be great
`.go xyz 289.179000 -2007.780000 194.126000 0 5.110760`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
