### ISSUE TITLE
Centaur Devotee

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1219]
> didnt disappear when princess died
`.go xyz 37.043900 66.281500 -125.688000 349 4.759210`

> spawn in too quickly
`.go xyz 54.832600 73.505700 -124.439000 349 3.922050`

**Comment by zana244** [comment]
one every 30 sec, seems ok, they hit quite hard though.
why should they despawn if princess died?

they also seem to despawn after a few min if you wipe
