### ISSUE TITLE
Chunky Grouper

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1223]
> Ãœnable to attack acouple of these fish. the dont evade but you cannot meele attack them
`.go xyz 632.202000 -3492.810000 98.464400 0 4.947340`

> Can't hit the damn thing most of the time. I'd guess it's actually a problem with underwater combat in general.
`.go xyz 491.525000 -3813.060000 113.608000 0 1.228160`

> Correction on my previous bug report on these npcs. Its when I jump while in water they reset, but I also often cant autoattack them.
`.go xyz 477.734000 -3446.130000 98.821900 0 0.804128`

> these mobs far too quickly start evading and regen health. Just had a mob a 10% hp and I hit the move key once, it swam away. Full reset hp and almost killed me.
`.go xyz 518.859000 -3389.030000 102.127000 0 5.234580`

> these mobs evade if u jump in the water
`.go xyz 471.229000 -4007.630000 98.948200 0 1.013080`

> appearently its only when i attack from the ground and not in the water they keep regenerating. sorry for inconvenience if its normal behaviour for these mobs
`.go xyz 516.937000 -3724.670000 95.139600 0 4.526200`

> keeps regenerating hp
`.go xyz 508.174000 -3685.070000 101.951000 0 5.814270`

> If you jump out of water in combat the mob resets. AS a hunter at least. If the pet attacks and you dont they dont engage and constantly reset until you attack it with the hunter not pet
`.go xyz 492.892000 -3957.090000 98.877800 0 0.358835`

> it cant be attackedt .
`.go xyz 536.687000 -3905.050000 100.311000 0 2.377470`

> Resets to full life
`.go xyz 466.840000 -3419.850000 101.416000 0 5.702600`

> Drops aggro and resets if you jump above the surface while in the water.
`.go xyz 477.740000 -3437.030000 98.733100 0 5.596220`

> Huge melee hitbox issues with these mobs while underwater
`.go xyz 430.342000 -4167.730000 98.575800 0 5.417530`

> Takes damage then resets
`.go xyz 474.853000 -4001.320000 98.858100 0 5.288850`

> mob don't agro pet when attacked
`.go xyz 505.829000 -3939.080000 98.438300 0 5.427210`

> Cannot autoattack / Resetting a lot
`.go xyz 497.654000 -3405.340000 103.102000 0 6.011760`

> Stupid hard to fight these things as a melee
`.go xyz 602.461000 -3436.130000 99.120700 0 4.866630`

> The pathing on this guy is a bit janky, not managing to auto-attack him and he re-sets quite often.
`.go xyz 606.778000 -3561.580000 101.571000 0 2.251410`

> if you jump out of the water they reset
`.go xyz 285.287000 -4436.080000 96.991700 0 2.846640`

> After killing these they can not be looted for the Quest
`.go xyz 590.394000 -3542.180000 98.598000 0 5.149640`

> It's not affected by slowing spells like ''slow'' from mage
`.go xyz 507.189000 -3730.010000 98.827300 0 4.159460`

> resets instantly if you jump at the top of the water, needs a short delay
`.go xyz 479.507000 -3437.360000 96.854500 0 6.188220`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
These were improved with the last update.
