### ISSUE TITLE
Foulcrest

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1226]
> Made Imp noises when it died.
`.go xyz -92.465900 -3228.580000 122.539000 0 1.508280`

> Death sound is the same as of murloc's.
`.go xyz -95.743400 -3080.830000 115.231000 0 3.461540`

> imp death sound
`.go xyz -61.329000 -3227.680000 121.714000 0 3.415810`

> This makes the Imp death noise when it dies, not a gryphon.
`.go xyz -70.722400 -3072.570000 121.367000 0 3.122110`

> This mob made imp noises upon death.
`.go xyz -32.224600 -3095.140000 130.043000 0 1.798940`

> Attack animations are not working on this enemy.
`.go xyz -32.224600 -3095.140000 130.043000 0 1.798940`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7960
