### ISSUE TITLE
Shore Shark

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1227]
> Shark bugs out and deaggros when you jump at the top of the water
`.go xyz -6647.820000 -4939.390000 -1.895260 1 4.516070`

> They drop gold)))))
`.go xyz -6833.100000 -5003.090000 -13.981000 1 3.949680`

> There are way too many of these spawned around the shores of Tanaris -  ecologically, they'd hunt prey species to extinction and cause their own extinction from a lack of food ;) Maybe tone 'em down slightly
`.go xyz -6900.820000 -5003.810000 -23.987200 1 6.165270`

> swam under the ground
`.go xyz -6515.320000 -4941.400000 -15.431400 1 0.566958`

> I love that skinning them gives you Shiny Fish Scales. Nice touch, and genuinely nice for my Shaman leveling here.
By the way their armor reduction ability works, but the armor in character sheet doesn't reflect the negatives to it (not red colored, but the number changes)
`.go xyz -7237.680000 -5000.370000 -27.704100 1 2.545560`

> Aggro resets if you surface the water.
`.go xyz -6645.140000 -4870.020000 -1.966340 1 3.174530`

> They are avoiding combat in water. bugged collision ?
`.go xyz -6768.700000 -4877.770000 -2.421470 1 5.022330`

> Shore Sharks are dropping coins
`.go xyz -7148.930000 -4974.500000 -30.406200 1 1.679340`

> The combat sounds from this creature sound odd (not very shark like)
`.go xyz -6768.150000 -4906.250000 -11.839300 1 5.917710`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
