### ISSUE TITLE
Cleanup Crew

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1230]
> not enough car parts
`.go xyz -6948.580000 -3542.720000 33.240000 1 3.126520`

> These guys could use a few guards to protect them from the wildlife. as it is, I see one overlapping with a scorpion.
`.go xyz -7048.620000 -3528.950000 18.536700 1 0.758191`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
