### ISSUE TITLE
Six Gill Shark

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1240]
> Mob constantly evade/resets when engaging, even while fighting in the water.
`.go xyz -10110.600000 -3609.880000 0.535566 1 2.628640`

> Swimming up the cliff
`.go xyz -9578.760000 -4362.410000 -0.555593 1 0.997176`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
