### ISSUE TITLE
Dak'mal

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1255]
> Summons portals, but nothing seems to come out of them?
`.go xyz 153.240000 11.373700 -0.977976 731 4.624670`

> Kinda seems bugged the fight. He just ran into the middle of the room and did nothing.
`.go xyz 150.600000 9.147350 -0.977965 731 6.237830`

> You can polymorph this mob, probably should be immune. When polymorphed, the adjascent mob (his felhunter pet) did not agro.
`.go xyz 157.254000 -46.722500 -0.977946 731 1.550060`

**Comment by Bennylavaa** [comment]
polymorph still seems to work

his portal stuff is fine now though @kaytotes

**Comment by kaytotes** [comment]
Next Deploy.
