### ISSUE TITLE
Luyua Earthmoon

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1260]
> She has an exclamation mark to indicate a quest, but interacting does not give a quest option.
`.go xyz -4445.470000 780.548000 132.808000 1 0.905124`

> this npc seems to have a quest. with quest marker. but it is not dosplayed when talking to her
`.go xyz -4445.850000 779.047000 132.858000 1 0.942221`

> Quest marker is visible but unit does not give quest.
Used to work at the start of the beta
`.go xyz -4444.530000 777.428000 132.708000 1 4.452030`

> after you abandon the quest "freedom for all creatures" this npc still follows you around
`.go xyz -4432.080000 753.303000 125.316000 1 4.940030`

**Comment by Bennylavaa** [comment]
gives me a quest
