### ISSUE TITLE
Moruul

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1266]
> Quest completion dialogue says "I wouldn't do that too" you. That is incorrect. It should say "I wouldn't do that to you".
`.go xyz -10158.700000 -2801.330000 28.843000 0 1.896530`

**Comment by Bennylavaa** [comment]
![image](https://github.com/user-attachments/assets/6813aafa-020a-4498-a16e-ec3a3c6c55f0)
