### ISSUE TITLE
Kurdol Thunderfist

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1267]
> Griffin to this character's location is not available, can only fly from him.
`.go xyz -10098.600000 -2809.180000 61.080100 0 2.157810`

> flight path and map need fixing
`.go xyz -10101.200000 -2799.450000 61.078400 0 3.053990`

> When interacting with this NPC, you do not unlock a new flight path. When pulling up the flying menu, it states that you are currently located in Lakeshire, Redridge.
`.go xyz -10102.200000 -2801.760000 61.080500 0 2.635730`

> lakeshire redridge?  this is the harborage
`.go xyz -10101.600000 -2800.610000 61.080000 0 1.476860`

> cant discover flight point
`.go xyz -10100.800000 -2801.170000 61.080400 0 2.332240`

> This flightpath counts as redridge and doesn'tget discovered on its own
`.go xyz -10102.200000 -2798.930000 61.076200 0 2.683480`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7551
