### ISSUE TITLE
James Corbett

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1272]
> I completed the three quests to learn how to tame pets. At the end I got Tame Beast, Call Pet, and Dismiss Pet. 

The quest also hints that after taming a pet I should feed it immediately.

But I did not get Feed Pet! The trainer also does not offer feed pet at any level, so I'm thinking that something fundamental is broken here...
`.go xyz -9539.750000 35.678500 56.241900 0 3.270100`

**Comment by zana244** [comment]
The follow up quest makes you go to stormwind and will train you feed pet. Works as intended
