### ISSUE TITLE
Foreman Sprocket

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1275]
> Spellstole his "Immune to Fire Spells" buff and he kept hitting me for Fire dmg.
`.go xyz -135.398000 -238.715000 -34.880800 732 5.151560`

**Comment by zana244** [comment]
hmmm he does not hit for fire damage so I could not verify that, but if you spellsteal his buff it should only last 2 minutes. it lasts indefinitely.

**Comment by ghost** [comment]
Intended, the aura falls off when you leave the dungeon. The fire invulnerability is working fine, however one of sprockets attacks is accidentally flagged to ignore immunities. Closing the issue since this is invalid but that bug is still being fixed anyway.
