### ISSUE TITLE
Prismscale

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1279]
> Pathing was questionable. After taking a shortcut to reach me (I pulled it from above/behind) I proceeded to jump down and it kept doing a back and forth without reaching me despite nobody else building aggro.
`.go xyz -158.377000 -87.440400 -32.227000 732 5.099710`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Bennylavaa** [comment]
will mark this as duplicate, I cannot reproduce this though
