### ISSUE TITLE
Tidewater Oracle

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1282]
> not moving in combat
`.go xyz -370.664000 -243.236000 -45.033400 732 5.098640`

> they dont move when target is LoS
`.go xyz -365.032000 -240.177000 -44.253400 732 5.061930`

> May deal a bit too much dmg.
`.go xyz -303.314000 -282.076000 -36.752500 732 5.997280`

**Comment by Bennylavaa** [comment]
seems fixed
