### ISSUE TITLE
Rachael Ray

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1307]
> Currently not allowing training of fishing and first aid. Was able to pick up cooking
`.go xyz -8822.410000 647.378000 94.479200 0 2.144640`

> Learning secondary profession teleports you away from NPC.
`.go xyz -576.314000 -4235.490000 37.917800 1 0.179070`

> Profession boosts don't want to work when using this npc in Stormwind.
`.go xyz -8824.350000 647.306000 94.476900 0 1.342850`

> Broken, won't train proffs
`.go xyz 1619.240000 -4424.720000 13.791400 1 3.025440`

> When using the secondary profession boosts, I get teleported back to the character startpoint.
`.go xyz -8936.440000 -112.282000 82.657900 0 1.244790`

**Comment by Bennylavaa** [comment]
this is beta only why we reporting these.
