### ISSUE TITLE
Stonard Explorer - (862)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#131]
> Weird reaction with crossing water, seems to fall repeatly by teleporting up.
`.go xyz -10146.100000 -4122.140000 22.514100 0 4.344060`

> runs at hyper speed and teleports
`.go xyz -10065.200000 -3497.530000 22.462500 0 5.767530`

> Patrol elevation is above the level of the ground, resulting in jerky, perpetual falling motion as he walks around the Sorrowmurk. This particular Explorer was just west of the coast, north of the small Horde mini-quest hub at the time it was bugging out.
`.go xyz -10312.400000 -4268.060000 17.697200 0 0.302270`

> she jumps when crossing the water
`.go xyz -10111.400000 -4171.940000 19.561700 0 3.404550`

> I aggroed him from 50+ yards and he ran to me in A SECOND
`.go xyz -10067.500000 -3482.350000 22.244400 0 5.312100`

> he flew like 50 yards LMAO
`.go xyz -10067.600000 -3481.780000 22.170100 0 5.316030`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
