### ISSUE TITLE
Blackstone Swashbuckler

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1315]
> Dropped Invader's Scourgestone?
`.go xyz -2385.730000 50.710500 27.558200 0 5.456560`

> Mobs in front of Tol Barad drop silk instead of Runecloth.
`.go xyz -2352.610000 55.283300 28.586300 0 0.154831`

**Comment by zana244** [comment]
Confirmed on internal, they still drop invader's scourgestone but you now need the AD commision trinket to actually view it. But they still drop it.
#8323

**Comment by kaytotes** [comment]
@zana244 Sounds good thanks for confirming conditions carry over now. You'll find some other cases like this where we cloned loot, feel free to keep them open as a dev will revisit key ones like this.

**Comment by kaytotes** [comment]
Fixed on internal.
