### ISSUE TITLE
Tanum

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1325]
> The Fizz - Quest he doesnt provide the item needed to do it
`.go xyz 6421.730000 -4841.180000 716.724000 1 5.482820`

> quest "the Fizz" didnt work correct
`.go xyz 6423.440000 -4845.270000 716.653000 1 2.248030`

> Quest "The Fizz" doesn't give you item to charge.
`.go xyz 6423.010000 -4843.850000 716.579000 1 2.436080`

> Quest: "The Fizz"
No "Electro B.T.L.R. Device" in Inventory received
`.go xyz 6429.440000 -4849.410000 715.119000 1 2.401400`

> The Fizz" quest. Dont give the device.
`.go xyz 6426.650000 -4846.830000 715.956000 1 2.479220`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7599
