### ISSUE TITLE
Ghastly Spectre

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1346]
> These Guys seem to crash the Game. We will test it again later.
`.go xyz 20.631900 -280.507000 -14.543500 731 4.507950`

> Unpredictable 15k aoe with no cast time. :D instakilled
`.go xyz -8.387810 -242.596000 -14.546400 731 2.152630`

**Comment by Bennylavaa** [comment]
No creashes and doesnt do 15k damage on nova.
