### ISSUE TITLE
Daylooj

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1362]
> all it dropped was a corrupted soul  shard (felwood cleansing thing) :((
`.go xyz -7206.610000 -649.417000 -234.614000 1 0.123514`

> This guy dropped a Corrupted Sould Shard. We're not in Felwood.
`.go xyz -7243.530000 -606.016000 -269.210000 1 3.288190`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1582
