### ISSUE TITLE
Splashing Elemental

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1365]
> Dropped a Corrupted Soul Shard? Pretty sure these are meant to only drop in Felwood.
`.go xyz -7291.640000 -783.594000 -270.157000 1 3.593610`

> Drops Corrupted Soul Shards. Something that's supposed to be dropping from mobs in Felwood
`.go xyz -7255.190000 -484.458000 -265.665000 1 4.795810`

> Should be an elemental, not a humanoid.
`.go xyz -7096.320000 -763.715000 -272.049000 1 2.980700`

> Drops Corrupted Soul Shards for Felwood cleansing quests.
`.go xyz -7253.950000 -795.083000 -270.420000 1 1.384600`

> Just barely touching any water INSTANTLY resets these mobs. Very weird.
`.go xyz -7321.000000 -803.135000 -272.248000 1 3.952690`

> These NPCs are labeled as humaniods. Should be elementals.
`.go xyz -7295.690000 -795.187000 -268.882000 1 1.773390`

> Showing as a humanoid not an Elemental
`.go xyz -7149.930000 -761.069000 -271.011000 1 1.772370`

> He is evading when you go into water around Golakka Hot Springs in Un'goro Crater.
`.go xyz -7252.460000 -771.746000 -274.632000 1 4.220710`

> Creature drops "Corrupted Soul Shard", which is a felwood drop meant for cleansing felwood plants
`.go xyz -7240.400000 -791.473000 -272.357000 1 2.901410`

> Marked as Humanoid instead of Elemental
`.go xyz -7246.560000 -570.799000 -272.621000 1 6.171380`

> EVADES A LOT
`.go xyz -7329.910000 -826.532000 -271.528000 1 1.565310`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1364
