### ISSUE TITLE
Marius Hedrin

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1378]
> Model is a Night Elf female using a Human Male texture. Hilarity!
`.go xyz 6689.290000 -4665.980000 721.614000 1 1.778840`

> this is legit horrorfying
`.go xyz 6692.350000 -4662.600000 721.590000 1 2.426430`

> Model is bugged. dunno if this was intentional
`.go xyz 6690.950000 -4662.820000 721.627000 1 1.293960`

> Face mixed with an elf and a human
`.go xyz 6691.610000 -4662.410000 721.626000 1 2.023360`

> skin has screwed up on this mob, why does she have a human face with a moustache?
`.go xyz 6690.250000 -4662.350000 721.677000 1 0.820825`

> Marius Hedrin's model is now of a night elf female, with the textures of a human male, what went wrong? :D
`.go xyz 6691.600000 -4663.050000 721.593000 1 1.726720`

> NPC has male human skin on a female night elf body.
`.go xyz 6692.200000 -4663.240000 721.560000 1 2.060990`

> Broken texture. Human male texture on a night elf female model.
`.go xyz 6692.000000 -4662.620000 721.601000 1 2.217000`

> She is missing her face or body textures.
`.go xyz 6691.650000 -4663.220000 721.581000 1 2.124490`

> This NPC has broken textures. A human male NPC's textures are placed onto her.
`.go xyz 6692.700000 -4657.170000 723.173000 1 1.391330`

> Somethings wrong with her/his head
`.go xyz 6692.820000 -4661.660000 721.625000 1 2.843450`

> A vendor but sells nothing.
`.go xyz 6692.620000 -4664.610000 721.471000 1 2.306320`

> Yeah, this npc doesn't look right
`.go xyz 6691.360000 -4664.210000 721.537000 1 1.453330`

**Comment by zana244** [comment]
Seems solved on internal. Good texture, he sells scrolls and blank parchment, and the quest scroll after you finish the quest line.
