### ISSUE TITLE
Teles'aran Citizen

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1379]
> I've noticed some of the undead have ghostly appearances while others appear solid and alive. Not sure if intended or not.
`.go xyz 7630.150000 -4542.190000 697.141000 1 4.679340`

> A lot of the Teles'aran Citizen spawns do not have the telltale look of an udead. No glow and nor transparency.
`.go xyz 7901.210000 -4467.770000 703.610000 1 2.274240`

> Some of the citizens around the area do no appear as ghosts, just as regular night elves
`.go xyz 7615.310000 -4546.300000 699.047000 1 1.186410`

> Could probably use an ethereal look to communicate that they're undead
`.go xyz 7580.250000 -4484.220000 677.636000 1 0.652833`

> creatures aren't ethereal or ghostly
`.go xyz 7630.940000 -4536.560000 696.384000 1 4.353910`

> some of these elfses do not have the spectral ghostly hue that hte others have.
`.go xyz 7871.980000 -4466.270000 699.363000 1 5.080530`

> They have their "greetings" text when you left click on them. Winterspring, Tele'aran,
`.go xyz 7629.260000 -4540.150000 696.815000 1 5.053250`

> are they suppose to appear as ghosts? They look like normal living night elves
`.go xyz 7564.550000 -4493.450000 671.722000 1 1.349730`

> Some of these have a ghostly aura on them, but a lot of them don't, making them look like normal humanoids instead of undead.
`.go xyz 7746.180000 -4515.960000 709.145000 1 0.802298`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8083
