### ISSUE TITLE
Silt Crawler - (922)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#138]
> Lots of creatures on this beach can't find a path to attack and set in evade mode
`.go xyz -9820.320000 -4097.390000 11.884400 0 4.927010`

> These mobs and the Monstrous Crawlers on this beach appear to be stuck in place often. Refuses to come when aggro'd.
`.go xyz -9847.390000 -4181.480000 0.079919 0 1.321220`

> Occassionally (not rare at all) spawns underground, can be seen via Track Beasts.
`.go xyz -9861.190000 -4134.290000 11.033600 0 1.446420`

> Several (all?) are on Evade if not fought in melee range.
`.go xyz -9933.530000 -4242.000000 2.668350 0 2.362220`

> evades
`.go xyz -9818.830000 -4097.300000 11.235700 0 4.833950`

> clips under the map, evades constantly
`.go xyz -9698.980000 -3962.450000 1.893190 0 4.238400`

> Not just this creature, but the entire coastline in SoS is very buggy
`.go xyz -9788.180000 -4046.660000 17.665200 0 5.510000`

> keeps evading
`.go xyz -9697.060000 -3965.140000 1.527210 0 4.209630`

> constantly evading
`.go xyz -9776.620000 -4089.690000 1.331250 0 0.376513`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
