### ISSUE TITLE
Izalnir

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1391]
> Gives a quest to my ally toon in what looks like a horde camp.
`.go xyz -11348.200000 -3671.640000 20.485200 0 2.242800`

> This NPC Is friendly to Alliance but is located in Horde outpost. Bug? I was able to get a quest from him as Alliance.
`.go xyz -11336.300000 -3690.780000 14.093700 0 0.155875`

> we can pick this quest up as an alliance player. i think it shouldn't be, is it?
`.go xyz -11335.100000 -3694.110000 14.193400 0 1.235070`

> This NPC is a horde questgiver in Izalnir's Camp in Blasted Lands
This NPC is friendly towards Alliance players and thus gives access to the quest [The Best of the Worst] to Alliance players.

Is this intended ?
`.go xyz -11335.400000 -3691.800000 14.115500 0 0.597629`

> im able to accept this horde quest as alliance
`.go xyz -11352.100000 -3687.150000 13.217600 0 6.071490`

> Alliance can accept the quest he has, but he is in the Horde area  Izalnirs camp
`.go xyz -11376.700000 -3680.310000 5.968360 0 6.149860`

**Comment by Bennylavaa** [comment]
read the quest.....
