### ISSUE TITLE
Nightmare-Plagued Druid

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1396]
> didnt despawn
`.go xyz -677.392000 13.286100 -90.012800 109 4.913430`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310

**Comment by Shadownflame** [comment]
They disappear now a few seconds after resetting combat. Still persisting after boss dies, I guess that could be intended, though it's a little weird that the portal doesn't despawn and continues spawning them after Eranikus is long history.
