### ISSUE TITLE
Muln Earthfury

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1398]
> Mouse Icon changes to the spellbook icon when i'm a warrior
`.go xyz -1389.210000 469.173000 81.003400 1 3.216780`

**Comment by Bennylavaa** [comment]
Still happens

**Comment by kaytotes** [comment]
This isn't even a bug. Blizzlike.

Applies to every single class trainer. There is no such thing as a conditional mouse icon.

**Comment by Shadownflame** [comment]
I marked this for testing because there was a change in last update that affected this npc. It was about training the wrong class, I assumed that's what the report is about? Is he training warriors?

**Comment by Bennylavaa** [comment]
Nope it is just the icon when hovering over him
