### ISSUE TITLE
Raha'glor the Inferno

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1405]
> mob doesnt move nor does any dmg
`.go xyz -7932.830000 -2618.500000 220.241000 0 1.441460`

> Mob doesn't attack
`.go xyz -7926.460000 -2585.190000 213.469000 0 1.735030`

> can be killed easily with ranged attacks
`.go xyz -7919.530000 -2593.210000 216.626000 0 2.134510`

> Elemental not moving from its place. Not attacking, while nuking it down with ranged. In melee it owrks as it should.
`.go xyz -7916.400000 -2598.280000 221.148000 0 2.247320`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2343
