### ISSUE TITLE
Meeran

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1407]
> He's a bit weak and gets a lot of damage from the orgres Flamestrike (AoE). If you're not a healer class, he'll probably die, unless you kite the mobs away. 

Since the quest is long (the guy does walk slowly), I can see some users being frustrated
`.go xyz -8034.500000 -2409.070000 124.459000 0 1.376650`

> brother takes FOREVERRR
`.go xyz -8113.740000 -2635.190000 133.439000 0 0.869703`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2524
