### ISSUE TITLE
Fox Sounds

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1408]
> Repeatedly making aggro noises after dying.
`.go xyz -1952.640000 -412.788000 -5.350980 1 4.002070`

> death sound repeats on loop
`.go xyz -2878.950000 -598.379000 54.926100 1 2.335820`

> looping death sound
`.go xyz -3171.190000 -106.432000 47.329700 1 3.902630`

> lvl 5 but died in one hit like a critter
`.go xyz -3157.510000 -118.515000 47.185100 1 3.635590`

> Keeps playing the death sound long after being dead
`.go xyz -2695.110000 -1153.410000 13.266600 1 6.213390`

> His dying sound plays on repeat when killed lol
`.go xyz -1016.900000 -598.717000 -59.000100 1 1.933020`

> This creature makes looping sounds when killed.
`.go xyz -3363.590000 -333.222000 62.855900 1 2.175010`

> I moonfired this little fox and it is repeating the sound of its demise/or aggro noise,  over and over again... taunting me.
`.go xyz -2880.170000 -593.191000 54.835600 1 4.746240`

> Their death sound does not playing.
`.go xyz -3374.810000 -328.497000 66.980100 1 2.289250`

> Dying sound echos when killed.
`.go xyz -1560.470000 271.613000 17.298700 1 1.133640`

> Killed a lvl 5  Juvenile Fox in Red Cloud Mesa 
it is able to parry as a critter 
and when it died the death sound plays indefinetly
`.go xyz -2889.010000 -591.986000 54.692100 1 6.188890`

> Upon death he continuously emotes a death sound, non-stop.
`.go xyz -1595.510000 232.721000 1.565610 1 5.642180`

**Comment by Bennylavaa** [comment]
fixed in Build 2553
