### ISSUE TITLE
Helga Ashgate

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1410]
> Quest called "The Art of Golemancy" doesn't count up whenever I kill an enemy creature
`.go xyz -8022.590000 -2238.120000 133.747000 0 1.345960`

> the art of golemancy, didnt work for us, tried to do it together with my friend.  we killed 2 scorpids and 3 ogers but nothing was counted towards enemy slain
`.go xyz -8021.290000 -2241.910000 133.739000 0 1.969550`

> The art of gollemancy can't be completed
`.go xyz -8022.650000 -2236.230000 133.751000 0 6.250770`

> The 'Art of Golemancy' Quest has several issues. The golem does such little damage even killing one mob can be a challenge and killing a mob with the Golem doesn't count towards the quest kill count.
`.go xyz -8025.030000 -2234.650000 133.773000 0 1.404860`

> The Art of Golemancy - looks like Golem is abit underpowered, it takes a lot time to kill any enemy, poison ability is useless - too low damage, other abilitys barely kill any enemy if used all correctly and with planning
`.go xyz -8021.630000 -2233.630000 134.300000 0 1.960140`

> The Art of Golemancy, quest does not update when killing enemies. Hunters with Active pets causes glitch with Golem abilities, works fine when dismissed.
`.go xyz -8024.460000 -2232.880000 133.777000 0 1.260680`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
