### ISSUE TITLE
Black Guard Sentry

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1413]
> They don't seem to chain aggro. Three aggroed with Avenger's Shield, fourth sat idle.
`.go xyz 3998.740000 -3413.730000 118.247000 329 0.029712`

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/764767d9-298f-4297-8d8f-2dcd8a4e9145)
happens if you pull one from either end.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8297
