### ISSUE TITLE
Felsnap

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1417]
> Not much of a "Rare" mob, was up again after I ran by his spawn again 15 minutes later.
`.go xyz -10931.600000 -3134.030000 46.120600 0 3.266040`

**Comment by zana244** [comment]
Confirmed on internal, 5 minute spawn timer, drops a pretty good helmet. Hits like a truck and has like twice the hp of a normal mob. Probably just needs spawn timer increased.
