### ISSUE TITLE
Frostmane Novice - (946)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#142]
> I don't think this mob is functioning correctly.  It has mana and seems to use it's mana, but it doesn't cast any spells or at least it does not appear to cast any spells.
`.go xyz -6529.550000 301.612000 382.501000 0 2.265340`

> this guys have missing animation i think some spell, they stand still, my life bar goes down like a missing spell effect
`.go xyz -6489.090000 302.307000 371.423000 0 2.733060`

**Comment by Bennylavaa** [comment]
uses frostbolt and has animations.
