### ISSUE TITLE
Foe Reaper 8000

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1420]
> unmarked elite
`.go xyz 2949.160000 -5057.780000 108.630000 0 3.815620`

> Drops loot "Stabilization Sigil" which is equipment only a death knight can equip.
`.go xyz 2859.720000 -5048.220000 103.264000 0 0.001664`

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/08c3e72f-65df-4e8a-b437-f146577c6e48)
