### ISSUE TITLE
Deep Woods Moth

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1429]
> Weird pathing up the mountain, like hugging the side of it instaed of just flying
`.go xyz -4506.570000 2318.160000 1.472700 1 1.541060`

> falling under the bridge during pathing
`.go xyz -4523.230000 2036.160000 50.025200 1 0.251149`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
These mobs do produce intermittent falling movements while flying around the bridge/mountainside. Seems to happen mostly when they hit the edge of the terrain.
