### ISSUE TITLE
Skullflame Shield - (1168)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1439]
> Dmg from the flame strike is splitted betwen the targets, and doing avg 1k dmg splitted on 36 targets while it sould do avg 100 dmg to each target. The shiled nerfed like it was in wotlk, the tbc and classic version of it was better and without aoe reduce by count mobs

**Comment by ghost** [comment]
Not a bug, AoE damage gets reduced after so many targets in wrath and we kept this intentionally to dampen Mass AoE farming.
