### ISSUE TITLE
Mining Pick - (2901)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1463]
> Mining is bugged. It's supposed to be very frequent to gain + mining skill-up even when picking on green veins. Currently it's very rare to see that happen on Epoch. Something is wrong with the skill-up system with Mining veins.

**Comment by Bennylavaa** [comment]
in vanilla you only get 1 level per node and it happens on the first tap it also depends on the node level compared to your current skill level. 

I tested a few nodes from 1 - 10 and it seemed to level just fine.
