### ISSUE TITLE
Crude Throwing Axe - (3111)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1467]
> This was in my inventory as a starter item for Troll Warrior. I do not have the Thrown weapon proficiency

**Comment by Shadownflame** [comment]
This seems to be an error due to wrath client usually allowing warriors to start with Thrown proficiency, but that was reverted to classic where they couldn't. It is pending developer decision whether to add back the proficiency or remove the item.

**Comment by Shadownflame** [comment]
Troll warriors now start with the thrown skill.
