### ISSUE TITLE
Sawtooth Snapper - (1087)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#149]
> evades
`.go xyz -9759.740000 -4041.190000 10.110400 0 5.862610`

> monster losk on ground.. if move evade.. doesnt follow. 84.16/15.08
`.go xyz -9851.430000 -4152.690000 2.327810 0 4.116650`

> evaded constantly, cant kill
`.go xyz -9868.090000 -4136.790000 12.174200 0 5.688950`

**Comment by zana244** [comment]
Solved by fatigue issues in swamp of sorrows.
