### ISSUE TITLE
Small Barnacled Clam - (5523)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1496]
> Opening this sometimes doesn't give you anything. To my knowledge it should ALWAYS have at least one Clam Meat inside.

> very often there is nothing inside clams

> Despawns once opened and doesn't grant any loot

> If your inventory is Full and you use the Clam, the Clams disappear instead of cancelling the Looting.

> The clam sometimes contains no items.

> Does not always contain loot..is it intendet?

**Comment by Shadownflame** [comment]
Can confirm some are empty, although it's rather rare.

Related https://github.com/Project-Epoch/bugtracker/issues/1495
