### ISSUE TITLE
Cracked Silithid Carapace - (5877)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1502]
> completed the quest, however its still in my inventory. 

i can delete so not a major issue

**Comment by Shadownflame** [comment]
https://www.wowhead.com/classic/item=5877/cracked-silithid-carapace#comments Stays in your bag after completing the quest that it gives you Parts of the Swarm[ Parts of the Swarm](https://www.wowhead.com/classic/quest=1148/parts-of-the-swarm) . Safe to delete once complete!
