### ISSUE TITLE
Mind-numbing Poison II - (6951)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1516]
> Placed in "Junk" section of Poisons, can be crafted but has no effect.. I see nothing mentioned on the Rogue section of Custom Content on the website that rogues should only be able to use the Rank 1 poison so I therefore assume that this item is bugged.

> Broken + classed as Junk?

> is craftable by rogues under the "Junk" Section of the poisons menu.

In addition to the actual poison being in the normal spot

> mind numbing poison is showing up as gray vendor trash

> Why is this junk lmao, even in the junk category in the poison creation window

> Is listed under junk in the poison menu and can't be put on a actionbar.

> Mind-numbing Poison II is in a subclass called Junk rather than Consumable in the Poisons skill window.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6687
