### ISSUE TITLE
Revelosh's Gloves of the Owl - (9390)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1550]
> dropped from zalas witherbark. probably not what should drop this.

**Comment by zana244** [comment]
Why not? Requires lvl 35, uncommon item.
After Vmangos loot update it drops 2 uncommon items all the time though.

**Comment by Bennylavaa** [comment]
https://www.wowhead.com/classic/item=9390/reveloshs-gloves

because it was boss loot, however its been fixed with vmangos loot.
