### ISSUE TITLE
Crystal Pylon User's Manual - (11482)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1579]
> https://i.imgur.com/JlBQ2S2.png
Filled with raw html

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/7c6a7184-54ee-49cf-bf5d-278d2575da25)
I do not have this issue, must be some addon or client mod causing the issue

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/6fc56c64-05e4-48fc-9bba-fe1d56039fcd)
also checked without elvui
