### ISSUE TITLE
Wendigo - (1135)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#158]
> drop too much vendor trash armor
`.go xyz -5687.740000 -297.414000 366.713000 0 5.831900`

> lowered chance drop quest item
elevated change drop gear item, shields in my case
`.go xyz -5674.120000 -262.368000 367.004000 0 0.024640`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1455
