### ISSUE TITLE
Darkshore Grouper - (12238)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1589]
> Fishing with Fishing Pole (6256) until Shiny Bauble (6529) expires results in :

50 fish Achievements
50 fishing skill

only 3/6 Darkshore Grouper

**Comment by Bennylavaa** [comment]
Not sure if the loot pool is messed up here but the drop rate is non-existent for this quest fish.

**Comment by Bennylavaa** [comment]
This could be fixed a few updates ago will test it later.
