### ISSUE TITLE
Winterfall E'ko - (12431)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1591]
> Cant be stucked more than 1

> Dropds without doing the pre q

> doesnt seem to be a place to turn in.  also doesnt require the Cache to obtain

> Didn't do the quest to get those. Also seen one more E'ko and a quest item (can't loot them) on a mob. Quest item was "Empty Firewater Flask" I already had one.

> Item drops from mobs before completing the pre-requesite quest and gaining the cache.

> Excluding the fact that E'kos drop without having Cache of Mau'ari, the winterfall e'ko dropped from vilehorn satyrs.

> Drops without having the prerequisite quests for Cache of Mau'ari.

> This dropped without me having the necklace required for these to drop.

> Item does nothing

> Can only have 1 stack of 20, won't allow you to loot any more

> I dont have the Man'ari whatever item from the troll yet I can loot

> Sometimes i can loot it from mob, sometimes is sais - already looted

> can loot only 1 item like that, even that is not unique

> i do not done any quest and get this questitem

**Comment by zana244** [comment]
#8305
