### ISSUE TITLE
Egan's Blaster - (13289)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1609]
> This doesn't seem to free any ghosts.

> literally doesn't do anything. The quest "The Restless Souls" asks me to use the blaster on the friendly ghosts just outside the questgivers house but when I use the item it channels on the Spectral Residents but doesn't actually do anything.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8297
