### ISSUE TITLE
Elixir of the Mongoose - (13452)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1616]
> Can't use mongoose and flask of titans at the same time. I mean, this might be a feature, if it is, well, it'd be less ugly if it was just a bug

> Would be nice if these stacked in larger quantities than 5. 10 minimum

> Cant have mongoose(elixir) with any flasks.

**Comment by Shadownflame** [comment]
Tbc behaviour, by design.
