### ISSUE TITLE
Mountain Silversage - (13465)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1617]
> just way too few of them already and it's going to be an extremely high demand herb, I would suggest you try doubling the quantity off the bat - possibly more when you reassess. extremely important herb

> There are not enough nodes of these spawning in the appropraite zones.

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/ce0384d2-18f4-420a-8d98-fe8cbd57431b)
I think this has more to do with the pooling respawns than anything.  https://github.com/Project-Epoch/bugtracker/issues/8295
