### ISSUE TITLE
Black Lotus - (13468)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1618]
> I just picked a black lotus and it gave me 3 of them

**Comment by TetraDisaster0** [comment]
Do the devs intend to keep this? Or restrict it to the original one?

**Comment by Bennylavaa** [comment]
Good question, @kaytotes ?

**Comment by kaytotes** [comment]
Not an issue following vMangos loot. While looking into this I noticed lotus affinity couldn't proc from lotus so I've fixed that too. 

No more than 1 can drop normally with a 0.5% chance for a 2nd if affinity procs.

![image](https://github.com/user-attachments/assets/d2b8a274-2e40-47b7-85ef-994a1b943f00)
