### ISSUE TITLE
Stonesplinter Geomancer - (1165)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#163]
> They never seem to get their Flame Ward ability cast off. I attack them and I can see an inerrupted Flame Ward cast as soon as they react, like they just insta-canceled.
Expected: they should finish that cast if not purposely interrupted by CC.

Note: the ability may not actually be named Flame Ward.
`.go xyz -5580.340000 -3917.860000 328.935000 0 1.775200`

> Start a cast on pull, instantly cancel it.
`.go xyz -5586.520000 -3876.210000 329.568000 0 4.912000`

> It auto-interrupts itself every time it tries to cast a spell
`.go xyz -5621.020000 -3931.620000 325.882000 0 2.868660`

> Mob doesnt seem to cast any spells
`.go xyz -5690.830000 -3994.990000 327.797000 0 6.261210`

**Comment by Bennylavaa** [comment]
id: 4979 [Quick Flame Ward] effmask: 1 charges: 0 stack: 1 slot 0 duration: 4868 maxduration: 10000   caster: creature guid: 12615
[08:38 AM] Target unit has 1 auras of type 39:
[08:38 AM] id: 4979 eff: 0 amount: 0

Actually puts it on himself. Also, the only spell this npc knows which is blizlike
