### ISSUE TITLE
Enchanted Resonite Crystal - (16603)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1643]
> Doesn't get deleted after the quest

**Comment by TetraDisaster0** [comment]
Just because a quest item not getting deleted after completing them is "blizzlike" doesn't mean it shouldn't be corrected in my opinion. I understand such fixes would be low priority but it would be nice if these quests eventually properly deleted their item after completion.

**Comment by Shadownflame** [comment]
Could be true for some quest items, but this one in particular is the tool to summon a npc, which means it has an active purpose so it makes sense to stay in case somebody wants to use it again. I disagree with purposefully changing this behaviour for quest items that have some form of usability just to save two seconds of deletion time for those who don't want to keep it.
