### ISSUE TITLE
Filled Cerulean Vial - (17696)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1653]
> Damn, 3rd report regarding this quest. There small non interactable mushroom-like plants are apparently what constitutes a "vine" in this questgivers oppinion. I guess you can figure it out if after trying the vial on different plants and enduring the misleading voice prompt you deduce that mushroom = vine. Could be better.

> Ignore my previous report regarding this quest. I got it to work by spamming along the walls in the orange part of the dungeon. Who knewthat these vines seem to invisible (maybe herblist can see them?) and become visible when the vial is used. Pretty confusing if you ask me given everyone can take this quest and if you have no means of spotting the locations where you have to use the vial you can easily assume its broken. The voice prompt that "I don't have a target" contributes to confusion.

> For the quest Vyletungue Corruption this item should be usable next to the vines without needing a target. After the mobs that spawn are killed, it should count as 1 vine healed/cleansed.

As it stands the item has no effect whatsoever on the vines and says that you need a target. The vines where never targetable in the first place. The vial should work just in proximity, unless you want to make the vines targetable.

**Comment by Bennylavaa** [comment]
what are you guys on about this quest is a blizzard quest and works just like it should
