### ISSUE TITLE
Weakened Morbent Fel - (1200)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#166]
> did not give credit for Morbent Fel quest when killed
`.go xyz -10318.100000 375.247000 65.268400 0 2.404880`

> Was not actually protected by the enchantments that the provided quest item is supposed to dispel.
`.go xyz -10314.900000 363.088000 65.257700 0 2.322520`

> If you weaken him the quest doesn't complete
`.go xyz -10316.600000 364.650000 65.251200 0 1.628880`

> I had to kill this guy in his elite form and not used the quest provided item to weaken him in order to get kill credit for the Morbent Fel quest.
`.go xyz -10314.800000 360.755000 65.253400 0 2.509070`

> I did not get quest completion for Morbent Fel on this guy.
`.go xyz -10317.900000 359.689000 65.245600 0 1.839140`

> had to kill him twice...i think my pet got the tag so i didnt get the kill
`.go xyz -10314.600000 361.796000 65.256900 0 2.242290`

**Comment by Bennylavaa** [comment]
I recieved credit for this on ptr.
