### ISSUE TITLE
Design: Citrine Pendant of Golden Healing - (20976)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1667]
> Dropping in SoS, No JC prof

> is this in the game for now ? ans is this suposed to be soulbound?

> This should not exist, though why not just make it a BS pattern :)

> This dropped. It shouldn't have.

> This shouldn't exist.

> shouldnt drop

> This should be out of game or for the blacksmithing proff

**Comment by Shadownflame** [comment]
Should be fixed with vmangos update.
