### ISSUE TITLE
Design: Dark Iron Scorpid - (21956)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1672]
> I forgot which mob dropped this one but I recall it's from BRD. Recipe is related to Jewelcrafting

> Jewelcrafting pattern dropped from Golem Lord Argelmach

> jewlcrafting?.. dropped off ofGolem Lord Arglemach

> dropped Design: Dark Iron Scorpid for jewelcrafting

> shouldnt be in gam e:)

> jc drop?

> kewelcrafting

> jewel crafting on vanilla

> recipe isnt for blacksmithing

**Comment by zana244** [comment]
does not drop anymore, hopefully solved fully by vmangos loot update.
