### ISSUE TITLE
Featherbeard's Map - (23695)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1692]
> Eggs are displayed where they are supposed to be but can't be interacted.

> The eggs are not pickable.
They don't become active.
I can see their model in-game though

> Eggs for the quest are not interactable, can't pick them up

> the quest associated with this "Reclaiming the Eggs" from hinterlands can't be completed, the eggs are visible but can't be picked up, at least on alliance

> description of whereabout of quest items is very confusing

> eggs are not lootable

> I can't interract with the eggs of this quest.

> Quest dosent work, eggs cannot be used and taken

> Quest bugged, eggs are not lootable - name of quest  - Reclaming the Eggs - eggs are there, but cannot use it

> Cannot use eggs on this quest, eggs are there, but not any of them lootable

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
