### ISSUE TITLE
Young Threshadon - (1224)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#170]
> It deaggros and goes into evade and resets the moment you exit the water, even if it's just jumping to not be underwater anymore to make sure I'm at the top so I can breathe.
`.go xyz -5226.850000 -3252.540000 296.331000 0 2.268640`

> It's weird that a level 13 collections quest "Medicinal Restocking" is guarded by level 20 aggressive mobs. Maybe make them neurtral, or adjust the level down?
`.go xyz -5343.090000 -3405.310000 296.303000 0 1.514400`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
