### ISSUE TITLE
Dragonstrike Leggings - (29971)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1709]
> A lot of the new TBC crafts are in (and you should keep them in), but don't forget to adjust the stats to reflect 1.12.1 state. Like % instead of ratings.

Also, consider adjusting the old 1.12.1 crafts if you're introducing these much stronger items with way cheaper materials.

> All Letherworking specializations like Elemental letherwork, Tribal, Dragon - all items from this specializations got TBC stats on items - meaning that they got something like critical strike rating by 12, that's probably no suppouse to work that way

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2918
