### ISSUE TITLE
Light Skyforged Axe - (30072)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1710]
> I appreciate the devs adding the new TBC recipies to Epoch, despite us having 1.12.1 items for the most part. 
With that being said, it would be much appreciated if some of the more expensive / specialized crafts of 1.12.1 were made more relevant / cheaper to craft. A lot of cool things in Vanilla that never ever get crafted or seen by players, due to their mediocrity or extremely expensive/hard to attain nature, when compared to much easier to get and much stronger alternatives.

**Comment by Shadownflame** [comment]
Profession overhaul is in the plans by Eredun/Kes, however unlikely to happen prior to launch.
