### ISSUE TITLE
Rock - (45201)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1722]
> This should stack like the rest of the gray items you get from Fishing

**Comment by Bennylavaa** [comment]
By Varicelle (8,352 – 3·17·95) on 2009/11/21 (Patch 3.2.2)		
Your rock fact of the day : rocks don't stack.

This is a Wrath item though and prob should be removed?

**Comment by Bennylavaa** [comment]
looks like this is intended to add flavor to fishing.
