### ISSUE TITLE
Ragnar Thunderbrew - (1267)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#173]
> This NPC is not offering the quest Beer Basted Boar Ribs to human players
`.go xyz -5599.890000 -502.965000 400.342000 0 5.474380`

> The quest Beer Baster Boar Ribs seems missing, I don't know if it's intended
`.go xyz -5597.310000 -502.346000 400.240000 0 5.071940`

**Comment by Bennylavaa** [comment]
he gives the quest
