### ISSUE TITLE
Requisition Orders

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1730]
> Gramatically as well - ending the sentence with "bring me." and then starting the next with "Bring me" is just horrible English :D 

Why not just simplify it - "My seller is paying top coin for  Mistvale Gorilla heads and pelts. Bring me all you have to my encampment...

> Typo on here - "Once" is spelt as so

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
