### ISSUE TITLE
Courser Hide Cape

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1747]
> Missing armor? Its wierd that this item comes from a level 20ish quest but gives a cloak that is far worse than any others

**Comment by zana244** [comment]
Confirmed on internal, no armor. Also, heavily suggest to buff the cloak just a bit, lvl ~22 quest with 4 stat budget is not even worth considering.
https://www.wowhead.com/classic/item=4706/lambent-scale-cloak has 6 stat budget at lvl 24, req 19.
