### ISSUE TITLE
Frostmane Seer - (1397)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#177]
> Range on their spell is too long, HUGE!
`.go xyz -5193.260000 -151.707000 440.743000 0 3.479360`

> no attack aniation
`.go xyz -5030.750000 -281.117000 442.433000 0 0.034328`

**Comment by zana244** [comment]
Has attack animation.
https://www.wowhead.com/classic/npc=1397/frostmane-seer#abilities
On internal range seems like 40 yards, same as wowhead.
