### ISSUE TITLE
Cloak of Physical Accuracy

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1787]
> cant be enchanted with cloak enchants

> Not a valid target for Enchant Cloak - Superior Defense (not sure about other back enchants).

> Can not be enchanted. Gives error saying "Cloth must be equipped".

> Decreases your damage taken drom  other payers by 1% do not work on any item, we try compate damage full pve gear vs full pvp gear and even compare different damage from different classes - instant damage and DOTs, we got exact same results with damage, so PVP stat do not work at all

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4420
