### ISSUE TITLE
Emblem of Dominance

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1793]
> Proc from any non-harm ability. This is common bug with simmilar pvp items in other expansions. They should proc only from damaging abilities and autoattack. Not buffing, eating a food, crafting items etc. Probably other simmilar pvp trinkets (agi/sp/sh/mp5) affects the same global bug.

> Proc activates from switching warrior stances.

> emblem of dominance" can proc off crafting items.

> Has a lower strength bonus than the level 45 equivalent trinket

> Appears to have 'on-equip' stats swapped with the lvl45 version of this item

> worse than same 45 lvl trinket

> Mount up triggers trinket

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
