### ISSUE TITLE
Emblem of Alacrity

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1794]
> Trinket effect is proccing while I'm not doing anything, super cool :D but not intended I'm sure. Started after I cooked a bunch of thistle tea by a fire I made.

> Spell procs when out of combat, when casting a mount.

> This item gives fewer stats than the lvl45 one

> Has activated its effect off of mounting and Engineering crafts.

> The agility bonus is lower than the level 45 version

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
