### ISSUE TITLE
Emblem of Renewal

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1796]
> 100% proc rate and procs when mounting

> The equip effect triggers on every direct cast healing spell (healing touch, regrowth), every single time. However, it never triggers on my heal over time spells (lifebloom, rejuvenation, tranquility). The tooltip indicates it's all spells and abilities, not just direct heal/damage spells. I think it should trigger on my other healing abilities as well.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
