### ISSUE TITLE
Ancient Battery

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1797]
> the clickables for these items seem to stop respawning after a while for no apparent reason.

> Not enough quest items for quest "The perfect fuel". This will be crowded area and should be more quest items to loot

> This item either requires more spawnpoints or faster spawn timers. Really tough quest to complete.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
