### ISSUE TITLE
Empty Oil Cannister

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1800]
> The Perfect Fuel is incompletable because you can't be in the Oil Platform Base. The entirety of that oil rig is still Wavestrider Beach.

> If there even is a valve underwater where you can use this flask as stated in the quest description, it certainly is exceedingly well hidden I did not find a spot where i could use it, instead there were a few spots where i could mount up underwater..

> Canister" is spelled with only one 'n'.

> About the item earlier, apologies, I didn't correctly read the quest text, Apologies again.

> For some reason doesn't seem to work propper, When I am on the oil rig it states I am not on it.

**Comment by Bennylavaa** [comment]
Canister is indeed only spelt with 1 n the item has two. 

The rest of the stuff here is a duplicate.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229 just merged into here seeing its all part of the quest.
