### ISSUE TITLE
Oil Absorber

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1803]
> During this quest, if you target an NPC or enemy, it says not in range rather than using the item when on top of an oil spill, you then have to untarget the NPC to use item

> Out of range error while im staying into the oil spill

> You have to target yourself? Not the oil spill?

> Standing inside a spill, using the item, nothing happens

> not allowing me to use on an underwater oil spill, says out of range

> quest not working with my orc hunter, even in th middle of the pools i am not close enoug,  works perfect with a Tauren  ...  Size matters ?

> This quest the item sometimes doesnt work

> for some reason it is not possible to clean up an oil spill when targeting an enemy, even when standing inside the oil spill. you have to not be targeting anything for this item to actually work

> If I have a target it will say "out of range". Would it be possible for it to target automatically a Tanaris Oil Spill regardless of my target?

> cant use if targeting something

> This item doesn't activate/do anything to the oil soaked critters.

> I don't know how to use this. Rightclicking it does nothing - no targeting, no AoE if im right next to the spill

> not cleaning up oil spill, tried to stand on it tried reloading

> Able to target mobs wit hthis, there's no reason to. gotta untarget the mob to use it on the oil spill in the water

> Not cleaning up oil spills

> Cannot be used on the oil spill when targetting something. No errors given just silent fail until you de-target and use it

> can't use if targetting a mob even if you are on an oil spill "target is too far away

> Can't use while in combat, clashes with Think Of The Animals quest, which occasionally puts you in combat with enemies; but is bugged where they don't actually attack you

> if targeting a nearby mob, the item cannot be used

**Comment by zana244** [comment]
#2234
