### ISSUE TITLE
Flame Sack

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1805]
> The drop rate feels a touch low compared to how many of the mobs spawn. Doable, but will be a pain when competeing with other players.

> it should just be called Flame Sac

> Low drop chance on quest "Boom!Boom!Boom!" (tanaris0

> horrendeous drop rate

> Drop rate on these is kinda bad. Quest takes a long time, I like that it synergizes with the Clamlette Surprise cooking quest, but you finish that one way before you find all the Flame Sacks.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2237
