### ISSUE TITLE
Filter Parts

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1806]
> These can still be looted after getting 8/8 for the quest, causing the object to despawn. Potential for griefing.

> Spawn rate bug appears to still be ongoing

> way to rare

> Too low respawn rate, low respawn spots

> These are underwater at tanaris beach for quest "Water Co. saviour" I am alone and cant find enough quest items. Imagine if 2-3 people are doing it at same time

> Spawn rate seems way too low. I am the only person here and it's taken me almost an hour to get 7/8

> Sparse and hard to spot. Simple enough quest with aquatic form, but would be immensely annoying to complete without water breathing.

> respawns bugged? havent seen another part in a while

> There should be more in the water... had 4 guys in there all looting them and it was awful trying to get my own

> not enough parts to find was collecting the same 4 ones twice (had to wait for respawns)

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
