### ISSUE TITLE
Revamtusk Pouch

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1817]
> RevaMtusk lmao, rename the item and it's all good

> Typo, Revamtusk should be Revantusk

> Typo -- RevaNtusk, not RevaMtusk

> Mispelled

> Possible spelling mistake, maybe you meant Revantusk?

> Misspelled Revantusk

> It should be called Revantusk, not Revamtusk.

> Spelling error, probably should be RevaNtusk Pouch since it's from a Revantusk Village quest

> Pretty sure this item has a typo and  is supposed to be called "Revantusk Pouch" after the trolls of Revantusk village.

> just a little typo in the name, m instead of n

**Comment by Shadownflame** [comment]
Same issue https://github.com/Project-Epoch/bugtracker/issues/7575
