### ISSUE TITLE
Zanzil Zombie - (1488)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#182]
> Chest respawned 5 mins within looting it and it had nothing the 2nd time. @ Ruins of Aboraz in STV.
`.go xyz -13666.300000 -284.011000 8.175840 0 5.604250`

> This mob appears to be sliding across the ground instead of walking
`.go xyz -13610.300000 -420.143000 0.650093 0 0.006976`

**Comment by zana244** [comment]
Chest did not respawn within 5 minutes, and the mob seemed fine to me ?
