### ISSUE TITLE
Wetland Hemp

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1822]
> This is supposed to grow around Feralas rivers ... but it wasn't at the Verdantis river, or on the Forgotten Coast where that river drains into the ocean. Think the respawn time is fcked as well - picked 2 of it and they stil weren't back 30 mins later

> The quest "Fit for a King" describes finding hemp by rivers but it is literally growing on the coast, confusing description.

> there are so few spawns :c

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7967
