### ISSUE TITLE
Hemovac Max

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1823]
> Unable to suck the beasts blood

> You can double-loot blood because it also drops from mobs.

> Not all beast in the zone are eligible: "Invalid target"

Seems to work close to the quest giver but beast to the north do not.

> This doesn't appear to work on the beasts north of the compound, so it doesn't work on all beasts in feralas.

> Can only be used on wolves

> Item isn't working

> This item does not extract blood from weakened beasts.

> target can still move and attack when used

> doesn't work on higher level beast mobs in northern feralas

> Says "Invalid Target"  when targetting low health beasts

> 8 second cast is too much if you play dot/pet class or you need to hardcast non-dot abilities and stop pet from attacking mob since you can only use this item on low-hp mobs

> If my pet has aggro on the mob while using the item the mob will follow the pet in a lying-down animation

> beasts are still auto attacking while imobilized

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2267
