### ISSUE TITLE
Darkened Needler

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1825]
> 3.9 dps for an item level 47 crossbow looks wrong

> Damage on the bow is way too low

> Wrong damage and stats for an item of this level

> Doesn't count as a ranged weapon

> 7-18 damage on a 47 item level blue weapon

> The stats of this weapon are way lower than it should be?

**Comment by zana244** [comment]
Wrong stats, and cannot even use it -- you can equip it but you cannot attack with it.
