### ISSUE TITLE
Gnarfang's Bloody Battleaxe

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1851]
> Sorry not for the item but more for the NPC to kill. Gnarfang seems a little bit easy as a level 20 elite. I was able to solo him without trying too hard as a level 20 druid. Hogger at similar level ranges feels difficult if not impossible to solo but Gnarfang feels like he will be easily soloable by a lot of the classes.

**Comment by zana244** [comment]
doesn't seem easily soloable by a lot of classes, has 1.8k hp and hits for 60 per hit... naked hunter has 500 hp for reference at lvl 19.
