### ISSUE TITLE
Emblem of Dominance

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1877]
> didnt delete from my bag when i tried to sell it

> Flash of Light force procs the trinket

> I just adore how bugged these PvP trinket procs are. The Cozy Fire buff you get (+spirit) for being next to a campfire, somehow procs this item. So you can have 100% uptime just by  plopping down a cozy campfire next the boss you're dpsing.

> This item procs from any and all kind of interactions. (Looting, casting mount, swapping warrior stances)

> Gets triggered by using anything (Stances, Mounts, Quest Items)

> Appears to have 'on-equip' stats swapped with the lvl55 version of this item

> mounting procs the effect

> This trinket grants more strength than the lvl 55 trinket

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
