### ISSUE TITLE
Emblem of Alacrity

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1878]
> I'm seeing the trinket proc on mount up and skinning as well -- are these considered "spells"?

> The proc seems to happy 100% of the time on healing self (like with lesser healing wave) as a Shaman but not 100% on anything else

> This trinket activate by simply standing near a fire.

> This trinket procs on absolutely everything, mounting up, bandages, crafting, anything that the games consider a spell.

> Getting on a mount procs this trinket

> this and similiar items even proc when I mount - probably not intended, since it puts the items on ICD

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
