### ISSUE TITLE
Emblem of Power

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1879]
> It procs all the time, even when summoning mount, not sure if it's intented

> This trinket procs off creating bandages

> Procs off of mounting up

> Healing spells with cast time have a 100% chance to proc the damage bonus effect on this item. Tested with Druid's Regrowth and Healing Touch and got the spell damage buff every single time even with Rank1 spells.

> These items are still proccing wrongly, no procs for any abilities as a ret paladin but 100% proc rate on heals

> has no ICD, procs when mounting

> This item seems to have no internal cooldown. Procs left and right, even off self-buffs and mounting.

> Proc from mount up

> Smelting bars (and presumably other profession recipes) can trigger this item.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
