### ISSUE TITLE
Young Scavenger - (1508)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#189]
> When this mob is attack or chasing rats which takes him many hits to kill he is not able to be attacked
`.go xyz 1981.870000 1689.370000 78.327900 0 3.922610`

> This wolf is a bit buggy I tried to auto-attack it while it was chasing a rat to save the rat (I love rats) and it kept saying "out of range" even though I appeared to be in range.
`.go xyz 1901.090000 1637.440000 92.402500 0 4.848960`

**Comment by zana244** [comment]
Could not reproduce?

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/190

happens on reset after attacking the mouse.
