### ISSUE TITLE
Darkeye Bonecaster - (1522)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#191]
> so LoS workin on buildings , but not around trees in this area Agmand Mills
`.go xyz 2772.110000 793.032000 113.159000 0 2.327820`

> they aren't casting frostbolts or autoattacking
`.go xyz 2660.840000 844.785000 109.156000 0 0.009039`

> Projectiles of his spell can not be seen.
`.go xyz 2539.950000 954.698000 92.366900 0 2.145230`

**Comment by zana244** [comment]
Could not reproduce. Trees not providing LoS is intended.
