### ISSUE TITLE
Scarlet Missionary - (1536)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#194]
> During the quest "Proof of Demise" from Brill, these guys are supposed to drop Scarlet Insignia Rings, but me and my friend have slaughtered them for half an hour yet they've only dropped 5, 4 was in quick succession, however the last one was after a while and now they haven't dropped any since. Not sure if something is up with the rng or if the game was like this intentionally. Just figured I'd let you guys know. Thank you!
`.go xyz 1846.210000 635.977000 44.870500 0 2.793710`

**Comment by Shadownflame** [comment]
Works fine. 40%ish drop rate.
