### ISSUE TITLE
Manashield

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1958]
> Disappears when sheathed.

> No block value

> Shield does not show on character model unless attacking.

> Not visually appearing on character model's back.

> 8% crit?

> This shield does not appear on character's back when equiped

> 8% Spellcrit? This has to be a bug.

> 8 CRIT?

**Comment by Shadownflame** [comment]
Spell stat corrected from 8% crit to 10 int 1 crit.
Still missing block value.
