### ISSUE TITLE
Nightmare Seed

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#1960]
> since the item starts a quest you can only pick up one but you need to pick up 5 for the quest

> says already looted but i cant loot it

> these stack

> no more than 1 of these can be picked up, which makes it impossible to progress past 1/5 nightmare seeds towards quest completion. probably need a separate item to start the quests than is required for the subsequent collection part.

> can't loot

> Sometimes some items like this one will say it has already been looted while staying on the corpse and making no changes in my inventory.

> Says it's "Already looted" even though I've never looted this item. Can't get it at all.

> says i already looted but nope.

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7598
