### ISSUE TITLE
Bloodsail Warlock - (1564)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#199]
> These warlocks do a ton of shadow damage. Might be scaled too high.
`.go xyz -14606.900000 329.756000 2.651300 0 4.148830`

**Comment by zana244** [comment]
check first comment
https://www.wowhead.com/classic/npc=1564/bloodsail-warlock#comments
intended. I'm more scared of the succubus lash of pain damage.
280-300 shadow damage on both succ and lock spell. bring a friend or cc
