### ISSUE TITLE
Thorgrum Borrelson - (1572)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#200]
> The 'Send me to the Airfield!' option during the 'The Ironforge Airfield' quest is not working.
`.go xyz -5422.340000 -2928.990000 347.117000 0 3.177200`

> Is the FP to the Airfield meant to be working?
`.go xyz -5422.470000 -2928.110000 347.111000 0 4.459840`

> Can't seem to take the trip to the Airfield - clicking the option does not do anything.
`.go xyz -5424.700000 -2929.720000 347.577000 0 4.571210`

> Send me to the Airfield!" as no effect
`.go xyz -5428.180000 -2929.790000 347.559000 0 0.169150`

> Doesn't initiate flight after clicking send to airfield
`.go xyz -5422.330000 -2927.660000 347.071000 0 5.526510`

> When I click "Send me to the Ironforge airfield", it does nothing.
`.go xyz -5424.670000 -2927.700000 347.386000 0 4.679700`

> When clicking "Send me to the airfield!" for The Ironforge Airfield quest, nothing happens.
`.go xyz -5422.920000 -2928.410000 347.193000 0 3.854140`

> Does not send to Airfield
`.go xyz -5423.500000 -2928.010000 347.276000 0 4.012120`

> I just hit level 15 and the option to fly to IF airfield isnt 
working
`.go xyz -5423.260000 -2927.660000 347.223000 0 3.899940`

**Comment by Bennylavaa** [comment]
fixed on ptr
