### ISSUE TITLE
Gryth Thurden - (1573)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#201]
> Upon accepting "The Ironforge Airfield" from this NPC, selecting the "Send me to the Airfield!" dialogue option does... nothing at all. Just closes the dialogue window but that's it.
`.go xyz -4819.830000 -1154.100000 502.210000 0 3.484720`

> Send me to the Airfield! does not work. Clicking on the link does not work. not from here neither from the Thelsamer flight master.
`.go xyz -4820.990000 -1154.790000 502.210000 0 1.624730`

> send me to the airfield!" does not work
`.go xyz -4820.790000 -1153.520000 502.210000 0 1.876180`

> He doesnt send me to the Airfield when I use the chat option after talking to him.
`.go xyz -4826.480000 -1160.820000 502.208000 0 2.499840`

> Send me to the Airfield" dialogue doesnt work.
`.go xyz -4823.270000 -1153.360000 502.210000 0 0.745255`

**Comment by Bennylavaa** [comment]
fixed on ptr
