### ISSUE TITLE
Soldier's Dagger

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2011]
> no level requirement

> I think this item is supposed to have a level 55 req. It currently has no level req

> Missing a level requirement

> this item doesnt have a level requirement

> Forgot to add {Require level 55] on this weapon.

> It doesn't have a level requirement of level 55 like the rest of the items.

> Doesnt have level requirement

> This item has no level requirement, while other level 55 pvp armaments do.

> Does not have a level requirement like the other weapons.

> this dagger have no level restriction

> no requirements

> this pvp item does not have a level restriction at the moment.

> This dagger seemingly lacks a level requirement. It 
should have a level requirement of 55 for parity with the other "Soldier's" weapons.

> this dagger doesnt have any lvl requirement so people can buy it at lvl 1 and go zoom

> Has no requirement from the vendor

> No level restriction, can buy and equip as a Level 7.

> Make it 55lvl item it does not have any level restrictions now

> no lvl requeriment

> Doesn't have a Level Requirement on it.

> This item does not have level requirements

> No Level requirement on it

> Doesnt have level requirement yet, I am currently running around with it at level 15 :D

> PvP Item that does not have requirment and you can just get it at any level

> Currently has no level requirement. Supposed to require lvl 55 like all the other weapons of this tier.

> Soldier's Dagger has no level requirement.

> No level requirement on this item.

> You're able to buy this weapon at lvl 1 with no cost (I know there's no cost due to it being beta), but idk about being available at low lvl's

> No Level restrction on the Item.

> applied poisons and it shows 36 min instead of an hour

> All other items on Weapons Quartermaster Captain O'Neal are at level 55 limit except this dagger with no level limit at all

> this dagger does not have a level requirement. The other weapons sold by this vendor have level 55 requirement

> It does not require a lvl to wear, all the other Soldier items does.

> no level requirement on this from warmode vendor, should be 55 like rest i believe

> Resold to vendor, is now eating up space and greyed out in my inventory on top of being unmovable and unequipable right now.

> No level requirement, while everything else this vendor sells does have a level requirement.

> has no level requirement when all other rare upgraded items require 55

> Are these supposed to have no level requirement?
Looks sus AF. From pvp vendor in Org, the weapon quartermaster.

> stuck in my inventory

cant remove

> Does not have a level requirement

> This item doesn't have a level requirement

> No level requirement

**Comment by zana244** [comment]
Level requirement solved during beta 3.
