### ISSUE TITLE
Pearl Diving - (705)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2036]
**In Progress Reports**

> My report on The Vile Reef was meant for this one. My mistake. There are far too few active clams for this quest. It took me about 30 minutes with active water breathing to find 9 pearls. Several of these were clams that had respawned due to enough time passing. Also the pearls are not quest items, and I am not sure if that is intended.

**Comment by Bennylavaa** [comment]
Blizlike they're also not quest items because they are a reagent for engineering flash bombs (mostly used vs hunters or druids in pvp)
