### ISSUE TITLE
Encrusted Tail Fins - (1107)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2052]
**In Progress Reports**

> These can drop from the non-elite murlocs in the jungles, rather than the intended murlocs in the vile reef.

**Comment by Bennylavaa** [comment]
Confirmed they are dropping from 4457, 4458, 4459, 4460

Should only drop from these npcs: 871, 873, 875, 877, 879

**Comment by Shadownflame** [comment]
Fixed with vmangos port.
