### ISSUE TITLE
The Super Egg-O-Matic - (2741)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2062]
**In Progress Reports**

> This quest gives no clue where to go to find the required eggs? Weird.

> This quest has no initial quest text. I don't know what I'm getting or from where.

> When recieveing the quest, there is no quest text. I get that it may be by design, as the task is somewhat clear from the context, but at least a sentence of description or the like would be nice.

**Comment by Bennylavaa** [comment]
This is blizlike
