### ISSUE TITLE
Arcane Runes - (3449)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2082]
**In Progress Reports**

> Xiggs was at the platform without the flaregun being to be used.

> The q giver just appeared. Is not he supposed to come on airplane or something? :)

> Pilot is spawned and using the flare gun spawns another

> Saw a Fatigue Timer when swimming here.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/766
