### ISSUE TITLE
Betrayed - (3506)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2083]
**In Progress Reports**

> When I entered the area, there was a pile of Magus Rimtoris at the location. Presumably, someone had done it before me and failed? Or accidentally summoned her multiple times. Either way retail had some way to deal with players spawning quest mobs such that you didn't see them like this.

> The delay in spawning the mobs after breaking one crystal made me think I needed to break all three of them. This caused everything to spawn three times, making it a lot harder.

**Comment by Bennylavaa** [comment]
Happens like this on vmangos as well classic it seems this is how it was on classic as well.
