### ISSUE TITLE
Slavering Ghoul - (1791)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#211]
> Pathing issues when running toward uthers tomb
`.go xyz 1010.480000 -1818.710000 79.348400 0 3.395820`

> These fuckers melee attack from 30 yard range
`.go xyz 1036.530000 -1676.610000 61.290900 0 2.661190`

> Every time this mob activates Thrash (extra attack) the extra melee they receive will hit enemies at infinite range. A range check seems to be missing from the proc.
`.go xyz 1036.200000 -1806.180000 75.715000 0 3.283970`

> These mobs are meleeing me from 20 yards away.
`.go xyz 1051.550000 -1669.790000 60.912500 0 5.429620`

> Can auto attack from over 25-45 yards away once aggro'd not sure if thats due to pathing
`.go xyz 1118.060000 -1774.680000 62.626400 0 6.250720`

> They are attacking on very large range even when frozen
`.go xyz 1129.210000 -1769.400000 63.045300 0 5.946830`

**Comment by Shadownflame** [comment]
Fixed on beta.
