### ISSUE TITLE
Corruptor's Scourgestones - (5508)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2115]
**In Progress Reports**

> Corrupter, minion, and invader scourgestones all reward the same Honor gained

**Comment by Kestrana** [comment]
Assuming you mean XP since they don't award Honor at all...Yeah, they do.

![image](https://github.com/Project-Epoch/bugtracker/assets/41452431/c31cfd06-a37a-4c11-ad36-78c004b36a9b)
