### ISSUE TITLE
Devouring Ooze - (1808)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#215]
> Spawns 6 oozeling on death with 1k hp each.
Are you serious ?
This is an instant death sentence for any class that has no AoE and a pain in the ass for most classes.
`.go xyz 2280.210000 -2338.590000 62.757200 0 1.110000`

> The strength and quantity of Oozelings spawned by these enemies make them extremely difficult compared to other enemies in the area
`.go xyz 2366.980000 -2248.700000 56.253900 0 1.740370`

> they spawn 3 oozeling that have 1k hp each, a bit much for singe target mana users maybe
`.go xyz 2320.530000 -2363.690000 55.403200 0 0.059827`

**Comment by Bennylavaa** [comment]
blizlike
