### ISSUE TITLE
Spirit Totem - (8412)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2156]
**In Progress Reports**

> I suggest greatly increasing the drop rate of these items. I spent an hour on this quest alone and built up several stacks of various spider silks in the process, nice.

Anyway, the quest doesn't even mention the fact that only the Bears/Spiders on the West side of WPL are worth farming. The others towards the East have less than 1% drop chance, making this quest pure evil to people that don't know this.
I suggest increasing the drop rate to about 20-25% for ALL bears/spiders in WPL.

**Comment by Kestrana** [comment]
Blizzlike, drop rate looks like ~10% on eastern WPL mobs and 1% on western WPL mobs.
