### ISSUE TITLE
Kyle's Gone Missing! - (11129)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2163]
**In Progress Reports**

> I feed the dog, he performed  the "special dance", but I didn't get credit for the quest objective

> I fed hungry Kyle, and he did his little dance. However Ahab here does not accept this and it's not completable.

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/f8157720-2c41-47d1-8376-06b621ba24f3)
