### ISSUE TITLE
Arms of the Grimtotems - (11148)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2164]
**In Progress Reports**

> Items to collect are not interactive

> No idea where the quest item Blackhoof Armaments is supposed to be. Doesn't drop from any of the mobs as far as I can tell, killed about 20 of them. Nothing lootable in the village.

> Can't interact with the world objects that give these items

> The item racks from which these items have to be collected cannot be interacted with.

Proposed solutions: enable the world object interaction that would allow the collection of the quest items, or make the Grimtotem npc's in the area (Grimtotem Elder, Grimtotem Breaker, Grimtotem Spirit-Shifter to drop the Blackhoof Armaments)

**Comment by Kestrana** [comment]
This was fixed during the beta.
