### ISSUE TITLE
Just Desserts - (26147)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2169]
**In Progress Reports**

> Grammar error "I spent weeks, finding the best ingredients and researching the best recipes in order to give them a meal to remember." should have the comma removed after "weeks".

Spelling error "palettes" should be "palates"

Spelling error "Bring me some of the mana berries from the garden Ginger tends too." should be "Bring me some of the mana berries from the garden Ginger tends to.

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
