### ISSUE TITLE
Diseased Grizzly - (1816)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#217]
> Please massively increase the drop rate of 'Thick Black Claw'' for the Shaman Sunken Temple quest chain from these mobs. It is pure evil to advertise these as dropping these items, but then having less than 1% drop rate.
`.go xyz 1931.950000 -2272.460000 60.047200 0 6.140210`

**Comment by Bennylavaa** [comment]
this is blizlike, there are other npcs with a better drop rate.
