### ISSUE TITLE
Linus Stone Tips - (26156)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2174]
**In Progress Reports**

> Typo in completion "Now... Allow me to imbue the stone for you." is what it should look like.

**Comment by Bennylavaa** [comment]
In the first sentence there should either be 2 commas or no commas at all:
"[...] that my assistant, Linus, has been working[...]"
or
"[...] that my assistant Linus has been working[...]"

In the 2nd paragraph, there should be a comma after "Unfortunately

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
