### ISSUE TITLE
Beastial Allies - (26163)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2175]
**In Progress Reports**

> Spelling error in quest description:  have been poaced should be POACHED

**Comment by zana244** [comment]
Confirmed on internal.
Linking here duplicates from same quest series.

In the last quest, the whistle has the sound of a flask when it's being moved in the backpack.

Also, unless beastial is used as a pun, it should be bestial.

**Comment by Kestrana** [comment]
Fixed spelling in PR https://github.com/Project-Epoch/epoch-core/pull/1514
