### ISSUE TITLE
Keeping Us Warm - (26172)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2176]
**In Progress Reports**

> droprate is ASS !!!!

uch a low droprate, esp on a low level is a reason for me not to play this game ...

> There are wolves near the ramp to Ironforge which aren't Winter Wolves, but are right next to Winter Wolves.  It took me a moment to realize that I wasn't getting quest progress from killing them, since they look so similar.  It might be worth changing their model color or something?

**Comment by Bennylavaa** [comment]
the drop rate is like 100% its only from the winter wolves not the others.
