### ISSUE TITLE
Ore for Grumnal - (26174)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2178]
**In Progress Reports**

> Respawn rate of ore nodes very slow

> One of the Kinetic Ore nodes, in the frozen lake room, was spawned on top of and at the same time as a copper ore node.  It was the node in the northern 'nook' of the frozen lake room.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295 related
