### ISSUE TITLE
Carrion Lurker - (1821)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#218]
> Killed about 30 of these and not a single one dropped the 'Bloodshot Spider Eye' for the Shaman Sunken Temple quest chain. 
I suggest either removing these mobs from the list of mobs that can drop it (hovering over them tells you they can drop it), or significantly increasing the drop rate of it from these spiders.
`.go xyz 2425.170000 -1774.080000 103.077000 0 2.566630`

**Comment by Bennylavaa** [comment]
yet again blizlike there are other mobs with a higher drop rate.
