### ISSUE TITLE
A Village In Need - (26190)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2184]
**In Progress Reports**

> all good

> Raptors are dropping broken bows that sell for 56 copper and this is lvl 2 quest on raptor part i think thats a bit too much

**Comment by Kestrana** [comment]
Blizzlike ![image](https://github.com/Project-Epoch/bugtracker/assets/41452431/e5bc11bf-8453-4a77-bc2f-7487bf8ac086)
