### ISSUE TITLE
Our Bodies Forsaken - (26216)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2187]
**In Progress Reports**

> I use the symbol of life and he will revive but is yellow and attackable. Unable to complete the quest.

> This quest does not work properly. I did use Symbol of Life on NPC and he just did some roleplay(said 2 lines) and despawned. Quest item  was lost and i could not proceed to finish quest.

**Completed Reports**

> Did it again. I killed mob after ressurecting him. And it worked. Quest complete. A bit odd but ok

**Comment by Bennylavaa** [comment]
lol that is part of the RP read what the npcs says when you rez him
