### ISSUE TITLE
Scarlet Hunter - (1831)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#220]
> Scarlets in Felstone Field do not attack nearby Scourge
`.go xyz 1763.290000 -1211.880000 59.535600 0 4.619480`

> Pretty sure these Scarlet Hunters in Felstone field are supposed to attack undead. They didnt react in any way when standing right next to an undead mage mob.
`.go xyz 1787.370000 -1220.680000 59.508700 0 4.224030`

> The Scarlet NPCs often fail to "run away in fear" instead they just stand still for a second, and then go back to attacking the player.
`.go xyz 2111.390000 -1812.360000 58.915600 0 1.396630`

> Pet disappeared after killing the Hunter
`.go xyz 1916.330000 -1618.940000 60.664300 0 2.517380`

> Does not attack nearby undead.
`.go xyz 1877.750000 -1622.160000 60.586900 0 5.964540`

> Pet doesnt attack
`.go xyz 2099.380000 -1771.250000 66.149700 0 4.314340`

> Scarlet patrols (here and in Felstone field) are static, which looks weird and wrong (because it is), but also makes it difficult to enter the buildings because you'll pull half a dozen mobs
`.go xyz 1871.790000 -1611.710000 60.351200 0 0.954411`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8070

**Comment by Shadownflame** [comment]
Flee behavior resolved with generic fix. Pet issue reported elsewhere. RP behavior reported elsewhere.
