### ISSUE TITLE
Riders In The Night - (26311)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2200]
**In Progress Reports**

> There are only 5 Nightbane Tainted One spawns in the cave, making this quest really awkward, as you are forced to wait for respawns to be able to complete it.

> If you interact with Mardigan before you have finished the quest (e.g., only 5/6 slain worgen), he says "What are you doing here, Kai? Get to that mine." which makes absolutely no sense, as I am in the mine, right now. This seems like something that was intended to be said by the quest giver not the quest turn-in NPC.

**Completed Reports**

> This was a bit annoying. Required 6 kills, but there were only 5 spawns in the mine, so I had to wait for respawns and clear the entire mine again.

**Comment by Bennylavaa** [comment]
there are 14 spawns in duskwood. think outside the cave.
