### ISSUE TITLE
The Ring of Strength: Brokenhorn - (26409)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2209]
**In Progress Reports**

> Fire totem attacked, got destroyed the quest NPC dissapeared. I can abaddon and start again but still.

> Boss despawned upon exiting arena. Have to abandon quest to retry. Maybe add npc option to respawn.

**Completed Reports**

> bug with brokenhorn disappearing

**Comment by Kestrana** [comment]
As this quest is easily repeatable if this happens I don't think the effort to troubleshoot all possible pet scenarios is worthwhile.
