### ISSUE TITLE
The Lost Calf - (26426)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2214]
**In Progress Reports**

> unable to place calf bait outside inn entrance, just shows out of range

> I cannot place the bait so I cannot complete the quest,

**Completed Reports**

> I could only finish the quest at the third try (after abandoning twice) because I could not place the bait the two first times.

Perhaps because the first two times I was doing it through the item in the bag and not through the icon in the quest tracker, but all 3 times I was at the same spot.

**Comment by Bennylavaa** [comment]
works just fine
