### ISSUE TITLE
Scarlet Invoker - (1835)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#222]
> More of these need to spawn
`.go xyz 2125.090000 -1813.930000 65.805600 0 1.790550`

> Their spell casting, channeling, seems a bit strange. It will spontaneously fail without me pummeling.
`.go xyz 2124.790000 -1826.260000 62.509200 0 2.838710`

> These mobs auto-cancel their "Arcane missiles" cast.
`.go xyz 1900.120000 -1292.450000 62.521500 0 4.309650`

> All scarlet mobs here should attack undeads.
`.go xyz 1694.010000 -1247.390000 62.009700 0 0.523039`

> scarlet mobs don't fight scourge in felstone field
`.go xyz 1790.390000 -1216.230000 59.500800 0 4.146180`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8070

**Comment by Shadownflame** [comment]
I cannot reproduce the issue with interrupting their own spellcasts. Other issue reported elsewhere.
