### ISSUE TITLE
Turtle Power - (26487)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2222]
**In Progress Reports**

> The quest is yellow at 43 however the quest target mobs are 48-50 so orange/red.

> Quest is level 45 but turtles are level 49-50

> quest is green at lvl 48 despite the mobs being lvl49-50

**Comment by Bennylavaa** [comment]
The quest "Turtle Power" spells the Lean Turtle Flanks as "Lean Turtle Flank's". There's an extra apostrophe that is unneeded.

![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/b6719aba-781d-407f-8cd4-605abc32dd6c)

**Comment by Kestrana** [comment]
Spelling Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Kestrana** [comment]
Fixed level issue in https://github.com/Project-Epoch/epoch-core/pull/1597
