### ISSUE TITLE
Oil Baron Beatdown - (26518)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2235]
**In Progress Reports**

> Typo in the quest description. The text says

"He goes by the name of Overseer Looney and apparently can be find right at the top of the rig in his control room". 

It should instead say

"He goes by the name of Overseer Looney and apparently can be found  right at the top of the rig in his control room". 

 "find" is to be replaced with" found".

**Completed Reports**

> quest text forgots to mention npc who you turn in the quest

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
