### ISSUE TITLE
A Saboteur In Our Midst - (26526)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2242]
**In Progress Reports**

> Typos:

Quest text states "a sabateur". That is incorrect. The English form of this word is "saboteur".

Quest objection typo:

Text says "Question Bruser's", which is incorrect. The proper form is "Question Bruisers".

**Completed Reports**

> The guards can be questioned even when not on the quest.

> Works

> I could question some npcs for this quest before this quest was even available. Specifcially I noticed it for a sleeping guard in a house here.

> In the original quest text "saboteur" was misspelled as "sabateur".

> The guards have the text option belonging to this quest even when you are not on the quest. Before unlocking this quest I thought it was some sort of hidden secret they were pointing towards

**Comment by Kestrana** [comment]
Spelling fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Bennylavaa** [comment]
looks good
