### ISSUE TITLE
A Chilly Stranger - (26532)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2245]
**In Progress Reports**

> Sturdy Root had a pretty low drop rate. Maybe 20-25%.

> The Sturdy Roots drop rate is way too low. If there was competition I wouldn't do this quest again. Also... it would be helpful if more of the new quests mentioned where to turn them in. Without quest helpers it's hard to remember where to go to turn in quests since they don't say.

**Comment by Bennylavaa** [comment]
not really that low I would say its more like 40% seems fine to me.
