### ISSUE TITLE
They Mostly Come At Night... Mostly - (26539)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2248]
**In Progress Reports**

> This quest is a nightmare. First off, there just aren't enough Nightstalkers crawling around. If even one other player is in the area working on the same quest, it becomes a miserable experience. Secondly, the drop rate is nowhere near sufficient, compounding the first issue. And last but certainly not least, I watched a Nightstalker corpse despawn before I could even loot it. I was fighting a second mob that aggro'd and before I could kill it, the dead Nightstalker disappeared. It took about 4s

**Comment by Kestrana** [comment]
Can't confirm. I see a lot of Nightstalker spawns at each of the hives. The despawning may have occurred due to the day/night cycle shift but can't reproduce.
