### ISSUE TITLE
The Southern Hills - (26697)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2283]
**In Progress Reports**

> Typo spotted in quest. Doman = Domain?

Also, the quest doesn't allow me to complete it. I approached the shrine, but it still says I have to locate it and cannot progress the quest.

> Well, I have found a Sunken Shaman Shrine but it won't allow me to progress the quest in any way.

> Pretty sure this shrine is supposed to let me communicate with the fire elemental quest giver, but it seems broken

**Completed Reports**

> Approached this shrine once from the north and the quest didn't update or allow me to complete it.  Leaving and approaching from the south seemed to fix it.

> Quest progesses only if you approach from the South?

> This quest required me to run past the stone about 100 yards to complete, rather than just arrive at the stone

> I had to kind of run past the shrine as if I was ignoring it to trigger the quest completion credit.

> Hm ok I moved slightly further south and the objective completed. Think the objective marker location needs adjusting slightly

> This was weird. Quest didn't complete when I approached the shrine, but when I ran away I suddenly got completion and could hand the quest in.

> The zone trigger for this quest is not in the right position. To complete the quest, you need to walk a little further south of the pillar to discover it.

**Comment by Kestrana** [comment]
Spelling fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Bennylavaa** [comment]
the other errors I cannot reproduce
