### ISSUE TITLE
Reagants For The Undercity - (26738)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2286]
**In Progress Reports**

> Seems to be a lack of Doomwarder Captains/Lords. Perhaps you folks forgot to populate the cave south of Mannoroc Coven?

**Comment by zana244** [comment]
Typo in the title, it should be Reagents

**Comment by Kestrana** [comment]
Spelling fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514

**Comment by Bennylavaa** [comment]
spelling looks good on ptr
