### ISSUE TITLE
Those Unrecovered - (27262)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2293]
**In Progress Reports**

> Cannot continue this quest, I have the cloak from talking to nazgrel but when I try to talk to Patrick Milis and inform him of what nazgrel said the click on the text does not register.

> The dialog option to deliver the Tattered Cloak does nothing, so this quest can't be completed.

> Can't turn in the cloak to him since it doesnt allow me to click the dialogue option

> Can't talk to the npc to finish the quest, every time i click the option nothing happens

**Comment by Shadownflame** [comment]
The RP seems to be working properly now when speaking to Patrick Mills.
