### ISSUE TITLE
Tirion Fordring - (1855)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#230]
> nvm im an idiot
`.go xyz 2656.550000 -2468.510000 70.672800 0 6.100890`

> cant get Taelan's Hammer from the dirt mound for the quest "Of Forgotten Memories
`.go xyz 2669.650000 -2477.780000 72.475300 0 6.093720`

**Comment by zana244** [comment]
Drops as intended from Mercutio Filthgorger.
