### ISSUE TITLE
The Fizz - (27288)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2300]
**In Progress Reports**

> The quest text implies that you're supposed to receive an item to charge. No item received on quest pickup.

> never gave the quest item.

> The device talked about in the quest description for use in the quest is not given to the player upon accepting the quest

> No quest item provided by npc

> Quest giver doesn't give you the quest item

> Tanum doesn't give you any item to charge with

> might be based on a quest item, which is NOT given on quest accept.

> appears before you turn in the wraithroar quest.

> He does not give me the quest item needed to proceed.

> I think the quest "The Fizz" is bugged, since it mentions a device I'm supposed to use on mobs, but it doesn't provide any item to use.

> The quest dialog implies that you're supposed to get a device to charge using the lightning breath from nearby chimeras, but you don't actually get anything in your inventory and just killing chimeras doesn't seem to work, so the quest can't be progressed.

> Based on the quest text, I assume you're supposed to receive a quest item upon accepting the quest(?) and use it to collect the charges but I did not receive one, tried abandoning and reaccepting the quest multiple times and still not getting anything.

**Completed Reports**

> From the description of the quest, it sounds like Tanum is giving you some item/device to use on the Chimaeras. I was looking in my inventory and it was just confusing me.

Also, this quest is pretty dull. The fastest way to do this quest is just pull the Chimaera that spawns just behind his hut, and then go afk and grab some drink. Come back to a completed quest. 

Going AFK shouldn't be the best way to do something, very non-interactive!

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/7599

**Comment by Bennylavaa** [comment]
looks fully related to the one linked closing this as a duplicate. I will mention the afk stuff seeing there is only one mention of that, tbh making it a item that you have to use or something would fix both of these complaint. 

edit nvm you already did :P
