### ISSUE TITLE
Cooking with Carrion - (27372)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2304]
**In Progress Reports**

> There's no lootable eggs anywhere, quest can't be completed.

> 1. I did not see vultures north of andorhal.
2. Why do I even have to kill vultures when they have nests with eggs on the ground?
3. The eggs in the nests are very bright, almost glowing.

> It's odd that the eggs drop off of the vultures instead of being collected from their nests. Also, I wasn't able to find any vultures in the northern part of the zone

**Comment by Kestrana** [comment]
Vultures share spawns with Bears/Wolves/Spiders. 
The nests are for a different quest.
