### ISSUE TITLE
Advanced Alchemy - (27375)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2305]
**In Progress Reports**

> This quest is sorted under Elwynn Forest in the quest log, but it takes place in Western Plaguelands.

> Appears in elwynn forest category instead of western plaguelands in quest log.

> Quest assigned tos incorrect zone - Elwynn Forest.

> This and Scourge Botany are mistagged as Elwynn Forest in the quest log.

> This quest is wrongfully listed under "Elwynn Forest

> This quest is grouped under Elwynn Forest in the Log Book.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8300 merging into the overall bug for this chain.
