### ISSUE TITLE
Senior Prank - (27382)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2307]
**In Progress Reports**

> It might be worth mentioning that Scarlet Invokers can be found at the various Scarlet Camps across Western Plaguelands.

Also, the drop rate of this item needs to be greatly increased. There's only a few Scarlet camps in WPL and only 1-3 Invokers at each camp. I shouldn't have to run between these camps 2-3 times waiting for Invoker respawns just to get this drop.

**Comment by Kestrana** [comment]
Not every quest is going to have abundant mobs and high drop rates. This quest is intentionally more time consuming than most others in this chain.
