### ISSUE TITLE
A Matter of Life and Death - (27432)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2311]
**In Progress Reports**

> The quest text says to sample 3 different types of ghosts, but then the quest objective says to sample any 10.

**Comment by Kestrana** [comment]
Confirmed, this was because in implementation it wasn't working as originally designed so we made it any 10 ghosts but the quest text wasn't updated to reflect the change.

**Comment by Kestrana** [comment]
Fixed by https://github.com/Project-Epoch/epoch-core/pull/1597
