### ISSUE TITLE
Berserking for Beginners - (27544)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2325]
**In Progress Reports**

> Flask of Big Mojo is more likely to drop from Vilebranch trolls in Jinthalor in Hinterlands, or Sunken Temple. The quest suggests to try jungle trolls in general. Maybe add a more specific description of where to obtain the Mojo, or require just a Flask of Mojo (which drops from the trolls in STV)

> Typo in quest text Hal'deh refers to himself as "Hal'eh

**Comment by Kestrana** [comment]
Fair feedback, will make updates.

**Comment by Kestrana** [comment]
Cloesd by https://github.com/Project-Epoch/epoch-core/pull/1597
