### ISSUE TITLE
Rarest of Them All - (27588)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2329]
**In Progress Reports**

> When you said rare you really meant it. I fished for hours in multiple spots in Azshara. Open water, fish pools, bay of storms, little in land pools...nothing. Im starting to question if this quest works.

**Comment by Bennylavaa** [comment]
this will need to be retested after the fishing fix @Bunnyblock2

**Comment by Bennylavaa** [comment]
Fixed with the new fishing level system
