### ISSUE TITLE
Scarlet Smith - (1885)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#233]
> Sees through the Scarlet Disguise buff and attacked me while on Scarlet Subterfuge. Looting this NPC broke the disguise, but not fighting?
`.go xyz 2939.290000 -1492.000000 146.411000 0 2.085600`

**Comment by Bennylavaa** [comment]
Scarlet Smith doesnt see through the buff, also any looting of those npcs will trigger the buff to leave this is intended.
