### ISSUE TITLE
The Shrine of the Deceiver - (27722)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2339]
**In Progress Reports**

> Maybe the writers of the quest know better, or there's a follow-up that explains this (after all some of the yellow text seems to be about the comics which I'm not familiar with), but why would Burning Legion cultists have a memento of Illidan when the others are Legion leadership? Doesn't seem to fit.

> Doesn't make sense for Demon worshippers to have a memento of Illidan, a Demon Hunter.

**Comment by Kestrana** [comment]
Fair enough feedback, I can change it to something else.

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
