### ISSUE TITLE
Missing In Action - (219)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2360]
**Completed Reports**

> might be wrong, but it feels like his attacks on mobs shouldn't result in a chunk of them not being lootable.  honestly forget if it is a damage of total health threshhold or not

> Keeshan has quite a large aggro radius, sometimes attacking random mobs on the road back to Lakeshire. Within the cave it was fine

**Comment by Kestrana** [comment]
I did this quest on Classic and Keeshan does indeed aggro on all sorts of mobs along the road on your way back to town. If you do not damage mobs you won't be able to loot them. Can't confirm.
