### ISSUE TITLE
Frostmane Hold - (287)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2362]
**Completed Reports**

> Completion quest text says Senir Whitebeard is at Shimmer Ridge when he is actually at Kharanos.

> I completed the escort quest "Breaking the Ice" without getting credit for fully exploring frostmane hold.  I'm not saying this is incorrect, it just felt weird having to turn around and go back into the cave to find where the exploration spot was.  It might be worth changing his route or moving the exploration spot?

**Comment by Bennylavaa** [comment]
this quest works as it should
