### ISSUE TITLE
Free From the Hold - (898)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2378]
**Completed Reports**

> This quest has an enormous missed opportunity: having the escort end as you leave Northwatch hold (it's not exactly interesting to fight against mobs that, for most players doing the quest, are probably already gray). This is rather iconic content in how awful it is, but then, Mankrik's wife is even more iconic.

Also, escort AI is not at all blizzlike, and on this quest it's particularly apparent. This quest would be a good place to cross-reference retail footage.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/406
