### ISSUE TITLE
Onu is meditating - (960)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2382]
**Completed Reports**

> Legit no freaking clue what to do, no info, can't complete the quest, nada

**Comment by Kestrana** [comment]
When you have more information, speak to me through a scrying bowl.  If you require a [phial of scrying](https://www.wowhead.com/classic/item=5251/phial-of-scrying) in order to create a bowl, then...here is another.

Use the Scrying Bowl
