### ISSUE TITLE
The Missing Diplomat - (1266)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2386]
**Completed Reports**

> something was wrong. First had to fight hendel, then there was the script with jaina and the other mage and they took him away. Had to w8 for him to respawn (now friendly) to turn in the quest

**Comment by Kestrana** [comment]
It sounds like someone else had started the event (Private Hendel turned unfriendly) when this person came up to turn it in. In that case, what they experienced was correct.
