### ISSUE TITLE
Aurius' Reckoning - (5125)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2410]
**Completed Reports**

> This quest is bugged and he immediately dies in the chapel instead of partaking in the Rivendare fight.

**Comment by Kestrana** [comment]
Correct, this does not have the intended behavior, consistent with Stratholme not having been implemented in TrinityCore. From Wowhead, a description of the correct behavior is:  "Partway throught the fight, Aurius shows up and attacks the baron - it is to my understanding that he will also heal members of your party, as he is a paladin. Once the baron is down, Aurius collapses and allows you to complete the quest, choosing either the necklace or ring for your reward." @kaytotes for more Stratholme updates

**Comment by kaytotes** [comment]
Added to stratholme parent issue and closing.
