### ISSUE TITLE
The First and the Last - (6182)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2417]
**Completed Reports**

> Reference to "SI:7" instead of correct word, in quest-text, door-sign of the building, tooltip info of the npc's

P.S.: <3 your work!

**Comment by Kestrana** [comment]
SI:7 is not mentioned in this quest at all but it correctly tells the player where to find Matthias Shaw. SI:7 is a legitimate in game reference to this location as well. Unclear what is at issue here.
