### ISSUE TITLE
Deadwood of the North - (6221)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2418]
**Completed Reports**

> This quest should definitely not be greyed out at lvl 57. There were still yellow-lvl mobs here.

> this quest still says to meet grazle at the emerald sanctuary

**Comment by Kestrana** [comment]
1. Correct. This a level 55 quest and isn't grey until level 66. Available at 45.
2. Correct. This text needs to be updated to the later version with Grazle's correct location.

**Comment by zana244** [comment]
Seems to have been fixed on internal. Quest ID 6221 is deprecated for Grazle, Nafien gives instead quest ID 8461 which rewards XP. Quest becomes grey at 64 but that is a non-issue :D.
