### ISSUE TITLE
Webwood Spider - (1986)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#242]
> wierd pathing
`.go xyz 10848.000000 926.039000 1334.840000 1 6.198980`

> This mob dropped linen cloth, is it supposed to?
`.go xyz 10724.600000 928.736000 1329.530000 1 5.246280`

> I get line out of sight error even though I have a direct line of sight to it. Might be because the spiders is on the cave object, while I am not.
`.go xyz 10726.600000 945.549000 1331.190000 1 5.558830`

**Comment by Bennylavaa** [comment]
for the los the cave has a lip and that is what is breaking the los.
