### ISSUE TITLE
Escaping Airheart

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2462]
**Completed Reports**

> Terrible escort in it's current state. Needs some heavy revision.

1. The enemy appear to be using retaliation, The escort NPC can kills self even if you tank for them.
2. Escort NPC has low hp and dies in 5 of any attack. NPC is also non targetable, can't heal.
3. Character sprints off abruptly at a higher speed than player movement. Keeps rushing into pulls before HP is even restored.
4.enemy ambushes spawn on top of just cleared locations.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7228
