### ISSUE TITLE
The Killing Fields

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2480]
**Completed Reports**

> The text says "you can find some [Harvest Golems] right on this farm, or at the Molsen Farm".

But the mobs en these two farms are actually Harvest Watchers so don't count for the quest. 

Quest text should be ammended.

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/54da474f-bcc5-486f-9e5e-a68fc56994d3)
but they are on his farm
