### ISSUE TITLE
Crazed Carrion

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2483]
**Completed Reports**

> love the added quest here  :)

> brings peace to the aging Kodo who journey to this place you have done"... punctuation!

**Comment by Shadownflame** [comment]
This seems to have been already fixed. There is a dot at the end of "place" and "you have done" starts with a capital Y. There is no comma missing between "Kodo" and "who" as the latter half of the sentence is not a nonrestrictive clause but belongs to the noun as a definer.
