### ISSUE TITLE
Advanced Alchemy

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2493]
**Completed Reports**

> outside the courtyard walls to the east" doesn't make much sense here, probably should be removed?

> Quest says "Speak with Proctor Blackwood" NPC name is Proctor Phillips

> Quest text says find him to the East. Pretty sure I had to travel west from last NPC. Though perhaps I'm mistaken <3

**Comment by Bennylavaa** [comment]
duplicate of https://github.com/Project-Epoch/bugtracker/issues/8300
