### ISSUE TITLE
The Legend of Aru-Talis

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2507]
**Completed Reports**

> Site four does not appear to have a subzone, making it much more difficult to locate than the others.

> Aru-Talis Site Four doesn't appear on your screen when you enter its location. This can confuse players like myself that ran a whole lap trying ot find Site #4. All the others have their name pop-up on your screen when you enter their area. Site #4 does not.

Also, you should probably just combine all the rubbing items into one. No need to fill up 4 different bag slots.

> One of the areas being in "Slithering Scar" subzone was incredibly confusing (others being "Fourth Aru-Talis area whatever")

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
