### ISSUE TITLE
Defensive Stance

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2526]
**Spell ID's:** 71

> The stance is not shown in buffs, only battle stance is shown in buffs.

> Battle stance is a buff, but defensive stance isnt

> warrior stances are using wrath animations instead of vanilla/tbc. here is defensive stance 
https://www.wowhead.com/classic/spell=71/defensive-stance#screenshots:id=69546

**Comment by zana244** [comment]
Using 3.3.5 client aura, up to devs if they want to change. Does not show as buff, intended, only battle stance is bugged.
