### ISSUE TITLE
Slow Fall

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2529]
**Spell ID's:** 130

> This spell doesn't work as in vanilla or classic. in vanilla and classic with this spell the mage could jump wider. This was used for example to get the quest at the Tandol Span, the questgiver could only be reached with a long jump.

**Comment by Shadownflame** [comment]
Slow fall does properly extend your jump and you can reach thandol span just fine.
Classic uses some modern version of slow fall that takes you in a greater arc but epoch is using the old version.
