### ISSUE TITLE
Curse of Recklessness

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2544]
**Spell ID's:** 704, 7659

> Should break the fear effect when applied after Fear, and also fear shouldn't work when applied before.
I was able to fear but only the visual effect applied which is weird.

> Only works if you cast it before the target suffers from fear

> Recklessness is not breaking fear

> This spell is not getting increased range from the Grim Reach talent.

**Comment by zana244** [comment]
See issue.
Also, indeed, it does not benefit from Grim Reach talent on internal.
