### ISSUE TITLE
Demon Armor

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2545]
**Spell ID's:** 706, 1086, 11733

> Applying this spell should overwrite Demon Skin buff, but it doesn't

> Demon armor do not overwrite Demon skin. Demon skin is lower rank buff

> Higher level buff cannot overwrite lower one.

> flight path from theramore to tanaris flies thru new steamweedle port building

> casting demon armor doesn't override demon skin

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4007
