### ISSUE TITLE
Cat Form

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2547]
**Spell ID's:** 768

> When I shapeshift into Cat Form it always says "That ability is not ready yet" as if i t's trying to cast another spell after cat form

> Able to parry attacks in shapeshift form, probably not intended

> Any druid form makes it being immune to sap

**Comment by zana244** [comment]
first two issues are solved on internal.
last one is non-issue, it's tbc mechanic (and vanilla)
