### ISSUE TITLE
Disengage

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2550]
**Spell ID's:** 781, 14272, 14273

> disengage rank 1 and 2 dont share a CD!
this would be major op in pvp

> Does not always work

> NERF ME

> 5 second cooldown is ridic. Make it longer cool down and make it a bigger jump then it will be balanced. I can spam this against melee and they auto lose

> Tooltip still says 5sec cooldown

> shouldnt be on gcd

> Does not have a 5s cd

> It's possible to use Disengage while I'm rooted
(The root effect still stays on me, I just fly backwards)

> No tooltips available for any spells

**Comment by zana244** [comment]
The skill cooldown is 25 seconds, but casting 1 rank will incur only a 5 second cooldown on the other 2 ranks (it has 3 ranks in total)... major bug.

Also, you can cast it while rooted and it actually flies you backwards... I think it should tell you it's unavailable and not incur a CD.

Would be nice to not be on the GCD, but it might be too OP anyway.
