### ISSUE TITLE
Blessing of Salvation

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2557]
**Spell ID's:** 1038

> Count as both, a blessing and a hand

> This spell reomves Hand of Freedom and vice versa. Shouldn't happen according to the "Custom Content" section on the Project Epoch website.

**Comment by Shadownflame** [comment]
Confirmed, spell currently behaves both as blessing and hand when it comes to buffing. Should be only exclusive with blessings.
