### ISSUE TITLE
Aquatic Form

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2558]
**Spell ID's:** 1066

> You get unshifted from Walrus form if you run along the sea floor; it seems to think you're not longer underwater I guess?

> I am getting knocked out of Aquatic from when hitting the sand right in front of the pier in Steamwheedle Port

> Is dispelled any time you make contact with the seabed - may relate to custom terrain, or might just happen everywhere.

> cancels at seemingly random times while still under water

**Comment by zana244** [comment]
#8308
