### ISSUE TITLE
Blackwood Totemic - (2169)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#256]
> Not sure if this is a bug with this particular enemy, but it has 1 Linen Cloth in his loot bag inventory, it is currently being displayed on my screen, right clicking it gives me a red font error saying "Already looted".
`.go xyz 6849.640000 -452.654000 43.122200 1 1.717630`

**Comment by zana244** [comment]
Sounds like a scavenging bug.
