### ISSUE TITLE
Drain Soul

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2560]
**Spell ID's:** 1120, 8289, 11675

> Improved Drain Soul doesn't work, no mana return.

> Drain soul will not cast if below 210 mana

Drain Soul spends ~19 mana per tick but you need 210 mana to cast it

> Drain Soul tooltip does not reflect mana cost changes

> since drain soul is now mana/per, make it tick every seconds please!

> using a channel ability against player pet causes fast spinning

> low mana cost, insanely high damage

**Comment by Shadownflame** [comment]
1-4 resolved
6) needs a group test lol

**Comment by Shadownflame** [comment]
Pet doesn't spin when drained.
