### ISSUE TITLE
Power Word: Fortitude

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2563]
**Spell ID's:** 1243, 1244, 1245, 2791

> The tooltip in the buff says it incrases my stamine by $w1

> Bugged tooltip for buff

> says stamina increased by $w1 when used on a lvl 1 player as a lvl 45

> says "increases Stamina by $w1"
(might be an addon conflict but i dont know which it would be if so)

> The description says "Increase Stamina by $w1" 
if it helps, i'm a gnome priest. Thxs :)

> Spell reads "Increases Stamina by $w1.

> Tooltip says "Increase Stamina by $w1.

> the tooltip says "Increases Stamina by $w1" instead of a number. It has been like that with 2 ranks of the spell

> Description text bugged

> The spell tooltip says "Increase Stamina by $w1." instead of the number of the stamina it increases

> Rank 2 of power word fortitude.

Info on skill on action bar says it increase stamina by 10, info on buff bar says by 8.

I have increased talent points so maybe info on buff bar does not update withou relog

> Buff says "Increases Stamina by $w1.

> Spell boosts stamina by $w1.

> Increases Stamina by $w1

> incorrect name its $w1

> When spellstolen the buff as a mage with [Spellsteal] it shows the value of "increases Stamina by" as "$w1" instead of a number.

> Wrong tooltip from buff. Is says "Increases Stamina by $w1.

> The tooltip doesnt show the actuall stamina value. It seems to show only the variable name e.g. $w1

> tooltip for stamina says $w1

> values bugged display

> tooltip reads "Increases Stamina by $w1." which appears incorrect.

> Displays "Increases Stamina by Sw1." instead of its normal value.

> When I hover over it it says "Stamina increased by $w1

> tooltip does not correctly display stamina number

> Description is bugged, it says "Increases Stamina by $w1

> Power Word: Fortitude displays "$w1

> While casted on self or a target and hovering the mouse over the buff it says "Increases Stamina by $w1

> Hovering over the buff says "Increases Stamina by $w1.

> values not right

> Buff on friendly player says a variable instead of a value
"Increases Stamina by $w1

> give "$w1" stam

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5506
