### ISSUE TITLE
Levitate

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2569]
**Spell ID's:** 1706

> When using Levitate you are able to stick on walls. 
Example: Use Levitate and walk against a mountain that is normaly unclimbable, keep walking against it while pressing A or D (strafe). You will notice that your Character will stick on the Mountain allowing you to basically float in mid air.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4661
