### ISSUE TITLE
Darkshore Thresher - (2185)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#258]
> Instantly resets if player jumps above water surface
`.go xyz 6584.090000 764.419000 -13.446700 1 1.134170`

> Cant be melee  attacked, but it can attack you back,
`.go xyz 6636.550000 592.315000 -1.710720 1 6.229810`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
