### ISSUE TITLE
Bloodlust

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2583]
**Spell ID's:** 2825

> Displays as Rank 1.

> Tooltip says "party" when it's raidwide, also mentions Heroism when it doesn't exist.

> Mana cost is too high. It is the same as in TBC: 750. Something like 400~500 i more reasonable for  lvl 60 I think

**Comment by zana244** [comment]
Indeed bloodlust appears as rank 1... cosmetic issue.
Same with the party vs raid. Heroism does exist though, being the BL counterpart for alliance.
Not sure mana cost is an issue, it's a big buff, up to devs to change.
