### ISSUE TITLE
Far Sight

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2614]
**Spell ID's:** 6196

> far sight does not work at any distance

> I'm getting "The spell is not available to you" when using it, in outdoors (Tanaris desert). Distance of the spell does not change anything.

> disabled in beta environments" im assuming nothing is out of bounds in beta 3, except instanced

> Spell still broken from last beta

**Comment by zana244** [comment]
beta specific issue... disabled in tooltip
