### ISSUE TITLE
Eagle Eye

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2615]
**Spell ID's:** 6197

> dont work

> Error 'The Spell is not available to you'

> says this spell is not available to me

> spell does not belong to you

> When I try to use this spell, it just says "This spell is not available to you.

> Eagle Eye doesn't work "This spell is not available to you

> gives an error message "this spell is not avaliable to you" and does not cast at all.

> Can't use and get the message "That spell is not available to you

**Comment by zana244** [comment]
beta specific issue... was written in tooltip.
