### ISSUE TITLE
Create Firestone

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2618]
**Spell ID's:** 6366, 17951, 17952

> I couldn't use the Firestone on a ilvl 24 weapon but it seems quite odd as I don't remind we couldn't use our spell enchant on any weapon. Might be a bug

> Tooltip for firestone not updated

> weapon level requirement not listed

**Comment by Shadownflame** [comment]
Confirmed, firestones all have some unhinged level requirement. None of the ranks are possible to use with the gear available at their intended level. I'm not even sure why they have any requirement, considering they are soulbound and not possible to use for friends/alts etc. You should be able to put it on anything you wear, no matter how poor level/quality it is.

Cosmetic issue: the firestone item description is missing a dot from the end of the sentence for each rank.

Item IDs 1254 (rank1), 13699 (rank2), 13700 (rank3), 13701 (rank4)
Spell IDs 6366, 17951, 17952, 17953
