### ISSUE TITLE
Sentry Totem

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2619]
**Spell ID's:** 6495

> Not sure if this totem is supposed to spawn over 100 yards from caser in a random location.

> The totem places itself 20 times farther from the Shaman than it should be. Also you cannot switch to totem sight if you mounted and dismounted after placing the totem

**Comment by Hatson22** [comment]
This is a very strange bug. I'm not sure exactly what's going on with its behavior, but I can confirm it can spawn at varying ranges away from the Shaman. Needs to be looked into further.

https://github.com/user-attachments/assets/2f3a6399-49d7-40d4-8228-b8ad2046193c
