### ISSUE TITLE
Contagion of Rot

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2629]
**Spell ID's:** 7102, 7103

> Multiple Contagion of Rot debuffs are stacking on me

> Is able to have multiple applications

> Zanzil zombies able to stack this debuff, pretty overpowered

> can have multiple instances of the debuff which stacks?

> It's possible to get multiple individual instances of this spell applied, when a new application should merely refresh its duration.

> Multiple applications stack

> it can be cast multiple times by one mob and they stack with all of these types of mobs here and the time between attack keeps stacking

> For some reason you can spread it to yourself so u get 2 debuffs instead of one.

> LUA error on mouseover

> Ability seems to stack instead of refreshing when applied by different mobs.

> these are supossed to stack?! bc they are stacking.

> got this debuff twice from a single mob, according to the tooltip the chance to spread differs. Still one mob should not give the almost identical debuff twice
IDs: 7102 and 7103

**Comment by zana244** [comment]
Seems to have been solved on internal, only ID 7102 is being cast... tested zanzil, feralas gnolls and ghouls in WPL.
