### ISSUE TITLE
Rockbiter Weapon

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2643]
**Spell ID's:** 8017, 8018, 8019, 10399, 16315

> Rockbiter weapon is not refreshing and overwriting the buff time, tested at 10 minutes and down to 2 minutes it never refreshed the buff.

> Recasting weapon enhancement doesn't reset duration: have to click off buff first

> Rockbiter 1 does not overwrite exisitng Rockbiter 1 on weapon, thus refreshing the Buff Duration.
For example, weapon had 2 mins left, trying to cast Rockbiter 1 used mana, but did not refresh the weapon buff. I had to wait until the buff full left the weapon before recasting

> Can be replaced by flametongue but cannot replace flametongue, i have to manually remove the flametongue buff and then reapply rock. Ive only tested this with rockbiter rank 2 and flametongue rank 1

> Of the weapon imbues Rockbiter is the only one that will not overwrite other buffs or itself.

> Rank 2 of the spell will not overwrite Rank 1 of the spell ( previously reported Rank 1 would not overwrite Rank 1 to refresh the cooldown)

> Cannot refresh rockbiter if there is another enchanmnt applied(FP, FT, rock, doesnt matter)
It seems only rockbiter has this issue

> reusing spell does nbot refresh duration

> Buff does not refresh or replace other Shaman weapon enhancement when activated.

> Can't refresh the spell while applied.

> dont apply when recast for offhand. Need cancel buff on offhand weapon and after that its apply.

**Comment by zana244** [comment]
#7823
