### ISSUE TITLE
Disease Cleansing Totem

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2651]
**Spell ID's:** 8170

> Does not tick on initial cast.

> Disease cleansing totem should remove diseases as soon as it is dropped. Currently it removes diseases on first tick instead. 

Poison cleansing totem works correctly. This one isn't.

> should cleanse disease instant it is dropped

**Comment by zana244** [comment]
Confirmed on internal, it should tick as soon as it's dropped. It does not atm.

**Comment by ZugZug11** [comment]
As i recall, during beta Disease Cleansing Totem was cleansing both poisons and diseases at the same time, forgor to report it and i guess noone else found out. Pls check, maybe am wrong.

**Comment by Hatson22** [comment]
Can confirm what ZugZug mentioned above, there's also even more bugs related to this totem, since it's still using the 30yd base range from WotLK. Going to attach a reference to my bug report regarding it and Mana Tide here.
