### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2657]
**Spell ID's:** 8417, 10212

> if clearcasting is proc'd this spell does not cast

> sometimes the spell immediately cancels after mana is spent to cast. also triggers a gcd

> Sometimes doesnt work, like not to any damage but takes a global cooldown

> Sometimes the spell just fails, goes on gcd, takes the mana but then doesnt cast. Doesnt show up as miss or resist or anything and i'm certainly in range and not moving or being interrupted.

> If arcane missiles misses or gets resisted fully (the spell doesnt cast at all) it shouldnt consume the stacks from arcane blast but right now it does.

> Arcane Missiles costs way too much mana. It completely breaks the Arcane spec.

The rotation is designed to built X3 stacks of Arcane Blast, using Arcane Missiles to deplete those stacks and cause Arcane Barrage.

But Arcane Missiles costs 10% of my mana to cast one time. It doesn't fulfill its purpose. As of now, it's better to point 0 points into Arcane Missile talents and spam Arcane Blast mindlessly and ignore the stacking mana penalties, because Missiles still is worse for mana.

**Comment by Shadownflame** [comment]
Mana cost corrected mid beta.
Spell failing to cast reported here https://github.com/Project-Epoch/bugtracker/issues/5003
Misses/Resists consuming stacks to be confirmed.
