### ISSUE TITLE
Eviscerate

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2658]
**Spell ID's:** 8623, 8624

> I sometimes get through the damage without reseting the combo points, i dont think i got any talents giving me that ability.

> (Rank 6, does less damage than the tooltip

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4077

**Comment by Shadownflame** [comment]
1) resolved
2) is due to enemy armor, damage values check out
