### ISSUE TITLE
Rip

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2663]
**Spell ID's:** 9752, 9896

> Occasionally does not consume combo points despite the debuff being applied to the target.

> The 0.5 set bonus increases the duration by 3 seconds. However, this ability ticks every 2 seconds. So now you it lasts one second too long and does nothing :)

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4077

**Comment by Shadownflame** [comment]
1) resolved
2) tier bonus now increases duration by 2seconds
