### ISSUE TITLE
Conjure Mana Ruby

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2667]
**Spell ID's:** 10054

> it does not have 3 charges

> I only have 1 charge of this spell but....

Conjure Mana Ruby now has 3 charges to mimic the Burning Crusade rank of Mana Gem known as Mana Emerald."

Am I doing something wrong? I have it at 1 charge, and try to make another, but it won't let me. Using it, and I have 0 charges,

**Comment by zana244** [comment]
solved on internal, has 3 charges which behave correctly.
