### ISSUE TITLE
Blizzard

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2668]
**Spell ID's:** 10186

> Sometimes Blizzard takes the mana cost but fails to cast when you attempt to cast it at max range. This is not supposed to happen, if the spell fails due to range it should not take the mana cost.

**Comment by Shadownflame** [comment]
I can't seem to reproduce this on the internal realm, but experienced the spell sometimes interrupted on beta. Might not be a range issue, but possibly something else.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5003 related
