### ISSUE TITLE
Inner Fire

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2674]
**Spell ID's:** 10952

> If I learn Improved Inner Fire, under buff section, I don't see changed numbers. For example, Rank 6 has 1395 Armor by default and 1813 as buffed, if 3 points were spent on. I can see buffed value (1813) under my character sheet but not on buff section (1395)

**Comment by zana244** [comment]
Works perfectly. Snapshotting tooltips works in cataclysm and beyond.
