### ISSUE TITLE
Battle Shout

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2678]
**Spell ID's:** 11551

> The action bar tooltip says it should give 241 AP with 5/5 Commanding Presence but the buff tooltip still shows it's only giving 193

> Not really a bug, but would be good to have warrior shouts 5m duration instead of 2m.

**Comment by zana244** [comment]
Typical client limitation, that gets solved in Cataclysm. Buff correctly gives 241 AP on char sheet.
