### ISSUE TITLE
Life Tap

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2682]
**Spell ID's:** 11688

> Life Tap now scaling by 50% (i believe it was intended to be TBC 80%) and is still not benefiting from improved life tap talent

> Life Tap is not scaling from spell power or improved life tap

I have 98 spell power and improved life tap

Naked Life Tap returns 301 mana

With full gear it returns 301 mana

**Comment by zana244** [comment]
works on internal, 80% spell damage scaling and improved talent scales by further 10/20%
