### ISSUE TITLE
Drain Life

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2684]
**Spell ID's:** 11700

> doesnt heal at all

> supose to transfer life to the caster, it only damges enemy didnt heal me

**Comment by zana244** [comment]
works on internal.

However, you can use it on mechanical units. Not possible afaik in vanilla, probably the same in TBC?
https://wowpedia.fandom.com/wiki/Drain_Life

**Comment by Shadownflame** [comment]
Not an issue specific to drain life, but all life stealing effects.
Suggestion exists here for dummies https://github.com/Project-Epoch/bugtracker/issues/5986
