### ISSUE TITLE
Presence of Mind

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2687]
**Spell ID's:** 12043

> You can't activate Presence of Mind while Arcane Power is active (this was a change made in WotLK).

**Comment by zana244** [comment]
Confirmed on internal.

Patch 3.0.9 (2009-02-10): Arcane Power and Presence of Mind now share a category cooldown. Arcane Power causes a 15 second cooldown. Presence of Mind, once consumed, causes a 1.5 second cooldown.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5844
