### ISSUE TITLE
Pyroblast

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2691]
**Spell ID's:** 12524, 18809

> Haven't got the talent, can cast the skill

> I reset my talents but my learned Pyroblast rank5 stayed in the spellbook free to use even if i dont have it in my talents anymore

> I can still use it after speccing out of it.

**Comment by zana244** [comment]
Bug still exists on internal, using dual spec at lvl 60 correctly unlearns ranks 1 to 7 but you still retain rank 8 pyroblast.
