### ISSUE TITLE
Goblin Mortar

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2695]
**Spell ID's:** 12768

> shows up in the general page of my spellbook

> I can make learn other players this by clicking on it

> Goblin Mortar appears in the general tab of my spellbook, and says "You alreadt know Goblin Mortar" when I click on it. I am unsure if this should be here or its a part of testing.

> I unlearned engineering but it still in my spellbook

> This is showing in the General tab of the spellbook.

> I have Goblin Mortar in spellbook general tab. It shouldn't be here. I boosted myself to lvl 45 then boosted engineering and then unlearned it.

> Not sure why this is in my spellbook.

> Why is this in my spell book.

> Ability appears in general tab, not sure what it is.

> What the hell is this?

> For some reason when i learned Engineering, this spell appeared on my general tab. When i click it it says that i already know it.

> Got it from engi

> This spell appear after get Engyneering via goblin and you can actually use it of friendy targets - they will glow, no harm effects encountered with it, only glowing around

**Comment by zana244** [comment]
Beta only issue, the spell is wrongly added when you boost engineering from the beta goblins. Learning goblin mortar from a trainer correctly learns the recipe without getting a strange spell in spellbook.
