### ISSUE TITLE
Deep Wounds

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2696]
**Spell ID's:** 12867

> Dealing 60% of the weapons avg damage every tick rather than over 12 seconds

> Tooltip says it works over 24 seconds, but ingame it works over 12 seconds.

> Does not work after Execute critcal hit

> It deals 60% of average weapon damage per tick instead of full duration.

**Comment by zana244** [comment]
Indeed, it does a lot of damage per tick. Pendulum of doom (124- 187 dmg) does 130 dmg per tick... which is more than 60% of average dmg... per tick.

**Comment by ghost** [comment]
Fixed next deploy

**Comment by kaytotes** [comment]
Opening for state testing.
