### ISSUE TITLE
Ice Barrier

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2700]
**Spell ID's:** 13031, 13032

> I have Ice Barrier on my alt spec. When I change to my main spec of Arcane, I still have Ice Barrier and I am able to cast it. The UI says that I lost rank 1 of the spell, but I can cast it at rank 2. Thank you.

> Iam in 2nd spec (arcane) and learned Ice Barrier for my 1st spec (frost). Now i can use Ice Barrier in arcane spec, without speced into it.

**Comment by zana244** [comment]
Seems solved on internal.
