### ISSUE TITLE
Opportunity

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2726]
**Spell ID's:** 14072

> Opportunity buffs mutilate all the time, not just when behind the target.

I assume this is because at the time, mutilate required being behind the target. Please restore mutilate to having this requirement, as all the balancing and engaging gameplay of the spec back in TBC was based on that.

**Comment by zana244** [comment]
Based on basic testing on internal, mutilate always gets the 20% increased damage (i.e. regardless of position). To my mind this makes sense and is intended, as the devs removed the from behind requirement...

**Comment by zana244** [comment]
After build 2592, correctly buffs mutilate only from behind.
