### ISSUE TITLE
Improved Poisons

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2727]
**Spell ID's:** 14113, 14115, 14116

> one point spent makes poisons duration to 12 minutes

> I put in a ticket yesterday to note that my poisons were only lasting 12 minutes. Ive tracked the bug to this talent. It seems to be reducing poison duration to 20% per point rather then adding 20%.

> poisons originally lasted for an hour, but this talent reverts it to 10 minutes, and improves the 10 minutes to 12/14/16/18/20 min!

> This talent seems to reduce the duration of my poisons instead of increasing it. At 3/5 points my poisons last 36 minutes instead of 1 hour.

> Actually reduces duration of poison on weapon, probably because here default is 1 hour, and this talent came from times where default was 30, it gives me 48min poison with 4/5 talents spend.

**Comment by zana244** [comment]
Solved during beta 3.
