### ISSUE TITLE
Remorseless Attacks

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2728]
**Spell ID's:** 14148

> This effect should disappear after using listed spells

> Triggers on low level kills, and the buff remains for the full duration, even after you use the abilities. It doesn't get consumed.

**Comment by zana244** [comment]
As far as I could test on internal, this issue only happens with Mutilate -- you can spam it for 20 seconds benefitting from the crit chance. 
Low level kills (grey mobs) do not seem to give the buff, which is correct.

**Comment by zana244** [comment]
Solved by build 2592
