### ISSUE TITLE
Syndicate Wizard - (2319)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#274]
> 30 second sheep! Really!
`.go xyz 707.651000 -946.947000 164.930000 0 1.724210`

> 30 sec sheep a bit much lol
`.go xyz 685.710000 -956.870000 164.289000 0 3.223420`

**Comment by zana244** [comment]
extremely based.
could maybe be tweaked to 20 sec but it adds a bit of spice.
