### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2740]
**Spell ID's:** 14892, 15363

> This spell only activates whenever I heal myself under crit. If tried to other targets, it doesn't proc, even under crit. Tried with Flash Heal + Heal + Greater Heal but I feel like others don't work as well.

> Does not proc on flash heal or greater heal

> Procs always on yourself, but rarely if you cast it on others. Sometimes it proccs twice on a person in one fight, but not the third time or not at all

> bugged, doesnt proc at all, crited many times

> not working

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6706
