### ISSUE TITLE
Shadowform

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2747]
**Spell ID's:** 15473

> Cant recast shadowform after leaving it

> Switching shadowform on and off has made it become greyed out and spell not ready yet permanently

> Deactivated in fight and is on cd. Can't be activated anymore

> I was in Shadowform and used Power Word: Shield and it removed me from Shadowform as intended, but after that I couldn't ever return back to Shadowform, it was gray in the bar and spellbook, I had to logout and loggin to make it work

> So im finding a glich where if i heal and get outta Shadowform its locking me out can use the spell to get back in.

> I was in this Form then i got out to heal and then it wont let me back in

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4090
