### ISSUE TITLE
Elemental Mastery

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2750]
**Spell ID's:** 16166

> bugged 1 time in baradin hold.  cd stopped working. i needed to relog

> Are you sure this affects crit by totems and flametounge weapon?
doesnt seem so

> The cooldown doesn't always show for some reason. I have it macroed into a chain lightning macro so that I click it and cl at the same time, but I have #showtooltip set to Elemental Mastery

> I'm sure the devs are already aware, but this is currently insanely broken in the fact that Shocks are not consuming the buff, but still gain the 100% crit chance benefit.

> buff stay after i crit with any shok spell

> I believe Earth Shock is recieving the guarentee'd crit, but it is not consuming EM

**Comment by Shadownflame** [comment]
1) & 3) cant reproduce
2) intended
4-6) already resolved
