### ISSUE TITLE
Hemorrhage

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2752]
**Spell ID's:** 16511, 17347, 17348

> I am able to use Hemorrhage as asassination without being specced to it

> Stays as a spell (rank 2) even though I've switched talents (to Combat) - it is also perfectly usable in combat

> after learning hemorage rank 2 and 3 the spell stays viable even after changing specs, might work that way for other abilities unlocked in skilltree and who have more ranks at trainer too.

**Comment by zana244** [comment]
Solved on internal, unlearns fine.
