### ISSUE TITLE
Nature's Grasp

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2755]
**Spell ID's:** 16812, 16813, 17329

> having natures grasp without talent from dual spec

> Spell is not unlearned after unlearning talents.

> Duel-spec bug: Able to equip and use bought higher ranks of spells after switching spec.

> I change specializations and still can use Nature's Grasp

**Comment by zana244** [comment]
Confirmed on internal. Retains ranks 2 to 6 upon switching specs.

**Comment by kaytotes** [comment]
Next deploy.
