### ISSUE TITLE
Improved Shadow Bolt

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2765]
**Spell ID's:** 17793, 17803

> This spell is bugged twofold.
1) the initial shadow bolt which applies it seems to consume one stack, so it gets started with 3 stack everytime
2) dot spells like drain soul seem to consume stack too, this shouldnt happen

> Gives only 3 stacks, not 4! Seems like SB which crit and trigger this talent already eats 1 proc but the dmg is not increased! It should give 4 Procs!

> Only applies 3 or 1 is auto consumed

**Comment by Shadownflame** [comment]
This debuff is currently being consumed by any and all Shadow school ability, including non-damaging curses and effects and even its own initial application.

**Comment by Shadownflame** [comment]
No longer consumed by non direct damage effects.
