### ISSUE TITLE
Consume Shadows

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2767]
**Spell ID's:** 17852

> Raises my stealth detection for 6 seconds too. Doesn't seem right.

> Procs felhunter's paranoia

> voidwalker Consume Shadows abiltiy still gives a stealth detection aura like in WOTLK

**Comment by zana244** [comment]
Confirmed on internal, the stealth detection effect was added in WoTLK, it should not be present in TBC.

**Comment by Shadownflame** [comment]
No longer procs paranoia
