### ISSUE TITLE
Emberstorm

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2768]
**Spell ID's:** 17954

> make destruction warlock become a fire warlock because right now we are getting forced into a shadowbolt spam build which sux 

wotlk did really good when it came to destruction which means imp + immolate + conflagrate and chaos bolt. Maybe get soulfire back into the rotation, 8 sec cd and no soulshard pls (like chaosbolt) or just get chaosbolt. 

I know you want to focus on tbc build and go from there, but pls give fire warlocks some love. Adding old sacrifice would also make more sense. Thanks

**Comment by Shadownflame** [comment]
Not a bug report.
