### ISSUE TITLE
Dun Garok Mountaineer - (2344)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#277]
> Sleeping NPCs keep the player in combat but won't get up and fight them
`.go xyz -1352.630000 -1249.170000 49.904500 0 0.487057`

> Respawn times of these mobs is ridiculously fast. This is an elite quest hub and they repop every 3mins with no other players around. Should be at least 7 minutes
`.go xyz -1264.260000 -1178.490000 39.246000 0 5.844520`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330

**Comment by Bennylavaa** [comment]
their respawn is 5 min which is normal. 

Most likely the over all dynamic spawn stuff.
