### ISSUE TITLE
Improved Drain Soul

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2772]
**Spell ID's:** 18213, 18372

> Doesn't seem to be giving mana back.

> The mana regen portion of this talent is not working

> Mana return doesn't work. Tried killing it without dots, no pets attacking, only Soul Drain, no mana returned.

> This talent doesn't return mana

> doesnt seem to be working, no mana return after killing a mob that gives xp. Tried even without a pet to make sure that it didnt get last hit

> no mana gain

> Talent return mana doesn't work, not sure about the threat part.

> Does not return mana.

> Does not return mana at all

> Doesn't seem to grant mana back at rank 2

> does not return mana after killing the target

> Improved Drain Soul not giving mana back upon kill.

> The mana return affect is not working on this

> do not work, don't reget any mana

> 15% max mana dont return if mob be killed by me.

> not returning mana at all

> The Mana return doesnt work

> It is currently not increasing the damage of Drain Soul at all.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8207
