### ISSUE TITLE
Dark Pact

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2773]
**Spell ID's:** 18220, 18937, 18938

> TRIGGERS NEUTRAL GUARDS FOR SOME REASON WTF

> This spell is not getting increased range from the Grim Reach talent.

> if you change spec and unlearn talent rank 3 of this spell is still available

**Comment by zana244** [comment]
Could not reproduce first issue nor third.

However, it indeed does not get the range from Grim Reach, which it seems that it should
https://www.wowhead.com/tbc/spell=18219/grim-reach -- affected spells.
