### ISSUE TITLE
Devour Magic

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2795]
**Spell ID's:** 19731, 19734, 19736

> tooltip healing number not showing

> Tooltip reads "the Felhunter will be healed for $s1."  Rank 2.

> The Healed amount in the tooltip doesnt show any amount, only an error message

> devour magic tooltip  shows healing value as $s1

> A variable isn't remplaced by the actual value on this pet skill

> the felhunter will be healed for $s1

**Comment by zana244** [comment]
Confirmed on internal, Rank 2 and 3 show $s1 in tooltip.
