### ISSUE TITLE
Blessing of Might

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2796]
**Spell ID's:** 19740

> In the action bar it says it increases AP by 21 but in the buff tooltip it says 20.

I have 2 points in Improved Blessing of Might.

> Not an issue but just wanted to say that I like it being pushed up to a duration of 10 minutes, up from 5 minutes!

**Comment by Shadownflame** [comment]
It's already 10 minutes. Buff tooltips don't update with talents.
