### ISSUE TITLE
Blessing of Wisdom

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2797]
**Spell ID's:** 19742, 19853

> Not so much an issue, but a suggestion.  Trial run it for 15 min buff time?  Keeps it vanilla short but makes it a little more bearable for dungeon runs when the tank is the buffer.

> Hability says that Blessing of Wisdom will restore 27 mana per second but aura only restoring 25 per second. Im using Improved bow talent

**Comment by Shadownflame** [comment]
2# might be an issue with tooltip of buff not updating if they took the holy talent to improve the spell. That's an age old 3.3.5 client issue that's not going away, but the spell gives the proper amount of mp5.
