### ISSUE TITLE
Blessing of Light

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2800]
**Spell ID's:** 19977, 19979

> Cant rebuff Blessing of Light befores duration time ends. I can do it with other blessings

> At level 45, spell rank 1, you cannot refresh it on a target that already has the blessing.

Instead, an error "more powerful rank already active" is printed.

> this blessing of light effect doesnt work at all

**Comment by Shadownflame** [comment]
Confirmed.
1) spell is not possible to refresh at all - this needs fixing
2) the effect does work, but it's considerably weaker than the displayed values as it behaves like bonus healing and only a portion of that goes into actually increasing the spell's healing. FOL has a 40%ish healing coefficient and HL around 70%, so you have to multiply the numbers with those values.

Before gear and any other modifiers:
Rank 1 increases the highest rank Flash of Light range from 348-389 to 373-412 (+24 healing average) which is around 40% of the 60 bonus healing given.
Rank 2 increases FOL range from 348-389 to 385-422 (+35 healing average) (bonus healing 80)
Rank 3 increases FOL range from 348-389 to 397-437 (+48 healing average) (bonus healing 115)
Different ranks of FOL all receive the same healing bonus.

For Holy Light:
Rank 1 increases HL range from 1272-1414 to 1436-1556 (+153 avg healing points out of 210 bonus heal)
Rank 2 increases HL range from 1272-1414 to 1487-1602 (+201 avg extra healing out of 300 bonus heal)
Rank 3 increases HL range from 1272-1414 to 1570-1699 (+291 avg healing average out of 400
Lower ranks of Holy Light receive a lower bonus.

As per Eredun, this is working as intended.
