### ISSUE TITLE
Dalaran Summoner - (2358)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#281]
> This quest rng is horrendous. I've been running back and forth solo for an hour now and still not close to finishing. Please have the "materiel" drop more often or even if the ward spawns creatures
`.go xyz 25.393200 423.747000 43.410500 0 0.758435`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7545
