### ISSUE TITLE
Seal of Wisdom

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2812]
**Spell ID's:** 20357

> This spell is supposed to proc off spells, and melee attacks. I tested it just now, 2 minute fights on dummy:
SOR: Does not proc it, and neither does its judge.
(This shouldn't be able to proc it, but the judgement should).
SOC: Does not proc it, and neither does its judge.
(This should be able to be procced by both the seal effect and judgement).
The seal debuff which should proc off spells AND melee attacks, seems to be locked to white hits only.

**Comment by Shadownflame** [comment]
It can proc off spells and ranged attacks now and also seals and judgments.
