### ISSUE TITLE
Diplomacy

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2820]
**Spell ID's:** 20599

> Racial passive +10% rep doesn't seem to work

> This racial passive doesn't work

> I am not sure this is working, all of my rep gains seem to be the normal unboosted amounts.

> no reputation increase for humans

> Passive does not effect quests

> broken

**Comment by kaytotes** [comment]
Next Deploy

**Comment by TetraDisaster0** [comment]
Is Diplomacy being removed at launch and swapped out for a different racial? Or is this going to be a later change?

**Comment by Bennylavaa** [comment]
Gnome:
![image](https://github.com/user-attachments/assets/fc6c25fd-0bdb-4996-8146-02b741534406)

Human:
![image](https://github.com/user-attachments/assets/f2fed237-13fe-4e4f-b82e-728f31c8ef9e)


Working for quests but not npc kills.

**Comment by Bennylavaa** [comment]
looks like its due to the rounding 5.5 isnt possible to you get 5. on a higher npc rep kill it works as intended.
