### ISSUE TITLE
Ancestral Spirit

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2822]
**Spell ID's:** 20610, 20776

> Cannot rez cross faction.

> Sometimes I cant ress people that die underwater. Weird.

> Cannot ressurect members of the group from the opposite faction after they leave the body

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7744

**Comment by kaytotes** [comment]
This was resolved mid beta. It was not possible to target enemy corpses. It is now.
