### ISSUE TITLE
Feline Grace

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2825]
**Spell ID's:** 20719

> Seems to apply in all forms.

**Comment by zana244** [comment]
Doing the jump from thunder bluff, you barely survive on a non-druid character (less than 1%hp)
Doing the jump on a lvl 1 druid (no form) or in bear form gets you to about 30% hp.
Doing the jump in cat form gets you to about 60% hp.

It seems that every druid has Feline grace applied to them from level 1, and when inside cat form it might be applied twice.

**Comment by kaytotes** [comment]
Confirmed. There was essentially an extra hidden feline grace effect.

Resolved in next deploy.
