### ISSUE TITLE
Aimed Shot

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2826]
**Spell ID's:** 20902, 20903

> This spell is kept in the spellbook when talents are unlearned. Only the rank 1 is forgotten.

> When I switched from Marksman to Beast Mastery, Aimed Shot stayed available and I can still use it

> For every rank besides rank 1, when Dual specced this ability remains in your spellbook

> I unlearnt my talents but still kept the Aimed Shot

> Aimshot works when I am not specced into it. It seems if you buy ranks higher than rank 1, you can still use higher ranks without the talent. So right now in my spellbook i have rank 2-5 of aimshot. Seems other classes are the same

**Comment by zana244** [comment]
Works on internal.
