### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2828]
**Spell ID's:** 20922, 26573

> Consecrations effect passes through walls and ceilings

> Can this be buffed for the cost of the mana its kind of useless

> Rank one does not scale with bonus damage

> Should have 2 chances to proc Judgement of Wisdom on cast. It currently doesn't proc at all.

**Comment by Shadownflame** [comment]
Wisdom fixed. LOS issue reported here https://github.com/Project-Epoch/bugtracker/issues/8359
