### ISSUE TITLE
Gift of the Wild

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2832]
**Spell ID's:** 21849, 21850

> Tooltip says the buff should grand 324 armor, all attributes by 12 and resistances by 20, BUT when used the actually values are 240 armor, all atributes by 10 and resistances by 15.

> goes away from others when taking a break doesn't do this if i buff with mark of the wild

> i buffed me and my friend and his pet 31 minutes ago, logged out to get some coffee etc..  when i logged in i still have te buff, the pet and my hunter friend have lost the buff.

> is not revriting the 30 min buff if the target is opposite fraction and out of the dungeon, but still in group!

**Comment by Shadownflame** [comment]
1) grants correct stats just wont display the updated numbers when talented - blizzlike
2-4 same issue as https://github.com/Project-Epoch/bugtracker/issues/4885
