### ISSUE TITLE
Ferocious Bite

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2833]
**Spell ID's:** 22568, 22827

> As far as i can tell, the spell is still not converting your additional energy into damage. 

At 5 combo points and 100 energy i should be non critting at Rank 1 for 194-210 (+100) ... however I am hitting for 200ish

> The dmg scaling with combo points doesnt seems to work properly. It always do the same dmg no matter the number of combat points. It always do around 190dmg.

**Comment by Shadownflame** [comment]
Must have been resolved during beta. Works fine on internal.
