### ISSUE TITLE
Master Demonologist

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2836]
**Spell ID's:** 23785, 23825

> this talent's tooltip wasnt updated to having no felguard

> Imp should get + % fire dmg or so

> Tooltip includes the demon Felguard, but as far as im aware there is no such creature on this server #bringbackblueboy

> Felguard is mentioned but there is no felguard summon

**Comment by Shadownflame** [comment]
Felguard is back.
