### ISSUE TITLE
Bloodthirst

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2837]
**Spell ID's:** 23881, 23885

> I'm using macro for bloodthirst, but it says rank 1 even though the dmg on tooltip is from rank 2

> This is giving two different 5x stacks of Bloodthirst buff when used.

> Bloodthirst rank 2 gives 2 buffs, for 13 and 10 healing per hit

> i don't think i should be getting this buff

> 1 Bloodthirst give 2 buffs for healing

> I get bith the 10 and the 13 Health restore buff after using BT healing for 23 total instead of my Highest Rank BT.

**Comment by zana244** [comment]
Confirmed on internal, bloodthirst casts 2 buff on the warrior. Its intended rank buff + buff from rank 1 BT. If you cast R1 BT, you only get 1 buff (intended).

**Comment by kaytotes** [comment]
Next deploy.
