### ISSUE TITLE
Shield Slam

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2838]
**Spell ID's:** 23925

> Damage done does not reflect what the tooltip says

**Comment by zana244** [comment]
Trying it out on low level (low armour mobs) gives me the damage in the tooltip, but I found that the damage does not scale with shield block value, as indicated by the tooltip. Think it should be 1:1 scaling
https://www.wowhead.com/tbc/spell=30356/shield-slam#comments
LvL 1 shield and LvL 60 shield do same damage. Haven't checked threat modifier or slam dispell effect but they should work.

**Comment by kaytotes** [comment]
Can confirm the above. Its impacted by enemy armor (and is meant to) and it definitely was missing the bonus from shield block.

Fixed in next deploy.
