### ISSUE TITLE
Moonkin Form

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2846]
**Spell ID's:** 24858, 80980

> This talent are bugged, when i hit as melee with the Moonkin Form i always get the mana proc

> I can't mount while shapeshifted :( Lol

> It could've some bow animations instead of looking like a statue

**Comment by ghost** [comment]
Mana proc was buffed, with a slow weapon it is pretty much every hit. Person likely had a staff on.
