### ISSUE TITLE
Lightning Breath

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2849]
**Spell ID's:** 25010

> Having this pet ability on auto-cast will break the pet AI. Pet will never enter melee range or seemingly even move once the target is within the 20yd range.

**Comment by zana244** [comment]
Confirmed on internal. I'm trying to find video of how wind serpent behaves on vanilla/classic as a reference but I find it hard :|
When I played SoD for a bit I remember not micromanaging my wind serpent and it would go into melee to attack on its own, when it no longer had focus for lightning breath.

Assume it's the same for all ranks, I confirmed on rank 5 25011.

**Comment by kaytotes** [comment]
Next Deploy
