### ISSUE TITLE
Pursuit of Justice

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2854]
**Spell ID's:** 26022, 44414

> The tooltip is saying it gives 5% chance to avoid spells, instead of 1% per talent point, :D I hope it's not 5% per! xD

> Should be reduce chance by 1% rather than 5%, havign 15% resistance chance for spells is OP , should be only3%

> 15% on no-spell hit, text error or is a bug?

**Comment by zana244** [comment]
Confirmed on internal, tooltip mentions 15% chance instead of only 3% (5% per rank instead of 1%). Have not tested the chance in game yet, hopefully easy to check in code.

**Comment by Shadownflame** [comment]
Removing confirmed until checked if its visual issue or gameplay too.

**Comment by kaytotes** [comment]
Confirmed this was purely visual. A description mismatch because TBC classic can have > 3 effects and that's where we pulled em from. Updated description in next deploy. The underlying effect is working as intended.
