### ISSUE TITLE
Rampage

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2864]
**Spell ID's:** 29801, 30029, 30030, 30031

> Hey Epoch TEAM! Just wanted to suggest a different cap talent. No one used Rampage back in tbc, it is terrible. Now that  you have given arms Bladestorm which is HUGE! in pvp and from what Ive tested.. pretty dang good in pve. I suggest either Single-minded fury ( maybe increase dmg with 1 handers + slam hits with both weps? ) or perhaps titans grip, maybe even Dragons roar ( from MoP) Hell maybe even some sort of version of raging blow. thank you team!

> The activation window is not refreshing on subsequent crits. This feels bad to play

> This is not a bug, but Theorycrafting, Fury warrior is lackin power with this ability that will fall off in power soon like warriors was in TBC in general, so i hope there will be something else for fury

> This talent Rampage Rank:1 is bugged. It will come up without needing to bring it back up after you use it, and will continue to go up to x5 attack power without need ing to crit like the Tooltip suggests.

> More feedback on Rampage (Rank 2): It's looking like what happens is that I can only stack this ability by activating Rampage AGAIN, when it is already active.  Then I'll go from 1 stack to 2, or 2 to 3, etc.

But the ability doesn't stack properly from melee hits.

> Rank 2 of Rampage does not seem to be stacking correctly.  Not sure if this has to do with the mobs I am fighting here in Silithus, or the ability itself.

> Rampge rank 1 gains an extra stack every time the player deals damage, while Rampage rank 2 only gains an extra stack when it is cast again. One of these 2 Rampages is working incorrectly

> Rank 2 Rampage isn't stacking to 5. You can only accumulate 1 stack. Rank 1 Rampage worked fine

> Rank 1 Rampage spell can proc from melee damage without criting involved. Rank 2 is working the intentional way I think.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4853
