### ISSUE TITLE
Arcane Potency

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2880]
**Spell ID's:** 31573

> Tbh it doesnt really seem that you get the bigger crit chance, maybe im just unlucky but i have 23% base crit + 4% for scorch and when i proc clearcasting i should get another 30% and from all the casts lets say about 20min on the dummy i didnt get a single crit while being under the effect of clearcasting

> This spell is bugged and not giving extra crit to the clearcast spell

**Comment by zana244** [comment]
Confirmed on internal, does not give the crit. You should be able to see it in the character sheet I think.
