### ISSUE TITLE
Empowered Arcane Missiles

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2881]
**Spell ID's:** 31583

> Arcane barrage consumes tacks, but there is no increase dmg

> This is a fun talent, but sometimes the Arcane Barrage does not trigger at the end of the channel, even if the channel completes and there is no movement, spells, or any other interruptions that would interfere.

**Comment by Shadownflame** [comment]
1) reported here https://github.com/Project-Epoch/bugtracker/issues/2917
2) Could not reproduce this with the pushback talent. If you lose a tick to pushback normally the barrage won't trigger (which is intended), but the ticks lost without pushback still allow the barrage to fire.

**Comment by Shadownflame** [comment]
Arcane barrage redesigned.
