### ISSUE TITLE
Sanctified Judgement

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2884]
**Spell ID's:** 31878

> First, change the icon of this talent. There's already a version of this, with a different color (blue).

Secondly, this should be a T1 talent with Rank 2/2, located right next to Improved Blessing of Might, which should be 3/3

Thirdly, it needs a buff, Paladins are EXTREMELY mana hungry, so consider giving them a % of total mana back on a judgment.

**Comment by Shadownflame** [comment]
This is a blizzlike TBC talent.
