### ISSUE TITLE
Blacksmith Verringtan - (2404)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#289]
> He has the repair/blacksmith icon on mouseover, but his buy/sell menu doesn't show up when clicked.
`.go xyz -547.331000 36.448700 48.653800 0 1.755540`

> cannt interact with him
`.go xyz -492.063000 57.541800 56.181900 0 0.473127`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7865
