### ISSUE TITLE
Lifebloom

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2895]
**Spell ID's:** 33763

> spell duration in the description is 14seconds but it actualy lasts 6 seconds

> the bloom does not heal the target but the caster

> tooltip for this spell says it heals over 14 sec but it is 7 sec and healing numbers are bigger than in reality

> there is a baseline "possession" change with this spell in TBC.
It is intended that the casting druid gets healing credit and threat generation for the hot ticks.

BUT the "bloom" effect is intended to heal the target(not the druid that originally cast the spell)

AND

the target of the lifebloom receives healing credit and threat credit for the bloom heal. It is YOUR server, you are very welcome to change this intended credit/threat mechanic. but the bloom should heal the target, at least.

**Comment by Shadownflame** [comment]
Resolved on beta
