### ISSUE TITLE
Kill Command

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2900]
**Spell ID's:** 34026

> Kill command does not make the pet do damage when used

> The ability goes off whether pet is in melee range or not.

> doesnt work, pet does no dmg off this spell

> I can hear the sound effect of Kill Command, and it consumes my mana, but I just can't see any damage from it.

> I strongly believe, this doesn't do anything. In Details (addon) I can't see any sign of this. All I'm doing (for testing purpuse) to auto shot and pet melee the mobs. When Kill Command procs, I use it, yet I don't see any damage named Kill Command in my Details. Only pet melee and auto shot. Also, in combat log, I can see: "Donolen casts Kill Command at Plague Runt.". Next line is, that my pet suffers damage, the next is, that my pet melee swings the target. No damage from Kill Command.

**Comment by zana244** [comment]
Confirmed on beta 3 and internal, becomes active upon the hunter critting, but casting it does nothing.
