### ISSUE TITLE
Expose Weakness

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2908]
**Spell ID's:** 34500, 34503

> Talent currently works like in WOTLK where it gives you an AP boost of 25% of your AP on crits. The wording applies it is the TBC version where when you crit the target, 25% of your agility is applied to phy damage increase. Currently doesnt work like it is worded

> Doesnt make a debuff on the target instead does buff only the player no one else but even the player doesnt get the bonus of AP just a buff icon without an effect, still the same dmg with or without it

**Comment by zana244** [comment]
Confirmed on internal, works like WOTLK version.
Should be applied as a debuff on target so all raid can benefit.

**Comment by kaytotes** [comment]
Testable
