### ISSUE TITLE
Vampiric Touch

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2912]
**Spell ID's:** 34914, 34916

> mana returned is now showing up on floating combat text as "energy gains

> not showing DPS when you hover over icon

> spell still awelible after respec

**Comment by zana244** [comment]
mana counts as energy gain, unsure if it should show as periodic or instant... non-issue
debuff tooltip doesn't show dps, blizzlike
https://www.wowhead.com/tbc/spell=34914/vampiric-touch#comments
correctly unlearns itself upon talent reset.
