### ISSUE TITLE
Narillasanz - (2447)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#292]
> This rare strays close to horde guards near the AV entrance, engaging the guards and losing.
`.go xyz 320.408000 -961.209000 102.364000 0 4.803720`

> Rare does not have any loot
`.go xyz 342.816000 -1008.350000 103.090000 0 0.496814`

**Comment by Bennylavaa** [comment]
needs new pathing to not agro guards.

**Comment by kaytotes** [comment]
Sniffed waypoint now
