### ISSUE TITLE
Bladestorm

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2922]
**Spell ID's:** 46924

> Can be disarmed while Bladestorming

> Stacks with the Ravager Bladestorm effect, unsure if intended.

> Bladestorm performs 7 whirlwinds instead of 6.

**Comment by ghost** [comment]
Disarm confirmed a bug, ravager is probably intended. Bladestorm performing 7 whirlwinds is correct, the tooltip says "instantly Whirlwind up to 4 nearby targets AND for the next 6 seconds perform a whirlwind attack every 1 sec." That's 7.

**Comment by ghost** [comment]
Cannot replicate, I believe this got fixed by an earlier Bladestorm change
