### ISSUE TITLE
Water Shield

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2923]
**Spell ID's:** 52129, 52134

> you need to make early-level Shaman tanking a thing, otherwise no one will play this class

you have made so much good work on Epoch but I fear that you're not making it attractive enough for people who want to DO things during leveling; will people reach your new endgame content if the leveling journey is not fun for certain classes? 
they will quit beforehand

> does not appear to have an internal cooldown on consuming water sheild charges.

> The water globe triggers have no GCD. And the trigger seems to happen on any offensive effect, even debuffs that don't deal damage (like the Blood Fury Orc racial)

> Charges are consumed with every attack, no activation delay

> Water Globes proc on every attack taken with no delay inbetween. If something is attacking fast enough, it will use up all water orbs within a second, instantly giving a bunch of mana.

**Comment by zana244** [comment]
Solved on internal. Does not get triggered by orc racial, and has around 2-3 sec delay between charges getting activated.
