### ISSUE TITLE
Tarnished Soul

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2933]
**Spell ID's:** 80902

> Hearthstone still works with debuff active, 75% is painfully slow walking from the middle of stv though ;(

> The moment I got the debuff I got stuck in place cannot move.

> Died twice and debuff stacked to 2x and now can't move cause of -150% movespeed

> if you die 2 times the debuff stacks to -150% movement speed
cant move anymore

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8020

**Comment by Shadownflame** [comment]
Hearthing still works and probably so do portals (cannot test right now as portals are completely broken). Leaving this one open.

**Comment by Shadownflame** [comment]
Can confirm mage teleport and portal spells are still usable as well. The spell tooltip doesn't actually say they shouldn't, but if players cannot hearth or use FPs, it would make sense.

**Comment by kaytotes** [comment]
Next deploy.

**Comment by Shadownflame** [comment]
Teleports are now disabled.
