### ISSUE TITLE
Cloth Scavenging

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2942]
**Spell ID's:** 81311

> i'm lvl killing lvl mobs and it seems like this is giving me linen cloth

> Always says "Already Looted

**Comment by Shadownflame** [comment]
1) The level ranges seem to be somewhat off. 
Linen and Wool are okay as the mobs themselves drop both in the 15-25 range and the procs seem to reflect this, though I feel the chance of a Wool proc should be higher on lvl 20+ mobs. 
However, everything above 30 seems to be mostly Silk. Some mobs (not all) in the 50-58 range drop exclusively Mageweave, but the 40-50 range that should have the most mageweave doesn't give any at all. Level 50-60 mobs also tend to proc Silk, which they shouldn't do at all, it should be mostly Runecloth.

2) I can confirm the "already looted" bug happens to the Scavenging procs but it's extremely rare. I literally had to kill hundreds of mobs to get one of them stuck. So it's not a major issue.

3) You seem to get procs off many humanoid mobs that don't normally drop cloth. (Yetis, Nagas) And also a few dragonkin.

**Comment by Shadownflame** [comment]
Waiting for rework to be applied.

**Comment by Shadownflame** [comment]
Waiting for next fix.

**Comment by Shadownflame** [comment]
Works as intended after last rework.
