### ISSUE TITLE
Mercenary of the Alliance

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2943]
**Spell ID's:** 81346

> Not flagged for pvp

> I am in warmode but not pvp, maybe because I was on the central tower and then left?

> I just completed Featherbeard's Endorsement with gave me 1000 reputation, and I don't think Warmode increased it by 5% which it says it should. Is it an issue with warmode or the quest, or did it actually increase and I am stupid?

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7597
