### ISSUE TITLE
Mercenary of the Horde

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2944]
**Spell ID's:** 81347

> Something is fishy.. it doesnt show the correct 5% more reputaion in chat.. but looking in repbar i might be correct

> It doesnt give the 5% reputation gain.

> blocks you from attacking people who are warmode off when dueling (invalid target error)

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7597
