### ISSUE TITLE
Axe Specialization

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2947]
**Spell ID's:** 81502, 81984

> It performed extremely poorly in a dungeon  run, doing 1.2% of my total damage. If you intend to make it useful only in raids, please reconsider.
Idk what the intended mechanics are so here are some things i observed, you can decide if its working or not:

- the damage does not add up like ignite when the bleed is refreshed

-it only scales with weapon dps and speed(slower does more), no ap scaling

-if you have the same weapon in mh and oh, the bleed from oh does half damage even with dw spec

> This has very low damage compared to sword spec. Sword spec is 5% chance to make 100% weapon damage instantly. Axe = 5% chance to make 50% weapon damage over 15 sec

> Hello, why did you add additional passive skills to all races? I ask you to bring the game closer to version 1.12

**Comment by ghost** [comment]
Intended behavior, just a bit undertuned
