### ISSUE TITLE
Racial Knowledge: Troll

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2954]
**Spell ID's:** 81932

> It's activating only haste on the main hand, should activate haste on both hands

> I think you should position the Racial Knowledge Tab towards the top; directly over the General Tab. 

This would display that it should be one of the first priorities to focus on, being that this is a KEY feature in Project Epoch. This would be a much more polished/clean design in my experianced opinion. 

Super excited for the release, you're all doing great!

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2996
