### ISSUE TITLE
Saltwater Snapjaw - (2505)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#296]
> The dropratee for lean turtle flanks is pretty rough
`.go xyz -361.917000 -4489.560000 11.622600 0 1.539800`

> I KILL ALL the turtle i see on the coast ,i only got 3 lean turtle flank . it is so touturous
`.go xyz -165.751000 -4618.970000 6.318260 0 2.411270`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2222
