### ISSUE TITLE
Tribal Totem: Bloodhoof

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2972]
**Spell ID's:** 82338

> Disappears whilst mounted

> Tribal totem no longer visible when shapeshifting back into normal form. Buff remains but no totem visible

> Totem visually disappears after shapeshitfing as druid and won't appea again unleass removing the active spell and casting it again

> it gets removed when going out of cat/bear forms. Would be cool to still have it on your back even in bear form though :3

> Druids lose it with transformation, the buff stays up and when the spell is clicked again happens nothing unless you manually left click it up right in the buff row.

> Visual bug after shapeshifting back into caster form the totem isn't visible.

> Totem visual disappears after shapeshifting, however buff remains. Totem reappears when UI is reloading and when going through loading screens.

**Comment by ghost** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/2971
