### ISSUE TITLE
Molten Blast

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2985]
**Spell ID's:** 91801, 91803, 91806, 91807, 91808, 91809

> Not sure if this is a bug or working as intended, but a miss with this spell still refreshes the duration of Flame Shock.

> This spell would make more sense to unlock at lvl 10 or later, since that's when Shamans start getting their fire spells (Flame Shock, Searing Totem, etc). It's also just weird to have synergy with a spell you don't even have access to yet at levels 8-9.

> Make it like original, give it CD and make it stronger than lightning bolt, instead of it being off cd and hitting like a wet noodle.

> Does not consume stacks of Clearcasting

> Need a new icon.

> This spell is refreshing the Flame Shock DoT even if it misses the target.

> The spell can "miss". I would expect it to only resist or hit

> Molten blast procs elemental focus but dont consume the effect so you can spam very cheaps molten blast forever

> Some way to get cast pushback reduction on this ability as Enhancement would be nice, if the decision is made to have weaving this between melee attacks intended.

> It resets active Flame Shock, even if Molten Blast miss or resist. Feels like it shouldn't

> Doesnt consume clearcasting effect stack(elemental focus), possible to have 100% uptime on manacost reduction

> Doesn't consume Clearcasting stack received by Elemental Focus talent in Elemental tree

> Flame Shock refreshing on the target even if Molten Blast missed

**Comment by ghost** [comment]
Only valid bug here is that it refreshes flame shock upon miss/resist

**Comment by Shadownflame** [comment]
Misses no longer refresh Flame Shock.
Now consumes 1 stack of Clearcasting.
