### ISSUE TITLE
Penance

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#2987]
**Spell ID's:** 91834, 91843, 91852, 91861, 91870

> doesnt proc any shadow stuff like shadow weaving

does like 75% x 3 of mind blast damage and each tick can crit

crazy spell for mind blast mana cost

:(

> at lvl 45 I feel that, this hits too much, like 500 for tick.

> From previous report, Helaing and damage values are inverted

> Doing 3x intended damage it seems

> Does not apply Shadow Vulnerability

> When used in shadow form, it would often shoot only one projectile and cancel itself. Very often, I wouldn't get hit, I wouldn't move or cancel the cast in any other way. It would cancel itself.

> Besides being massively overtuned damage in Shadowform, this spell also just randomly stops channeling for no discernable reason quite often. You never know if you get 1,2 or all 3 hits off. There's no indicator either for resist, miss, or anything of the like. The channel simply just stops halfway through at random.

> Shadow Penance does not trigger the Shadow Weaving talent and thus does not give any stack of Shadow Vulnerability on the target

> Penance" in shadowform does shadow dmg, but it doesn't trigger "shadow weaving" from tallent tree

> Spell can miss, and when it does, channelling stops

> It's not applying Shadow Weaving debuff by using Penance in Shadow form, since it's an Shadow ability while in the form, it should add stacks of Shadow Weaving

> Penance (offensive) is still way too OP. With only 46 spell damage, this ability is doing 351dmg per "missile" i.e 1053 dmg for a full Penance. Non-crit.

This is approx. 40% of a normal lvl 45 mobs HP. If not nerfed, this spell will make our dots pretty much useless. I would say nerf it by 30% so it does around 245 dmg per "missile" or something similar.

Love the server, cant wait until its live!

> Its doing WAAAAY too much damage. Around 400dmg per tick at lvl 45 in shadow-specced. Makes all priest dots unneccesary to use.

> Seems a bit overpowered in shadowform to deal 3x450dmg during 3seconds.. Non-crit

> This should be Shadow Damge in Shadowform.. it also should be able to add Stacks of Shadow Weaving.. :P

> Penance is able to be casted while interrupted out of Shadow school but it will not do anything and waste a cooldown.

> Perhaps it does a bit TOO much dmg, the same amount as Mindblast-> PER TICK-> 500 vs 1500 (roughly)

Also, it can  cast 2 or 3 shots-> seems to be random (protected by PW Shield)

> sometimes does only 1 or 2 orbs instead of 3, also overtuned a bit, but iirc that is known

> Penance in shadow form doesn't seem to proc the talent "Shadow Weaving" from the Shadow tree in priest. 

Penance turns to shadow damage with shadowform active, but the talent doesn't consider the damage as shadow damage. The talent seems to only consider shadow damage from spells in the shadow tree, not all shadow damage spells from the caster.

Not sure if its considered intentional or not.

> So many damage, especially if I'm playing as undead. Humans have big damage too, but less then undeads.

> doesn't apply shadow talents effects when used to dmg

> sometimes it stops channeling with no reason

> Sometimes firing two instead of three bolts.

> Rank 3 requires Engineering 325 to learn.

> Uncertain if it's just because of all my spellpower buffs and all the passive damage increase debuffs I apply as a shadow priest, but a rank 3 Penance (117 to 119 Holy damage) deals up to the 500s (700s if it crits) in shadow damage even after the patch 0.24.0a nerf.

> Shadow penance does not apply Shadow Weaving talent.

> Does not feel like it interacts with any of the shadow talents - doesn't stack Shadow Weaving, haven't seen Blackout procs, maybe would benifit with being on the crit/mana cost talents?

> all ranks after rank 1 require Engineering 325

> In shadowform counts for shadow stun procs but not for Shadow vulnerability procs

> Goes on cooldown even if "Invalid Target".

**Comment by Shadownflame** [comment]
Here is a summary of shadow talents that penance is not interacting with while in shadowform:
- Does not get effect from Shadow Focus talent (spell ID 15330)
- Does not get effect from Shadow Affinity talent (spell ID 15320)
- Does not get effect from Shadow Reach talent (spell ID 17323) (note, this is not an issue as base range of the spell is like 40 yards it's OP)
- Does not proc Shadow Weaving talent (spell ID 81421, Shadow Affinity debuff spell ID 81416)

As an additional note, the issue with channeling being cancelled seems to be a general problem with many channeled spells, not specifically just Penance.

**Comment by Shadownflame** [comment]
Related (channeling issues) https://github.com/Project-Epoch/bugtracker/issues/3351
https://github.com/Project-Epoch/bugtracker/issues/5003
https://github.com/Project-Epoch/bugtracker/issues/2668

**Comment by Shadownflame** [comment]
RIP balance.
