### ISSUE TITLE
this is about the fit for a king quest part 2 in feralas about g...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3002]
> this is about the fit for a king quest part 2 in feralas about gathering hemp. Went to the river in search of the hemp and can't find any spawns. Also no other players in sight so unlikely that they nabbed em.

.go xyz -4693.450000 1152.550000 105.900000 1 3.759350

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7967
