### ISSUE TITLE
The Perfect Fuel Quest in Tanaris, doesnt seem to have any locat...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3005]
> The Perfect Fuel Quest in Tanaris, doesnt seem to have any locations under the oil rig to fill the cannister, checked every pipe and spammed the item, no valve anywhere either

.go xyz -6715.250000 -4835.920000 0.546154 1 2.687530

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
