### ISSUE TITLE
Here  should be floating wreckages to fish up , bit confused

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3011]
> Here  should be floating wreckages to fish up , bit confused

.go xyz -964.206000 -3775.940000 5.552450 1 5.380600

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295

wreckage exist, may have been not respawning as intended
![WoWScrnShot_081424_132757](https://github.com/user-attachments/assets/99a40707-2960-4bee-8585-cab9c54ce365)
