### ISSUE TITLE
the quest sunken treasure is not straightforward.  while looking...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3018]
> the quest sunken treasure is not straightforward.  while looking for the sunken treasure with my friends we were unable to find it in any of the 4 ships that were present.

.go xyz 1457.760000 163.758000 -50.882200 0 0.491817

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8171
