### ISSUE TITLE
Witherbark Witch Doctor - (2555)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#302]
> These cast healing ward, then cast magma totem always
`.go xyz -1842.570000 -3176.420000 49.916200 0 3.676130`

> Occasionally casts Healing Ward and immediately Magma Totem afterwards, which despawns the Healing Ward.
Either the Healing Ward should not despawn at all, or if it should, then the Magma Totem should not be spawned immediately after.
I'm quite sure the two should be allowed to exist simultaneously, however.
`.go xyz -1789.520000 -3365.640000 36.079200 0 5.056600`

**Comment by zana244** [comment]
Still does it on internal, casting one totem after the other despawns the first one. Change AI maybe or let the two totems co-exist (and maybe add a small delay between casts).

**Comment by kaytotes** [comment]
Blizzlike.
https://youtu.be/aoHRVsKY5js?t=262

Note the Healing Ward dropped by the witch doctor despawns the moment the same witch doctor spawns a magma totem.

**Comment by kaytotes** [comment]
Second example https://youtu.be/aoHRVsKY5js?t=281
