### ISSUE TITLE
in the Questlog during the Advaned Alchemy quest it shows that t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3024]
> in the Questlog during the Advaned Alchemy quest it shows that the Quest should be done in Elwynn Forest and not in Western Plaguelads

.go xyz 2151.050000 -2387.070000 61.621300 0 6.055590

**Comment by Bennylavaa** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/8300
