### ISSUE TITLE
Rite of Vision quest  THIS PLAINS VISION WOLF IS TOO DAMN FAST!!!

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3027]
> Rite of Vision quest  THIS PLAINS VISION WOLF IS TOO DAMN FAST!!!

.go xyz -2057.830000 -361.970000 -7.891920 1 0.953288

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2375
