### ISSUE TITLE
The time it takes to open a chest seems a lot shorter than usual...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3028]
> The time it takes to open a chest seems a lot shorter than usual. (testing on a chest in skull Rock near orgrimar)

.go xyz 1478.160000 -4742.700000 11.998200 1 4.087130

**Comment by Shadownflame** [comment]
It seems to have the 1sec wotlk timer, it was a lot slower in vanilla (4-5sec, not sure of exact value)

**Comment by zana244** [comment]
Hijacking this thread to also add that herbalism/skinning suffer from the same issue. In WoTLK they had the cast times reduced.

Herbalism: From 5 sec reduced to 3 sec.
(https://www.wowhead.com/classic/spell=11993/herb-gathering#comments vs https://www.wowhead.com/wotlk/spell=11993/herb-gathering#comments

Skinning: From 2-3 sec (varying by rank) to 1.5 sec
(https://www.wowhead.com/classic/skill=393/skinning vs https://www.wowhead.com/wotlk/skill=393/skinning)

Mining seems to have remained at a stable 3.2 sec.

**Comment by kaytotes** [comment]
Next deploy
