### ISSUE TITLE
The description of the quest "Fit For A King"(the part where you...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3029]
> The description of the quest "Fit For A King"(the part where you collect 20 Vials of Beast Blood) is a bit confusing, it implies that it is possible to use the item on ANY weakened beast in Feralas, while in fact it can only be used on the beasts in the vicinity of the camp where the quest giver resides.

.go xyz -4651.910000 1493.600000 113.505000 1 5.625170

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2267
