### ISSUE TITLE
When flying from Gadgedstan to Theramore as alliance, your griff...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3034]
> When flying from Gadgedstan to Theramore as alliance, your griffon flies trough buildngs  of Steemwhedle port instead above the city

.go xyz -3825.370000 -4516.580000 10.437500 1 0.827786

**Comment by Shadownflame** [comment]
Issue goes both ways between the two towns.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4099
