### ISSUE TITLE
For the quest "the plaguewood cauldrons" it's not clear where to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3037]
> For the quest "the plaguewood cauldrons" it's not clear where to find alchemist arbington to turn it in.

.go xyz 1808.590000 -3709.670000 171.144000 0 1.863810

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7217

**Comment by Bennylavaa** [comment]
come on now its the guy you got the quest from...
