### ISSUE TITLE
In original WoW, Augustus the touched gives a quest even to alli...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3044]
> In original WoW, Augustus the touched gives a quest even to alliance player. Here he is hostile to alliance (it may be a deliberate choice, I don't know)

.go xyz 2929.250000 -2746.110000 109.615000 0 5.755560

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1000
