### ISSUE TITLE
The custom quest "The storm gathers" ask to investigate both pil...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3045]
> The custom quest "The storm gathers" ask to investigate both pillars at the entrance of Tanaris and Silithus but investigating one seems to be enough

.go xyz -8363.550000 -2074.340000 -46.196100 1 0.078543

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2514
