### ISSUE TITLE
The gryphon eggs in Shadra Alor for the quest "Reclaiming the Eg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3046]
> The gryphon eggs in Shadra Alor for the quest "Reclaiming the Eggs" are not clickable.

.go xyz -459.901000 -2871.610000 96.791200 0 6.038590

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
