### ISSUE TITLE
The Perfect Container quest in tanaris. went to the rocket car t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3047]
> The Perfect Container quest in tanaris. went to the rocket car to find parts. nothing to interact with, can't attack the gnome mobs, seems like a dead end

.go xyz -7180.080000 -3487.640000 12.719700 1 0.707600

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
