### ISSUE TITLE
Trying fishing daily, caught about 30 fish none ever for the req...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3049]
> Trying fishing daily, caught about 30 fish none ever for the required daily quest. Two catches came up empty possibly was supposed to be quest fish but never appeared?

.go xyz -4323.600000 3203.320000 6.524920 1 1.377410

**Comment by Bennylavaa** [comment]
cannot reproduce this and this needs more info anyway not sure which one they are talking about.
