### ISSUE TITLE
Not really confused as to where to go, more confused as  to why ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3052]
> Not really confused as to where to go, more confused as  to why there are barely any spawns of 'Filter Parts' for the quest 'Water Co. Saviour' I have seen 5 total spawns. There needs to be WAY more, esp since this is a custom quest and people WANT to experience your hard work! Please add more spawns and more frequently.

.go xyz -6846.380000 -4935.300000 -1.901750 1 0.125672

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
