### ISSUE TITLE
the shadowprey orcas dont get aggroed from my pets, my pet can a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3070]
> the shadowprey orcas dont get aggroed from my pets, my pet can attack them and they do nothing, but then will aggro me and my void walker cant taunt them, my pet goes for their tale, i dunno if this monster has a huge hit box or multiple but the pets go for the tail but the aggro area is in the face

.go xyz -1935.180000 3203.120000 -1.418550 1 2.708250

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1306

**Comment by Bennylavaa** [comment]
added to the other report.
