### ISSUE TITLE
in the quest a sticky situation a horde camp is mentioned that c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3078]
> in the quest a sticky situation a horde camp is mentioned that cannot be found i believe or not enough information is given

.go xyz 457.691000 -3501.710000 105.123000 0 4.792750

**Comment by Shadownflame** [comment]
This is a blizzard quest. Some crates spawn around Agol'Watha, but most inside the Skulk Rock Cave. The Horde base was once presumably Skulk Rock itself, although blizz never bothered elaborating on that.
