### ISSUE TITLE
Sprogger - (2594)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#308]
> Facing Negolash" can be unlocked twice. Same as "The Captain's Cutlass
`.go xyz -14302.000000 515.738000 8.690930 0 0.281410`

> Faceing Negolash! Quest can be accepted twice
`.go xyz -14303.000000 516.570000 8.673870 0 1.196730`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2158
