### ISSUE TITLE
Zone: Tanaris
Quest: The Perfect Fuel (Part 2)

At the stage of ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3088]
> Zone: Tanaris
Quest: The Perfect Fuel (Part 2)

At the stage of the quest where you must go to "the base of the oil rig" , I could not find any location where to use the quest item. There were no highligted objects or valves that would work.

.go xyz -6817.310000 -4804.850000 11.952200 1 2.795030

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
