### ISSUE TITLE
Using flight path as a gnome (with the racial passive) into Iron...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3096]
> Using flight path as a gnome (with the racial passive) into Ironforge. The blades of the helicopter is colliding with the ceiling. Works with no problem but does not look good visually :)

.go xyz -4821.780000 -1155.440000 502.210000 0 3.418590

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
