### ISSUE TITLE
[The Perfect Fuel] is throwing us for a loop. Three of us are ha...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3099]
> [The Perfect Fuel] is throwing us for a loop. Three of us are having trouble finding any valve to interact with on this oil rig.

.go xyz -6477.750000 -4929.940000 6.798010 1 3.833130

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
