### ISSUE TITLE
Alliance Quest Witherbark Cages in Hinterlands
Contains absolute...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3100]
> Alliance Quest Witherbark Cages in Hinterlands
Contains absolutely no directions where to find the villages. Some hint in the the line of "to the south" or "near tha blablabla" would be nice.

.go xyz 58.171700 -2609.760000 112.339000 0 5.396780

**Comment by zana244** [comment]
blizzlike quest ...
