### ISSUE TITLE
I don't think this is a bug, but a quest in Searing Gorge named ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3102]
> I don't think this is a bug, but a quest in Searing Gorge named "Do slavers keep records?" seems to be.
I've killed around 100+ dark iron slavers and noone of them have dropped me the item to complete the quest

.go xyz -7112.380000 -1021.120000 242.562000 0 4.316370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
