### ISSUE TITLE
Tanaris quest; Water Co Saviour. Filter parts are very sparse, a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3103]
> Tanaris quest; Water Co Saviour. Filter parts are very sparse, and their spawn rates take very long. Combined with having to swim to collect these parts, it makes it a frusrating quest.

.go xyz -6947.220000 -4447.630000 9.604150 1 4.352820

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
