### ISSUE TITLE
The quest in Tanaris, Steamwheedle Port, called Water Co. Saviou...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3124]
> The quest in Tanaris, Steamwheedle Port, called Water Co. Saviour.   The items I need to recover from the sea floor are nowhere to be found.

.go xyz -7184.930000 -4940.190000 -5.656330 1 1.981160

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
