### ISSUE TITLE
Quest "The perfect fuel" says trolls of the noonshade ruins made...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3127]
> Quest "The perfect fuel" says trolls of the noonshade ruins made batteries and i need to get them, no clue where to find the batteries.

.go xyz -6909.030000 -4324.640000 16.847400 1 5.419800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
