### ISSUE TITLE
The quest "The perfect fuel" mention that there are trolls in th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3129]
> The quest "The perfect fuel" mention that there are trolls in the Noonshade ruins, but no trolls only humans. Is it a bug or ? I can't get the battery

.go xyz -7089.690000 -4340.280000 10.947800 1 2.173960

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
