### ISSUE TITLE
Starting areas mobs deal 1 point damage  instead of classic 2-3 ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3140]
> Starting areas mobs deal 1 point damage  instead of classic 2-3 points.

.go xyz 10301.200000 845.315000 1333.170000 1 3.693590

**Comment by zana244** [comment]
mobs seems to deal intended damage, the lvl 1 starting zone deal 1 damage on classic too, as they level up they deal more
https://www.youtube.com/watch?v=5_G4cEI55cY
