### ISSUE TITLE
The quest "The Storm Gathers" gets accomplished with you just go...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3141]
> The quest "The Storm Gathers" gets accomplished with you just going to one of the two pylons. (Went to the one in Silithus first.)
s

.go xyz -6251.920000 -614.231000 -120.612000 1 4.299050

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2511
