### ISSUE TITLE
The timer for "A little help from my friends" doesn't stop even ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3143]
> The timer for "A little help from my friends" doesn't stop even after you accomplish the finish BUT don't deliver it yet.

.go xyz -6198.250000 -1101.140000 -216.302000 1 0.685757

**Comment by zana244** [comment]
On all servers I played that's how the game works. Seems to be the same on classic
https://youtu.be/Uq2vwTHJ6hY?feature=shared&t=297
Be quick to turn in.
