### ISSUE TITLE
The third part of "The Un'Goro Hunt" is labeled as "Elwynn Fores...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3144]
> The third part of "The Un'Goro Hunt" is labeled as "Elwynn Forest" in the quest log.

.go xyz -8055.960000 -1206.140000 -332.112000 1 4.066190

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
