### ISSUE TITLE
I'm not confused per say I just want to report a Typo clean up f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3148]
> I'm not confused per say I just want to report a Typo clean up for the quest "Just desserts" in Elwynn Forest: Tower of Azora, quest text says "but I have a plan to back at him" instead of "back at him

.go xyz -9537.580000 -696.035000 64.647100 0 3.660620

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
