### ISSUE TITLE
Elder Saltwater Crocolisk - (2635)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#315]
> Hits like a wet noodle.
`.go xyz -12076.800000 375.333000 3.686630 0 4.096360`

> Hits weaker than a troll non elite of his level.
`.go xyz -12007.900000 598.015000 3.024400 0 6.162330`

> hitting like a normal mob instead of an elite
`.go xyz -12288.700000 309.046000 1.361580 0 0.210416`

**Comment by zana244** [comment]
LvL 38 elite hits for around 120 damage, mobs at lvl 35-36 hit for around half that... could possibly be buffed a bit, but it has 6k hp so I don't think there's a need... leaving as suggestion.
