### ISSUE TITLE
Graves in ZF do not spawn mobs when engaging witch doctor loot.
...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3150]
> Graves in ZF do not spawn mobs when engaging witch doctor loot.
Witch doctor boss doesnt drop loot.

.go xyz 1908.540000 1009.610000 11.881900 209 0.892295

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/8115

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/683
