### ISSUE TITLE
I just logged in after logging out yday in eastern plaguelands. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3158]
> I just logged in after logging out yday in eastern plaguelands. My character legit right away after logging in started flying through the entire content with only his body in an weird animation. sadly cant provide u guys with video footage but yea. I was logged on a normal Street where everything is perfectly fine to log out for. After logging my character just went nuts flying around straight down eastern kingdoms through every obstacle / mountain / under the World xd

.go xyz -3298.250000 -4136.490000 77.484500 0 3.052100

**Comment by Bennylavaa** [comment]
Maybe was on a flightpath prior?
