### ISSUE TITLE
the final reward for the Defias chain to receive the Seal of Wry...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3163]
> the final reward for the Defias chain to receive the Seal of Wrynn refers to talking with King Varian still, holdover from WOTLK

.go xyz -8440.050000 338.665000 121.746000 0 1.511210

**Comment by zana244** [comment]
you'd think so, but the quest text is the same in vanilla / tbc. you complete, as intended, at Prestor who informs you the king is unavailable.
