### ISSUE TITLE
Vilebranch Aman'zasi Guard - (2648)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#318]
> The 3 mobs circling the ancient egg here, do a swimming animation at some points in the puddle, seems kind of wonky.
`.go xyz -741.744000 -3766.960000 232.378000 0 3.445070`

**Comment by Bennylavaa** [comment]
Confirmed, needs some pathing improvements. 

npc ids: 2648, 10802

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
