### ISSUE TITLE
Quest The Perfect Fuel indicates that the trolls of the Noonshad...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3188]
> Quest The Perfect Fuel indicates that the trolls of the Noonshade ruins has batteries. The Noonshade Ruins are full of humans and no battery in sight

.go xyz -7351.910000 -3976.710000 9.342190 1 4.254390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228

Duplicate and they are troll ruins you don't kill any trolls and the trolls have since moved.
