### ISSUE TITLE
Centipaar Tuenneler's for the quest SIlithid Scramble spawn but ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3190]
> Centipaar Tuenneler's for the quest SIlithid Scramble spawn but then despawn and I saw a total of two between both camps. Wasn't able to kill/tag either before they stealthed and disappeared

.go xyz -7090.060000 -3778.950000 8.853730 1 4.419470

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
