### ISSUE TITLE
Bound by Blood and Honor- Orc Racial Knowledge questline
Gnome v...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3192]
> Bound by Blood and Honor- Orc Racial Knowledge questline
Gnome variant i'm assuming

Location of where to use Incense is very unclear and I cannot find the location either

.go xyz -43.320500 2492.350000 -3.479410 369 0.404445

**Comment by Bennylavaa** [comment]
eh its fairly accurate just have to check both tunnels.
