### ISSUE TITLE
Can't finish the quest "Learn to ride in Elwynn Forest" from the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3196]
> Can't finish the quest "Learn to ride in Elwynn Forest" from the mailbox

.go xyz -9453.070000 -1377.760000 46.768100 0 1.738420

**Comment by Bennylavaa** [comment]
its a wrath quest and should be removed.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3196
