### ISSUE TITLE
Jade Ooze - (2656)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#320]
> Slime down in the cafe "Target not in line of sight
`.go xyz 381.826000 -3851.330000 96.142800 0 5.593470`

> Just chilling, doing nothing. Untargetable as well.
`.go xyz 390.141000 -3860.030000 96.016500 0 1.505380`

> This specific Ooze in Skull Rock is evade bugged. He doesn't attack and can't be attacked.
`.go xyz 386.318000 -3856.690000 96.027500 0 2.328420`

> Jade Ooze stuck in Skulk Rock. Can't be attacked.
`.go xyz 383.808000 -3846.030000 96.948800 0 4.678610`

> mob dont attack
`.go xyz 383.687000 -3834.840000 97.838700 0 4.209850`

> Stuck
`.go xyz 378.125000 -3856.170000 96.383500 0 5.106570`

> This jade ooze is untargettable
`.go xyz 383.216000 -3847.190000 96.756500 0 1.366370`

> I'm standing in it, it is "too far away" and not moving
`.go xyz 382.468000 -3852.770000 96.028000 0 1.018070`

> Got a bugged spawn right about where I'm at, he's just sitting here, can't be attacked.
`.go xyz 379.615000 -3848.250000 96.343900 0 0.213870`

> This creature does not attack and cannot be attacked.
`.go xyz 382.990000 -3849.660000 96.444700 0 5.781020`

> this OOze is bugged doesnt attact and cant attack
`.go xyz 382.058000 -3854.040000 95.856700 0 5.476230`

> This creeature is patting throw the floor. in this cave. its coming form above to below
`.go xyz 362.321000 -3875.770000 105.716000 0 0.832362`

**Comment by zana244** [comment]
Could not find it on internal... maybe I'm blind, but all mobs seem to be working fine.
