### ISSUE TITLE
Can't find any Ancient Batteries in the Noonshade Ruins in Tanar...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3202]
> Can't find any Ancient Batteries in the Noonshade Ruins in Tanaris for The Perfect Fuel quest.

.go xyz -7093.720000 -3807.060000 9.514200 1 1.729220

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
