### ISSUE TITLE
hey there i was wondering
since penance in shadow form deals sha...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3204]
> hey there i was wondering
since penance in shadow form deals shadow damage
isnt it supposed to proc my shadow Weaving Talent ?
im asking this cause its not and wanted to know if its meant to be like this or not

.go xyz -7028.080000 -4355.910000 9.121810 1 0.239881

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2987
