### ISSUE TITLE
I have been herbing all day, but never once has Lotus affinity p...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3208]
> I have been herbing all day, but never once has Lotus affinity procced, I have however gotten several lotus' from a single pick. Not sure if something is wrong here..

.go xyz 3197.000000 -4515.150000 110.538000 0 5.772250

**Comment by Shadownflame** [comment]
Only procs from maximum level herbs such as mountain silversage or dreamfoil.
