### ISSUE TITLE
The Perfect Fuel - Says to collect Ancient Battery from trolls a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3210]
> The Perfect Fuel - Says to collect Ancient Battery from trolls at Nooneshade Ruins... but there are no trolls there, so not sure where to find them

.go xyz -7046.570000 -4300.500000 9.207750 1 4.339340

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
