### ISSUE TITLE
humanoids that have ranged attacks like Throw do almost double t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3213]
> humanoids that have ranged attacks like Throw do almost double the melee damage with ranged attacks, (melee swing 64, Throw 106)
lvl8 kolkar outrunner does 9 damage with melee but 16-20 with Shoot

.go xyz 115.078000 -2447.950000 121.656000 0 4.045850

**Comment by Shadownflame** [comment]
Must have been already fixed. Melee damage and range damage roughly matches,
