### ISSUE TITLE
Hello. I wonder if loot drop is supposed to be like this. I open...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3221]
> Hello. I wonder if loot drop is supposed to be like this. I opened 3-4 chests, killed 2 rares and no green rarity item dropped.

.go xyz 1524.150000 -186.323000 30.512300 0 4.368730

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249
