### ISSUE TITLE
Fire Roc's in Abyssal Sands is dropping Linen Cloth. Also the dr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3222]
> Fire Roc's in Abyssal Sands is dropping Linen Cloth. Also the drop rate for Flame Sacks for the quest is really bad.

.go xyz -7878.780000 -3585.590000 49.400500 1 4.253180

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/543
