### ISSUE TITLE
Trying to to the tanaris quest The perfect Container. Is this po...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3223]
> Trying to to the tanaris quest The perfect Container. Is this possible as alliance. I can't speak to the gnomes outside gadgezan and i can't attack them either

.go xyz -7349.660000 -2962.790000 9.112790 1 1.979670

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
