### ISSUE TITLE
Another day, another seemingly bugged fishing daily. Sharp-Infes...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3224]
> Another day, another seemingly bugged fishing daily. Sharp-Infested Waters quest item doesn't seem to want to drop despite having 380 fishing (rod+lure). Tried fishing in both oceans (Faldir's Cove & Drowned Reef in the Great Sea & Alestone Estate in the Forbidding Sea) and the small ponds outside Stromgarde Keep. Not sure what I am doing wrong if anything

.go xyz -2190.790000 -1880.710000 0.314993 0 1.297530

**Comment by Bennylavaa** [comment]
Cannot reproduce
