### ISSUE TITLE
Grazle, the Timbermaw furbolg south of the Emerald Sanctuary, wh...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3225]
> Grazle, the Timbermaw furbolg south of the Emerald Sanctuary, who gives tasks related to killing corrupt furbolgs in the area is not where he should be. He seems to be absent entirely.

.go xyz 3869.840000 -1292.350000 220.030000 1 2.868160

**Comment by zana244** [comment]
#950
