### ISSUE TITLE
i killed a desertfox in tanaris but the sound it made while atta...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3226]
> i killed a desertfox in tanaris but the sound it made while attacking persisted even after it was dead. Even if i got some good distance. WIth distance not hearable but when going back to the spot, the soundmaking was again there but the mob was dead. relogging fixed it. I just wanted to let you know, im not sure if this was a bug from game (cause relogging fixed it?)

.go xyz -7282.910000 -3918.420000 9.036390 1 2.519970

**Comment by zana244** [comment]
Solved on internal, dead fox makes no sound.
