### ISSUE TITLE
Berserking for Beginners quest (troll racial knowledge, Alliance...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3230]
> Berserking for Beginners quest (troll racial knowledge, Alliance side). I just died to this insanely busted Shatterspear Fetish (2k shadow damage per cast, dayum!) and now i have to ressurect via spirit healer because there is no way i gan get to my body in that troll village. Would be nice to add a small radius graveyard in that area if that's the intended amount of damage this thing will deal

.go xyz 6744.900000 206.662000 23.170100 1 1.437390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2326
