### ISSUE TITLE
mobs out in the world are far too wuick to evade and reset

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3232]
> mobs out in the world are far too wuick to evade and reset

.go xyz -9328.910000 -966.654000 66.784800 0 2.926520

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by T1ti** [comment]
This isn't encessarily a pathing issue, it can be related to the leash system (conditions for a mob to keep chasing a player), which is mostly radius based in trinitycore, and completely wrong.

**Comment by T1ti** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5116 example, I opened an issue for leashing mechanics on azerothcore a few years ago

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7331 also exists
Duplicate anyway
