### ISSUE TITLE
after killing the humans here Ogron was just standing in front o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3233]
> after killing the humans here Ogron was just standing in front of Paval Reethe not doing anything and seems bugged. nothing has happened for quite a while.

.go xyz -3372.220000 -3212.920000 34.294800 1 0.459641

**Comment by zana244** [comment]
hmmm first time I tried it worked for me, I'll need to retry some other time.
quest id 1273
#8140
