### ISSUE TITLE
Quest - The Perfect Fuel, the valve to fill the bottle is nowher...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3236]
> Quest - The Perfect Fuel, the valve to fill the bottle is nowhere on the oil platform, as per the quest text.

.go xyz -6786.600000 -4837.810000 0.666546 1 2.751110

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
