### ISSUE TITLE
Storm,Earth,Wind and fine Quest lets you cast the item on a dead...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3245]
> Storm,Earth,Wind and fine Quest lets you cast the item on a dead wind elemental

.go xyz -6209.710000 -1117.000000 -221.116000 1 2.618790

**Comment by zana244** [comment]
Confirmed on internal (and beta 3), you can do 6/6 on the quest by casting the totem on 1 corpse. Make it so you can only cast on low hp and alive mobs.
Quest ID 27511
Totem ID 63060
#1947
