### ISSUE TITLE
Could it be that the gorduni orgres in feralas are overtuned? th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3259]
> Could it be that the gorduni orgres in feralas are overtuned? they hit strong have a huge range, kicks or whatever makes you fly and more hp than usual ?

.go xyz -4812.160000 1152.050000 89.836500 1 4.684320

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/515
