### ISSUE TITLE
Witherbark Broodguard - (2686)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#326]
> These spiders should have an indicator that they drop quest items for Falling Up To Grace. But they don't.
`.go xyz -281.774000 -2910.270000 84.204600 0 2.631220`

> Not only this creature but all creatures randomly heal themselves when you fight them
`.go xyz -367.312000 -2753.850000 87.947500 0 5.549020`

> This spider spawns 2 little spiders when die. Little spiders do not attacking
`.go xyz -274.258000 -2909.410000 85.442500 0 4.698510`

**Comment by zana244** [comment]
Could not reproduce.
