### ISSUE TITLE
tbh not sure, but I played really not healthy amount of vanilla ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3261]
> tbh not sure, but I played really not healthy amount of vanilla and tbc servers, and I think that mana regen on lvl 1+ is really low even for vanilla/tbc standarts

.go xyz -8797.510000 -125.483000 83.509800 0 0.596129

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8274
