### ISSUE TITLE
For the quest: Suspicious Hoofprints. I could get the other 3 qu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3262]
> For the quest: Suspicious Hoofprints. I could get the other 3 quests from the Shaddy Rest Inn, but does not matter what I do, I cannot click on the hoofs to accept the next quest.

.go xyz -3701.940000 -2533.770000 68.652800 1 1.871600

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2424
