### ISSUE TITLE
Kinelory - (2713)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#327]
> Casts Rejuvenation on enemies.
`.go xyz -1551.530000 -3035.000000 13.639700 0 2.202860`

> During the escort quest, Kinelory casts rejuvenate onto her hostile target instead of herself.
`.go xyz -1427.610000 -3031.960000 32.353200 0 5.281740`

> While doing "Hints of a New Plague?" escort part, she's healing (Rejuv 89003) orcs she's trying to kill...
`.go xyz -1423.940000 -3029.140000 33.556500 0 4.354210`

> I just did her escort quest and she kept casting Rejuvenation on enemy mobs
`.go xyz -1426.270000 -3030.670000 32.834400 0 4.358450`

> she healed an enemy?=!
`.go xyz -1536.330000 -3038.030000 13.148000 0 3.254760`

> she buffs enemies during the escort quest
`.go xyz -1464.150000 -3092.770000 13.132700 0 1.671000`

**Comment by zana244** [comment]
#2372
