### ISSUE TITLE
PVP rogue 3.

if I hold the flag, and I cast the vanish spell......

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3274]
> PVP rogue 3.

if I hold the flag, and I cast the vanish spell....the flag falls off me, I appear in stealth, but I don't see stealth spells. Which it shouldn't be.
It's supposed to work if I cast vanish, the flag falls off me and I'm in stleath. And I have spells in stealth

Will there be a change?

.go xyz -8731.830000 541.931000 101.103000 0 5.581390

**Comment by zana244** [comment]
works as intended on internal.
