### ISSUE TITLE
PVP rogue 2.

if i hold the flag and cast the stealth spell...th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3275]
> PVP rogue 2.

if i hold the flag and cast the stealth spell...the flag falls off me and the stealth cooldown appears. which it shouldn't be either.
It's supposed to work if I cast the stealth spell, the flag falls off me and I'm in stealth. No cooldown.

Will there be a change?

.go xyz -8731.830000 541.931000 101.103000 0 5.581390

**Comment by zana244** [comment]
works as intended on internal, if you stealth with flag you lose the flag but you get stealthed.
