### ISSUE TITLE
The Legend of Aru-Talis Quest
Unsure where to go for Golakka Hot...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3282]
> The Legend of Aru-Talis Quest
Unsure where to go for Golakka Hot Springs Core, others were pretty straight forward, but the highest point of the springs has the rare boss (can't really get past them?)

.go xyz -7272.460000 -691.407000 -274.044000 1 1.396600

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
