### ISSUE TITLE
The Perfect Fuel Quest
Says to go to Noonshade Ruins for the Anc...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3283]
> The Perfect Fuel Quest
Says to go to Noonshade Ruins for the Ancient Batteries, but none of them are on the ground or drop from mobs in the area?

.go xyz -7003.560000 -4384.610000 10.283400 1 1.773270

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
