### ISSUE TITLE
Water Co. Saviour Quest
Asks you to look for parts near the boat...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3284]
> Water Co. Saviour Quest
Asks you to look for parts near the boat dock, but there's nothing there?  Do they spawn in a different location?

.go xyz -6882.990000 -4893.380000 0.662280 1 3.649470

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
