### ISSUE TITLE
The quest: "The Perfect Fuel" reads "Collect 8 Ancient Batteries...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3285]
> The quest: "The Perfect Fuel" reads "Collect 8 Ancient Batteries from the Noonshade Ruins" and in the description mentions "The trolls of the Noonshade Ruins west of here" (here is Steamwheedle port). But there are no batteries or trolls at noonshade, just the bandits & thiefs from "regular" quests.

.go xyz -7499.270000 -3801.800000 18.692800 1 4.152370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
