### ISSUE TITLE
Quest "The Perfect Fuel", I no it's not bugged because someone e...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3287]
> Quest "The Perfect Fuel", I no it's not bugged because someone else completed it but I'm under water at the oil workers and I can't seem to fill the cannister, I tried swimming all around it but can't do it

.go xyz -6851.960000 -4917.370000 -6.032620 1 0.028991

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
