### ISSUE TITLE
TAKING DAMAGE WHILE ON THE ELAVATOR IN UNDERCITY? WHILE ITS  GOI...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3289]
> TAKING DAMAGE WHILE ON THE ELAVATOR IN UNDERCITY? WHILE ITS  GOING DOWN IF YOU JUMP

.go xyz 1524.470000 236.941000 -41.389800 0 4.831520

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5484
