### ISSUE TITLE
There should be quest Suspicious Hoofprints object is here, but ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3298]
> There should be quest Suspicious Hoofprints object is here, but it doesnt give any quest, i'm playing as horde so no pre-quest here.

.go xyz -3698.980000 -2535.160000 68.712700 1 3.500000

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2424
