### ISSUE TITLE
For the quest "Water Co. Saviour" in Tanaris, it isn't clear whe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3301]
> For the quest "Water Co. Saviour" in Tanaris, it isn't clear where to find the filter parts required filter parts for the quest. Dialog seems to indicate they should be underwater around the Steamwheedle dock, but there are none to be found there.

.go xyz -6964.440000 -4922.220000 -11.989600 1 2.202240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
