### ISSUE TITLE
In the new quest "The perfect Container" I think i found the cra...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3308]
> In the new quest "The perfect Container" I think i found the crashed gnome cart with a bunch of friendly mobs called cleanup crew, but i cant find any items to pick up.
I also searched the whole west of gadgetzan and could not find any

.go xyz -7043.240000 -3538.430000 13.334000 1 4.121870

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
