### ISSUE TITLE
Can't find Tharil'zun in Redridge for quest.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3312]
> Can't find Tharil'zun in Redridge for quest.

.go xyz -9309.110000 -2993.840000 123.273000 0 1.126350

**Comment by zana244** [comment]
Hmmm, he is where he is supposed to be? (not at the provided xyz)

**Comment by kaytotes** [comment]
Confirmed he spawns fine, painfully.

![image](https://github.com/Project-Epoch/bugtracker/assets/7526918/3ade383d-52e3-4ef5-b40a-3af1ab85d253)
