### ISSUE TITLE
Water Co. Saviour quest. I really have no clue where the Filter ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3316]
> Water Co. Saviour quest. I really have no clue where the Filter Parts are. I can't find them on the seabed around steamwheedle port. not one

.go xyz -6902.420000 -4926.540000 -13.249100 1 1.154390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
