### ISSUE TITLE
Killed the Sludge Beast (Rare Spawn) in the Barrents at The Slud...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3317]
> Killed the Sludge Beast (Rare Spawn) in the Barrents at The Sludge Fen, It granted no exp or loot. Not sure if bugged or not

.go xyz 1088.820000 -3111.160000 79.827400 1 3.311880

**Comment by zana244** [comment]
Grants XP and loot (after vmangos loot update) on internal.
