### ISSUE TITLE
Arya Devout in Silverpine Forest should probably should be marke...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3318]
> Arya Devout in Silverpine Forest should probably should be marked as rare elite and not rare or tuned down a bit

.go xyz -631.791000 1532.300000 7.837660 0 2.120370

**Comment by zana244** [comment]
1.6k hp vs 530 hp which is the hp mobs around her level have... Up to devs if they want to mark as rare elite.
