### ISSUE TITLE
Tried to summon a party member with my summoning portal but no o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3322]
> Tried to summon a party member with my summoning portal but no one in my party was able to click on the portal. We tried inside the instance, outside the instance, and I even tried to relog. No work.

.go xyz -4.461370 -9.153340 -2.414300 732 4.701760

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8257
