### ISSUE TITLE
Just killed the Sentinel of Archaedas in Uldaman and he can't be...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3323]
> Just killed the Sentinel of Archaedas in Uldaman and he can't be looted. Can't be selected either so idk if that's a bug or he isn't lootable because he may have something new.

.go xyz 93.735200 269.947000 -52.148700 70 4.644220

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4158
