### ISSUE TITLE
My voidwalker tries to stand on the exact same pixel as whatever...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3324]
> My voidwalker tries to stand on the exact same pixel as whatever it's attacking. So it makes it difficult for a rogue friend or anyone to attack the enemy from the back if my minion has aggro.

.go xyz -6815.330000 -2891.850000 8.880860 1 0.759547

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3816
