### ISSUE TITLE
Reclaimign the eggs quest in shadra'alor, Can't find eggs. Seein...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3332]
> Reclaimign the eggs quest in shadra'alor, Can't find eggs. Seeing egg spotted assets but cant interact with them

.go xyz -337.122000 -2853.860000 77.082100 0 2.032470

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
