### ISSUE TITLE
Chunky groupers dont aggro sometimes and keep healing to full he...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3333]
> Chunky groupers dont aggro sometimes and keep healing to full health randomly

.go xyz 496.019000 -3403.210000 103.754000 0 0.211371

**Comment by Bennylavaa** [comment]
Confirmed its like their pathing is borked

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1223
