### ISSUE TITLE
some areas of water in bay under orgrimmar's zepp quarter got "w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3335]
> some areas of water in bay under orgrimmar's zepp quarter got "waterbreathing", timer gains more seconds, as if player is above water

.go xyz 1752.490000 -4790.430000 -2.259240 1 4.752360

**Comment by zana244** [comment]
example at
.go xyz 1753.649536 -4797.647461 -4.667461 1 3.553817
#8308
