### ISSUE TITLE
food/water regeneration rates seems too low, in classic full t3 ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3336]
> food/water regeneration rates seems too low, in classic full t3 shaman has 7k mana, here ~5k in just preraid, with gear progression gap will increase, gib nice food

.go xyz 2275.350000 -5324.690000 88.587600 0 0.851447

**Comment by Hatson22** [comment]
Mana/Health regen rates is a separate issue in other reports, this is a suggestion if anything. And it's making assumptions that we will have inflated mana values in tier 3, whenever that will be.
That just depends on how the devs balance items, this report is not relevant, at best it's a suggestion for endgame food/drinks later on that give increased values of HP/Mana. That isn't necessarily a bad idea, but we'll see with time if it will be a good idea or not.
