### ISSUE TITLE
https://youtu.be/5hLF2W62YNc?si=D5b9bvjYmc2aQ59M&t=1740
some tot...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3337]
> https://youtu.be/5hLF2W62YNc?si=D5b9bvjYmc2aQ59M&t=1740
some totems should not be affected by LOS, currently healing stream, windfury, poison/disease cleanse, tremor are bugged in that regard

.go xyz 1623.390000 -4376.080000 28.273800 1 2.871970

**Comment by zana244** [comment]
Confirmed on internal, the totems mentioned in here all respect LoS which is not intended. Same for windfury totem (and probably other pulse totems).

**Comment by ghost** [comment]
Fixed
