### ISSUE TITLE
swapped racials from orc to tauren, endurance(5% hp) doesnt seem...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3338]
> swapped racials from orc to tauren, endurance(5% hp) doesnt seem to be working, tried relogging, swapping items

.go xyz 1604.210000 -4378.310000 9.486070 1 4.952690

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2953
