### ISSUE TITLE
quest "Poisoned Water"(id 6804) Discordant Bracers never drops, ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3345]
> quest "Poisoned Water"(id 6804) Discordant Bracers never drops, ~20 elementals killed 0 q items

.go xyz 1644.770000 -4511.430000 73.233200 0 0.734384

**Comment by zana244** [comment]
you need to use the quest item on them. definitely works now on internal, maybe vmangos update fixed it.
