### ISSUE TITLE
Priest Spell: Penance
Issue: Seems to sporadically  cancel mid c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3351]
> Priest Spell: Penance
Issue: Seems to sporadically  cancel mid cast for no reason.

.go xyz -4911.380000 1703.370000 66.032500 1 2.187540

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/5003

**Comment by Shadownflame** [comment]
RIP penance.
