### ISSUE TITLE
The Quest "Reclaiming the Eggs" in the Hinterlands for the Allia...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3356]
> The Quest "Reclaiming the Eggs" in the Hinterlands for the Alliance side, I am unable to loot the gryphon eggs at specified locations in Shadra'Alor.

.go xyz -442.585000 -2841.580000 92.909100 0 0.023797

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
