### ISSUE TITLE
The drop rate for the quest "Magical Material" seems very low. Y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3372]
> The drop rate for the quest "Magical Material" seems very low. You can see which lockboxes have loot vs which ones are warded as well due to the sparkles.

.go xyz 30.164800 432.619000 42.627000 0 0.967941

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7545
