### ISSUE TITLE
I died last night in zul'farrak, logged out as a ghost.  Today i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3379]
> I died last night in zul'farrak, logged out as a ghost.  Today i logged in and run to zul'farrak to recover my body, when i zoned into zul'farrak i'm still a ghost and now i noticed my gravestone is missing from the map. forcing me to spirit rez.

.go xyz 1276.030000 832.587000 8.895130 209 3.050890

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
