### ISSUE TITLE
Rich Thorium Viens seem like the WoTLK version, with 1 tap minin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3384]
> Rich Thorium Viens seem like the WoTLK version, with 1 tap mining and increased chance to get Arcane Crystals. Not sure if intended.

.go xyz -8131.820000 -1145.490000 -237.876000 1 6.029510

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8068
