### ISSUE TITLE
The quest Speak to Nafien is either available in error, or canno...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3413]
> The quest Speak to Nafien is either available in error, or cannot be completed as Nafien has been removed and replace with Grazzle.

I don't know if the intetion is to have Nafian remain removed, or to put him back and relocate Grazzle to Deadwood VIllage in the south.

.go xyz 6390.390000 -2536.200000 540.056000 1 0.107754

**Comment by zana244** [comment]
#950
