### ISSUE TITLE
Flight path from Gadgetzan to Theramore Isle flies you through t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3428]
> Flight path from Gadgetzan to Theramore Isle flies you through the Steamwheedle Port buildings. Its quite painful.

.go xyz -5917.080000 -5107.410000 8.445610 1 6.068540

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3034
