### ISSUE TITLE
Favored of Elune? quest seems to imply (at least to me) that the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3437]
> Favored of Elune? quest seems to imply (at least to me) that the owlbeasts in Hinterlands can drop the Feathers, however I have yet to get one to drop. Unsure if this is intended or not

.go xyz -193.710000 -3146.990000 117.698000 0 0.769868

**Comment by zana244** [comment]
Intended and blizzlike, cannot drop from NPCs
