### ISSUE TITLE
Primitive Owlbeast - (2928)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#345]
> Primitive Owlbeast (ID 2928) spawn is under the map @ The Hinterlands (51, 50).
`.go xyz 194.437000 -3520.380000 131.602000 0 4.459440`

> Doesn't have quest tracking in tooltips.
`.go xyz 309.983000 -3282.660000 115.068000 0 1.228830`

> Not skinnable
`.go xyz 132.051000 -3156.510000 122.735000 0 3.222250`

**Comment by Bennylavaa** [comment]
they are humanoids not skinable. 

Also none under the map

quest tracking tooltips are for a addon not the game.

**Comment by Bennylavaa** [comment]
Cannot be [skinned](https://wowpedia.fandom.com/wiki/Skinnable), with the exception of [yetis](https://wowpedia.fandom.com/wiki/Yeti), [worgen](https://wowpedia.fandom.com/wiki/Worgen), and [flamewakers](https://wowpedia.fandom.com/wiki/Flamewaker).

https://wowpedia.fandom.com/wiki/Humanoid
