### ISSUE TITLE
mob "Spirit of Lake Mennar" cannot pathfind from its spawning po...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3453]
> mob "Spirit of Lake Mennar" cannot pathfind from its spawning position and resets constantly, making it very difficult to kill for the racial knowledge quest

.go xyz 2674.920000 -5348.340000 76.100300 1 2.917390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1350
