### ISSUE TITLE
mob "Dark Whisper" for quest "The Earth Mother Provides is liste...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3454]
> mob "Dark Whisper" for quest "The Earth Mother Provides is listed as "rare", when it should be listed as "elite" or "rare elite" as it is a very strong elite mob for one person to fight. The quest overall seems way too difficult compared to other Racial Knowledge questlines.

.go xyz -722.838000 -1244.600000 181.644000 1 2.518500

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7585

**Comment by Bennylavaa** [comment]
moved the details to the main issue
