### ISSUE TITLE
Mob "Scarlet Hunter" does not send its pet "Scarlet Hound" to at...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3457]
> Mob "Scarlet Hunter" does not send its pet "Scarlet Hound" to attack the player, the player must run in aggro range of the "Scarlet Hound" to be attacked by it.

.go xyz 2064.580000 -1794.750000 58.393700 0 0.012013

**Comment by zana244** [comment]
#4502
