### ISSUE TITLE
mob "Splashing Elemental" in Un'Goro Crater is dropping Corrupte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3465]
> mob "Splashing Elemental" in Un'Goro Crater is dropping Corrupted Soul Shard. This item should only be obtainable from Felwood Mobs and while carrying a specific item, which I did not have on my character whyen the item dropped.

.go xyz -7244.090000 -448.214000 -271.872000 1 0.861368

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1582
