### ISSUE TITLE
The Un'Goro Hunt quest is listed as an Elwynn Forest quest when ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3468]
> The Un'Goro Hunt quest is listed as an Elwynn Forest quest when it should clearly be in the Un'Goro section

.go xyz -4821.780000 -1155.440000 502.210000 0 2.041460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
