### ISSUE TITLE
quest Do Slavers Leep Records? doesn't appear to have it's quest...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3475]
> quest Do Slavers Leep Records? doesn't appear to have it's quest item on the loot table of the Dark Iron Slavers if it is an item drop that fulfills the quest. Quest item doesn't appear in the tooltip of the mobs.

.go xyz 168.231000 -2160.870000 100.989000 0 1.347120

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
