### ISSUE TITLE
Zorbin's Ultra-Shrinker, quest item for Zapped Giants, does not ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3480]
> Zorbin's Ultra-Shrinker, quest item for Zapped Giants, does not aggro the giants when used. I believe it is supposed to aggro them when they are shrunk.

.go xyz -4939.730000 2187.340000 4.692400 1 5.821020

**Comment by zana244** [comment]
https://www.youtube.com/watch?v=4iugy43iEbo
intended it seems.
