### ISSUE TITLE
Gargantuan Ooze (ID 9621, quest "Melding of Influences") does no...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3482]
> Gargantuan Ooze (ID 9621, quest "Melding of Influences") does not get infight. - Always resets life.

.go xyz -7604.810000 -1579.490000 -271.471000 1 6.154090

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2099
