### ISSUE TITLE
Pet disapears when hearthing

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3484]
> Pet disapears when hearthing

.go xyz -575.198000 -4239.500000 38.010000 1 0.252168

**Comment by zana244** [comment]
Confirmed on internal. Pet should stay with you.
https://youtu.be/Cg6Ie6abAAE?feature=shared&t=4151

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7942 related
