### ISSUE TITLE
The NPC ringo for the quest Lost! doesn't spawn in his cave in U...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3493]
> The NPC ringo for the quest Lost! doesn't spawn in his cave in Un'Goro. It's possible I'm unlucky on timing, but i've checked a couple times and he's not here.

.go xyz -7204.540000 -1392.980000 -232.407000 1 3.348520

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
