### ISSUE TITLE
tranq spell on lost ancient is not working

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3497]
> tranq spell on lost ancient is not working

.go xyz -5560.770000 1588.710000 65.368400 1 2.924970

**Comment by Shadownflame** [comment]
NPC ID 45888
Spell ID 21793 Twisted Tranquility

Spell is just auto interrupted after one second by the npc itself for no particular reason. It's supposed to be a channeled AOE.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1268
