### ISSUE TITLE
I'm not sure if it's an actual bug or not but Aimed Shot does no...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3504]
> I'm not sure if it's an actual bug or not but Aimed Shot does not trigger auto shot after casting like all the other hunter shots. I remember it always starting after the cast from my experience.

.go xyz -9269.540000 -2400.640000 57.337600 0 1.333360

**Comment by zana244** [comment]
Intended in TBC (sadly). Aimed shot resets auto shot timer.
