### ISSUE TITLE
The bug I have is with The Fargodeep Mine. The "scout through" d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3506]
> The bug I have is with The Fargodeep Mine. The "scout through" does not trigger at any point to show it complete. I've went through the whole mine, even killed Goldtooth. I'm trying to run around to see if I can find the trigger spot but so far, nothing. 

Thanks

.go xyz -9784.310000 117.343000 5.786310 0 3.363070

**Comment by zana244** [comment]
#2354
