### ISSUE TITLE
After picking up the quest "The Ironforge Airfield" in Thelsamar...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3510]
> After picking up the quest "The Ironforge Airfield" in Thelsamar, the dialogue option to take you to the quest destination does nothing when selecting it. Abandoning the quest and re-accepting does not fix it

.go xyz -5426.010000 -2933.300000 347.563000 0 1.452180

**Comment by Bennylavaa** [comment]
fixed on ptr
