### ISSUE TITLE
Rich thorium vein only gave 2 thorium ore

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3511]
> Rich thorium vein only gave 2 thorium ore

.go xyz -7972.950000 -1830.930000 -269.579000 1 3.008260

**Comment by Bennylavaa** [comment]
needs review, from what I can find on this is classic had some bug that allowed 6 taps always other comments say 3-4 taps on average with a chance for 2 taps.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8068
