### ISSUE TITLE
combat bug when i missed the initial attack the mob did not come...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3515]
> combat bug when i missed the initial attack the mob did not come for me and im in combat until i kill that mob

.go xyz -9052.940000 -2343.360000 11.575200 1 3.425870

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6800

**Comment by Shadownflame** [comment]
Can't reproduce. Missing the initial attack properly aggroes these mobs. Might be some sporadic glitch.
