### ISSUE TITLE
The quest 'The  Un'goro Hunt' appears under Elwynn Forest in the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3518]
> The quest 'The  Un'goro Hunt' appears under Elwynn Forest in the quest log rather than Un'goro

.go xyz -7987.670000 -1800.470000 133.565000 0 4.137800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
