### ISSUE TITLE
Learn to Ride in Elwynn Forest isn't working as it should be for...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3521]
> Learn to Ride in Elwynn Forest isn't working as it should be for paladins or possibly warlocks too if boosted.

This may be a class level issue due to the mount quests giving free riding training.

.go xyz -6325.900000 -1157.860000 431.623000 0 5.654320

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3196
