### ISSUE TITLE
My group was doing the Rend event. In my only two attempts, the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3528]
> My group was doing the Rend event. In my only two attempts, the fight ended after the first wave of adds. In the first instance, a GM came and opened the two doors that are locked at the start of the event so we could proceed.

.go xyz 188.283000 -419.867000 110.880000 229 0.228352

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8012
