### ISSUE TITLE
The quest The Fizz, in Winterspring is supposed to give you an i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3530]
> The quest The Fizz, in Winterspring is supposed to give you an item on acceptance, but my two attempts to get this item from the quest giver have not gotten me the quest item.

.go xyz 6418.700000 -4839.680000 716.946000 1 5.222130

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7599
