### ISSUE TITLE
Kalaran the Deceiver, who is summoned as a part of the Divine Re...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3535]
> Kalaran the Deceiver, who is summoned as a part of the Divine Retribution questline, can be attack and will absolutely truck the poor little group. Perhaps, he could be killed which is probably very bad.

.go xyz -6685.760000 -1188.380000 240.014000 0 4.774890

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/771
