### ISSUE TITLE
When flying from Gadgetzan to Orgrimmar, the flight path goes st...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3540]
> When flying from Gadgetzan to Orgrimmar, the flight path goes straight through the neat tower Epoch added to Razor Hill. I don't really care and it doesn't matter that much to most, I imagine.

.go xyz 1677.590000 -4315.710000 61.167400 1 2.861990

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
