### ISSUE TITLE
character turns in slo mo out of strafe position

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3544]
> character turns in slo mo out of strafe position

.go xyz -573.499000 -4234.050000 38.133600 1 0.435905

**Comment by zana244** [comment]
That's an amazing thing to notice...
I booted up 2.4.3 stormforge to check and it might be a tad bit slower... I'm not even sure it's server controlled.
Basically, after you strafe and let go of the key your character will take some time  to return to neutral forward facing position...
IMO purely cosmetic, not even sure if fixable...

**Comment by kaytotes** [comment]
In no way server controlled. Nothing we can do.
