### ISSUE TITLE
I am able to drink whilst autoshotting if i start the drink and ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3547]
> I am able to drink whilst autoshotting if i start the drink and shoot animation at the same time.

.go xyz -8009.320000 -5372.150000 0.569384 1 4.408710

**Comment by zana244** [comment]
Confirmed on Internal.
Steps to reproduce:
1. Cast auto shot
2. Eat or drink before 0.5 sec elapse ( before you shoot)
3. Profit
Thrown/Shoot for other classes work correctly, as trying to eat/drink during the cast gives the error "Another action in progress"

**Comment by zana244** [comment]
#2527
