### ISSUE TITLE
Venture Co. Worker - (2978)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#355]
> Dealing 25-32 damage a hit at level 9 on a Druid.
`.go xyz -1866.910000 -1117.620000 96.779400 1 5.463830`

> Some lower level mobs, like this worker for example, hit very hard for their level. They hit for 35-45 and crit me for 60+ on normal auto attacks.
`.go xyz -1877.710000 -1115.730000 94.564900 1 5.875390`

> Hits way to hard like comparatevely, other mobs here(non workers hits like half less)
`.go xyz -1908.710000 -1100.820000 83.515500 1 0.471710`

**Comment by zana244** [comment]
they got strong from mining. not tweaking individual npcs
