### ISSUE TITLE
When using a macro to enable or disable the AutoLoot function fo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3551]
> When using a macro to enable or disable the AutoLoot function for the 3.3.5a client, there is an error on the Server side preventing AutoLoot from being shut off. Macro text -

/Script setCVar("autoLootDefault","1");end

This works correctly, as it should from my 2011 notes to turn AutoLoot On. The same macro text with a "0" as the set value does NOT reset Autoloot for the client as being Off. I am uncertain as to why this is so on this server - on retail and then Bloodcraft a "0" would work.

.go xyz -5666.390000 -372.631000 366.708000 0 0.194041

**Comment by Bennylavaa** [comment]
what are these reports lol

/script if GetCVar("autoLootDefault") == "1" then SetCVar("autoLootDefault", "0"); print("Autoloot Off"); else SetCVar("autoLootDefault", "1"); print("Autoloot On"); end

This works fine.
