### ISSUE TITLE
If a druid is shapeshifted and trying to use the Essence Focuser...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3558]
> If a druid is shapeshifted and trying to use the Essence Focuser in Silithus for the daily quests, they are told the crystal is not the right one, rather than it cannot be used while shapeshifted.

.go xyz -6837.770000 220.536000 3.593060 1 5.399770

**Comment by Bennylavaa** [comment]
Lets me use it fine  in all forms.
