### ISSUE TITLE
The Perfect Fuel" quest from steamwheedle port seems to be bugge...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3592]
> The Perfect Fuel" quest from steamwheedle port seems to be bugged. I cant find any  Ancient B
atteries in the noonshade ruins

.go xyz -6949.930000 -4342.920000 12.354400 1 4.457230

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
