### ISSUE TITLE
Western Plaguelands quest "Advanced Alchemy" is categorised at E...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3600]
> Western Plaguelands quest "Advanced Alchemy" is categorised at Elwynn Forest in the questlog

.go xyz 984.203000 -2506.890000 60.178300 0 2.979970

**Comment by Bennylavaa** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/2305
