### ISSUE TITLE
Unable to loot the ligther colored ravasaur eggs for Venomhide E...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3603]
> Unable to loot the ligther colored ravasaur eggs for Venomhide Eggs quest in Un'goro Crater.

.go xyz -7446.400000 -1935.540000 -269.349000 1 0.289076

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
