### ISSUE TITLE
Razormane Scout - (3112)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#361]
> Respawn rate is too high
`.go xyz 74.035000 -4563.510000 55.725100 1 6.282480`

> Animations of him attacking are not being displayed even though my Hp bar goes down
`.go xyz 131.451000 -4482.450000 37.084700 1 2.454850`

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/8330
