### ISSUE TITLE
Quest, Call to Arms! Horde/Revantusk village Hinterlands, Item r...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3611]
> Quest, Call to Arms! Horde/Revantusk village Hinterlands, Item reward "Revamtusk Pouch" misspelled.

.go xyz -562.562000 -4618.170000 9.753300 0 4.521380

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7575
