### ISSUE TITLE
Razormane Dustrunner - (3113)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#362]
> mobs are not castin enouhgt, why make a caster mob that goes in to melee
`.go xyz 398.167000 -4321.240000 24.493100 1 1.501110`

> While being down to around 50% he stops in place and does nothing for second or so. On retail he usually casts debuff during this time
`.go xyz 410.697000 -4315.850000 24.857700 1 1.869750`

**Comment by Shadownflame** [comment]
Brother is lvl 8, give them a break. They cast their faerie fire as intended.
