### ISSUE TITLE
In the last step of 'Betrayed' where you click on a crystal to s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3633]
> In the last step of 'Betrayed' where you click on a crystal to summon Rimtori, it's possible to click the crystal twice (there's a delay before the mob spawns so you think it did not work and retry). Doing so  summons a 2nd Rimtori NPC.

.go xyz 4279.140000 -6295.680000 95.561400 1 0.496117

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5419
