### ISSUE TITLE
Durotar Tiger - (3121)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#365]
> weird thing, can not skin on party this one and the one from the hill
`.go xyz -805.907000 -5510.970000 2.188070 1 4.450640`

> when in party i cant skin the animal
`.go xyz -730.355000 -5597.180000 24.906300 1 3.492470`

> IT resets and is not possible to kill
`.go xyz -999.898000 -5128.400000 -1.633040 1 4.332330`

> If you put one toe in the water they freak out and reset
`.go xyz -1061.700000 -5161.330000 -0.203965 1 3.031490`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
