### ISSUE TITLE
Objectives tracker seems to count items in bank towards quest pr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3657]
> Objectives tracker seems to count items in bank towards quest progress. At least for Another Message to the Wildhammer. Shows I have 3/10 Long Elegant Feather even though those are in the bank. Not sure if this is intended behavior or not.

.go xyz 1162.950000 -2254.110000 71.593500 0 4.250020

**Comment by zana244** [comment]
afaik it's intended (misleading) behaviour
