### ISSUE TITLE
A lot of the Drywallow crocolisk spawns seem to be doubling up. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3661]
> A lot of the Drywallow crocolisk spawns seem to be doubling up. As if the points are supposed to be able to spawn a Snapper OR Vicejaw, but instead chooses to spawn both. They even patrol in pairs of the two.

.go xyz -3016.580000 -3125.020000 42.007000 1 4.920710

**Comment by zana244** [comment]
#6532
