### ISSUE TITLE
Flight path from Camp Taurajo to Brackenwall Village clips throu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3662]
> Flight path from Camp Taurajo to Brackenwall Village clips through multiple walls and buildings in Fort Airhart on the way.

.go xyz -3147.390000 -2842.180000 34.610000 1 6.114960

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
