### ISSUE TITLE
Flight path from Sepulcher to Tarren Mill goes through the Dalar...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3663]
> Flight path from Sepulcher to Tarren Mill goes through the Dalaran barrier briefly.

.go xyz -274.256000 -477.270000 149.328000 0 4.102050

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8077 duplicate 
 https://github.com/Project-Epoch/bugtracker/issues/6744 related
