### ISSUE TITLE
Flight path from Tarren Mill to Sepulcher goes straight through ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3664]
> Flight path from Tarren Mill to Sepulcher goes straight through the Dalaran shield, exposing the flat ground inside the shield.

.go xyz 282.814000 1391.530000 148.911000 0 1.009330

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6921
https://github.com/Project-Epoch/bugtracker/issues/6744
