### ISSUE TITLE
Not entirely sure if it's related to the flight path or not, but...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3667]
> Not entirely sure if it's related to the flight path or not, but I logged out on the flight path between Camp Taurajo and Thunder Bluff. When I logged in, it didn't autmoatically join me to any channels (General, Trade, LocalDefense, World, etc.) Relogging did cause me to join all channels, though.

.go xyz -1213.070000 35.700800 176.819000 1 2.924060

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4099
