### ISSUE TITLE
When i use moonfire at max rank and then use another moonfire wi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3672]
> When i use moonfire at max rank and then use another moonfire with less rank the dot its uptaded with the lowest rank moonfire dmg instead maintain the moonfire max rank dot dmg and only make direct dmg with the lowest rank moonfire

.go xyz -6893.470000 -4471.220000 24.711000 1 3.579590

**Comment by zana244** [comment]
#2661
