### ISSUE TITLE
PvP won't disable even though I have it set to disabled.

Additi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3674]
> PvP won't disable even though I have it set to disabled.

Additionally. My Blizzard AoE will place me into pvp if a flagged player of the opposing faction enters it.

.go xyz -8065.070000 -5329.360000 1.128130 1 0.958205

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7703
