### ISSUE TITLE
Burning Blade Fanatic - (3197)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#368]
> Drop rates seem very high for Collars and the Lieutenant's Insignia, not related to this mob but Kron's Amulet Quest dropped on the very first crokolisk mob I fought, this one took 5. This could be just a -very- small chance of concurrence but with how fast Searing Collars are dropping I'm inclined to think it may be statistically significant. I'll be keeping a closer eye on drop rates.
`.go xyz 1497.070000 -4833.090000 11.899400 1 1.367670`

**Comment by Bennylavaa** [comment]
vmangos loot fixed.
