### ISSUE TITLE
Shaman Talent Tree to skill issue: when gaurdian totems has 2 po...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3682]
> Shaman Talent Tree to skill issue: when gaurdian totems has 2 points you receive an increase in the amount of damaged reduced by your stoneskin totem and windwall totem by 20% and reduces the cooldown of yoru grounding totem by 2 sec. WHILE this reflects in the spell book the correct tooltip information, The totems dropped are not giving the correct numbers, i.e. windwall totem SHOULD give 38 damage reduction , it is only giving 32

.go xyz -6233.930000 346.259000 383.653000 0 1.627940

**Comment by zana244** [comment]
As far as I am aware, this is a 3.3.5 client limitation -- purely visual issue on the buffs. The stoneskin totem part works (I think, shoddy testing). However, it seems that windwall totem does not work at all.
#8380
