### ISSUE TITLE
The path up to Aru-Talis Site Three could use some smoothing out...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3702]
> The path up to Aru-Talis Site Three could use some smoothing out too.

.go xyz -6790.770000 -2279.130000 -229.292000 1 3.978730

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/2317

**Comment by Bennylavaa** [comment]
added it to the other report for the quest should be fine living there.
