### ISSUE TITLE
Path up to Aru-Talis Site Two could use some smoothing out.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3703]
> Path up to Aru-Talis Site Two could use some smoothing out.

.go xyz -6413.800000 -2029.450000 -215.765000 1 6.009060

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/2317

**Comment by Bennylavaa** [comment]
added it to the other report for the quest should be fine living there.
