### ISSUE TITLE
Quest; Punctuation;
Wanted: Foulcrest (ID 26506)
"Some months ag...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3705]
> Quest; Punctuation;
Wanted: Foulcrest (ID 26506)
"Some months ago, while...skies, a brave...since then, he's fallen into a blood-fury, meaning he's slaying...

.go xyz 357.457000 -2116.940000 121.839000 0 6.272050

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7960
