### ISSUE TITLE
I boosted a shaman to 45 and spent talents in the enhancement tr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3716]
> I boosted a shaman to 45 and spent talents in the enhancement tree until getting to Unleashed Rage.  Every time I clicked to spend talents on Unleashed rage it unlearned the rank immedietly.  I am now missing talent points and cannot spend any further talent points in enhancement.  posted with screenshot to discord as well.

.go xyz -2923.930000 -243.062000 53.843000 1 1.178090

**Comment by Shadownflame** [comment]
Resolved on beta.
