### ISSUE TITLE
[The Un'Goro Hunt] quest where you have to kill a stegodon, is l...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3724]
> [The Un'Goro Hunt] quest where you have to kill a stegodon, is listed under Elwynn forest and not Un'Goro crater

.go xyz -7265.020000 -938.122000 -271.722000 1 6.104120

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
