### ISSUE TITLE
Quest: Cant make an omlett witout...
is bugged. cannot click the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3731]
> Quest: Cant make an omlett witout...
is bugged. cannot click the eggs even thogh they are shiny and should be clickable

.go xyz -375.956000 -2835.180000 74.840600 0 0.435264

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8293
