### ISSUE TITLE
A Strange Request  -    this quest has been changed i noticed. y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3750]
> A Strange Request  -    this quest has been changed i noticed. you made a new NPC in feralas to turn in the shunken head to so the player doesnt have to return to org. I went to the Lariss Pavillion but the NPC in quesiton is not there an for that matter neither is the previous night elf NPC

.go xyz -4960.950000 -1691.010000 4.163240 1 5.004710

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2075
