### ISSUE TITLE
kyles gone missing quest in mulgore. fed kyle strider meat. he a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3763]
> kyles gone missing quest in mulgore. fed kyle strider meat. he ate, dance, dissapeared. no quest credit

.go xyz -2183.130000 -458.934000 -6.748490 1 3.037130

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/995addbb-e64d-45ca-8c1e-0c52635f9d0c)
