### ISSUE TITLE
When flying from gadgetzan's flight path (alliance) to theramore...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3764]
> When flying from gadgetzan's flight path (alliance) to theramore, your gryphon goes through the buildings in the new steamwheedle port, which looks awful + unintentional.

.go xyz -4806.840000 -5264.820000 9.723870 1 0.125277

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3034
