### ISSUE TITLE
Silithid Swarmer - (3252)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#377]
> I know technically its supposed to be tameable, but we were discussing with Eredun in the hunter channel about silithids being untameable, and perhaps this guy should be made as such?
`.go xyz -3325.170000 -2013.250000 91.720500 1 0.635901`

**Comment by Shadownflame** [comment]
These guys aren't true silithid, but scorpids. Blizzlike.
By Kicw [on 2007/05/12](https://www.wowhead.com/classic/npc=3252/silithid-swarmer#comments:id=2840248) (Patch 1.12.1)		
Subject: "Just got one"No they do not keep their swarm power.. and they are tamable... they are the scorps.. not the grubs
