### ISSUE TITLE
If you only dot the Wastewander shadow mages in Tanaris, the cas...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3775]
> If you only dot the Wastewander shadow mages in Tanaris, the caster with the voidwalker pet, then only the shadow mage will aggro. I killed one with only dotting with corruption and curse of agony. The pet did not attack me at all. Once I use a spell that does damage on cast, i.e. Immolate, the pet aggros. The same is not true for the pet. One dot on the pet, and the shadow mage aggros too.

.go xyz -7434.060000 -4354.170000 7.867490 1 3.007470

**Comment by zana244** [comment]
#559
