### ISSUE TITLE
health is regenerating way too fast.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3782]
> health is regenerating way too fast.

.go xyz -8965.550000 -372.368000 72.991700 0 0.817382

**Comment by Shadownflame** [comment]
I can actually confirm this. Health regen on low levels seems faster than vanilla-feel. (as opposed to mana)
Level 2 human warlock test case, 23 int  / 26 spirit, on classic 1.12 regen is approx 5-6 health per tick on video (takes 8 ticks to regen from ~33% to 100, for a total of 68 health = 16 seconds / 46 health) https://youtu.be/17X1ON3ZAJs?t=213
Recreating same test case on Epoch, I'm getting 13 health ticks and regen to full in 4 ticks or 8 seconds (from 33%).

**Comment by Shadownflame** [comment]
Work in Progress by Ktotes.

**Comment by Shadownflame** [comment]
After recent deploy, health regen is slightly closer to blizzlike value, the same test case is getting 9 health / tick instead of 13 now.
Currently both health and mana regen is slightly increased compared to blizz at the low level bracket.

**Comment by kaytotes** [comment]
Marking as complete. Latest implementation matches vMangos which is the majority of 1.12 servers. I agree it does not 100% line up with Classic in every case but that is an information problem not a programming problem. No further work will be done on this unless there are breakthroughs elsewhere eg upstream vMangos to correct the logic based on larger samples of data etc.

**Comment by Shadownflame** [comment]
Fair enough, I think the current values support the increased stamina on items better.
