### ISSUE TITLE
Water Co. Saviour quest you added takes way to long to do. chang...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3808]
> Water Co. Saviour quest you added takes way to long to do. change it from 8 to 3 or add more in the water. respawn is too long. 2 people cant even do the quest at the same time

.go xyz -6961.630000 -4959.190000 -14.569200 1 0.187425

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
