### ISSUE TITLE
I have encountered a bug with the quest Reclaiming the Eggs. The...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3811]
> I have encountered a bug with the quest Reclaiming the Eggs. The eggs are not clickable and thus not able to be completed. In the zone Shadra'Alor Hinterlands,

.go xyz -386.200000 -2958.890000 91.453500 0 6.060390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
