### ISSUE TITLE
Gordunnni Thieves quest is bugged, it drops the Camp Mojache Sup...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3813]
> Gordunnni Thieves quest is bugged, it drops the Camp Mojache Supplies but everytime it drops one it resets the next drop so you cant complete it.

.go xyz -4881.740000 1254.450000 79.634000 1 0.367112

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7334
