### ISSUE TITLE
You can open chests that are not in your line of sight.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3815]
> You can open chests that are not in your line of sight.

.go xyz -298.856000 -3468.360000 187.296000 0 5.805760

**Comment by Shadownflame** [comment]
Can confirm this is happening, you can snipe chests through walls floors and pillars.
![WoWScrnShot_081424_140247](https://github.com/user-attachments/assets/30462a3b-b23a-4d96-b619-6829dcd8f8d9)

**Comment by Shadownflame** [comment]
Might be blizzlike behavior, TBD.
