### ISSUE TITLE
Blackhoof Armaments item drop from "Arms of the Grimtotems" ques...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3826]
> Blackhoof Armaments item drop from "Arms of the Grimtotems" quest should be interactible items (the spears on wood in the area) but aren't clickable

.go xyz -2470.270000 -3187.110000 33.911900 1 5.711030

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3195
