### ISSUE TITLE
There is the minimap marker and minimap buildings of Mudsprocket...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3829]
> There is the minimap marker and minimap buildings of Mudsprocket, but it doesn't exists

.go xyz -8900.610000 773.459000 90.764400 0 3.102550

**Comment by Shadownflame** [comment]
Part related. Confirmed report doesn't mention buildings. https://github.com/Project-Epoch/bugtracker/issues/7623
