### ISSUE TITLE
Kolkar Wrangler - (3272)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#383]
> Very high magic resistances, I don't know if it's intended, but they resist almost 45% of my damage.
`.go xyz -6.902940 -1730.700000 94.136200 1 1.788730`

> Highly Resistant to Fire Damage -- Not Sure if intentional
`.go xyz -36.292100 -1690.860000 94.960300 1 1.952880`

> This mob resists all of my fire spells, about 75% of their damage. They probably have some very high fire resistance value. I don't see why a centaur would have this kind of resistance against fire? They didn't have on retail and it makes no sense for lore.
`.go xyz 68.090200 -2013.050000 92.279800 1 1.348710`

**Comment by Shadownflame** [comment]
Resolved.
