### ISSUE TITLE
Missing the interaction with "Suspicious Hoofprint" in Theramore...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3830]
> Missing the interaction with "Suspicious Hoofprint" in Theramore for the quest along with "The Black Shield" and "Lieutenant Paval Reethe

.go xyz -3698.530000 -2534.220000 68.446600 1 3.444160

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2424
