### ISSUE TITLE
When searing totem is down and you tag the mob, it attacks the m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3850]
> When searing totem is down and you tag the mob, it attacks the mob as it should. However, sometimes, when you  kill the mob and then tag another one, searing totem doesnt attack another one (although its in range), but just stays passive and not attack.

.go xyz -6483.840000 -4925.180000 6.804040 1 5.096990

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2591
