### ISSUE TITLE
Quest Think Of The Animals bug:

the creatures that I cleansed a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3853]
> Quest Think Of The Animals bug:

the creatures that I cleansed and they became hostile after clensing : they didnt attack me, they just became hostile (red) and stood there letting me kill them withouth hitting back

.go xyz -6989.340000 -4740.290000 8.578760 1 3.825610

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2233
