### ISSUE TITLE
Im stuck in pvp despite it being disabled; this was after leavin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3857]
> Im stuck in pvp despite it being disabled; this was after leaving warmode.

.go xyz -8451.380000 1111.280000 19.052100 0 0.094765

**Comment by Shadownflame** [comment]
Leaving Warmode properly removes PvP flag on the internal realm.
Other PvP flag sticking issues here https://github.com/Project-Epoch/bugtracker/issues/7703
