### ISSUE TITLE
Witchwing Slayer - (3278)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#386]
> I'm unsure if this is normal behavior, but these enemies do not "ask others" for help when they flee in fear and contact other similarly named mobs.
`.go xyz 513.954000 -1362.530000 91.667500 1 3.967440`

**Comment by Shadownflame** [comment]
Peer behavior should be fixed with last update.

**Comment by Shadownflame** [comment]
Properly calls for help now, assuming there is a mob close enough to reach. They're pretty scattered.
