### ISSUE TITLE
Can not find the spawn for Sunken Treasure -- searched for an ho...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3870]
> Can not find the spawn for Sunken Treasure -- searched for an hour or more with three people and a dwarf using their racial with no luck

.go xyz -11360.100000 -3979.410000 0.000834 0 2.393290

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8171
