### ISSUE TITLE
I turned in "A Taste of Flame" to Cyrus Therepentous, showing hi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3874]
> I turned in "A Taste of Flame" to Cyrus Therepentous, showing him the molt from the "Divine Retribution" chain, and I'm not getting the quest to kill Bael'Gar

.go xyz -7649.590000 -3044.570000 131.529000 0 4.950240

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5454
