### ISSUE TITLE
Dodge chance in  bear form is way higher than it should be, some...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3878]
> Dodge chance in  bear form is way higher than it should be, somehow it looks like its adding 15% flat dodge when u junp to the bear! atm i have like 17.62 dodge, in bear form it should be 21,62, but i get 36.62 which is a lvl of t4 geared druid in TBC

.go xyz -8369.600000 -2750.850000 186.147000 0 0.206966

**Comment by zana244** [comment]
#2759 most likely culprit
