### ISSUE TITLE
Pls try to fix armor in bear form scaling, all rings, trinkets, ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3879]
> Pls try to fix armor in bear form scaling, all rings, trinkets, weapon, and bonus armor on items( ggreen one) IS NOT scaling in bear form and from 10% armor talent in feral tree. ITS wotlk mechanic to not scale cosue there ferals where changed to get armro only from leather gear, BUT in tbc and classic druids where always getting armor and armor scales in form due to crushes!

.go xyz -8867.220000 531.486000 106.790000 0 2.078820

**Comment by kaytotes** [comment]
@Bunnyblock2 We fixed this right?

**Comment by Shadownflame** [comment]
Looks fixed to me.
