### ISSUE TITLE
People without warmode on can just jump into combat whenever the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3894]
> People without warmode on can just jump into combat whenever they want? Whats the point of warmode then? Sure they are now flagged. But if i went into a 1 v 1 and someone comes along without warmode on, can now jump me for a free kill uncontested and just walk away, go reset the warmode.

.go xyz -325.183000 -4500.420000 11.028700 0 0.422858

**Comment by Bennylavaa** [comment]
not a bug
