### ISSUE TITLE
Sergra Darkthorn - (3338)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#391]
> Completing Echeyakee played the graphical effect for bestowing it, but I did not properly receive Echeyakee's Grace.
`.go xyz -481.040000 -2667.280000 97.215300 1 4.205780`

**Comment by Shadownflame** [comment]
https://www.wowhead.com/classic/spell=5320/echeyakees-grace aura is hidden, works as intended. Your spirit does get increased by 2.
