### ISSUE TITLE
mobs in ZF wont follow you after u aggro them and go behind a wall

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3926]
> mobs in ZF wont follow you after u aggro them and go behind a wall

.go xyz 1472.350000 776.218000 23.370700 209 0.998267

**Comment by Shadownflame** [comment]
I can't reproduce this issue, however it's potentially a huge problem if this is possible to do. 
@Bennylavaa @zana244 any luck?

**Comment by Bennylavaa** [comment]
Cannot reproduce, this just needs more info currently only time they have issues is if you jump on top of the wall which they evade which is normal.
