### ISSUE TITLE
I can't seem to explore the area in the south of burning steppes...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3930]
> I can't seem to explore the area in the south of burning steppes, i think it's called Ashfall Post. The new questing hub. Maybe i'm not hitting the right point but it if that's true then it seems quite difficult to trigger the exploration of this area of the map.

.go xyz -7894.780000 -2320.620000 132.492000 0 1.970680

**Comment by zana244** [comment]
#4593
