### ISSUE TITLE
The Art of Golemancy quest feels terrible, I would test if it ac...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3931]
> The Art of Golemancy quest feels terrible, I would test if it actually works but there is no feedback to whether the mob you killed actually counts towards the 20 enemies slain, you can only control the golemn for 20 minutes, the golemn does barely enough damage and takes so much damage killing 1 mob per minute is just about doable. the heal it gets is interrupted by damage but the mobs around the are acan do poison that lasts for 30 seconds.

.go xyz -8084.290000 -2114.870000 132.115000 0 2.349690

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
