### ISSUE TITLE
probably well known and reported issue but mob pathing seems ver...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3935]
> probably well known and reported issue but mob pathing seems very inconsistent atleast in the open world. In some common aoe farming spots for mages mobs frequently change direction from the core pack, especially if there is 'unusual' terrain involved such as wooden fences in WPL or the Wodden Dock in Tanaris. Should be very easy to reproduce just running a normal frostmage aoe route on popular areas.

.go xyz -7584.660000 -1135.120000 261.534000 0 3.454250

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
