### ISSUE TITLE
felcloth droprate seems off or extremely reduced? killed satyrs ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3942]
> felcloth droprate seems off or extremely reduced? killed satyrs in both felwood and azshara more than 100 in total and not 1 fel cloth but 6 demonic runes.

.go xyz 4756.180000 -6580.700000 104.389000 1 3.858540

**Comment by Shadownflame** [comment]
DB is set to 3.7% for most of these satyrs, everything else is RNG. As is.
