### ISSUE TITLE
Southsea Cannoneer - (3382)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#396]
> Drops for whites are little overboard, pretty much every mobs drops simple shoes or similar
`.go xyz -1734.810000 -3768.790000 11.021400 1 2.074800`

> It dropped level 22 mail shoulders, not sur eif thats how it should be
`.go xyz -1665.390000 -3831.700000 13.310600 1 3.108910`

**Comment by Bennylavaa** [comment]
vmangos loot fixed
