### ISSUE TITLE
Enemies killed with the golem during the quest "The Art of Golem...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#3984]
> Enemies killed with the golem during the quest "The Art of Golemancy" doesn't propoerly count.

Plus fighting with the golem is horribly low, are you sure of his stats?

.go xyz -8024.610000 -2235.490000 133.763000 0 5.160640

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
