### ISSUE TITLE
My Scout's Tabard disapeared. I got it restored via mail but now...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4003]
> My Scout's Tabard disapeared. I got it restored via mail but now its saying i dont have the required rank (Scout). My current rank is Grunt tho. Cheers, great work with the server guys, Feels amazing so far! Thank you.

.go xyz -2335.950000 -367.344000 -8.486560 1 3.292970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1632
