### ISSUE TITLE
Jumping in water resets mobs.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4010]
> Jumping in water resets mobs.

.go xyz 482.634000 -3436.250000 96.120400 0 5.197490

**Comment by zana244** [comment]
Confirmed on internal, a lot of mobs will reset if you jump from land into water. Some of them will reset if you jump to the surface of the water while you were underwater.

**Comment by zana244** [comment]
#8302 Related probably.

**Comment by Shadownflame** [comment]
Resolved.
