### ISSUE TITLE
Died in a dungeon, got disconnect logged back in a few hours lat...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4019]
> Died in a dungeon, got disconnect logged back in a few hours later and when I enter the dungeon to retrieve my corpse it enters the dungeon as a ghost

.go xyz -7062.070000 -3316.930000 11.260600 1 4.190100

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
