### ISSUE TITLE
While repeatedly re-channeling arcane missiles (let the whole ch...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4033]
> While repeatedly re-channeling arcane missiles (let the whole channel end) sometimes it will do the casting animation and take your mana, but it won't cast.

.go xyz 3910.590000 -1175.650000 238.273000 1 0.727270

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5003
