### ISSUE TITLE
Respec not remove spells from spell book or useablity.

Spec'd p...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4048]
> Respec not remove spells from spell book or useablity.

Spec'd prot, when I respec'd it didnt not remove  Holy Shield, and is still useable, while spec'd holy.

.go xyz 5262.830000 -793.725000 356.795000 1 2.390780

**Comment by zana244** [comment]
Could not reproduce on internal anymore.
