### ISSUE TITLE
The quest [The Un'Goro Hunt] part 3 where you kill a Stegodon is...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4051]
> The quest [The Un'Goro Hunt] part 3 where you kill a Stegodon is marked under Elwynn Forest in the quest log.

.go xyz -7865.710000 -547.663000 -259.145000 1 4.604490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
