### ISSUE TITLE
There's a wanted poster at Springsprocket showing a yellow excla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4053]
> There's a wanted poster at Springsprocket showing a yellow exclamation mark indicating a quest, but it's not interactable with, can't take quest.

.go xyz -6894.120000 -3756.110000 333.781000 0 0.608991

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8139
