### ISSUE TITLE
the Dark iron smelt quest "the spectral chalice" did not grant t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4061]
> the Dark iron smelt quest "the spectral chalice" did not grant the ability to smelt dark iron

.go xyz 1238.250000 -235.502000 -85.674400 736 5.408180

**Comment by zana244** [comment]
Confirmed on internal, it does not teach Smelt Dark Iron after completing the quest.
Quest ID 4083

**Comment by kaytotes** [comment]
Blizzlike. The quest itself does not give you the skill, nor does the challice. On complete you speak to Gloom'rel again. Tested on internal, working fine. Closing.
