### ISSUE TITLE
No Darkiron nodes?

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4065]
> No Darkiron nodes?

.go xyz -1495.520000 -2931.470000 32.208500 0 4.778650

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/9978d713-2efa-4972-9f82-2dff71a68f9f)
they are not in arathi highlands, its in Arathi Basin
