### ISSUE TITLE
Dark Coffer chest/ heart of the mountain are not lootable

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4069]
> Dark Coffer chest/ heart of the mountain are not lootable

.go xyz 808.124000 -349.203000 -50.578100 736 4.445150

**Comment by Bennylavaa** [comment]
Can loot the secret safe, the Dark Coffer, and the relic coffers but cannot loot the heart of the mountain gem.

**Comment by kaytotes** [comment]
Next deploy.

**Comment by Bennylavaa** [comment]
Can loot the dark coffer chest but heart of the mountain gives nothing when looting
