### ISSUE TITLE
Echeyakee - (3475)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#407]
> Tame Beast fired but did not do anything after channeling the entire bar. Echeyakee appears to be untameable. I am not sure if this is intended or not.
`.go xyz 436.267000 -3021.730000 91.704100 1 5.388570`

**Comment by Shadownflame** [comment]
This is not a problem with Echeyakee. The spell can be resisted but it doesn't seem to display a resist message on Epoch when it fails.
