### ISSUE TITLE
Quest: Anatomy of the Afterlife

When you summon the abomination...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4075]
> Quest: Anatomy of the Afterlife

When you summon the abomination, you donÂ´t get its skills. 
That way it gets almost impossible to defeat Akagi.

.go xyz 509.350000 1615.780000 124.989000 0 4.382460

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6022
