### ISSUE TITLE
NPC Salfa in Winterspring gave no xp for the quest "Winterfall A...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4078]
> NPC Salfa in Winterspring gave no xp for the quest "Winterfall Activity" not to be confused with the other quest with the same name, are these meant to be a chain?

.go xyz 6545.650000 -2777.200000 570.351000 1 4.768240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2130
