### ISSUE TITLE
The flightpath leaving north out of Tanaris fly's through severa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4080]
> The flightpath leaving north out of Tanaris fly's through several buildings, not sure if you count this a a bug. Due to the new buildings in the port.

.go xyz -4739.100000 -5251.370000 17.097700 1 0.267968

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
