### ISSUE TITLE
XP gain is unequal for these early mobs, unsure if in groups? Du...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4085]
> XP gain is unequal for these early mobs, unsure if in groups? Dun Morogh area

.go xyz -5965.780000 -391.385000 414.217000 0 5.424320

**Comment by Shadownflame** [comment]
XP gain can be unequal for a dozen reasons. Some of the boars near the GPS are lvl 5, others are lvl 6. They would yield different exp. Group members could also get different exp depending on whether one of them is running the explorer contract or have rested exp. 
This report doesn't contain enough details to find out what's their problem.
