### ISSUE TITLE
Able to replicate the shadowform CD bug. It happens if you try a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4090]
> Able to replicate the shadowform CD bug. It happens if you try and enter shadowform whilst shadowform is on cooldown.

.go xyz -7174.050000 -3795.530000 8.385500 1 1.540910

**Comment by Shadownflame** [comment]
Confirmed, using the ability while on GCD or spamming it fast gets it stuck, ages old issue on private servers. Priest must relog to use the ability again.

**Comment by zana244** [comment]
Wasn't able to reproduce the bug without using .cooldown, but I found this commit on upstream TC
https://github.com/Project-Epoch/TrinityCore/commit/018e66bc914e3e39b01e15a51ad683a5e881d156
might be worth implementing, there's also a bit of discussion on the issue there.

**Comment by Shadownflame** [comment]
Can't seem to bug it anymore.
