### ISSUE TITLE
World chat channel isn't working for me. I can see it, but I can...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4099]
> World chat channel isn't working for me. I can see it, but I can't type anything in. for me, world chat channel is number 6 but when I go /6 space ... it doesn't work

.go xyz -4352.970000 2659.610000 -2.344340 1 1.577660

**Comment by kaytotes** [comment]
Super rare, hard to repro, but exists

**Comment by Shadownflame** [comment]
This happens if you relog or DC/server crash during a flight path. You can't access channels when you log back until you relog again on the ground. Unclear if any other circumstances can trigger it, I only experienced it once on the beta when server crashed on flight path.

**Comment by kaytotes** [comment]
Confirmed the above is a dependable test case

**Comment by kaytotes** [comment]
Note this actually applies to all channels eg /1 for general

**Comment by kaytotes** [comment]
Okay so on investigation the way this works is the client sends CMSG_JOIN_CHANNEL packet up to the server for each channel that the player is opted into client side. I assume so it remembers to not put you back into World if you've left World. 

It does this when the player logs in and is stood on the ground.

If the player is on a flightpath however weirdly the client does _not_ send the packet and waits until you have finished your journey and exited the flight path.

This issue was related to not rejoining on exit. 

As far as I can tell its blizzlike that you can't see the global / zone chats if you log in on a flight path. It's weird but I could not find a good way to force that server side while also respecting opted out channels. The client has to request.

So, Next Deploy it will now correctly join you to channels _after_ your flightpath ends in this scenario.
