### ISSUE TITLE
I've noticed some container items such as Pirate's Footlocker fr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4102]
> I've noticed some container items such as Pirate's Footlocker from Southsea Pirates and Mithril-Bound Trunk from Fishing have a chance to give you nothing at all

.go xyz -7955.280000 -5474.890000 7.528690 1 5.701110

**Comment by Bennylavaa** [comment]
about a 20% chance to get an empty one This could be due to the vmangos item import stuff as well.

**Comment by Shadownflame** [comment]
Seems resolved after last update. About 4-5% of them only drop silver when you get unlucky, but that's the worst case scenario.
