### ISSUE TITLE
QUEST - Escaping Airheart new escort in Dustwallow/Barrens.  May...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4103]
> QUEST - Escaping Airheart new escort in Dustwallow/Barrens.  Maybe increase the npc escort health they were dying very fast to the elite mobs and some parts the elites were respawning multiple times

.go xyz -2698.680000 -2339.820000 109.538000 1 0.754665

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7228
