### ISSUE TITLE
QUEST -  Lost! in Un'goro Crater.  Ringo is passed out in the ca...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4104]
> QUEST -  Lost! in Un'goro Crater.  Ringo is passed out in the cave and cannot start the quest.

.go xyz -7196.130000 -1389.270000 -231.674000 1 1.578350

**Comment by Shadownflame** [comment]
Probably same issue https://github.com/Project-Epoch/bugtracker/issues/7733
