### ISSUE TITLE
Rank 1 Power Fortitude buff tooltip says "Increases 
Stamina by ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4122]
> Rank 1 Power Fortitude buff tooltip says "Increases 
Stamina by $w1" on gnome priest

.go xyz -6148.070000 383.507000 395.542000 0 2.955470

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5506
