### ISSUE TITLE
The Paladin Spell 'Avenger's Shield' is supposed to have a dazed...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4129]
> The Paladin Spell 'Avenger's Shield' is supposed to have a dazed component added to the spell. Dazes are the only slow in game that cant be removed by players. 

The daze should hold as long as the debuff lasts on the Target, dispellable by spells like 'Cleanse' and 'Dispell Magic' only. spells like 'improved sprint' and 'Hand of Freedom' should not remove the Dazed effect.

.go xyz -7251.370000 -4655.410000 12.493300 1 1.160780

**Comment by zana244** [comment]
I heavily doubt that. NPC Daze =/= Player "Daze". It's no different to frostbolt slow.

Funnily enough it seems there was a bug on SoD where AS behaved like that. Unfortunate. (https://www.reddit.com/r/classicwow/comments/18aurbp/is_it_intended_that_avengers_shield_slow_is_not/)
