### ISSUE TITLE
Inside stratholme rogue poisons, when applied to a wepon, only l...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4147]
> Inside stratholme rogue poisons, when applied to a wepon, only lasted 12 minutes instead of 1 hour. I applied Crippling Poisona and Instant Poison to Laexxarn's Fang dagger in off hand

.go xyz 3607.230000 -3648.360000 138.512000 329 0.419396

**Comment by zana244** [comment]
Could not replicate. Someone else also mentioned this

**Comment by zana244** [comment]
#2584

**Comment by Shadownflame** [comment]
> Could not replicate. Someone else also mentioned this

This was an issue caused by Improved Poisons on the beta. Seems resolved.

**Comment by zana244** [comment]
Yeap, looking at other issues I found it out haha! Closing.
