### ISSUE TITLE
I sapped Blackbreath Crony as he came out of non-targeable anima...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4154]
> I sapped Blackbreath Crony as he came out of non-targeable animation when Hurley spawned and he became non-atatckable, and kept following me and keeping group in combat.

.go xyz 894.462000 -147.145000 -49.758600 736 5.731640

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/839
