### ISSUE TITLE
Deviate Creeper - (3632)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#416]
> wierd path / evasion
`.go xyz -705.076000 -2057.010000 65.471900 1 5.704710`

> Drops Crisp Spider Meat which shouldn't be in its loot table
`.go xyz -786.412000 -2032.950000 78.881700 1 2.935780`

> bugged, resetting
`.go xyz -703.123000 -2055.880000 65.520400 1 5.522900`

> this mob is perma evade
`.go xyz -706.632000 -2058.670000 65.736700 1 5.792320`

> bugging in the water, keeps evading even if we are in water too
`.go xyz -704.219000 -2050.730000 65.477100 1 6.152030`

> bugged mob, it takes about 10% damage then resets and never attacks me
`.go xyz -704.780000 -2062.030000 66.106800 1 2.261210`

**Comment by zana244** [comment]
#8302

**Comment by Shadownflame** [comment]
Loot issue resolved. Pathing linked to other report.
