### ISSUE TITLE
Don't know if its intended, but things like basilisks still stun...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4162]
> Don't know if its intended, but things like basilisks still stun even if you are facing away

.go xyz -7311.890000 -3125.700000 9.316650 1 2.516850

**Comment by zana244** [comment]
In all my playing time I never thought that turning around would counter it... probably not a mechanic in vanilla (first one that comes to ming is in wotlk 5man toc?)
if someone knows differently they can reopen.

**Comment by Shadownflame** [comment]
Mythical basilisks are like the one in Harry Potter... you have to look into its eyes to petrify you. 
However, back in vanilla wow, Blizzard didn't have this level of scripting. I also recall "Face away" type of mechanic was added in wotlk, and perhaps someday they added basilisks that behave properly, but alas, on the vanilla version of the world Epoch uses, that wasn't the case. You can outrange their stuns by stepping 5-10 yards back instead.
