### ISSUE TITLE
in the "Silithid Scramble" quest the Centipaar Tunnelers don't h...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4171]
> in the "Silithid Scramble" quest the Centipaar Tunnelers don't have enough spawns and randomly despawn.

.go xyz -8060.800000 -2523.080000 -39.117200 1 5.710490

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
