### ISSUE TITLE
Quest: The Legend of Aru-Talis. The Second and Fourth tables are...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4188]
> Quest: The Legend of Aru-Talis. The Second and Fourth tables are not to be found. They seems to not be there.

.go xyz -8025.620000 -1253.930000 -271.404000 1 5.910500

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
