### ISSUE TITLE
Quest Venomhide Eggs, you can see a lot of eggs on the ground ar...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4189]
> Quest Venomhide Eggs, you can see a lot of eggs on the ground around the area, but you cannot interact with them.

.go xyz -7209.720000 -2023.620000 -271.930000 1 4.989030

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
