### ISSUE TITLE
Quest: "Do Slavers Keep Records", the Slave's Record item wont d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4191]
> Quest: "Do Slavers Keep Records", the Slave's Record item wont drop. Killed 30+ Dark Iron Slaves and no drop.

.go xyz -7006.130000 -1222.730000 204.757000 0 1.934160

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
