### ISSUE TITLE
Tharnariun Treetender - (3701)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#420]
> able to turn-in the rabid bear quest after dying and losing the bear
`.go xyz 6439.370000 399.581000 11.635600 1 3.711440`

**Comment by zana244** [comment]
I really think it's blizzlike like that, on all servers I played you get the credit as soon as you capture the bear, and there is no failed state.
https://www.youtube.com/watch?v=8K8o_qWWNzU -- you can complete before you reach the quest giver with the bear.
