### ISSUE TITLE
There is a bug on chicken esqort quests. When u do it in party o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4207]
> There is a bug on chicken esqort quests. When u do it in party only person who started the quest gets it completed after  its done. We are sure that when we started everyone was on the same stage and rest of people in party clicked accept when one person stared for whole pt

.go xyz -14406.000000 420.194000 22.392900 0 1.426490

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2032
