### ISSUE TITLE
Quest Reclaming the Eggs - doesnt work. Eggs are not able to pic...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4208]
> Quest Reclaming the Eggs - doesnt work. Eggs are not able to pick up, even dont spirnke and no light up under the mouse cursor

.go xyz -416.301000 -2968.780000 96.185100 0 2.299240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
