### ISSUE TITLE
Despite not being in the game the town of Mudsprocket in Dustwal...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4209]
> Despite not being in the game the town of Mudsprocket in Dustwallow Marsh does still show up on your minimap (both the arrow pointing to it as well as the building once you're actually in the area - they're on the minimap though the assets themselves aren't actually in the world itself).

.go xyz -4717.820000 -3156.200000 36.641500 1 3.015890

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7623
