### ISSUE TITLE
Hunter pet portrait in the UI gets corrupted sometimes randomly....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4210]
> Hunter pet portrait in the UI gets corrupted sometimes randomly. I have no idea what causes it and frankly I can hardly even explain what it looks like. But it's as if the polygons of the pet start to go wildly out of control and my grey boar looks like it's been punctured by various steel spikes.

.go xyz -4125.210000 -3190.280000 35.483200 1 1.622870

**Comment by Shadownflame** [comment]
I cannot reproduce this issue. @zana244 ever happened to you?

**Comment by Shadownflame** [comment]
Probably something with corrupted client. Please reopen if someone manages to reproduce.
