### ISSUE TITLE
Several of the mobs on the eastern shore of Swamp of Sorrows can...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4212]
> Several of the mobs on the eastern shore of Swamp of Sorrows can only be aggro'd in melee range (they will evade ranged attacks) yet if you enter melee range, most of the time you will not be able to hit them in melee yourself.

.go xyz -9897.490000 -4212.880000 2.606810 0 4.035880

**Comment by zana244** [comment]
Think this was solved by fatigue lines, can't reproduce on internal.
