### ISSUE TITLE
There's at least one floating Iron Deposit node at the entrance ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4215]
> There's at least one floating Iron Deposit node at the entrance to the Blazing Hills of Arathi Highlands. Seems like some of the nodes may have been left unaccounted for when performing the terraforming necessary to create this custom area.

.go xyz -1402.170000 -3464.520000 58.570200 0 3.502670

**Comment by Bennylavaa** [comment]
moved to the node tracker
