### ISSUE TITLE
When you're located in Burndural (Wetlands) opening the world ma...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4220]
> When you're located in Burndural (Wetlands) opening the world map shows you the actual world map instead of just the map of Wetlands (similarly to when you're in the Deeprun Tram or in an instance, for example).

.go xyz -3863.270000 -1791.620000 137.832000 0 1.442330

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8298
