### ISSUE TITLE
Watertight Trunk" item received from fishing sometimes does not ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4222]
> Watertight Trunk" item received from fishing sometimes does not contain anything at all.

.go xyz -3340.940000 -967.074000 1.205680 0 3.761680

**Comment by Bennylavaa** [comment]
Opened 50 of them and they all had stuff in them. Maybe already fixed since beta?

**Comment by Shadownflame** [comment]
> Opened 50 of them and they all had stuff in them. Maybe already fixed since beta?

I think it might have been affected by the vmangos loot table port kaytotes made, although i'm not 100% sure if that was applied yet.
UPDATE: the chests still don't drop loot so I think it's not applied yet. Disregard.
