### ISSUE TITLE
LW bracer enchant kits seem to make an item soulbound only for t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4223]
> LW bracer enchant kits seem to make an item soulbound only for the duration of the buff. Once it expires, it is tradeable again. Frankly it kind of makes sense to work like this but I'll let you figure out whether that's intentional or not.

.go xyz -2848.440000 -1776.810000 6.424860 0 4.204610

**Comment by Shadownflame** [comment]
Most temporary enhancements work this way.
