### ISSUE TITLE
Caster mobs (possibly just general ranged as well) believe they ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4225]
> Caster mobs (possibly just general ranged as well) believe they have run away in fear successfully too early. Caster mobs will run away at low health relatively close to an ally and then start casting again as if they had gotten help successfully, however, they aren't close enough to the other NPC to actually get their ally to join the fight.

.go xyz -908.218000 -912.364000 32.214500 0 1.316130

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6624
