### ISSUE TITLE
Typos in "Just Desserts" quest description.

"the meal would dan...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4234]
> Typos in "Just Desserts" quest description.

"the meal would dance on their palettes" -> palates (the part of the mouth), not palettes (what painters use)

"aromas which I had createrd" -> created*

"Ginger tends too" -> to*, not too

.go xyz -9525.340000 -698.638000 61.674700 0 3.213290

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
