### ISSUE TITLE
The "Wanted: Big Blue" quest description has typos.

"one of the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4235]
> The "Wanted: Big Blue" quest description has typos.

"one of the master' experiments" -> missing s at the end of "master's"

"Deal with it and bring it's wing" -> its (possessive), not it's (contraction of it is)

"It's last known location" -> its, not it's

.go xyz -9525.340000 -698.638000 61.674700 0 3.213290

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6642
