### ISSUE TITLE
The "Spider Elixir" quest from Matron Darcy in Elwynn Forest has...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4237]
> The "Spider Elixir" quest from Matron Darcy in Elwynn Forest has typos in the quest description.

There is a missing space before the sentence "I've heard rumors that spiders have made a web deep in the mine."

In the same description also - "if you see any miners will you release them so they can get to me." should have a comma before "will", and the sentence should end with a question mark, not a period.

.go xyz -9488.270000 80.886200 57.003600 0 3.932420

**Comment by zana244** [comment]
#2171
