### ISSUE TITLE
The quest "Advanced Alchemy" is categorized under "Elwynn Forest...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4238]
> The quest "Advanced Alchemy" is categorized under "Elwynn Forest" in the quest log. This is a WPL quest.

.go xyz 2330.060000 -2420.240000 62.887500 0 3.182010

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2305
