### ISSUE TITLE
The quest Sunken Treasure seems to be bugged, or we are just bli...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4240]
> The quest Sunken Treasure seems to be bugged, or we are just blind. we've been swimming around for 20 minutes looking all around the ships, and found nothing.

.go xyz -11710.800000 -3762.510000 1.345710 0 2.238150

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8171
