### ISSUE TITLE
The quest "Reclaiming the Eggs" in hinterlands seem to be bugged...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4241]
> The quest "Reclaiming the Eggs" in hinterlands seem to be bugged, I cannot pick up any of the gryphon eggs here, they seem to be non-interactable

.go xyz -404.186000 -2891.490000 84.942700 0 0.654410

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
