### ISSUE TITLE
Elder Shadowhorn Stag - (3818)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#425]
> Level visable even though I'm level 10.  Tauren.
`.go xyz 2656.820000 -1984.890000 167.628000 1 3.234930`

**Comment by zana244** [comment]
Confirmed on internal... wonder why?

**Comment by ghost** [comment]
Yellow named mobs display their level, they do not ever become a skull. It's just that most mobs in the game are red named so this feature is not common knowledge.
