### ISSUE TITLE
Quest: Boom! Boom! Boom! in Tanaris
Droprate needs to be adjuste...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4264]
> Quest: Boom! Boom! Boom! in Tanaris
Droprate needs to be adjusted and slighty higher.

.go xyz 1660.080000 -5034.910000 115.431000 1 0.608646

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2237
