### ISSUE TITLE
Not a Bug, but a suggestion for the quest Water Co. Saviour in T...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4265]
> Not a Bug, but a suggestion for the quest Water Co. Saviour in Tanaris:
to few Filter Parts and too far apart and in deep water, maybe give the player atleast a goblin designed gadget to overcome this. ;)

.go xyz -6760.220000 -4834.430000 0.667022 1 2.622780

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
