### ISSUE TITLE
Deathstalker Adamant - (3849)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#428]
> Got into a deathmatch with Sorcerer Ashcrombe on being released.
`.go xyz -250.685000 2130.210000 81.180100 33 4.912250`

> these two are fignting each other
mixed faction dungeon group
`.go xyz -252.161000 2128.420000 81.179600 33 4.905670`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7699
