### ISSUE TITLE
Rot Hide Origins Lvl (18) quest only gives about 320 XP for the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4282]
> Rot Hide Origins Lvl (18) quest only gives about 320 XP for the collection quest. All other gather and kill quests give ~ 1000xp at this point

.go xyz 1764.890000 64.427100 -46.320300 0 1.222500

**Comment by zana244** [comment]
https://www.wowhead.com/classic/quest=444/rot-hide-origins
intended.
