### ISSUE TITLE
Sorcerer Ashcrombe - (3850)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#429]
> Got into a deathmatch with Deathstalker Adamant on being released.
`.go xyz -250.685000 2130.210000 81.180100 33 4.912250`

> This guy started hitting our deathstalker and we couldn't stop him.
`.go xyz -234.858000 2166.080000 88.947600 33 6.193320`

> these two are fignting each other
`.go xyz -252.161000 2128.420000 81.179600 33 4.905670`

> cant damage mob. seems passive.
`.go xyz -244.476000 2125.670000 81.179600 33 3.753060`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7699
