### ISSUE TITLE
Sunken Treasure" custom quest in the Blasted Lands is not functi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4292]
> Sunken Treasure" custom quest in the Blasted Lands is not functioning properly. Was doing it with a group and we were able to locate it the first time just fine. We've spent upwards of 1 hour looking for it/waiting for it to respawn again. Please consider looking into its respawn timer.

.go xyz -11591.500000 -3775.230000 1.899010 0 1.363880

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8171
