### ISSUE TITLE
quest "Turtle Power" asks for "Lean Turtle Flank" items but I'm ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4296]
> quest "Turtle Power" asks for "Lean Turtle Flank" items but I'm pretty sure what it is supposed to ask for is "Turtle Meat". Turtle meat drops from the turtles, not Lean Turtle Flanks.

.go xyz -139.416000 -4575.410000 12.827000 0 0.235167

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2222
