### ISSUE TITLE
Reclaiming the Eggs" quest items (the eggs) are non-interactable...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4297]
> Reclaiming the Eggs" quest items (the eggs) are non-interactable and unable to be picked up. The in-game model is present.

.go xyz 450.094000 -3692.340000 121.822000 0 2.151550

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
