### ISSUE TITLE
the quest "Do Slavers Keep Records?" does not seem to be droppin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4298]
> the quest "Do Slavers Keep Records?" does not seem to be dropping its quest item from the Dark Iron Slavers. I've been killing them for 30+ minutes

.go xyz -6720.310000 -1375.530000 210.228000 0 0.840499

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
