### ISSUE TITLE
Rich Thorium Vein @ 69.43, 38.45 inbetween two rocks says "This ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4305]
> Rich Thorium Vein @ 69.43, 38.45 inbetween two rocks says "This is already being used". It is only me here.

.go xyz 6713.300000 -5246.030000 779.910000 1 3.312370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6437
