### ISSUE TITLE
Seal of the Dawn not awarding Scourgestones and does not give it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4307]
> Seal of the Dawn not awarding Scourgestones and does not give it's +81 attack power to undead when I did testing on mobs. Verified through using several skills scaled off AP and tested it with my auto attack damage.

.go xyz 1851.280000 -1607.440000 59.321800 0 5.329270

**Comment by zana244** [comment]
Seems to work now on internal? damage seems increased, and auto attack increase seems to correspond to ~81 AP.
