### ISSUE TITLE
Searing Totem II - (3902)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#431]
> Searing totem has stopeed working. No longer attacks mobs. Im a lvl 21 enhance in barrens.
`.go xyz -2160.930000 -1987.170000 93.012900 1 5.724640`

> Rank II isn't firing.
`.go xyz -4031.880000 -2975.190000 11.552800 0 3.602530`

> Searing totem stopped shooting.  It's been few in a row now, that did not fire
`.go xyz -3345.740000 -1177.940000 9.132120 0 0.204162`

> Doesn't do anything
`.go xyz -3940.140000 -1641.510000 91.676800 1 1.721400`

**Comment by zana244** [comment]
#2591
