### ISSUE TITLE
Storm, Earth, Wind, and Fire" Weakened elementals stay level 61+...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4314]
> Storm, Earth, Wind, and Fire" Weakened elementals stay level 61+ elite when totem is used on them and cannot be killed at this level bracket.

.go xyz -7329.810000 -2242.640000 -272.584000 1 3.027830

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2322
