### ISSUE TITLE
The Un'Goro Hunt" part 3 where you kill Stegodon, it shows it as...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4315]
> The Un'Goro Hunt" part 3 where you kill Stegodon, it shows it as an Elwynn Forest quest

.go xyz -6170.290000 -1135.590000 -217.934000 1 1.815940

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
