### ISSUE TITLE
Healing Stream Totem III - (3907)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#432]
> This totem is not appearing on buff list.
`.go xyz 4.000800 -12.627900 -17.162200 389 3.429460`

> heal even with no group/raid
`.go xyz -8967.230000 818.361000 109.447000 0 3.879090`

> Healing totem heals not in group, just everyone neerby
`.go xyz -586.333000 -4249.460000 38.638300 1 3.219350`

> Totem is healing when I'm not in the party with shaman.
`.go xyz -581.652000 -4246.310000 37.892500 1 5.279440`

**Comment by Hatson22** [comment]
Confirmed that there is no visible buff on characters affecting by Healing Stream Totem (any rank).
Need others to test the rest of the report.

**Comment by Shadownflame** [comment]
Visible buff removed on purpose as spell was redesigned. Totem no longer heals ungrouped targets.
