### ISSUE TITLE
Right now a player can not use more than one Battle Elixir and G...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4337]
> Right now a player can not use more than one Battle Elixir and Guardian Elixir. A Flask even counts as both. This is of course a TBC chance, which does ruin the classic WoW Experience.
Classic WoW is known as a consumable-friendly game, with lots of options to combine Elixirs and Flasks.

.go xyz -7213.540000 -4259.230000 8.720800 1 2.648300

**Comment by zana244** [comment]
Intended
