### ISSUE TITLE
When Seal of Light and/or Seal of Wisdom is judged on a target, ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4338]
> When Seal of Light and/or Seal of Wisdom is judged on a target, all melee hits (for seal of Light) and all melee hits and spells (for seal of Wisdom) used on the effected target should have a chance to trigger the effect of seal of Light/Wisdom.
Seal of Righteousness and Seal of Command procs and their Judgements should count either as melee hits or spells, and therefore are supposed to trigger the Light/Wisdom effect on the Target.
Right now these Seals do not trigger the Light/Wisdom effect.

.go xyz -7258.040000 -4660.790000 12.796200 1 1.101070

**Comment by zana244** [comment]
Seal of righteousness/Command proc Judgement of Light/Wisdom, and their judgements do too. However, it seems like in TBC SoR should not proc anything... unsure about the judgements.

![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/6668fbab-d703-4736-8b78-32a49963634d)
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/c850de56-722c-4868-91b6-50446a3d3974)
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/b202edd8-f6e1-4407-8edd-aff70078fe25)

**Comment by zana244** [comment]
#2936
