### ISSUE TITLE
The eggs in the Hinterlands Quest "Reclaiming the Eggs" can stil...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4349]
> The eggs in the Hinterlands Quest "Reclaiming the Eggs" can still not be interacted with after the update.

.go xyz -400.613000 -2887.050000 84.496500 0 4.085810

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
