### ISSUE TITLE
The quest "Reclaiming the Eggs" in Hinterlands is bugged. The eg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4350]
> The quest "Reclaiming the Eggs" in Hinterlands is bugged. The eggs cannot be interacted with

.go xyz -396.892000 -2862.620000 71.994100 0 4.417240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
