### ISSUE TITLE
When using Judgement with Seal of Justice, I only take 1 mana ba...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4353]
> When using Judgement with Seal of Justice, I only take 1 mana back while haveing Sanctified Judgement talent 3/3.

.go xyz -224.065000 -3434.770000 152.704000 0 2.269850

**Comment by zana244** [comment]
Confirmed on internal. Both ranks are affected, other seals seem to work fine?
#2805

**Comment by kaytotes** [comment]
Next deploy.
