### ISSUE TITLE
Zone: The Hinterlands
Quest: Reclaiming the Eggs

There are no s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4354]
> Zone: The Hinterlands
Quest: Reclaiming the Eggs

There are no sparkls on the eggs and they cannot be clicked to pick up.

.go xyz -459.901000 -2871.390000 96.789500 0 5.376110

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
