### ISSUE TITLE
Quest: Learn to Ride in Elwynn Forest

Bugged, there is no quest...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4357]
> Quest: Learn to Ride in Elwynn Forest

Bugged, there is no question mark above the NPC and no completion at all if you speak to him.

.go xyz -9442.580000 -1389.410000 46.908300 0 5.076360

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3196
