### ISSUE TITLE
Area: Tanaris
Quest: The Perfect Fuel

While the scorpions drop ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4358]
> Area: Tanaris
Quest: The Perfect Fuel

While the scorpions drop the quest item, there are no batteries at the Noonshade Ruins.

.go xyz -4928.730000 -5051.740000 33.574600 1 0.173172

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
