### ISSUE TITLE
quest bugged :tanaris field sampling.  i get the water to get a ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4366]
> quest bugged :tanaris field sampling.  i get the water to get a power source, i get the quest to gather samples, but it wont let me do anything with the samples and i cannot complete the quest.

.go xyz -7158.650000 -3824.850000 8.611570 1 2.585670

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5665
