### ISSUE TITLE
flying to dustmallowmarch and since there are new buildings sout...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4369]
> flying to dustmallowmarch and since there are new buildings south east of camp taurojo on the mountains, i fly right through the buildings and mobs, dunno if it can be rerouted or not

.go xyz -3147.390000 -2842.180000 34.610000 1 6.114960

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
