### ISSUE TITLE
whenever i go to the flight master in org, from the bottom of th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4371]
> whenever i go to the flight master in org, from the bottom of the building, so going up the spiral, the visuals massively glitch n everything vanishes, i tried different camera angles n such but it just always happens there

.go xyz 1103.610000 -3745.270000 77.168900 1 2.833910

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7351
