### ISSUE TITLE
a lot of the new quests use apostrophes when making a quest item...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4374]
> a lot of the new quests use apostrophes when making a quest item plural, eg "a chilly stranger" - "...as well as 8 Study Root's from Thistleshrub Thornseekers

.go xyz -9689.300000 -4137.410000 128.462000 1 4.490420

**Comment by zana244** [comment]
needs reporting for every quest. this one seems solved.
