### ISSUE TITLE
Expected : Rogue Assassination talent "Remorseless Attacks" to d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4408]
> Expected : Rogue Assassination talent "Remorseless Attacks" to dissapear after using mutilate.

Observation; Buff remains after using mutilate until the timer finish, resulting in many sweet mutilate crits.

.go xyz -4648.480000 -1127.730000 508.550000 0 4.369900

**Comment by zana244** [comment]
#2728
