### ISSUE TITLE
Quest giver "Eridan Bluewind" does not show a "yellow questionma...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4414]
> Quest giver "Eridan Bluewind" does not show a "yellow questionmark" when I completed the quest "The Corruption of the Jadefire".

So I can't complete it even though I killed all the requiered enemies.

.go xyz 3994.980000 -1302.570000 253.701000 1 5.696190

**Comment by zana244** [comment]
#7895
