### ISSUE TITLE
Zone should be called "Aru-Talis Fourth Base" or smth along the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4415]
> Zone should be called "Aru-Talis Fourth Base" or smth along the lines with the 3 other bases in order to know you're at the right place for the "Legend of Aru-Talis" quest.

.go xyz -8288.580000 -1164.080000 -179.645000 1 2.219080

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
