### ISSUE TITLE
Quest : Storm, Earth, Wind and Fire


Bug where you can use the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4416]
> Quest : Storm, Earth, Wind and Fire

Bug where you can use the item to drain the power multiple times on the same cadaver.

.go xyz -7210.960000 -572.894000 -271.631000 1 3.453990

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2321
