### ISSUE TITLE
Quest: The Legend of Aru-Talis.

I used the quest item in the fo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4417]
> Quest: The Legend of Aru-Talis.

I used the quest item in the following order per location::
Golakka Hot Springs -> Fire Plume Ridge -> ...
At this point I had two areas left to use the item to finish the quest. 
Ironstone Plateau and Crystal Cave.

The item could be used in Ironstone Plateau but did not count for the quest. For a weird reason I had to first go to Crystal Cave and then back to the Plateau for it to work as expected.

.go xyz -7011.280000 -2363.150000 -219.279000 1 2.089200

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/2317

**Comment by Bennylavaa** [comment]
cannot reproduce this.
