### ISSUE TITLE
Quest "Reclaiming the Eggs"

Can't seem to be able to pick any o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4418]
> Quest "Reclaiming the Eggs"

Can't seem to be able to pick any of the eggs necessary to complete quest.

.go xyz -227.074000 -2921.400000 99.380900 0 5.555410

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
