### ISSUE TITLE
feralas escort oox-22 to safety,  i clicked the ? on the escort ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4424]
> feralas escort oox-22 to safety,  i clicked the ? on the escort started for me not for my teammate who also has the quest find 00x-22

.go xyz -4744.800000 1572.360000 84.915700 1 0.499907

**Comment by Shadownflame** [comment]
Report suggests teammate hasn't handed in their quest to find the chicken before escort quest was picked up. All party members need to be on the same stage of the quest chain (i.e. previous quest handed in) in order to start the escort.
