### ISSUE TITLE
the perfect fuel, tanaris, didn't find where to fill the oil can...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4427]
> the perfect fuel, tanaris, didn't find where to fill the oil cannister.  no indication on screen (like the valves for samophlange in the barrens)  on quest just states under water but i checked , can't find it

.go xyz -6490.530000 -4917.530000 -0.048713 1 5.244300

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
