### ISSUE TITLE
i am in thousand needles next to one of the egg locatins, just b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4432]
> i am in thousand needles next to one of the egg locatins, just before attacking a cloud serpent my pet despawned, when i called him he had lost his druid buffs that he got not 10 minutes ago in freewind post.

.go xyz -5568.500000 -2753.360000 -49.824700 1 2.217440

**Comment by Bennylavaa** [comment]
I cannot reproduce this.
