### ISSUE TITLE
Quest name: A Strange Historian
Minor bug.
Wording can be change...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4441]
> Quest name: A Strange Historian
Minor bug.
Wording can be changed to correctly point to the updated positioning of Chromie in the epoch version of Andorhal (old version.)

.go xyz 1162.840000 -1749.680000 61.349000 0 1.555550

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2107
