### ISSUE TITLE
Quest name: Arms of the Grimtotems
Armaments missing - no object...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4442]
> Quest name: Arms of the Grimtotems
Armaments missing - no objects are found in either of the two grimtotem settlements.

.go xyz -3342.940000 -2160.410000 91.667400 1 0.872499

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3195
