### ISSUE TITLE
Taking a flight from The harborage in Swamp of Sorrows to Rebel ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4443]
> Taking a flight from The harborage in Swamp of Sorrows to Rebel Camp in STV took me flying through textures up to the Redridge FP after which I resumed flight as intended.

.go xyz -11359.200000 -245.078000 94.624800 0 1.440390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
