### ISSUE TITLE
Quest name: Fiora Longears
NPC was moved in TBC from Theramore t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4444]
> Quest name: Fiora Longears
NPC was moved in TBC from Theramore to Auberdine (which makes more sense given the level and followups). On Epoch the quest text is the TBC one, stating she's in Auberdine, but she's nowhere to be found there. Haven't checked but she is most likely in Theramore.

.go xyz 8683.260000 892.945000 22.191300 1 4.513160

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2384
