### ISSUE TITLE
During quest Water Co. Survivor i noticed i'm getting kicked out...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4447]
> During quest Water Co. Survivor i noticed i'm getting kicked out of aquatic form. I think it happens if i move along the sea bottom so that it thinks i'm walking

.go xyz -6994.760000 -4966.140000 -13.586800 1 0.746660

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
