### ISSUE TITLE
Quest "The Southern Pylon" in Un'Goro got auto completed when I ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4449]
> Quest "The Southern Pylon" in Un'Goro got auto completed when I was walking on Aru-Talis Site One. Didn't have the pylone in sight and obviously didn't interact with it.

.go xyz -6361.690000 -1605.260000 -272.214000 1 4.352370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2511
