### ISSUE TITLE
Quest "Fiora Longears" offered in Wetlands - Menethil Harbor ask...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4450]
> Quest "Fiora Longears" offered in Wetlands - Menethil Harbor asked to talk to Fiora in Auberdine. Fiora is not in Auberdine as advertised in the quest. She may be in Theramore.

.go xyz 6394.690000 525.012000 8.661160 1 2.919050

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2384
