### ISSUE TITLE
ZF Boss Antu'sul's adds don't despawn after wiping, and keep sta...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4453]
> ZF Boss Antu'sul's adds don't despawn after wiping, and keep stacking. 3 spawn per attempt and then he has 3 more each try

.go xyz -7005.060000 -3417.690000 10.962200 1 1.441690

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7671
