### ISSUE TITLE
Stealth detection will put you into combat sometimes if you're c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4457]
> Stealth detection will put you into combat sometimes if you're close enough to a creature to "alert" them but if you move out of range of their detection they will then reset and not atack you and combat will drop. This could be linked to the evade bug encountered with pickpocketing

.go xyz -147.293000 -2988.730000 91.681800 1 5.637810

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7344
