### ISSUE TITLE
Pickpocket showing up as miss not resist

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4458]
> Pickpocket showing up as miss not resist

.go xyz 1103.480000 -4695.910000 17.213700 1 4.828640

**Comment by Shadownflame** [comment]
Not an issue unique to pickpocket, all spell misses currently show up as miss, not resist like they used to on vanilla. Pickpocket itself is a physical spell which is unaffected by school resistance mechanics, so whenever it fails it is a miss.
It is up to devs if they want to revert to the vanilla implementation where everything shows up as resist even if it's a miss, although it can get needlessly confusing for magical spells that can do both.

**Comment by Shadownflame** [comment]
Dev choice is to keep misses displaying separately.
