### ISSUE TITLE
Dustwind Storm Witch lightning bolt damage, Cant check this from...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4459]
> Dustwind Storm Witch lightning bolt damage, Cant check this from past experiences but it is back-back casting at 50 damage/cast while also doing melee damage

.go xyz 829.701000 -4791.670000 10.815600 1 5.021070

**Comment by zana244** [comment]
Seems fine to me, the bolt hits for around 38-45, and it has mana for around 4 casts...melee for 15-20... Nothing out of the ordinary, caster mobs are killer at low levels
