### ISSUE TITLE
Mobs will evade after they aggro onto you in stealth and you use...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4461]
> Mobs will evade after they aggro onto you in stealth and you use pickpocket. pickpocket will still go off succesfully but the mob will reset and then initiate combat again,

slightly tricky to reproduce exactly but very annoying as it means pickpocketing and then using an ability to attack/start combat that attack evades.

.go xyz 16.988800 -4615.130000 44.908000 1 5.566910

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7344
