### ISSUE TITLE
Caught! objective quest says "Return to the wooden outhouse in b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4483]
> Caught! objective quest says "Return to the wooden outhouse in badlands while its in searing gorge.

.go xyz -7009.950000 -1739.630000 234.098000 0 1.132830

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/0ea309ac-dc5e-4e6e-aada-53e32b3d62c8)
Can't reproduce
