### ISSUE TITLE
Tips of fire chain seems bugged. They seem to only give around 5...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4490]
> Tips of fire chain seems bugged. They seem to only give around 500 exp. One chain is also not described correctly. "Collect tar from tar beasts in Tanaris." Those mobs are in Un'goro.

.go xyz -9778.020000 -3960.040000 131.316000 1 5.539530

**Comment by Kestrana** [comment]
The XP is a duplicate of https://github.com/Project-Epoch/bugtracker/issues/2253 but the quest text does need to be revised so marking this as a quest issue for resolution.

**Comment by Kestrana** [comment]
Closed by https://github.com/Project-Epoch/epoch-core/pull/1597
