### ISSUE TITLE
Antu'sul adds should despawn after a wipe,
Current behaviou:r ad...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4492]
> Antu'sul adds should despawn after a wipe,
Current behaviou:r adds stay and dont despawn
Expected behaviour: Despawn adds after a party wipes

.go xyz -6927.160000 -3172.250000 9.077250 1 0.973920

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7671
