### ISSUE TITLE
The Quest "Poisoned Water" from Duke Hydraxis drop rates of the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4495]
> The Quest "Poisoned Water" from Duke Hydraxis drop rates of the elementals is not good. And the Item has to much of a CD you have to wait to long.

.go xyz 2480.780000 -4210.360000 72.400600 0 0.935569

**Comment by zana244** [comment]
solved with vmangos loot, close to 100% drop rate I think (unless I got mega lucky)
