### ISSUE TITLE
The Un'Goro Hunt Quest in Un'goro Part 3 with Stegodon Head is u...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4498]
> The Un'Goro Hunt Quest in Un'goro Part 3 with Stegodon Head is under the category Elwynn Forest

.go xyz -7542.510000 -764.312000 -261.553000 1 3.692620

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
