### ISSUE TITLE
The Queststep at the Quest "Fit For A King" with the Wetland Hem...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4500]
> The Queststep at the Quest "Fit For A King" with the Wetland Hemp, has way too low spawn chance. Its horrible

.go xyz -3337.620000 1916.330000 50.530200 1 0.432822

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7967
