### ISSUE TITLE
New Caer Darrow/Scholomance Quests "Advanced Alchemy" and "Scour...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4503]
> New Caer Darrow/Scholomance Quests "Advanced Alchemy" and "Scourage Botany" are listed in the quest log as quests in Elwynn Forest. Should say Western Plaguelands.

.go xyz 1083.710000 -2537.210000 59.199900 0 2.830410

**Comment by Bennylavaa** [comment]
duplicate of https://github.com/Project-Epoch/bugtracker/issues/8300 and https://github.com/Project-Epoch/bugtracker/issues/2302
