### ISSUE TITLE
Devouring Ooze Spans at The Weeping Cave in WPL hit like a truck...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4504]
> Devouring Ooze Spans at The Weeping Cave in WPL hit like a truck. They have quite high health too. 4-5 spawn as you kill the original ooze. Is this intended?

.go xyz 2262.770000 -2360.550000 60.284400 0 1.191250

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/215
