### ISSUE TITLE
Mind Control does not aggro adds on Mercutio Filthgorger in EPL ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4505]
> Mind Control does not aggro adds on Mercutio Filthgorger in EPL - the Only in Dreams quest. Tried and failed to kill him in and his buddies in fair fight. MCed and they ignored him. Ran him to me and then only had to fight him alone. Normally MC makes adds turn hostile and attack MCed target.

.go xyz 1587.730000 -3334.700000 108.292000 0 2.416540

**Comment by zana244** [comment]
The mobs do not ignore him while he is MC'd, however they do reset once the MC breaks, letting you fight Mercutio alone. Linking to Mind Control issue as it's a general MC spell issue.
#2538
