### ISSUE TITLE
looting doll parts for pamela's quest in EPL spawns hostile ghos...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4506]
> looting doll parts for pamela's quest in EPL spawns hostile ghost but they don't attack you until they see you try to loot another part near them. Should attack as you loot.

.go xyz 1474.410000 -3718.040000 80.514900 0 0.970789

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2106
