### ISSUE TITLE
All the Arthas Tears are spawned here. I that tradeskill nodes a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4507]
> All the Arthas Tears are spawned here. I that tradeskill nodes aren't supposed to spawn at the same time. They are anti-botting mechanics. Where you have 5 nodes for 1 herb and every 15-60 minutes it picks a place at random and spawns it. That way you can't sit in the same place and pick it at random. In the case of mineral veins this was usually 1 rich thorium for every named subzone. Having every location spawn individually will just oversaturate the auction house. Better to have too little.

.go xyz 1748.380000 -3345.140000 113.281000 0 0.396781

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8301
