### ISSUE TITLE
Fetid Zombies interupt faster than I can cast as a shadow priest...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4509]
> Fetid Zombies interupt faster than I can cast as a shadow priest. I get to penance and then constantly spell locked out of shadow. Is this intentional?

.go xyz 1486.480000 -1840.230000 58.630200 0 5.374130

**Comment by Shadownflame** [comment]
Blizzlike. It's their aura which does this periodically.
