### ISSUE TITLE
Corrupted Soul Shard just dropped from Water elemental in Ungoro...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4511]
> Corrupted Soul Shard just dropped from Water elemental in Ungoro. I haven't been to felwood yet to start the cleansing questline.

.go xyz -7364.760000 -844.625000 -272.498000 1 0.520876

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1582
