### ISSUE TITLE
The Un'Goro Hunt (Elite) Stegodon Head step shows up in Quest Lo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4513]
> The Un'Goro Hunt (Elite) Stegodon Head step shows up in Quest Log as an Elwynn Forest quest

.go xyz -6317.050000 -1182.370000 -269.989000 1 3.849740

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
