### ISSUE TITLE
Taking Gammeritas picture on Hinterlands Beach does not aggro him.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4516]
> Taking Gammeritas picture on Hinterlands Beach does not aggro him.

.go xyz -104.875000 -4605.820000 11.045100 0 1.008580

**Comment by zana244** [comment]
Confirmed on internal, should aggro
https://www.youtube.com/watch?v=BT88ZElemCM 1:30

**Comment by T1ti** [comment]
Your video is from a private server so not a reliable source, the sound icon and clock are missing from the UI. 
But it seems to be valid based on Wowhead comments and this video https://www.youtube.com/watch?v=cyjDibai91E

> You basicaly need to get close enough for ranged atack to take the picture and when you take it he will aggro you, I ran and got away fine but then decided to go back and kill but nothing good droped.

**Comment by kaytotes** [comment]
Fixed in next deploy. Setting to state testing ahead of time.

**Comment by zana244** [comment]
yikes, titi is right,
what's worse is I thought I checked the date on Bue's videos to make sure it's after classic release and my eyes played tricks on me :| it's before august 2019
i'll have to look at a few more issues I reported using this guy's videos, although most of them were sane, sorry about that.

**Comment by T1ti** [comment]
The best way to tell if a video/image is from classic is to look for those two icons 
![image](https://github.com/user-attachments/assets/d38a29ca-927c-4b73-9a3c-84291c8ad80d)
![image](https://github.com/user-attachments/assets/8621ea8a-8985-468b-b181-84a81eb8ce42)
There's a few guys that made videos of every quests on youtube but they're all from private servers lol
