### ISSUE TITLE
Flametongue totem doesn't apply its effect 
not showing on buff ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4527]
> Flametongue totem doesn't apply its effect 
not showing on buff bar nor does it gives the spell bonus

.go xyz -9118.530000 354.144000 93.458200 0 3.491310

**Comment by Shadownflame** [comment]
The buff effect works now, only doesn't show up on the buff bar until another buff is cast which "refreshes" the bar.

There is a separate issue with Flametongue never working in raids because of Windfury, but that goes in a separate report.

**Comment by Shadownflame** [comment]
This seems to be an addon issue. I cannot reproduce it with default UI.
