### ISSUE TITLE
Pet Attack doesn't work under these conditions:
- Stay is active...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4528]
> Pet Attack doesn't work under these conditions:
- Stay is active
- Pet Attack is macroed with a pet ability like Dash
- The ability is on cooldown

Macro example:
/petattack [@mouseover,harm][harm]
/click PetActionButton4

To reproduce:
1) use the pet ability in slot 4
2) command Stay
3) use the pet attack macro

.go xyz -3034.900000 2220.280000 44.114200 1 0.190476

**Comment by Bennylavaa** [comment]
I believe this is related to this issue: https://github.com/Project-Epoch/bugtracker/issues/4530 

The macro works for me but the ability says too far away.
