### ISSUE TITLE
Suggestion: Make pets despawn while mounted (TBC behaviour).
As ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4531]
> Suggestion: Make pets despawn while mounted (TBC behaviour).
As it is now, if you move through an area densely packed with mobs, the pet often pulls aggro, gets dazed and dies or despawns because it can't follow you at high speed while in Combat.

.go xyz -5192.670000 1482.180000 44.794500 1 0.772831

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7226
