### ISSUE TITLE
Pets are not using abilities that are set to Auto-Cast.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4537]
> Pets are not using abilities that are set to Auto-Cast.

.go xyz -4131.050000 4.028310 57.921800 1 4.900480

**Comment by zana244** [comment]
Confirmed on internal, steps to reproduce.
1. Send pet to attack with claw on auto cast.
2. Manually cast a different pet spell while on GCD from claw.
3. The pet will stop casting any spells, until you manually cast another spell (either claw, or bite/dash etc).

Seems like it somehow breaks the pet AI. Possibly the same for warlocks.

Testing a bit, seems to be the same for warlocks, if I make imp cast firebolt while casting it it straight out bugs.

**Comment by Shadownflame** [comment]
I can't reproduce this at all. Pressing the Firebolt during cast just interrupts the cast but then the imp resumes casting. The only thing that breaks my auto cast is the Wind Serpent's lightning and that's reported elsewhere for having a dozen issues. Was this fixed or I'm missing something?

https://github.com/user-attachments/assets/71c43848-56aa-4bc6-a61c-dd66281878b6

**Comment by kaytotes** [comment]
Next Deploy

**Comment by Shadownflame** [comment]
I could never reproduce this to begin with so @zana244 will need to confirm if they still experience this.
