### ISSUE TITLE
Rogue Flame Spirit - (4036)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#454]
> Killed a few of these and they've all been empty of loot. Not sure if normal behavior or not.
`.go xyz 1203.000000 1507.810000 63.014000 1 2.322240`

**Comment by zana244** [comment]
Loot is scuffed post vmangos loot update. 100% Drop rate of custom "Ignition Wand" item ID 60537, no other items.

**Comment by kaytotes** [comment]
Checked this mob on internal. No longer dropping ignition wand. 

This mob has an _extremely_ low chance to actually drop anything with essentially only quest items having a > 0.5% 

Seems fine now
