### ISSUE TITLE
Whenever I log out my macro wont save. However the slot the macr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4558]
> Whenever I log out my macro wont save. However the slot the macro goes in is saved on my keybinds. Like my steady shot macro I slot into #2 keybind. When I make the keybind it immediately goes there. If I do this fresh again but with a different macro it goes to my #2 keybind. It feels the macro slot is saved but not the macro itself

.go xyz -11709.800000 -3247.240000 9.007090 0 2.347450

**Comment by Shadownflame** [comment]
Gotta be player side issue with something on read only. Cannot reproduce this problem.
