### ISSUE TITLE
In Eastern Plaguelands, the pvp towers are not shown on the map ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4561]
> In Eastern Plaguelands, the pvp towers are not shown on the map or any icon of towers owned either on screen. Not sure if I am wrong but leaving it here.

.go xyz 1866.990000 -3710.890000 162.219000 0 5.362880

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2328
