### ISSUE TITLE
After Mind Controlling and releasing the ZF Executioner he did n...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4564]
> After Mind Controlling and releasing the ZF Executioner he did not able to be looted when killed.

.go xyz 1860.850000 1178.750000 9.117460 209 4.383400

**Comment by Bennylavaa** [comment]
needs at least two people to test

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8273
