### ISSUE TITLE
Sentinel of Archaedas aka the last boss of Uldaman is unlootable...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4565]
> Sentinel of Archaedas aka the last boss of Uldaman is unlootable after being killed. If it is of any help our group was considered a raid during the kill.

.go xyz 99.240000 269.086000 -52.148600 70 5.218240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4158
