### ISSUE TITLE
Zone: Un'goro
Quest: Venomhide Eggs

Found many "lighted colored...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4568]
> Zone: Un'goro
Quest: Venomhide Eggs

Found many "lighted colored eggs" in the ravasaur nests but none were interactible.

.go xyz -7735.600000 -1713.350000 -272.203000 1 2.613570

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
