### ISSUE TITLE
Zone: Feralas
Quest: Dental Record (Step 2 / Elder Ragescars)

T...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4570]
> Zone: Feralas
Quest: Dental Record (Step 2 / Elder Ragescars)

The quest item takes a few cycles of respawn to collect. It would probably be best if one of the following changes was made:

1- Make the item drop from more types of ragescars.
2- Make the item a 100% drop.
3- Give the item a change of dropping twice.

.go xyz -4041.030000 2049.860000 90.572400 1 5.948340

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2270
