### ISSUE TITLE
Zone: Searing Gorge
Quest: Do Slavers Keep Records?

Quest indic...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4571]
> Zone: Searing Gorge
Quest: Do Slavers Keep Records?

Quest indicates to kill slavers for the quest item. I've killed about 40 with no drops. 

The item either does not drop or the drop rate might be a bit too low

.go xyz -6867.980000 -1410.950000 172.754000 0 1.059240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
