### ISSUE TITLE
Zone: Tanaris
Quest: Water Co. Saviour

Filter parts appear to b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4574]
> Zone: Tanaris
Quest: Water Co. Saviour

Filter parts appear to be very scarse or spawn very slowly. Makes the quest unappealing to complete.

.go xyz -7160.560000 -3839.600000 8.648600 1 4.102190

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
