### ISSUE TITLE
Zone: Tanaris
Quest: Sink The Rig

The trigger area around the b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4575]
> Zone: Tanaris
Quest: Sink The Rig

The trigger area around the barrels may be a bit too small. I had no trouble using them but my GF's Tauren was almost alwyas out of range even when right on the barrels.

.go xyz -6486.110000 -4948.790000 20.234700 1 0.085049

**Comment by Bennylavaa** [comment]
I cannot reproduce this at all with any race/class there is a good amount of leeway for using it a decent amount away from the barrels.
