### ISSUE TITLE
Zone: Tanaris
Quest: The Perfect Fuel

Interactible objects requ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4576]
> Zone: Tanaris
Quest: The Perfect Fuel

Interactible objects required for the "Ancient Battery" part of the quest have either extremely long spawn times or have stopped spawning entirely.

.go xyz -6967.660000 -4733.450000 8.493530 1 0.092880

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
