### ISSUE TITLE
The quest The Fizz in Winterspring does give you the Electro B.T...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4588]
> The quest The Fizz in Winterspring does give you the Electro B.T.L.R device.

.go xyz 6428.490000 -4845.950000 715.668000 1 2.683680

**Comment by Shadownflame** [comment]
I have a feeling this report left out a "not" somewhere from that sentence.
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/7599
