### ISSUE TITLE
I think my character has actually gotten to a state where things...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4600]
> I think my character has actually gotten to a state where things in the zone cannot path to me and attack me. I can't explain it but I'll shoot things and they won't Evade, but take damage then regen to full. Their pathing is unperturbed by this.

.go xyz -8157.860000 -1343.250000 -221.188000 1 1.193050

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
