### ISSUE TITLE
I think the undamaged hippogryph feather drop rate is either non...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4605]
> I think the undamaged hippogryph feather drop rate is either nonexistent or obscenely low. I'm unable to find one after about 30 minutes of killing various types in the zone. "A Meeting with the Master

.go xyz 3513.770000 -4527.300000 131.585000 1 4.984340

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2400
