### ISSUE TITLE
The Slaver's Records do not seem to drop from the slavers in the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4606]
> The Slaver's Records do not seem to drop from the slavers in the cauldron here. Or the drop rate is obscenely low, as I've killed about 30-40 of them looking for it.

.go xyz -7082.590000 -1373.820000 241.262000 0 0.049005

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
