### ISSUE TITLE
Centipaar Tunnelers appear to not spawn at all in the other hive...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4612]
> Centipaar Tunnelers appear to not spawn at all in the other hive, while the Hazzali Tunnelers spawn here correctly. This renders Silithid Scramble incompleteable and any following quests in the chain.

.go xyz -9260.320000 -3935.550000 13.526000 1 3.241130

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
