### ISSUE TITLE
Elder Cloud Serpent - (4119)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#462]
> Elder Cloud Serpent basically 3 shot me as a lvl 30 mage. Damage seems a bit too high.
`.go xyz -5457.140000 -2929.160000 -38.860600 1 2.264300`

> May be hitting too hard. 200-250 dmg per cast for lvl 29 is a bit too much. Just my opinion.
`.go xyz -5467.310000 -2910.760000 -42.010700 1 1.124750`

**Comment by Bennylavaa** [comment]
only does slightly more damage than on vanilla this looks fine for the overall increase.
