### ISSUE TITLE
When I hearthed from Shimmering Flats during a dust storm to Thu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4620]
> When I hearthed from Shimmering Flats during a dust storm to Thunderbluff, the weather effect persisted and still persists after several minutes.

.go xyz -1280.080000 98.105300 129.611000 1 5.772590

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8312
