### ISSUE TITLE
This exact spot appears to cause a map transition and my charact...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4629]
> This exact spot appears to cause a map transition and my character model disappears. It changes to Orgrimmar from Valley of Strength. It appears to be about a 3 yard diameter area at the end of this ramp?

.go xyz 1672.350000 -4328.230000 61.109100 1 0.742153

**Comment by zana244** [comment]
Confirmed on internal, unsure if fixable?
#5164
