### ISSUE TITLE
I failed to attach this report to its quest, but the activation ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4634]
> I failed to attach this report to its quest, but the activation ranges for all three flames in Helcular's Revenge part two is extremely long, which might not be intended.

.go xyz -552.332000 -28.651900 45.972000 0 3.594120

**Comment by zana244** [comment]
Seems strange, but wowhead says it's 20 yards, which seems about right with ingame...
also https://www.youtube.com/watch?v=O-1g2kAvc3A at 2:20 shows activation at quite a high range.
TIL
