### ISSUE TITLE
freedom to ruul is a real headache with the cave respawn rate an...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4649]
> freedom to ruul is a real headache with the cave respawn rate and i don't think the second set of furbolgs that spawn from the quest disappear upon failure. that means fighting like 6 mobs at once. i tried running ahead to clear early and ruul despawned.

.go xyz 3356.530000 -684.162000 161.245000 1 0.607531

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330

**Comment by zana244** [comment]
#1009
