### ISSUE TITLE
don't recall if it's blizzlike but taming on multiple steps for ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4657]
> don't recall if it's blizzlike but taming on multiple steps for at least the orc tame beast quest is bad. you dont regen hp while holding onto the mob. i feel like that's not blizzlike and could be rigged somehow like stuff such as sm hound whistle. it so far applies to both the boar and the crab. to be fair, releasing the mobs during this doesnt net aggro and doesnt otherwise cause a problem. just seems like you could use the mob temporarily in the past.

.go xyz -745.570000 -5017.860000 17.448800 1 1.145520

**Comment by zana244** [comment]
#8321
