### ISSUE TITLE
tooltip of the "Feedback" priest racial buff doesn't properly sh...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4662]
> tooltip of the "Feedback" priest racial buff doesn't properly show the amount of mana burned per attack, instead displaying "$s1

.go xyz 9645.060000 2621.610000 1337.150000 1 5.024110

**Comment by Shadownflame** [comment]
Seems to affect rank 5 only

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2786
