### ISSUE TITLE
Quest "A Little Help From My Friends", involves scorting Ringo, ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4682]
> Quest "A Little Help From My Friends", involves scorting Ringo, but he's not moving, i wake him up with Spraggle's Canteen, but then he is just staring at me, not following me, not moving.

.go xyz -7202.150000 -1386.950000 -232.344000 1 6.190650

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
