### ISSUE TITLE
Rend fight in UBRS, only the first wave spawns then we get stuck...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4690]
> Rend fight in UBRS, only the first wave spawns then we get stuck because nothing progresses further. 2nd wave and on do not spawn and the gates just get stuck closed. We don't get the opportunity to fight Rend

.go xyz 1634.410000 -4411.650000 16.488800 1 3.232750

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8012
