### ISSUE TITLE
The flight path from EPL Lights Hope to Tirisfal The Bulwark tak...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4691]
> The flight path from EPL Lights Hope to Tirisfal The Bulwark takes you to Undercity and all the way back out before dropping you off at the Bulwark.

Seems unintended!

.go xyz 1928.040000 123.176000 45.286700 0 4.611090

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4955
