### ISSUE TITLE
A taste of flame (Quest) I turned in the molt and completed the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4693]
> A taste of flame (Quest) I turned in the molt and completed the quest, I got the XP drop and Completed the quest but was unable to pick up the follow up to kill Bael Gar in BRD.

.go xyz -7655.160000 -3011.430000 132.520000 0 1.710920

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/831
