### ISSUE TITLE
The guard's description of the location of the barbershop in Org...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4694]
> The guard's description of the location of the barbershop in Orgrimmar is: Moved out of the Cleft of Shadow and is now overlooking the valley of Strenght. 

The barbershop in Orgrimmar is in fact in the Cleft of Shadow. The description of the location the guards give needs to be changed.

.go xyz 1776.660000 -4336.500000 -7.883050 1 3.868080

**Comment by zana244** [comment]
#389
