### ISSUE TITLE
the fp to valors expedition doesnt go to the FP it goes to Marsh...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4705]
> the fp to valors expedition doesnt go to the FP it goes to Marshals Refuge in Un Goro and you have to click to fly to Valors Expedition at the FP in Un Goro

.go xyz -6350.990000 -250.989000 -2.104370 1 0.046967

**Comment by zana244** [comment]
Could not reproduce, flying from gadgetzan alliance fp to valor's exped worked.
