### ISSUE TITLE
Dwarf shaman - when I have the Stoneskin totem rank 1 buff all t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4707]
> Dwarf shaman - when I have the Stoneskin totem rank 1 buff all trolls in the Coldridge valley are literally unable to hit me. Every melee attack is a Miss

.go xyz -6467.600000 369.341000 378.988000 0 4.690190

**Comment by zana244** [comment]
AFAIK intended, if the damage done is 0 it behaves like that, at most it should show as a miss?
non-issue
