### ISSUE TITLE
Diplomacy not working when turning in rep quests as Tauren when ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4716]
> Diplomacy not working when turning in rep quests as Tauren when i have Human racials active. Im not sure if this is a bug are you have it disabled.

.go xyz -2334.550000 -366.823000 37.725600 1 0.991195

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2820
