### ISSUE TITLE
Shadowguard goes away after one charge used

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4735]
> Shadowguard goes away after one charge used

.go xyz -6285.490000 -1350.390000 -250.362000 1 3.357340

**Comment by zana244** [comment]
This seems to have been fixed, 1 attack = 1 charge on internal.

However, the spell has no internal cooldown... afaik it should work like Shaman shields, expending only 1 charge every few seconds. At the moment you can expend all 3 charges in less than 1 second.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5855
Merging
