### ISSUE TITLE
Commander Springvale - (4278)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#474]
> Consecration area is much much wider then visual
`.go xyz -299.714000 2289.080000 95.866900 33 4.728510`

> Invisible consecration
`.go xyz -256.160000 2245.300000 100.892000 33 5.085110`

> Shouldn't he be larger ?
`.go xyz -256.033000 2245.300000 100.894000 33 0.410523`

> consecrate radius way too big
`.go xyz -229.084000 2256.240000 102.756000 33 3.099230`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7697
