### ISSUE TITLE
Scarlet Diviner - (4291)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#475]
> Havent seen a single one cast mana burn, just fireball. Doesn't seem right.
`.go xyz 215.866000 -429.923000 18.533600 189 3.140130`

> mob named unkown in sm libary in Gallary of Treasures
`.go xyz 220.154000 -324.321000 18.533300 189 4.890860`

**Comment by Bennylavaa** [comment]
he only has firebolt that is why its also the same in classic era.
