### ISSUE TITLE
wiped in glittermurk mine, left group before getting back to ins...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4752]
> wiped in glittermurk mine, left group before getting back to instance portal now can't go in and ressurect

.go xyz -13158.100000 -564.621000 4.642700 0 2.917210

**Comment by Shadownflame** [comment]
Probably related https://github.com/Project-Epoch/bugtracker/issues/8292

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
