### ISSUE TITLE
Something is wrong with hit chance. After the blue dagger everyo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4756]
> Something is wrong with hit chance. After the blue dagger everyone was using got the level 55 req added I've been stuck using a skinning knife and shield and since around that time I miss roughly 50% of my swings.

.go xyz -5289.010000 -1766.470000 510.808000 0 4.830000

**Comment by Shadownflame** [comment]
Skinning knife is not qualified as a dagger so the culprit is probably missing unarmed skill.
