### ISSUE TITLE
The IronForge Airfield inn (Innkeeper is Tifaza Silvercord) is n...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4757]
> The IronForge Airfield inn (Innkeeper is Tifaza Silvercord) is not a rested area, or considered indoors. No rested, no instant logout.

.go xyz -4599.010000 -1710.880000 501.475000 0 2.553520

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7060
