### ISSUE TITLE
Mob pathing

I'm only level 15 so idk how pervasive this is, but...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4759]
> Mob pathing

I'm only level 15 so idk how pervasive this is, but so far it seems mobs often will run weird zigzags when they're trying to path around object like trees, if the terrain is not totally flat.

.go xyz -5889.690000 -3284.300000 290.447000 0 3.374200

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
