### ISSUE TITLE
Quest "The Ironforge Airfield"
NPC: Thorgrum Borrelson <Gryphon ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4760]
> Quest "The Ironforge Airfield"
NPC: Thorgrum Borrelson <Gryphon Master>

Supposed to talk to him to get flown to the If Airfield. The text option to get sent to the airfield is there but does not work.

.go xyz -5421.520000 -2929.420000 347.045000 0 4.352060

**Comment by Bennylavaa** [comment]
works in ptr now
