### ISSUE TITLE
I was dueling with Flyxrogue and somehow I killed him in the due...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4762]
> I was dueling with Flyxrogue and somehow I killed him in the duel.  He stealthed as my Hammer of Wrath was flying to him and the duel ended and he was dead on the ground

.go xyz 1360.600000 -4369.380000 26.102700 1 0.104348

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4533
