### ISSUE TITLE
hello epoch
you have failed in properly formatting emotes in the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4769]
> hello epoch
you have failed in properly formatting emotes in the quest of hand of azora. please fix this. add brackets. add arrows. add anything. otherwise, revil is telling me what he's he's doing like a freak.
please and thank you kind epoch devs

.go xyz -10638.900000 1179.370000 34.698300 0 5.385040

**Comment by zana244** [comment]
?
