### ISSUE TITLE
heyyo guys
botaniocal issdur here
so basicalry fdfi foiund a tre...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4771]
> heyyo guys
botaniocal issdur here
so basicalry fdfi foiund a tree outs idfet he ston plabnter and it really dont look too hot

.go xyz -8581.600000 752.392000 96.651000 0 5.106240

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/b723725d-2f76-4623-a1c9-4815a44d12da)

I assume this is what they mean?

**Comment by Bennylavaa** [comment]
Confirmed blizlike closing.
