### ISSUE TITLE
Load lightening quest - very few buzzard spawns.  Only 3 at dino...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4776]
> Load lightening quest - very few buzzard spawns.  Only 3 at dino skeleton on east side of shimmering flats.  Only 1 on the west side where their is usually another group.  Had to make more than a complete circuit to get 10 as the only person out here.

.go xyz -6190.590000 -3959.280000 -58.749800 1 3.340720

**Comment by Shadownflame** [comment]
Blizzlike.
