### ISSUE TITLE
In BRD, Dark Keeper Key unlocks the safe, but the lockbox inside...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4787]
> In BRD, Dark Keeper Key unlocks the safe, but the lockbox inside the safe doesnt unlock

.go xyz 805.869000 -354.250000 -50.198400 736 3.777080

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4069
