### ISSUE TITLE
Firemane Scalebane - (4328)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#480]
> Just continually spam casted Fire Shield on itself in combat.
`.go xyz -4362.210000 -2986.390000 28.629600 1 2.563040`

> This creature keeps spamming its Fire Shield ability even though the buff is already up.
(reposting in case it did not save through the crash)
`.go xyz -4730.860000 -3960.420000 57.201700 1 2.640220`

> This creature keeps spamming Fire Shield ability even though it's already applied on it.
`.go xyz -4657.340000 -3916.250000 46.467600 1 4.236160`

> Firemane Scalebane is just spam casting Fire Shield on itself instead of attacking
`.go xyz -4383.310000 -2926.230000 23.989900 1 3.321170`

> spams fire shield
`.go xyz -4445.020000 -2983.660000 32.036400 1 5.624720`

> Bugged fire shield cast
`.go xyz -4558.160000 -3804.170000 31.670800 1 0.678307`

> The mob spams Fire armor over and over again.
`.go xyz -4372.010000 -2981.520000 28.472000 1 1.826840`

> these are spam casting fire shield on themselves
`.go xyz -4615.700000 -3541.910000 33.000500 1 1.868790`

> Mob is bugged, just continually casts Fire Shield on itself
`.go xyz -4480.230000 -2895.230000 24.111500 1 5.605080`

> They spam fire shield
`.go xyz -4381.300000 -2965.750000 24.387400 1 2.918910`

> There might be somethign wrong with the scripting of this creature, as it spams "Fire Shield" on itself constantly
`.go xyz -4420.800000 -2981.220000 27.847200 1 1.681960`

> keeps casting fire shield emndlessles
`.go xyz -4709.950000 -3725.560000 54.532100 1 4.436100`

> Mob spams his Molten Armor Shield during Combat and combat with this mob just looks weird.
`.go xyz -4383.420000 -2965.040000 24.413300 1 2.305570`

> This mob is spamming fire shield and it need to be fixed
`.go xyz -4708.770000 -3536.000000 39.600900 1 1.348830`

> dropped stonemaul banner, i dont think he is supposed to do that, i think u gotta loot it to the left of me (the actual banner)
`.go xyz -4463.380000 -2965.390000 26.484100 1 2.653340`

> was constantly recasting fire shield on itself, at least once per second or so
`.go xyz -4583.570000 -3772.020000 37.899200 1 5.559420`

> Spamming Fireshield on GCD
`.go xyz -4420.070000 -2973.310000 27.229100 1 2.057450`

> Spams his fire shield ability until kingdom come.
`.go xyz -4714.280000 -3523.200000 37.356900 1 5.411170`

> These mobs should be Elite
`.go xyz -4720.200000 -3688.190000 57.814800 1 5.793440`

> It keeps spamming the Flame Shield ability over and over.
`.go xyz -4469.100000 -2894.730000 22.076400 1 4.067460`

> constantly applying buff to  itself
`.go xyz -4407.090000 -2949.160000 23.564600 1 0.866490`

> these npcs spam their fire shield ability
`.go xyz -4613.730000 -3553.380000 31.010600 1 1.937510`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8051
