### ISSUE TITLE
Firemane Scout - (4329)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#481]
> These guys hit like a truck and a half but have normal health bars for their levels and all their quests are flagged as Elite. Are these supposed to be elite NPCs?
`.go xyz -4339.370000 -2999.210000 34.468000 1 5.049250`

> Hitting too hard? or should these be elite?
`.go xyz -4288.700000 -2995.240000 37.983600 1 3.370260`

> Stats seem to be that of an elite, not a regular mob.
`.go xyz -4363.150000 -3216.790000 34.440500 1 0.593066`

> No pathing seems to be working
`.go xyz -4383.670000 -3487.860000 37.647200 1 4.841130`

> 41lvl non elite 6k HP
`.go xyz -4410.360000 -3493.010000 39.834300 1 6.028340`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7298
