### ISSUE TITLE
the noxious slime cloud these mobs drop upon death doesn't seem ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4816]
> the noxious slime cloud these mobs drop upon death doesn't seem to do any dmg, not even resists show up in my log.

.go xyz 791.922000 -216.214000 -65.236700 349 0.168898

**Comment by zana244** [comment]
Solved on internal.

**Comment by zana244** [comment]
Hurried a bit too quickly, while they do deal damage, it seems to me that the AoE cloud has mismatched visuals... it extends quite a bit outside of its AoE... maybe can be tweaked.

**Comment by zana244** [comment]
Also, noxious slime packs are not linked at all, when you pull one you should pull all of them

**Comment by kaytotes** [comment]
Pack linking is unrelated to this issue and the spell is a blizzard spell with blizzard ranges.
