### ISSUE TITLE
Firemane Ash Tail - (4331)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#482]
> This creature has Elite stats but is not flagged as Elite.
The quest asking to gather essence from them should be Elite too.
`.go xyz -4486.710000 -3096.730000 31.908400 1 4.292600`

> Hitting too hard? or should these be elite?
`.go xyz -4288.700000 -2995.240000 37.983600 1 3.904330`

> Damage and health are that of an elite, not a normal mob. 200 melee hits on my level 44 boar.
`.go xyz -4422.410000 -3194.340000 37.980800 1 5.225840`

> Elite stat and damage but normal quest content (Brogg)
`.go xyz -4479.960000 -3071.520000 39.634400 1 3.766140`

> No pathing on this one either it seems
`.go xyz -4383.670000 -3487.860000 37.647200 1 4.841130`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7298
