### ISSUE TITLE
Grey mobs give XP. I was killing turtles on Tanaris beach earlie...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4829]
> Grey mobs give XP. I was killing turtles on Tanaris beach earlier which were 10 lvls below. If this is a conscious decision and not a byproduct of non diminishing rep rewards or the like, please consider disabling this "feature" when playing with explorers contract.

.go xyz -6048.780000 -982.073000 -213.318000 1 3.245170

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8009
