### ISSUE TITLE
Improved Soul Drain (talent) - I don't believe I am getting the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4836]
> Improved Soul Drain (talent) - I don't believe I am getting the 15% mana returned after I kill a mob while soul draining the target.

.go xyz -12960.500000 -55.795500 9.441150 0 0.014602

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6367
