### ISSUE TITLE
Drywallow Daggermaw - (4345)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#484]
> has 6k hp for some reason. there was a mottled drywallow crocolisk next to him 3 levels lower that had less than 2k hp
`.go xyz -3913.510000 -3396.040000 30.633600 1 0.403193`

> Elite stats.
`.go xyz -4174.950000 -3668.800000 37.209400 1 0.440757`

> This mob has way too much HP, some values are wrong
`.go xyz -4100.330000 -3557.380000 39.241800 1 4.771030`

> 40lv non elite 5,8k HP
`.go xyz -4517.520000 -3411.690000 33.744200 1 6.110820`

> Deep underground or deep in the sky, my pet aggroes and I can see it on the minimap with Track Beasts. It's too far away to use Hunter's Mark
`.go xyz -4863.560000 -3627.830000 49.535500 1 1.731750`

> Deep underground or deep in the sky, my pet aggroes and I can see with Track Beasts
`.go xyz -4713.090000 -3641.280000 47.000200 1 2.218090`

> This is deep underground or deep in the sky, either way my pet aggroes on it and I can see it with Track Beasts
`.go xyz -4654.010000 -3658.020000 42.356300 1 1.744500`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7298 related
