### ISSUE TITLE
Quest "Venomhide Eggs" is broken, doesn't let me pick up the sam...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4856]
> Quest "Venomhide Eggs" is broken, doesn't let me pick up the same eggs the quest describes me and in the same are they should be, instead they just apear as a normal prop in the ground with no interaction

.go xyz -7422.960000 -2136.180000 -273.734000 1 4.391960

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
