### ISSUE TITLE
[Reclaiming the Eggs] quest is bugged in the hinterlands where  ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4868]
> [Reclaiming the Eggs] quest is bugged in the hinterlands where  you have to pick up gryphon eggs but doesnt work since you cant pick the eggs up

.go xyz -391.500000 -2796.570000 78.003300 0 2.998670

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
