### ISSUE TITLE
I can't access penance, account-wide.

I boosted to 45 and I did...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4869]
> I can't access penance, account-wide.

I boosted to 45 and I didn't receive it, it's not in the spellbook nor trainable from regular or beta trainers. (not even learned (greyed out)).
I tried making 2 new characters of other faction and races, I also tried boosting to 30 into 35 but it made no difference.

Using /cast penance gave an instant "interrupted" message with no cast, and further tries gave nothing at all - no cast nor message so I haven't just missed the spell in the spellbook :p

.go xyz -6999.130000 -4864.370000 0.532804 1 3.388600

**Comment by Shadownflame** [comment]
This seems to be an individual issue.
