### ISSUE TITLE
Quest "Reclaiming the eggs" in Hinterlands doesn't work (the egg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4883]
> Quest "Reclaiming the eggs" in Hinterlands doesn't work (the eggs aren't interactable)

.go xyz -461.529000 -2872.950000 96.781800 0 4.169260

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
