### ISSUE TITLE
Spwan Time in Night Web's Hollow waaaaaaaaaaaaaaaaaaaay too fast :)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4888]
> Spwan Time in Night Web's Hollow waaaaaaaaaaaaaaaaaaaay too fast :)

.go xyz 1640.770000 1677.250000 126.932000 0 4.539330

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330
