### ISSUE TITLE
Quest "The Good Stuff"- collect 20 dark iron fanny packs in BRD;...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4891]
> Quest "The Good Stuff"- collect 20 dark iron fanny packs in BRD; does not say where to return to after completion. This quest was shared with me and I have no idea where to go back to turn it in.

.go xyz -4929.110000 -978.182000 501.480000 0 2.537140

**Comment by Shadownflame** [comment]
Turn in info seems added to the tracker sidebar upon completion.
