### ISSUE TITLE
Feralas quest "Dental Records" - Collect 8 Elder Rage Scar Tooth...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4897]
> Feralas quest "Dental Records" - Collect 8 Elder Rage Scar Tooth is not fun. The drop rate is too low. There are about 4 spawns in total in the cave where the quest dropping yetis spawn. If another player was present, it'd be nearly impossible for both of us to finish this quest  in a timely manner. 

Overall, quests from new Glukks compound feel like a waste of time. The drop rate on quest items is wayyy to low.

.go xyz -3871.500000 1658.180000 136.600000 1 4.751340

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2270
