### ISSUE TITLE
I was killing Enraged Feral Scar (level 43-45 mob) in Feralas as...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4898]
> I was killing Enraged Feral Scar (level 43-45 mob) in Feralas as level 53. Even though the mob was grey to me, killing it gave full experience. I had Scroll of Experience buff.

.go xyz -5079.260000 1828.910000 77.458100 1 2.191870

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8009
