### ISSUE TITLE
Tanaris quest : The Perfect Fuel. Ancient batteries don't seem t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4899]
> Tanaris quest : The Perfect Fuel. Ancient batteries don't seem to spawn in their intended location.

.go xyz -6947.220000 -4447.630000 9.604150 1 4.352820

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
