### ISSUE TITLE
For quest in Hinterlands "Reclaiming the Eggs" - the gryphon egg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4900]
> For quest in Hinterlands "Reclaiming the Eggs" - the gryphon eggs do not spawn. Could not complete the quest.

.go xyz -203.297000 -2973.020000 128.739000 0 1.264620

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
