### ISSUE TITLE
Vilebranch Soothsayer - (4467)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#491]
> Nothing acts as LOS here, the barriers, the trees... SEND LOS
`.go xyz 459.647000 -3594.970000 118.492000 0 4.945820`

> Can shoot lightning bolts through the walls and seem to be hitting fairly hard
`.go xyz 314.920000 -4091.220000 118.575000 0 4.872730`

> Get stuck in the bonfire and become hard to target if you chain mobs inside
`.go xyz 321.421000 -4120.560000 119.217000 0 0.943383`

**Comment by zana244** [comment]
SEND LOS.
not a bug.

He can get stuck inside the bonfire and it's pretty funny but i'm not even sure it's a bug, you can still target and attack.
