### ISSUE TITLE
The minimap has a building of some description in The Dragonmurk...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4928]
> The minimap has a building of some description in The Dragonmurk area, but there is nothing actually in game other than trees and bare ground. Location ...almost directly south of the "S" in Stonemaul Ruins

.go xyz -4605.110000 -3175.640000 40.568600 1 2.879750

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7623
