### ISSUE TITLE
Can't imagine i was THIS unlucky ... Dustwallow Marsh appears to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4929]
> Can't imagine i was THIS unlucky ... Dustwallow Marsh appears to have zero herb nodes. Yes, I have Find Herbs on and have done since I entered the zone; been here 45 mins so far, no nodes.

.go xyz -2882.840000 -2883.100000 50.452100 1 0.788209

**Comment by Bennylavaa** [comment]
pooling related
