### ISSUE TITLE
There's a quest in the keep in Menethil Harbour to go talk to Fi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4932]
> There's a quest in the keep in Menethil Harbour to go talk to Fiora Longears in Auberdine (quest is literally called "Fiora Longears"), but this NPC does not seem to exist in Auberdine; i couldn't find her after searching the whole town

.go xyz 6548.970000 472.538000 9.053990 1 3.515250

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2384
