### ISSUE TITLE
inscription categories are in the auctionhouse

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4939]
> inscription categories are in the auctionhouse

.go xyz 1668.150000 -4459.760000 18.829200 1 4.605650

**Comment by zana244** [comment]
Confirmed on internal, glyphs are present. Unsure if modifiable.
Never mind, on second thought there are glyphs in Epoch wow but unsure if tradeable?

**Comment by kaytotes** [comment]
Won't fix.
