### ISSUE TITLE
the quest "The Art of Golemancy" is just fucked. I am not gettin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4947]
> the quest "The Art of Golemancy" is just fucked. I am not getting any kill credit, so I can't complete it, and I also cant leave the golem by clicking the leave vehicle button. it says "can't do that right now".

not only that, but the quest itself is just legit terrible and the golem needs to be like 3x stronger.

.go xyz -7912.380000 -2287.780000 129.545000 0 5.113500

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
