### ISSUE TITLE
Bug from Beta 2.5 is still present. If you aggro a mob from dist...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4950]
> Bug from Beta 2.5 is still present. If you aggro a mob from distance whilst in stealth and move away just as the mob starts to run  towards you, it will reset the mob and you'll remain in stealth.

.go xyz 2327.920000 1333.540000 33.681500 0 3.929850

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7344
