### ISSUE TITLE
Burning Steppes

Quest: The Art of Golemancy
         Kills does...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4954]
> Burning Steppes

Quest: The Art of Golemancy
         Kills doesnt count

Quest: Tired o' them Orcs
        Kills doesnt count

.go xyz -8023.310000 -2234.210000 133.760000 0 1.912230

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
