### ISSUE TITLE
flight path from bulwark to hopes chapel goes over undercity for...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4955]
> flight path from bulwark to hopes chapel goes over undercity for some reason :D nothing major but strange

.go xyz 1885.630000 -2278.800000 161.563000 0 4.943520

**Comment by Shadownflame** [comment]
Bulwark does not connect to EPL directly, so it either has to go through Undercity or Thondoril River FP. 
Thondoril FP was left out of being auto learned from the level boost on beta, but it exists, so it works fine.
