### ISSUE TITLE
Not sure if a bug or not, but I summoned the last boss in ZF wit...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4959]
> Not sure if a bug or not, but I summoned the last boss in ZF with the mallet. Our group wiped, and it let me click the gong again but nothing happend, then my option to click the gong was gone.

.go xyz 6.169880 -2997.050000 126.353000 0 1.814420

**Comment by zana244** [comment]
#8245 
Shouldn't need to resummon her since she should not despawn.
