### ISSUE TITLE
Flightpath Theramore>Valor's Point (Tanaris?) flies trough a roo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4967]
> Flightpath Theramore>Valor's Point (Tanaris?) flies trough a roof in Steamwheedle port

.go xyz -7301.170000 -3858.180000 15.693100 1 1.128730

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3034
