### ISSUE TITLE
Antu'Sul in Zul'Farrak spawns with too many basilisks (I think?)...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4968]
> Antu'Sul in Zul'Farrak spawns with too many basilisks (I think?) but also if you wipe he'll keep the pre-spawned ones for a while.

.go xyz -4840.490000 -862.589000 501.914000 0 1.404380

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7671
