### ISSUE TITLE
Aged Kodo - (4700)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#497]
> These kodos appear to be a zone patrol that is not moving.
`.go xyz -1999.010000 1711.470000 62.748300 1 0.603539`

> I think this is the front of a procession of travelling kodo in the zone, but they are just standing still in a line and not moving.
`.go xyz -779.891000 1984.020000 85.974300 1 3.896380`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7027 related

**Comment by Bennylavaa** [comment]
this is 100% a duplicate of the one linked, closing this.
