### ISSUE TITLE
I'm at 68.4, 13.6 in the Wavestrider Beach, in Tanaris.
Northeas...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4981]
> I'm at 68.4, 13.6 in the Wavestrider Beach, in Tanaris.
Northeast of Steamwheedle Port, in the Oil Rig.
Underneath it, there's a spot where you can breathe.
I don't think it's intended because there's no valve here or bubbles around.

.go xyz -6499.720000 -4940.570000 -16.550800 1 2.671360

**Comment by zana244** [comment]
confirmed on internal, breathing underwater.
#8308
