### ISSUE TITLE
In the quest "The Perfect Fuel" in Tanaris, even after you gathe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4982]
> In the quest "The Perfect Fuel" in Tanaris, even after you gathered all 8 Ancient Batteries, you can still interact and open the Ancient Troll Pots.
Although you won't get any more of the quest items, the Ancient Troll Pot will despawn.

.go xyz -6905.790000 -4338.020000 14.043300 1 3.653050

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
