### ISSUE TITLE
Geting aggroed while in the Cart.
Not sure if this is intended o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4983]
> Geting aggroed while in the Cart.
Not sure if this is intended or not.
It happened while moving from Tirisfal Glades into Silverpine, and got aggro from a Worg.

.go xyz 1011.860000 1285.430000 45.436000 0 0.752009

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6456
