### ISSUE TITLE
Aponi Brightmane is an NPC in Thunder Bluff that you need to spe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4986]
> Aponi Brightmane is an NPC in Thunder Bluff that you need to speak to for a Racial Quest "Aponi's Request". Aponi has nothing to say to you / you can't turn in the quest.

.go xyz -1057.530000 -300.236000 159.030000 1 5.806360

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7711
