### ISSUE TITLE
I cannot train Divine Spirit Rank 4 from Father Cobb in TB. I am...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4988]
> I cannot train Divine Spirit Rank 4 from Father Cobb in TB. I am a Disc priest with the previous ranks and I am level 60.

.go xyz -996.857000 249.131000 102.382000 1 0.112259

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7658
