### ISSUE TITLE
For the quest for Centipaar Tunnelers and Centipaar Sandreavers,...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4994]
> For the quest for Centipaar Tunnelers and Centipaar Sandreavers, there are only 3 Centipaar Tunnelers spawn and you have to kill 6. There really needs to be more.

.go xyz -9724.910000 -3975.090000 130.045000 1 3.211870

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
