### ISSUE TITLE
Quest Water Co. Saviour - there are not any spawns of the item o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#4996]
> Quest Water Co. Saviour - there are not any spawns of the item on the seabed, swam all the way to the pirate cove and all the way north, only found 2 and they never respawned. Trying to do this in a group of 4 people, so basically impossible to complete.

.go xyz -6957.350000 -4378.350000 9.774190 1 5.050040

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
