### ISSUE TITLE
Rogue tier 0.5 Darkmantle set bonus for 8 pieces doesnt seem to ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5005]
> Rogue tier 0.5 Darkmantle set bonus for 8 pieces doesnt seem to work at all.  Didnt get a single proc even tho sinister strike crit multiple times
Tested with Backstab as well, and no energy gain on crit.

.go xyz -8782.190000 351.478000 101.020000 0 5.627730

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1677
