### ISSUE TITLE
When Volchan resets, he floats and clips through anything. In at...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5010]
> When Volchan resets, he floats and clips through anything. In attempt to kite Volchan to Redridge, he reset and clipped through the Ogre mountain. Now volchan is missing, he may have clipped through the world

.go xyz -7686.610000 -2504.640000 140.512000 0 2.068200

**Comment by Bennylavaa** [comment]
I mean I cant reproduce him disappearing but the bouncing back to his spawn point is blizlike all npcs do this if you pull them far enough away.
