### ISSUE TITLE
the common attack macro:

/targetenemy [noharm][dead]
/cleartarg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5014]
> the common attack macro:

/targetenemy [noharm][dead]
/cleartarget [dead]
/cast Sinister Strike
/startattack

sometimes locks up leaving the user no longer attacking

.go xyz -7458.020000 -1270.920000 -268.362000 1 3.572210

**Comment by Bennylavaa** [comment]
Works fine for me
