### ISSUE TITLE
There dont seem to be any Ancient Batterys for The Perfect Fuel ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5024]
> There dont seem to be any Ancient Batterys for The Perfect Fuel quest. Searched Noonshade Ruins for severeal minutes

.go xyz -6940.290000 -4339.660000 12.126300 1 4.828120

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
