### ISSUE TITLE
NPC Missing : Andello Porter

According to the quest "The Apothe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5027]
> NPC Missing : Andello Porter

According to the quest "The Apothecary's Letter" which is a new Epoch quest, I was to give a letter that dropped on "Apothecary Cylla" to Andello Porter which was to be found at Tabetha's Farm in Duswallow marsh. Unfortunatly the NPC is nowhere to be found.

.go xyz -4045.440000 -3397.690000 38.273900 1 1.965990

**Comment by zana244** [comment]
#1713
