### ISSUE TITLE
Quest : Stones that Bind us.

Expected : Click on stone when Ser...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5029]
> Quest : Stones that Bind us.

Expected : Click on stone when Servant of Razelikh is low on health which kills him.

Observation : Can't click on the stone.

.go xyz -11758.400000 -3042.320000 18.771900 0 2.709600

**Comment by Bennylavaa** [comment]
well yea you have to hurt them to a certain point.
