### ISSUE TITLE
Quest: Water Co. Saviour

Objective : Collect 8 Filter Parts

Th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5032]
> Quest: Water Co. Saviour

Objective : Collect 8 Filter Parts

The filter parts are really too scarce. There should be more added ! 
There arn't even enough for one player !

.go xyz -7447.500000 -4944.870000 0.528157 1 5.159460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
