### ISSUE TITLE
The quest Favor for Krazek (627) the Lesser Bloodstone Ore does ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5044]
> The quest Favor for Krazek (627) the Lesser Bloodstone Ore does not spawn in Drywisker Gorge like the quest says. You cannot complete this quest.

.go xyz -951.187000 -3920.370000 145.957000 0 5.666830

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1483
