### ISSUE TITLE
https://www.wowhead.com/classic/quest=464/war-banners

This ques...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5047]
> https://www.wowhead.com/classic/quest=464/war-banners

This quest is not avalible after completing 

https://www.wowhead.com/classic/quest=473/report-to-captain-stoutfist

.go xyz -2354.700000 -2423.640000 74.747700 0 2.901100

**Comment by zana244** [comment]
Confirmed on internal, the nek'rosh quest line was moved on Epoch though. It may be worth deleting the "report" quest since it is functionally useless.

**Comment by Bennylavaa** [comment]
intended, was moved to a different spot in a custom chain. I think it is fine as it is.
