### ISSUE TITLE
If you take your time inside the Arcanaeum the door locks and yo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5055]
> If you take your time inside the Arcanaeum the door locks and you can't go outside. Add a way to open it from the inside or make the Elite that spaws after the quest drop a key.

.go xyz 7967.980000 -4555.060000 726.516000 1 3.422820

**Comment by zana244** [comment]
Confirmed on internal. Would be nice to not be forced to use hearthstone for this.

**Comment by kaytotes** [comment]
There is a rune on the door that appears when its closed.

![image](https://github.com/user-attachments/assets/dca9043b-4702-4320-9855-c7d93ff75452)

**Comment by zana244** [comment]
funnily enough I encountered no issues there on beta 3, brain afk on internal 🤣 my bad
