### ISSUE TITLE
Quest "Lost!" (id:4492) is not working. Ringo (id: 9999) doesn't...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5060]
> Quest "Lost!" (id:4492) is not working. Ringo (id: 9999) doesn't spawn

.go xyz -6552.500000 -1796.150000 -271.568000 1 0.773580

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
