### ISSUE TITLE
Quest "Dental Records" in Feralas (id: 26609) is probably workin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5061]
> Quest "Dental Records" in Feralas (id: 26609) is probably working but not reasonable. The quests asks you to get 8 Tooth from a bunch of yetis. There are only 5 spawns total in the area. No, shared spawnpools have never worked in this server.

.go xyz -4420.280000 2708.020000 -1.863240 1 1.422360

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2270
