### ISSUE TITLE
Hinterland quest "Reclaiming the Eggs" (id:9475) is bugged. Can'...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5065]
> Hinterland quest "Reclaiming the Eggs" (id:9475) is bugged. Can't interact with the world objects (the eggs)

.go xyz -254.455000 -3041.170000 127.831000 0 2.202660

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
