### ISSUE TITLE
The flight path in "The Harborage" is bugged. You can't discover...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5067]
> The flight path in "The Harborage" is bugged. You can't discover it, if you use it, it takes you to the first connection through the mountains (on top it all, it makes you go to Redridge first if you try to go to Duskwood)

.go xyz -10515.100000 -1260.320000 41.377400 0 0.668874

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7551
