### ISSUE TITLE
The pathing in the coast of Swamp of sorrows is still extremlly ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5068]
> The pathing in the coast of Swamp of sorrows is still extremlly bugged. The mobs (and pets) get stuck everywhere

.go xyz -9703.430000 -3997.220000 2.058990 0 4.868520

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
