### ISSUE TITLE
a 400 hp rare with magic damage is very unfair for warriors who ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5072]
> a 400 hp rare with magic damage is very unfair for warriors who have garbage abilities compared to a warlock that can have a pet tank the mob for it and rot it with dots. mob is unbalanced (precipise; northshire falls)

.go xyz -8322.040000 -258.621000 143.974000 0 3.053550

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6277
