### ISSUE TITLE
Aru-Talis Site Four in Un'Goro doesn't seem to have a middle of ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5082]
> Aru-Talis Site Four in Un'Goro doesn't seem to have a middle of the screen area entry message like the other three sites do.

.go xyz -8289.850000 -1164.010000 -179.644000 1 3.163650

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
