### ISSUE TITLE
The Un'Goro Hunt" Stegadon quest is labeled as being in Elwynn F...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5083]
> The Un'Goro Hunt" Stegadon quest is labeled as being in Elwynn Forest in the quest log. Don't think I'm finding any stegadons there!

.go xyz -6730.960000 -810.122000 -272.026000 1 2.643830

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
