### ISSUE TITLE
I have somehow managed to bug the "With a Little Help from His F...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5084]
> I have somehow managed to bug the "With a Little Help from His Friends" quest in Un'goro. I took Ringo all the way back and I think he collapsed in front of the quest giver and I didn't notice. I thought it was handed in. I then ran back and only after a while realised that it hadn't been completed.

I abandoned the quest and have been waiting around for his respawn for a while now, probably upwards of 30 minutes, but he doesn't seem to be coming back.

.go xyz -6274.950000 -1245.840000 -256.241000 1 0.464354

**Comment by Shadownflame** [comment]
same issue https://github.com/Project-Epoch/bugtracker/issues/7733
