### ISSUE TITLE
Grazle gives the Speak to Nafien quest still but Grazle is no lo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5085]
> Grazle gives the Speak to Nafien quest still but Grazle is no longer in the south of the zone. He has taken Nafien's place just outside the Timbermaw tunnel. I believe Nafiel no longer exists so that quest shouldn't be here any more?

.go xyz 6817.160000 -2082.100000 623.878000 1 6.199100

**Comment by zana244** [comment]
#950
