### ISSUE TITLE
Cauldron Lord Malvinious respawns instantly on death in WPL

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5088]
> Cauldron Lord Malvinious respawns instantly on death in WPL

.go xyz 1841.800000 -1572.400000 58.965900 0 0.101328

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330
This might be an odd one to check individually.

**Comment by zana244** [comment]
#939
