### ISSUE TITLE
Sanath Lim-yo in Azshara has two Meeting with a Master quests. H...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5089]
> Sanath Lim-yo in Azshara has two Meeting with a Master quests. He also has the old version where you have to hand in undamaged hippogryph feathers. These feathers do not currently drop.

.go xyz 3785.160000 -4613.110000 226.993000 1 5.548170

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2400
