### ISSUE TITLE
Do Slavers Keep Records?" in Searing Gorge either has an unreaso...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5092]
> Do Slavers Keep Records?" in Searing Gorge either has an unreasonably abysmal drop rate or I got super unlucky. Either that, or it doesn't actually drop. Thought I better report it just in case.

.go xyz -10070.200000 -1404.690000 109.424000 0 1.940070

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
