### ISSUE TITLE
The Hemovac foor "Fit For a King" seems to be bugged, I can't se...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5098]
> The Hemovac foor "Fit For a King" seems to be bugged, I can't seem to get it to draw blood out of a wounded beast.

.go xyz -5158.450000 1365.570000 41.711100 1 5.304580

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2267
