### ISSUE TITLE
On 'Fit For a King' the objective says "Vial's of Beast Blood". ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5099]
> On 'Fit For a King' the objective says "Vial's of Beast Blood". It should say "Vials of Beast Blood".

.go xyz -4569.700000 1851.970000 89.456100 1 0.527876

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2267
