### ISSUE TITLE
The respawns on Wetland Hemp for 'Fit For A King' seem ridiculou...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5100]
> The respawns on Wetland Hemp for 'Fit For A King' seem ridiculously long and the spawns are very scarse.

.go xyz -4746.300000 1017.900000 112.866000 1 5.977490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7967
