### ISSUE TITLE
The valve for the 'Perfect Fuel' quest is unreasonably hard to f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5103]
> The valve for the 'Perfect Fuel' quest is unreasonably hard to find, it's tiny and doesn't highlight.

.go xyz -6523.860000 -4944.640000 -1.823590 1 2.477490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
