### ISSUE TITLE
For Water Co. Saviour, I'm really struggling to find the Filter ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5104]
> For Water Co. Saviour, I'm really struggling to find the Filter Parts. The quest text says they fell around the boat but I could only find one spawn there, been up and down the shoreline, can't see them anywhere in the water.

.go xyz -6996.000000 -4935.470000 1.000490 1 0.178761

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
