### ISSUE TITLE
The Magical Material quest in Alterac Mountains made me question...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5107]
> The Magical Material quest in Alterac Mountains made me question as to whether or not there was any point to my life. I had enough time to reflect on this due to the utterly horrendous string ot requirements to complete the quest coupled with an utterly abysmal drop rate.

Please don't let people do this to themselves.

.go xyz 448.271000 213.707000 41.999800 0 0.502426

**Comment by Bennylavaa** [comment]
very very very grindy quest I think this is most likely the longest quest I did during beta 3.

**Comment by Shadownflame** [comment]
#7545
