### ISSUE TITLE
Theramore Skirmisher - (5044)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#511]
> One of these from Questioning Reethe turned friendly, but is still following me around, targeting me as if in combat. I'm not in combat.
`.go xyz -3362.000000 -3201.310000 34.469800 1 3.588700`

> npc is following me after completing (not turning in) the quest "questioning reethe" 
not sure if that's intended. he is friendly, but has a hostile animation
`.go xyz -3607.240000 -3214.060000 32.426300 1 2.948710`

> Friendly to horde during the quest line. Keeps aggro on the player but does not attack
`.go xyz -3371.720000 -3213.830000 34.190400 1 2.476710`

> This character hs become my permanent pet. It is following me around but is green.
`.go xyz -3142.730000 -2893.860000 34.280600 1 2.022390`

> this is following me, aggroed, not attacking, after the ogre reese quest
`.go xyz -3346.900000 -3184.920000 32.411400 1 3.081150`

> She doesnt aggro in final stage of quest Questioning reethe and keeps follow you like a pet.
`.go xyz -3146.060000 -2884.480000 33.933200 1 2.207710`

> after killing this npc for the quest "Questioning Reethe" instead of dying, it turns green and follows you around.
`.go xyz -3307.200000 -3094.350000 33.229500 1 1.291810`

**Comment by Shadownflame** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/8140

**Comment by Bennylavaa** [comment]
moved this info to the quests bug
