### ISSUE TITLE
Private Thorsen at the Rebel Camp  after completing loads of que...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5110]
> Private Thorsen at the Rebel Camp  after completing loads of quests in STV has an exclamation mark over his head like he has a quest but doesn't actually have one to offer.

.go xyz -11314.200000 -201.863000 75.519900 0 6.126050

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/117
