### ISSUE TITLE
Jann Langston in Stormwind's text says "Smoother than and elf,' ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5113]
> Jann Langston in Stormwind's text says "Smoother than and elf,' rather than "Smoother than an elf,

.go xyz -8634.850000 458.756000 102.130000 0 4.499850

**Comment by zana244** [comment]
Not sure on what quest, she has no dialogue option by default...
NPC ID 3626

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/415
