### ISSUE TITLE
Penance (Shadow) does not apply all of the shadow things that I ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5115]
> Penance (Shadow) does not apply all of the shadow things that I think it's meant to, according to old patch notes. Shadow Vulnerability, Blackout etc.

.go xyz -38.448900 -535.392000 153.960000 0 0.674233

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2987
