### ISSUE TITLE
For the Hillsbrad quest "Assistance to Jenna", the quest text di...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5116]
> For the Hillsbrad quest "Assistance to Jenna", the quest text directs the player westwards to a cottage in a clearing, but I can't find it for the life of me. Possibly skill issue.

.go xyz -693.621000 -249.655000 28.963600 0 5.246960

**Comment by Shadownflame** [comment]
If a Dwarven bunker passes as a cottage, then yes, it's just like the text says.
