### ISSUE TITLE
Arteris the Exile, elite rare in Darkshore does't seem to be wor...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5118]
> Arteris the Exile, elite rare in Darkshore does't seem to be working quite right. I pulled him and kited him a bit but after he threw his poisoned harpoon at me he seems to have lost his ability to chase me. If I go into melee range he will swipe me but otherwise he just stands there and waits for his Poisoned Harpoon cooldown.

.go xyz 5907.480000 601.695000 0.944734 1 1.792230

**Comment by zana244** [comment]
#1177
