### ISSUE TITLE
Handing in the quest "Clear Accusations" awarded me with XP and ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5135]
> Handing in the quest "Clear Accusations" awarded me with XP and completion, but did not close the quest popup. And now there's no follow up quest though it feels like from the text that there should be?

.go xyz -6975.590000 -4844.340000 8.228190 1 5.886590

**Comment by Bennylavaa** [comment]
you most likely were level 45, the next quest requires level 46.
