### ISSUE TITLE
Agamand Family Crypt has double spawns which make the quest requ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5136]
> Agamand Family Crypt has double spawns which make the quest require multiple people without using Death Run Cheeses to get to Dargol.

My suggestion is to either Label as Group Quest or adjust Spawns.

.go xyz 3057.030000 666.779000 58.211200 0 3.125320

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8118
