### ISSUE TITLE
Witchdoctor Mauri in Everlook is still hostile (red) to alli for...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5139]
> Witchdoctor Mauri in Everlook is still hostile (red) to alli for the quest A Little Luck. Means farming ekos isn't possible for alli. Is this Epoch's intention? Server pop should know this then for faction choice in character to play.

.go xyz 6716.010000 -4673.460000 720.969000 1 1.859960

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/869
