### ISSUE TITLE
Harvest Golem skin is bug? Maybe?

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5149]
> Harvest Golem skin is bug? Maybe?

.go xyz -10228.300000 1041.030000 36.625000 0 6.050010

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/86eaa402-1578-4370-8a60-a3dec0272e91)

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/63
