### ISSUE TITLE
Hillsbrad Defense for Horde doesn't trigger even though the crit...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5157]
> Hillsbrad Defense for Horde doesn't trigger even though the criteria is met and the "The Horde has defended the Central Tower" announcement is made

.go xyz -333.605000 -693.364000 56.495500 0 1.551360

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2449
