### ISSUE TITLE
Most Tin Veins in Barrens are exact doubles, as in not near each...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5159]
> Most Tin Veins in Barrens are exact doubles, as in not near each other but exactly spawned inside each other. Cant really give exact coordinates but a quick walk near the hills would provide you with the evidence

.go xyz 1739.370000 942.893000 133.875000 1 3.669500

**Comment by Bennylavaa** [comment]
blizlike that doubles can spawn near eachother but its most likely a pooling issue being looked at in https://github.com/Project-Epoch/bugtracker/issues/8295
