### ISSUE TITLE
At the top of the ramp of the flight tower in Org, the character...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5164]
> At the top of the ramp of the flight tower in Org, the character disappears in a certain spot.

.go xyz 1672.740000 -4326.760000 61.246400 1 1.200060

**Comment by zana244** [comment]
Confirmed on internal, unsure if fixable. Transition from Orgri <-> Valley of Strength. Linking previously confirmed issue here due to better title.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8006
