### ISSUE TITLE
After being mind-controlled by a Silithid in Silithus at Hive'Re...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5167]
> After being mind-controlled by a Silithid in Silithus at Hive'Regal, it flags me for PvP and puts the World Brawler debuff on me after hitting my teammmates

.go xyz -7670.600000 651.978000 -45.114600 1 3.958390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2967
