### ISSUE TITLE
Quest: "A Little Help from my Friends" in Un'Goro is bugged and ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5170]
> Quest: "A Little Help from my Friends" in Un'Goro is bugged and Ringo doesn't move once the escort has started.

.go xyz -7198.930000 -1390.130000 -232.127000 1 3.537750

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
