### ISSUE TITLE
The way mobs interact with totems is really strange. Totems don'...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5178]
> The way mobs interact with totems is really strange. Totems don't seem to be tied to me as their caster, so when a mob aggros my totem first it resets back to it's originally non-aggro patroling position. I watched a mob methodically, 1 by 1, kill all 4 of my totems in ZF while we were fighting a different set of mobs, and then reset back to its original patrol around Gahzrilla's pond.

.go xyz -4990.060000 1537.440000 60.644200 1 1.477180

**Comment by zana244** [comment]
#8216
