### ISSUE TITLE
When flying from Gadgetzan to Orgrimmar, the flightpath had me c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5181]
> When flying from Gadgetzan to Orgrimmar, the flightpath had me clip through the new tower in Razor Hill.

.go xyz 1676.830000 -4319.710000 61.139200 1 4.070550

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
