### ISSUE TITLE
The flight path in "The Harborage" for alliance in Swamp of Sorr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5186]
> The flight path in "The Harborage" for alliance in Swamp of Sorrows says "Lakeshire, Redrige" Instead of The Harborage

.go xyz -10099.500000 -2801.600000 61.079700 0 2.497900

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7551
