### ISSUE TITLE
Horde - Hinterlands > Undercity, very bumpy trip through houses ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5207]
> Horde - Hinterlands > Undercity, very bumpy trip through houses in western plaguelands on the ol' chimaera. xD

.go xyz 1887.430000 698.822000 59.539700 0 2.397780

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
