### ISSUE TITLE
Committed what would legally be defined as genocide on these Thu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5210]
> Committed what would legally be defined as genocide on these Thunderhead Hippogryphs, still no Undamaged Hippogryph Feathers for "A meeting with the master

.go xyz 3459.790000 -4255.020000 95.836300 1 1.400800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2400
