### ISSUE TITLE
Intimidation should not be consummed when the pet miss

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5226]
> Intimidation should not be consummed when the pet miss

.go xyz 7871.330000 -4610.090000 701.287000 1 4.891570

**Comment by zana244** [comment]
From what I know and what I've researched it's working as intended; if the pet somehow misses or gets dodged/parried then intimidate should not stun and should get "wasted". unfortunate but it is what it is...maybe it could get changed later down the road.
checking on internal it's actually bugged and does not get consumed like that, linking to main issue

later edit: fml after reading the actual spell tooltip, in classic and TBC it reads "after successful melee attack" whereas on wotlk it only has "after melee attack"...
https://youtu.be/PhQUqyCqlIE?feature=shared&t=355 -- joana on classic wow with intimidation not being lost on missed auto.

#2793
