### ISSUE TITLE
Elder Rage Scar - (5297)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#523]
> For the quest dental records, the elder rage scar tooth quest items seem to have a pretty low drop rate for the amount of elder rage car yeti found in the caves. It may need to be upped slightly.
`.go xyz -3895.130000 1569.800000 121.198000 1 1.290240`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2270
