### ISSUE TITLE
When your pet is dead and the corpse is too far it will diseaper...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5231]
> When your pet is dead and the corpse is too far it will diseaper wich is normal, but if you click call pet, the pet corpse should appear next to you

.go xyz -4667.520000 2031.040000 7.971930 1 4.470650

**Comment by zana244** [comment]
Hmmm this actually seems like a private server bug... there is no reason to be able to summon a dead pet. Revive pet works (as it should) with the dead, unsummoned pet.
