### ISSUE TITLE
Gcd desync doesnt work for steady shot, its a core tbc mechanic ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5233]
> Gcd desync doesnt work for steady shot, its a core tbc mechanic : https://boukx.github.io/threetwo/

.go xyz -6376.220000 -260.444000 -6.345840 1 2.391470

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/6618

**Comment by zana244** [comment]
A complete can of worms this is...
GCD desync is core for 2.4.3 TBC hunter, but not for TBC Classic... Up to devs what they want to implement.

**Comment by Shadownflame** [comment]
If my suspicions are right, this mechanic requires the same feature of spell queueing as the other GCD issues I linked, which is just hands down missing from the core right now. So I doubt it can be implemented at all.

**Comment by zana244** [comment]
While the issue consists of how the gcds/spells are queued, it's not really a matter of the spell queue feature :D. It's about how Steady shot would get queued after an auto shot, but the GCD starts earlier.

**Comment by zana244** [comment]
#8327
Linking to topic with more info.
