### ISSUE TITLE
The quest "A strange request" given by Witch Doctor Uzer'i in Fe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5240]
> The quest "A strange request" given by Witch Doctor Uzer'i in Feralas seems to be broken, as Xerash fireblade is missing. 

I think this is a Wotlk quest?

.go xyz -4376.390000 260.512000 26.064900 1 1.254290

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2075
