### ISSUE TITLE
Some Thick-shelled clam do not have clam meat in them.  They're ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5248]
> Some Thick-shelled clam do not have clam meat in them.  They're just empty.

.go xyz -941.411000 -694.545000 0.185287 0 0.776143

**Comment by Shadownflame** [comment]
Confirmed. [Thick-shelled clams](https://www.wowhead.com/classic/item=5524) should always drop [Tangy Clam meat](https://www.wowhead.com/classic/item=5504/tangy-clam-meat) + occasional pearls. Currently they often tend to be empty or dropping low level [Clam Meat](https://www.wowhead.com/classic/item=5503/clam-meat).
