### ISSUE TITLE
Logged out while dead in a Scholomance run.  Logged back in late...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5250]
> Logged out while dead in a Scholomance run.  Logged back in later since the group fell apart, and I can't rez by entering the dungeon.  My ghost just zones in and I'm still dead inside the dungeon.

.go xyz 1152.900000 -2530.900000 60.656500 0 0.388903

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
