### ISSUE TITLE
Devouring Ooze mini-ooze spawns on death seem a little overtuned...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5251]
> Devouring Ooze mini-ooze spawns on death seem a little overtuned.  They hit faster and harder than I remember.  Totem threat doesn't help either.

.go xyz 2296.340000 -2235.950000 55.681200 0 0.686687

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/215
