### ISSUE TITLE
Not necessarily a bug but filter parts for the quest 
Water Co. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5257]
> Not necessarily a bug but filter parts for the quest 
Water Co. Saviour should be more abundant.  Very few and far between and I'm the only one out here.  Can't imagine doing it with multiple players looking for them.

.go xyz -6973.420000 -4944.740000 -5.491730 1 6.182550

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
