### ISSUE TITLE
Bloodroar the Stalker - (5346)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#528]
> Failed to drop green loot
`.go xyz -5048.690000 1612.060000 68.415400 1 6.100750`

> This rare did not drop anything of note.
`.go xyz -5050.240000 1611.950000 68.122200 1 0.784189`

> Drops nothing
`.go xyz -5043.780000 1612.890000 69.594400 1 5.809370`

> underwhelming weak. felt like the regular yeti's near him
`.go xyz -5041.210000 1613.570000 70.344300 1 1.781040`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249

**Comment by Shadownflame** [comment]
Fixed.
