### ISSUE TITLE
Antilus the Soarer - (5347)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#529]
> Did not drop any loot as a rare
`.go xyz -5665.260000 1634.390000 80.698000 1 0.991301`

> This rare dropped nothing of note.
`.go xyz -5705.840000 1659.340000 88.735700 1 4.829210`

> killed 2 time never dropped greens?
`.go xyz -5768.980000 1674.080000 88.687400 1 4.490240`

> rare mob do not have any loot
`.go xyz -5790.410000 1593.610000 79.517800 1 0.779154`

**Comment by Bennylavaa** [comment]
fixed
