### ISSUE TITLE
The Art of the Golemancy quest in Burning Steppes does not regis...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5292]
> The Art of the Golemancy quest in Burning Steppes does not register kills made while within the golem. Also the damage indicated in the tooltip for its abilites do not match what it actually does. The damage is lower in reality than what the tooltip says.

.go xyz -7930.660000 -2408.160000 129.160000 0 4.958770

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
