### ISSUE TITLE
For the quest [Reclaiming the Eggs] in Hinterlands, I found the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5295]
> For the quest [Reclaiming the Eggs] in Hinterlands, I found the eggs, but I cannot interact with them. I can't click, target, loot, etc. If you need one specifically, one is near the Atal'ai Exile mob. Thank you.

.go xyz -460.267000 -2873.060000 96.798100 0 4.779800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
