### ISSUE TITLE
The Chunky Grouper mob in Hinterlands resets if you jump while s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5296]
> The Chunky Grouper mob in Hinterlands resets if you jump while swimming. If you jump straight up from the water and land in the exact same spot, the mob resets. I tested it 3x and it resetted each time. Thank you.

.go xyz 606.819000 -3511.100000 98.778400 0 0.779656

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1223
