### ISSUE TITLE
Arash-ethis - (5349)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#530]
> This rare did not drop anything.
`.go xyz -3521.900000 2327.510000 63.255900 1 1.148010`

> Drops nothing
`.go xyz -3528.070000 2327.250000 64.594100 1 1.599370`

> drops nothing
`.go xyz -3524.640000 2325.570000 63.403600 1 1.156840`

**Comment by Bennylavaa** [comment]
fixed
