### ISSUE TITLE
Reclaiming the Eggs" quest in Hinterlands, the eggs aren't click...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5301]
> Reclaiming the Eggs" quest in Hinterlands, the eggs aren't clickable.

2 on the altar near the water of Shadra'Alor and 3 in the trough by Atal'ai Exile, all unclickable.

.go xyz -407.372000 -2884.990000 83.721300 0 3.432370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
