### ISSUE TITLE
protection paladin feels sooo mana starved with no real regenera...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5303]
> protection paladin feels sooo mana starved with no real regeneration, can you guys lower the mana cost of spells or increase mana regen? i feel like i have to drink every pull in dungeons when my healer is good to go.

.go xyz -1762.350000 -1877.840000 58.326500 0 1.621330

**Comment by Shadownflame** [comment]
Not a bug report.
