### ISSUE TITLE
Dual spec seems bugged, I was fire spec lvl 45 with talents incl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5305]
> Dual spec seems bugged, I was fire spec lvl 45 with talents including blast wave, I bought dual spec, activated my second spec but the first spec talents (e.g blast wave) are still on my bar and usable

.go xyz -9004.810000 846.695000 106.021000 0 5.249960

**Comment by zana244** [comment]
solved on internal.
