### ISSUE TITLE
Rogue's cheat death ability appears to increase damage  drastica...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5306]
> Rogue's cheat death ability appears to increase damage  drastically (somewhere in the ballpark of doubling damage received from all sources, at all times unconditionally). This also compounds with the proc, and damage also becomes increased seemingly proportional to the rogue's dodge chance while the proc is active. The proc itself does work, though and avoids death properly.

.go xyz -4626.680000 -3015.760000 36.210500 1 4.292120

**Comment by zana244** [comment]
#2878
