### ISSUE TITLE
Old Grizzlegut - (5352)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#531]
> Rare mob only dropped gray item. Is this intentional? I thought rares always dropped a green.
`.go xyz -5153.600000 1314.560000 44.350700 1 0.764321`

> This rare didn't drop anything when killed.
`.go xyz -5103.480000 1332.110000 39.304000 1 4.136470`

> This rare creature did not drop any loot (a fair expectation for a rare)
`.go xyz -5126.480000 1314.570000 39.914600 1 3.974590`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249

**Comment by Shadownflame** [comment]
Fixed.
