### ISSUE TITLE
My character was stuck in a no animation mode for some reaosn. f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5312]
> My character was stuck in a no animation mode for some reaosn. fixed it with a restart. Happened in Redridge

.go xyz -9149.360000 -2674.040000 90.744000 0 2.986920

**Comment by Shadownflame** [comment]
Seems to be an issue with the launcher that happens super rarely. Running the launcher again resolves the issue. https://github.com/Project-Epoch/bugtracker/issues/6937
