### ISSUE TITLE
I have a bear as my pet on the Hunter class and it just ran in c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5315]
> I have a bear as my pet on the Hunter class and it just ran in circles when I told it to attack a target. Happened in The Master's Glaive in Darkshore

.go xyz 4538.170000 459.027000 31.496600 1 3.617180

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
