### ISSUE TITLE
I keep getting the Target not in line of sight when I try to sho...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5322]
> I keep getting the Target not in line of sight when I try to shoot an auto shot arrow at a target that less than 15 yd in front of me with nothing blocking the way of the shot.

.go xyz 10831.900000 922.844000 1337.920000 1 2.445730

**Comment by zana244** [comment]
Could not replicate. Some mobs are behind the world texture which correctly counts as LoS here (afaik).
