### ISSUE TITLE
Many of the elite mobs outside wailing caverns as you work your ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5332]
> Many of the elite mobs outside wailing caverns as you work your way to the instance seem to be having pathing issues. They are not attacking or aggroing at first and don't take damage when attacked but as you move some distance away from the they will come after you and attack as normal.

.go xyz -443.091000 -2601.950000 96.292700 1 1.064960

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
