### ISSUE TITLE
The npc "Ringo" in the quest "Lost!" in "Un'goro Crater at the F...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5333]
> The npc "Ringo" in the quest "Lost!" in "Un'goro Crater at the Fire Plume Ridge seem to not be spawning. I waited a very long time (what seemed longer than what it used to be) without him respawning. Ignore this if he has been moved to a new location.

.go xyz -7352.530000 -1446.630000 -267.374000 1 4.555370

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
