### ISSUE TITLE
I unlearned a profession (Leatherworking) to pick Herbalism inst...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5337]
> I unlearned a profession (Leatherworking) to pick Herbalism instead. However, when I talk to Rachael Ray (Profession booster), and click on Herbalism (or any other primary profession), nothing happens. I can't learn a second primary profession anymore. I went to the actual Herbalism trainer in Org, learned it, and tried boosting after that but not it just says I have 2 professions already.

.go xyz 1619.840000 -4420.100000 14.426500 1 3.489530

**Comment by Shadownflame** [comment]
Beta issue
