### ISSUE TITLE
Hero Worship part 2 - Unable to interact with Elven Heartwood pi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5338]
> Hero Worship part 2 - Unable to interact with Elven Heartwood piles.

They sparkle but cannot be clicked on.

.go xyz 1972.020000 -4373.460000 81.492100 0 5.106970

**Comment by Bennylavaa** [comment]
27779 - [Hero Worship] 

Piles are sparkly and cannot be clicked

**Comment by Bennylavaa** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/2350

**Comment by kaytotes** [comment]
Next deploy.
