### ISSUE TITLE
New ogre quest zone bear/ape meat doesnt drop. farmed for 30 min...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5343]
> New ogre quest zone bear/ape meat doesnt drop. farmed for 30 mins only got 1

.go xyz -7188.760000 -3808.110000 28.604800 1 2.508420

**Comment by Shadownflame** [comment]
Not clear what quest this means. Go xyz is from tanaris but the only "new ogre quest zone" I know of is Gluk's compound in Feralas, and those quests work fine.
If it refers to a different quest chain, I'm at a loss here.
