### ISSUE TITLE
The Quest "Reclaiming the Eggs" seems to be bugged, I can't seem...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5373]
> The Quest "Reclaiming the Eggs" seems to be bugged, I can't seem to collect the eggs required for the quest.

.go xyz -404.482000 -2962.680000 94.088900 0 0.701343

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
