### ISSUE TITLE
The quest : The Ring of Strength : The Final Challenge rewards y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5377]
> The quest : The Ring of Strength : The Final Challenge rewards you with the appearance of all of the items, regardless of the one you choose.

Steps to reproduce : 
Proceed to Stranglethorn Vale.
Proceed to the Ring of Strength.
Begin the "The Ring of Strength" chain.
Complete the chain until you have to speak to the NPC named Unja the Troll-Servant to turn the "The Final Challenge" part of the chain.
Select "Battle Mage Baton".
Notice that you get all appearances.

.go xyz -12324.700000 -440.137000 15.346800 0 3.153710

**Comment by zana244** [comment]
Intended for transmog system.
