### ISSUE TITLE
black lotus gave me 2 qty in burnign steppes

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5392]
> black lotus gave me 2 qty in burnign steppes

.go xyz -7888.140000 -793.232000 133.752000 0 0.678854

**Comment by Shadownflame** [comment]
This is maybe intended? Lotus affinity proc from the lotus itself? @Bunnyblock2

**Comment by ghost** [comment]
Yup that's intended, it can indeed proc on the lotus itself
