### ISSUE TITLE
While in Ghost Wolf and you "CTRL press an item to inspect" you ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5441]
> While in Ghost Wolf and you "CTRL press an item to inspect" you look like a ghost.

.go xyz -7181.130000 -3829.090000 8.992400 1 3.945030

**Comment by Shadownflame** [comment]
Weird visual glitch, not sure if blizzlike, but if possible to correct, should:
![WoWScrnShot_082624_222800](https://github.com/user-attachments/assets/374178af-1ed5-4397-bd70-42c8a8b099e3)

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2582
