### ISSUE TITLE
No death animation for Serpentshifter

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5448]
> No death animation for Serpentshifter

.go xyz -311.886000 -143.602000 -25.877200 726 1.911300

**Comment by zana244** [comment]
could not reproduce?

**Comment by zana244** [comment]
Never mind, the death animation does not happen if the NPC is shapeshifted. He just teleports from being a serpent to a dead elf on the ground with no animation/sound.
Same issue as feral disciple.

**Comment by kaytotes** [comment]
Not resolvable.
