### ISSUE TITLE
Cyrus Therepentous does not give Taste of Flame quest after givi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5454]
> Cyrus Therepentous does not give Taste of Flame quest after giving him the molt. It just takes the molt and acts like there's nothing further to do here.

.go xyz -7643.980000 -3050.070000 131.145000 0 1.930220

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/831
