### ISSUE TITLE
Not sure if intended.

Emblem of alacrity, level 45 trinket sold...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5455]
> Not sure if intended.

Emblem of alacrity, level 45 trinket sold by warsong vendor, procs form entering stealth.

.go xyz -7238.440000 -3370.940000 10.030000 1 3.766560

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
