### ISSUE TITLE
Soul Siphon talent should increase healing effect up to 60%, its...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5459]
> Soul Siphon talent should increase healing effect up to 60%, its been 24% currently which is bugged

.go xyz -585.085000 -4235.010000 38.254400 1 4.001610

**Comment by Shadownflame** [comment]
I believe this is an intentional change since it affects drain soul as well here so the wotlk cap was chosen? @Bunnyblock2

**Comment by ghost** [comment]
Correct that's intentional
