### ISSUE TITLE
Centipaar Stinger - (5456)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#546]
> These mobs are not correctly tagged as Beasts and cannot be tracked.
`.go xyz -7843.240000 -2519.840000 -45.078300 1 2.924050`

> doesn't have race "beast". im hunter and can't track beast them
`.go xyz -7735.190000 -2549.280000 -48.469900 1 5.148350`

**Comment by Shadownflame** [comment]
Centipaar are not beasts, they are uncategorized like oozes. This is intended.
