### ISSUE TITLE
The same issue for the Razormane Thornweavers. They should be ca...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5462]
> The same issue for the Razormane Thornweavers. They should be casting the armor debuff, but they just stop in place, no casting animation or castbar, no debuff

.go xyz -137.366000 -2964.130000 92.049500 1 3.062650

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6937
