### ISSUE TITLE
Centipaar Swarmer - (5457)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#547]
> i wa shere for the quest silithid scamble looking for tunnelers,  i have found in doing both tunnels at least 3 times cant seem to find them
`.go xyz -7695.260000 -2600.730000 -56.230200 1 1.697670`

> These are not correctly marked as Beasts and cannot be tracked.
`.go xyz -7841.520000 -2514.170000 -45.126700 1 3.956850`

> doesn't have race "beast". im hunter and can't track beast them
`.go xyz -7735.190000 -2549.280000 -48.469900 1 5.148350`

**Comment by Shadownflame** [comment]
Silithid aren't beasts.
