### ISSUE TITLE
The quest "The perfect fuel" Says the batteries should be in noo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5478]
> The quest "The perfect fuel" Says the batteries should be in noonshade ruins. I checked there during the day and night. ive killed enemies and havent seen a single battery

.go xyz 1810.310000 -4272.310000 7.044330 1 0.983199

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
