### ISSUE TITLE
Hunter Wind Serpent pet's currently only spam cast Lightning Bre...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5482]
> Hunter Wind Serpent pet's currently only spam cast Lightning Breath.  They will not move into melee range to attack and use their other ability BIte at any time unless the aggro of the melee mob pushes in to attack them directly.  If you engage a ranged mob with your Wind Serpent they will both stay at range casting only Lightning Breath even when out of focus they will wait for it to regenerate to begin attacking again.

.go xyz -13757.700000 544.265000 45.876300 0 2.474450

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5481
