### ISSUE TITLE
Centipaar Tunneler - (5459)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#549]
> Not enough spawn locations for this mob - Only spawns in 2 spots while the quest Silithid Scramble requires 6 kills
`.go xyz -8026.720000 -2489.190000 3.017310 1 4.000570`

> There is only one working spawn of this creature. You need 6 kills of these for "Silithid Scramble". Might consider adding a few more spawns :)
`.go xyz -7794.280000 -2584.660000 -48.718000 1 0.378994`

> These mobs seem to despawn at random, making the quest Silithid Scramble very frustrating to complete, as they often vanish as you approach them.
`.go xyz -8090.460000 -2454.670000 -54.277900 1 3.879310`

> This quest needs more of these for the quest Silithid Scramble - they may share a respawn... but they rarely do - too many sandreavers. I wouldn't do this quest again if no tunnelers
`.go xyz -8017.360000 -2486.810000 6.600330 1 0.387311`

> They seem to disappear at random and very few are spawned even at night. I've been unable to kill a single one since they despawn when I get close.
`.go xyz -7843.710000 -2569.290000 0.721653 1 5.897270`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/7580
