### ISSUE TITLE
While having a demon active (imp), when enslaving a demon and di...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5497]
> While having a demon active (imp), when enslaving a demon and dismissing it, original pet is still active but the pet bar is missing. Resummoning it makes the pet bar reappear

.go xyz -11612.200000 -3233.990000 9.723500 0 4.958570

**Comment by Shadownflame** [comment]
The issue here is that you cannot have two separate controllable pets at the same time. It bugs the pet bar because this scenario shouldn't be possible at all. I'll dump this into Enslave Demon https://github.com/Project-Epoch/bugtracker/issues/2559
