### ISSUE TITLE
The Loremaster - (1682)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#55]
> clicking on the deprecated achievment will crash the client
> Multiple Versions of this achievement exist.
> Clicked on one of the (Deprecated) achivemens and it hard crashed my computer. Couldnt alt-tab, alt-f4, or crtl alt del of thie game

**Comment by Bennylavaa** [comment]
1. I do not see any (Deprecated) achievements in the achievement UI
2. I linked one by grabbing an ingame link for wowhead, no crash when clicking it. 
3. .achievement add 681 and looking at the achievement in the UI doesn't crash my client or clicking on it in chat. 

I think this player has some weird modded client or something that or its some specific achievement they didn't specify seeing there are a lot of  (Deprecated).
