### ISSUE TITLE
Dunemaul Ogre - (5471)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#551]
> Cannot be hit with melee auto attacks
`.go xyz -8279.420000 -3020.950000 8.628260 1 0.544775`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892 related maybe

**Comment by Bennylavaa** [comment]
can't reproduce this, most likely due to the linked report.
