### ISSUE TITLE
the witherbark troll in the blazing hills drops item 
subjugatio...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5512]
> the witherbark troll in the blazing hills drops item 
subjugation report 
when i click it i cant accept the quest
after quest in the blazzing hills to the part when you kill the witherbark trolls i can now accpet it 
so mabye it shouldnt drop when you can accpet the  quest

.go xyz -2059.000000 -3723.490000 153.310000 0 0.879962

**Comment by zana244** [comment]
#1848
