### ISSUE TITLE
The level 10 hunter pet quest gets you stuck in combat as soon a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5513]
> The level 10 hunter pet quest gets you stuck in combat as soon as you tame one of the quest pets. You need to outrange it or it needs to die for combat to drop. I can't right click the portrait either to abandon it.

.go xyz 9952.000000 2346.980000 1330.760000 1 1.560860

**Comment by zana244** [comment]
#8321
