### ISSUE TITLE
Quest Reclaim the Eggs
Alliance Hinterlands

The eggs required t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5518]
> Quest Reclaim the Eggs
Alliance Hinterlands

The eggs required to loot are uninteractable

.go xyz -402.263000 -2961.850000 94.224600 0 0.178595

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
