### ISSUE TITLE
After dropping shadowform the CD was never triggered and I had t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5524]
> After dropping shadowform the CD was never triggered and I had to relog inorder to use shadowform again.  Prior I used shadowfiend and it was currently on CD with the pet bar still active but pet gone.

.go xyz 6902.320000 -4520.440000 710.772000 1 4.990440

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4090
