### ISSUE TITLE
Custom-Quest: An Unlikely Ally (find Izalnir) 
NPC ID: 8022 

Th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5525]
> Custom-Quest: An Unlikely Ally (find Izalnir) 
NPC ID: 8022 

The quest text says he is 'near the coast' - but in this version of WoW there is no coast in the Blasted Lands

.go xyz -11000.900000 -3488.940000 103.111000 0 1.089700

**Comment by zana244** [comment]
joke's on you, this is why you play epoch. there is a coast on epoch.
