### ISSUE TITLE
Quest "Reclaining the Eggs" is bugged - eggs cannot be picked up...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5526]
> Quest "Reclaining the Eggs" is bugged - eggs cannot be picked up

https://www.wowhead.com/quest=9475/reclaiming-the-eggs

Someone also posted this bug in the Discord:
https://discord.com/channels/729423227373355040/1022596106242236446/1226079848938737744

.go xyz -396.713000 -2971.490000 100.334000 0 1.154720

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
