### ISSUE TITLE
First the bug, probably reported but in BRD after the bar was st...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5533]
> First the bug, probably reported but in BRD after the bar was stuck in combat unable to drink until randomly before the final throne area.
random rant: 
rip the dream
no one ever wants to run ubrs/are busy running other things/only want 3 druids for one boss
go to ubrs, instance bugs at the end
go to ubrs, group implodes by arguing with itself as the healer constantly talked about dps meter readings and the tank gets one shot by groups in drak's chamber
dungeon achieve req damned by STdrakes

.go xyz -6227.650000 326.176000 383.103000 0 4.836660

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095
