### ISSUE TITLE
forgotten pools, the barrens...fissure at bottom of the forgotte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5538]
> forgotten pools, the barrens...fissure at bottom of the forgotten pools provides no air for breathing

.go xyz 89.899700 -1941.210000 88.129600 1 4.820170

**Comment by zana244** [comment]
Unsure on the intended behaviour.
On VMangos, you get a physical (red) debuff "Air Bubbles" which gives you breath back, both at the forgotten pools and the stagnant oasis...
However, on classic I'm not sure if that's the case...
https://www.youtube.com/watch?v=yqUGLvUMt9Y
https://www.youtube.com/watch?v=sZAVF2zPwos
#4625
