### ISSUE TITLE
shaman level 8, when rockbiter 1 is active casting rockbiter 2 d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5540]
> shaman level 8, when rockbiter 1 is active casting rockbiter 2 does not overwrite the existing rockbiter 1. i must remove rockbiter 1 then initiate rockbiter 2

.go xyz 169.266000 -4745.840000 11.348600 1 3.282930

**Comment by zana244** [comment]
#7823
