### ISSUE TITLE
Occasionally when levelling up, the game freezes for some amount...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5556]
> Occasionally when levelling up, the game freezes for some amount of time. Once it atually locked up my pc and I had to reset

.go xyz -8952.210000 -255.825000 75.751800 0 2.803870

**Comment by kaytotes** [comment]
Can not replicate. Nothing we can do to cause this. User has a funky PC.

**Comment by Shadownflame** [comment]
Strange I had a similar issue on the beta (never as bad as freezing PC, but terrible frame drops when lvling up), but it's not happening on internal.
