### ISSUE TITLE
Fishing is broken

Levelled 1-300 in Ironforge. Mixed trash 1-65...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5558]
> Fishing is broken

Levelled 1-300 in Ironforge. Mixed trash 1-65, only sickly fish from 65-300. Something is very broken.

Several zones are similar: even with 405 fishing you get nothing but sickly fish e.g. Ashenvale near where teleporter spawns you in (discovered while doing fishing daily).

.go xyz -4642.780000 -1085.200000 500.537000 0 3.068850

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6852
