### ISSUE TITLE
i entered the central tower in hillsbrad without pvp flag, it sa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5565]
> i entered the central tower in hillsbrad without pvp flag, it said i had to pvp flag to capture it. So i enabled pvp.   But even then the bar isnt moving , i tried to zone out and in, the same issue occurs. Capping isnt working even with pvp flag on

.go xyz -335.298000 -697.204000 57.155800 0 4.281270

**Comment by Shadownflame** [comment]
Sounds like there was a stealthed enemy in there. It works fine.
