### ISSUE TITLE
Uldaman final boss fight.
Sentinel of Archaedas can't be interac...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5567]
> Uldaman final boss fight.
Sentinel of Archaedas can't be interacted after killed. So can't be looted.
I was kiting him around his room when he enraged untill he died, other than that the fight seemed to work fine.

.go xyz 93.454100 259.146000 -51.783100 70 4.631460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4158
