### ISSUE TITLE
Using the flight path from Gadgetzan to Theramore causes your gr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5570]
> Using the flight path from Gadgetzan to Theramore causes your griffin to fly through various buildings in the new Steamwheedle Port.

.go xyz -6213.450000 -5052.730000 8.831790 1 6.175250

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3034
