### ISSUE TITLE
Aquatic form bugged. I am not able to see the form on my charact...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5581]
> Aquatic form bugged. I am not able to see the form on my character, but I can breathe under water and swim fast. I tried this in Ironclad Cove in Deadmines.

.go xyz -704.080000 258.741000 -121.897000 725 5.142500

**Comment by zana244** [comment]
Confirmed on internal, might be due to bugged water interaction. Aquatic form gets cancelled but the swim speed does not get removed.
#8308
