### ISSUE TITLE
Crushing blows, as in tripple swings interrupt spellcasts three ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5583]
> Crushing blows, as in tripple swings interrupt spellcasts three times. Channeled spells like Penance or Mind Flay gets cancelled immediately instead of losing 1 tick.

.go xyz -7971.900000 -2396.990000 -26.647900 1 0.016101

**Comment by Shadownflame** [comment]
Crushing blows aren't triple swings... thrash effects are. And those are three separate attacks so it's intended.
