### ISSUE TITLE
Increase spawn locations and decrease respawn time for Water Co....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5587]
> Increase spawn locations and decrease respawn time for Water Co. Savior. It takes way too long to find 8 cogs. If multiple people were doing this it would be impossible.

.go xyz -6856.210000 -4765.360000 9.660950 1 5.792820

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
