### ISSUE TITLE
Think of the Animals quest - after cleaning a turtle it aggro'd ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5591]
> Think of the Animals quest - after cleaning a turtle it aggro'd onto me and stood in place. I had to kill it to get out of combat.

.go xyz -7267.630000 -4880.120000 0.568981 1 2.589370

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2233
