### ISSUE TITLE
Priest dps pvp dont have a proper set, or make a neutral set to ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5593]
> Priest dps pvp dont have a proper set, or make a neutral set to heal dps for priest or make 2 separated pvp sets.
With neutral y mean, Power word shield, mana reduction on instant abilities or something that can benefit a priest in every spec ofc focusing on pve or pvp areas.
Ex: SP-pvp shield bonus, this could be great for either heal or dps,
Ex:HP: mana reduction on instant abilities, like dispel, abolish, renew etc. this can benefit the 3 branches i just 1 set

.go xyz 1329.470000 -4382.570000 26.218300 1 4.784720

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7977
