### ISSUE TITLE
I am a human hunter, my pet is constantly on attack mode even if...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5596]
> I am a human hunter, my pet is constantly on attack mode even if he's in passive mode and his abilities activates even though he's not attacking anything and the biggest problem is that I also am in attack mode constantly because of that state he's in
By the way just putting that here but amazing work you are doing ! I really hope it explodes in the future in terms of popularity :D

.go xyz -9503.240000 147.407000 56.588400 0 0.785607

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8321
