### ISSUE TITLE
Hunter pets following while mounted are aggroing mobs and should...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5607]
> Hunter pets following while mounted are aggroing mobs and should not be.  They also lag behind based on your mount speed and should keep up next to you while mounted.

.go xyz -4081.160000 364.138000 56.808300 1 4.183690

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7226
