### ISSUE TITLE
Venomhide Ravasaur Eggs for quest Venomhide Eggs don't seem to b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5612]
> Venomhide Ravasaur Eggs for quest Venomhide Eggs don't seem to be lootable

.go xyz -7784.600000 -2101.620000 -269.777000 1 3.428800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
