### ISSUE TITLE
Quest Advanced Alchemy (27376) says 'report to Proctor Blackwood...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5613]
> Quest Advanced Alchemy (27376) says 'report to Proctor Blackwood' there is no Proctor Blackwood, it should read 'report to Proctor Philips'

.go xyz 1185.870000 -2399.950000 60.272800 0 5.780890

**Comment by Bennylavaa** [comment]
duplicate of https://github.com/Project-Epoch/bugtracker/issues/8300
