### ISSUE TITLE
Quest Advanced Alchemy (27375) has quest header elwynn forrest i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5616]
> Quest Advanced Alchemy (27375) has quest header elwynn forrest instead of western plaguelands

.go xyz 1124.560000 -2516.380000 60.589300 0 1.297510

**Comment by Bennylavaa** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/2305
