### ISSUE TITLE
I've killed more than 30 Dark Iron Slavers with the quest Do Sla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5619]
> I've killed more than 30 Dark Iron Slavers with the quest Do Slavers Keep Records? (27242) and haven't received one, I assume it must be bugged? Im an undead paladin lvl 60

.go xyz -6563.650000 -1218.850000 185.665000 0 6.046160

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
