### ISSUE TITLE
The quest A Hive Cleared, is taken from Dumont Hollowcry, and yo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5621]
> The quest A Hive Cleared, is taken from Dumont Hollowcry, and you are told to go inform Urulg in the quest text, however you can instantly complete the quest by talking to Dumont again.

.go xyz -9726.010000 -3972.960000 130.095000 1 4.204520

**Comment by zana244** [comment]
#2472
