### ISSUE TITLE
Quest A Chilly Stranger (26532) has the objective 

"fill the cr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5623]
> Quest A Chilly Stranger (26532) has the objective 

"fill the crystal phial with water from the moonwell in thistleshrub valley well as 8 sturdy root's from..."

it should say "as well as GET 8 sturdy roots"

it's missing the word get as well as using an apostrophe when it's just a plural.

.go xyz -10301.800000 -3834.890000 0.642508 1 0.332822

**Comment by Shadownflame** [comment]
Seems resolved.
