### ISSUE TITLE
Looks like there is no way to complete the quest The Perfect Con...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5625]
> Looks like there is no way to complete the quest The Perfect Container because the parts needed for the quest either don't respawn or are not obtainable for some other reason.

.go xyz -7016.130000 -3534.660000 9.968390 1 4.531850

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
