### ISSUE TITLE
Shade of Eranikus - (5709)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#563]
> The spawn rate on the adds for this boss is way too high
`.go xyz -654.925000 -41.999700 -90.835100 109 5.501440`

> Very strong boss.  We got him to maybe 50% at best. with a group including a 55, 54, 53 dps
`.go xyz -630.321000 -21.180900 -90.835200 109 4.989870`

> Engaging Eranikus is supposed to aggro all green dragons that are still alive inside the instance, but this does not currently happen.
`.go xyz -638.366000 64.222000 -90.837100 109 4.606820`

> killable even tho every other dragon boss despawned
`.go xyz -666.146000 37.475100 -90.835200 109 4.885080`

> size doesnt match tail swipe hitbox
`.go xyz -670.575000 -21.171200 -90.835200 109 4.835690`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310
