### ISSUE TITLE
The quest An Offering of Peace objective test says

Collect 8 Tu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5630]
> The quest An Offering of Peace objective test says

Collect 8 Turtle "Nugget"'s

it should read

Collect 8 Turtle "Nuggets"

it is a plural not a genitive/possesive case

that would be 8 Turtle's "Nuggets

.go xyz 406.070000 -4784.210000 12.790700 0 3.446670

**Comment by zana244** [comment]
#5629
