### ISSUE TITLE
The quest 'Unfinished Business' in WPL is bugged. I went to the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5634]
> The quest 'Unfinished Business' in WPL is bugged. I went to the top of the tower in the middle of Hearthglen, the one you're meant to go to, and I did not get quest completion.

.go xyz 2738.290000 -1580.610000 135.105000 0 6.218770

**Comment by Bennylavaa** [comment]
it works you have to be on a specific part of the tower.
