### ISSUE TITLE
The Summoner's Tomb is inaccessible in BRD. So I can't test Wrai...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5637]
> The Summoner's Tomb is inaccessible in BRD. So I can't test Wraith Scythe scaling. :(

.go xyz 1298.680000 -329.495000 -90.497600 736 5.454390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6142
