### ISSUE TITLE
I've had this issue since Beta 1 and I have absolutely no clue w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5638]
> I've had this issue since Beta 1 and I have absolutely no clue why it's happening: My FPS drops by 80 whenever I have the "Self" section of my Combat Log open.
It's worth noting that that green bar that fills up as your Combat log is loading, never actually finishes loading on the "Self" section. That might be related to the issue.
Either way, it's a very weird bug. I don't have any addons related on related to my chat/combat log.

.go xyz 2157.480000 -4628.660000 52.729400 1 3.791840

**Comment by Bennylavaa** [comment]
cannot reproduce
