### ISSUE TITLE
Jammal'an the Prophet - (5710)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#564]
> His mind control / transform ability drops you out of combat if you're the only person left alive, or running solo. I don't know if he's even supposed to be able to cast that ability if there's only 1 person fighting. Since it just drops combat and resets the fight.
`.go xyz -496.146000 -109.784000 -90.827500 109 2.312160`

> felt a little weak, low hp/dmg
50+ grp
`.go xyz -441.342000 -95.893700 -90.827500 109 1.932050`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310
