### ISSUE TITLE
The Tauren NPC and quest-giver 'Storm Shadowhoof' is missing in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5640]
> The Tauren NPC and quest-giver 'Storm Shadowhoof' is missing in Everlook. He gives the elite hunting quest chain that starts with Ursius.

.go xyz 6717.430000 -4671.260000 720.868000 1 1.452280

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7995
