### ISSUE TITLE
Some debuff in Jinta'alor was giving me permanent reduction to A...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5646]
> Some debuff in Jinta'alor was giving me permanent reduction to Attack Power, only logging out removed it. I'm not sure what exactly caused it, but maybe the Hex?

.go xyz 1729.920000 -726.172000 59.281400 0 0.190914

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7998 related
