### ISSUE TITLE
Weapon Skill leveling seems bugged at the moment. I remember in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5648]
> Weapon Skill leveling seems bugged at the moment. I remember in early betas it was too slow, but now it's way too fast. At least at the later levels here, I just gained Axes 275 -> 280 on a single mob in 4 seconds.

.go xyz -10858.600000 -3737.240000 23.617100 0 2.292190

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7059
