### ISSUE TITLE
Stuck in combat in BRD, might be related to the non-active NPC g...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5652]
> Stuck in combat in BRD, might be related to the non-active NPC golem at Fineous Darkvire place.

.go xyz 607.396000 73.089600 -73.870200 736 0.700943

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7534
