### ISSUE TITLE
There's currently a golem that patrols Fineous Darkvire place in...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5653]
> There's currently a golem that patrols Fineous Darkvire place in BRD that's just a "non-mob", he's not interactable with in any fashion, he just paths up and down and doesn't do anything.

.go xyz 568.333000 -199.386000 -52.949600 736 3.088560

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7534
