### ISSUE TITLE
LoS is broken in the Jammal'An prophet room. Ranged doesn't appr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5654]
> LoS is broken in the Jammal'An prophet room. Ranged doesn't approach you behind the crevaces in the walls.

.go xyz -490.072000 -76.573200 -90.827400 109 6.276550

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310

**Comment by kaytotes** [comment]
Can not replicate.

https://github.com/Project-Epoch/bugtracker/assets/7526918/87c92390-c032-46ef-84e1-05004e7b50e4
