### ISSUE TITLE
Weaver - (5720)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#566]
> no loot
`.go xyz -473.100000 32.780400 -91.071800 109 1.781740`

> This boss (as well as his twin Dreamscythe) are supposed to patrol in a circle around the room after spawning. They are also supposed to be linked together. Neither of these things are currently true.
`.go xyz -490.428000 30.891200 -90.946600 109 2.088270`

> not patrolling as with other mobs in ST
`.go xyz -514.783000 19.102700 -90.881900 109 1.036700`

**Comment by zana244** [comment]
#8310
