### ISSUE TITLE
Magtoor in Swamp of Sorrows gives a quest that horde can take bu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5677]
> Magtoor in Swamp of Sorrows gives a quest that horde can take but he is in an area that looks like an alliance camp. Not sure if this is intended?

.go xyz -10108.100000 -2813.330000 61.079400 0 3.677950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/208
