### ISSUE TITLE
Not really enough Doomwarders in Mannoroc Coven to complete the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5679]
> Not really enough Doomwarders in Mannoroc Coven to complete the quest for 1 person in 1 go with the current drop rate and number of spawns

.go xyz -2030.000000 1919.430000 70.474600 1 0.470893

**Comment by Shadownflame** [comment]
As per ktotes this is intended to be a painful quest for the vanilla feel. Players will have to do it in parts while running around for other quests.
