### ISSUE TITLE
Deviate Shambler - (5761)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#568]
> Can't tell if my Scorch isn't properly scaling on this particular mob or unusually tanky against fire spells.
`.go xyz 130.742000 -80.130900 -24.716100 726 4.349310`

> Too many "resist" for my mindflay ability. I'm 60 lvl against 20 lvl shambler.
`.go xyz -324.255000 36.283100 -41.406100 726 0.954341`

**Comment by Shadownflame** [comment]
Elemental mob with high resistances.
