### ISSUE TITLE
Typo in description for quest Wanted: Keiko 

Bring proof of thi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5682]
> Typo in description for quest Wanted: Keiko 

Bring proof of this acto to Jinzar'Zillen

should be

Bring proof of this act to

.go xyz -1713.770000 3193.270000 4.401230 1 5.069650

**Comment by zana244** [comment]
Confirmed on internal. Could also use a comma before but in "this Village fed, but" (and maybe lowercase V for village?)

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
