### ISSUE TITLE
Quest The Dustwind Escape, the quest description says "I didn't ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5684]
> Quest The Dustwind Escape, the quest description says "I didn't think I would see another Orc again" when you play as orc. but the dude is literally captured by orcs.

.go xyz 794.888000 -4790.480000 37.057400 1 5.275470

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2450
