### ISSUE TITLE
Charging to Kul Tiras Deckhands or Admirals around boats  in dur...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5685]
> Charging to Kul Tiras Deckhands or Admirals around boats  in durotar consistently result in warriors falling through the floor and chilling in the boat under the sea bed

.go xyz 208.492000 -5248.590000 -10.272900 1 3.056890

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6681
