### ISSUE TITLE
Dark Iron Deposits are non-interactable. You can't even get a to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5692]
> Dark Iron Deposits are non-interactable. You can't even get a tooltip when you mouse over them.

.go xyz -6801.230000 -1796.530000 256.857000 0 3.178610

**Comment by Shadownflame** [comment]
There are some non-interactable nodes here but need to confirm what exactly they are supposed to be.

**Comment by Bennylavaa** [comment]
confirming this as it looks weird seeing their object it just named "Dark Iron" where the true ones are named "Dark Iron Deposit" I also do not see any special quests for the "Dark Iron" one

**Comment by Shadownflame** [comment]
I found just a single interactable dark iron deposit in the whole zone, it seems that most of the outer world spawns are entirely missing or are in this bugged state. Now that pooling is fixed, there is no excuse to find only a single node on a completely empty server.

Also, the node in question is in a spot where I can't seem to reach without GM hacks:
![WoWScrnShot_093024_145252](https://github.com/user-attachments/assets/3a7fb905-39ac-4889-8dca-d9f58a2340f8)

Burning steppes has a single interactable node as well, that's at least within reach.

**Comment by kaytotes** [comment]
Adding testing, should be resolved.

**Comment by Bennylavaa** [comment]
fixed
