### ISSUE TITLE
kul'tiras deckhand (underwater mob) paths UNDERGROUND when pulli...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5696]
> kul'tiras deckhand (underwater mob) paths UNDERGROUND when pulling him. not sure if specific to this mob or just underwater mobs in general

.go xyz -373.475000 -5232.010000 -1.545650 1 5.946150

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
