### ISSUE TITLE
Pirate Lord in Baradin hold doesnt drop loot/give achievement pr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5697]
> Pirate Lord in Baradin hold doesnt drop loot/give achievement progression, and is still pretty overtuned but we managed to kill it

.go xyz 83.534400 -382.890000 -7.776580 731 6.076380

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1254
