### ISSUE TITLE
BOSSES DONT DROP LOOT IN SCHOLOMANCE MOST OF THE TIME REEEEEEEEEE

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5699]
> BOSSES DONT DROP LOOT IN SCHOLOMANCE MOST OF THE TIME REEEEEEEEEE

.go xyz 158.401000 0.159288 75.554300 289 6.197940

**Comment by zana244** [comment]
Welcome to vanilla
