### ISSUE TITLE
Mining node spawns are out of hand, at some spots there are so m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5736]
> Mining node spawns are out of hand, at some spots there are so many nodes like 7 next to each other. I am talking about Rich Thorium Veins

.go xyz -7245.510000 -1465.890000 -227.385000 1 2.033630

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6634
