### ISSUE TITLE
So, for the quest "The Earth Mother Provides" I think the Dark W...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5738]
> So, for the quest "The Earth Mother Provides" I think the Dark Whispers are very overtuned probably to keep people away before 60, but as a lvl 60 prot paladin with 55% reduced physical damage taken they do an avarage of 300 dmg and I am barely able to kill them with 1 immunity + heal to full. I corpse runned the stuff u need from the cave by stunning the nearest Dark Whisper and looting them. And if these racial quests are meant to be soloable they have way high dmg and health.

.go xyz -858.225000 -846.134000 9.530010 1 0.159674

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7585
