### ISSUE TITLE
The Art of Golemacy, the golem takes like 2  minutes to kill 1 m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5742]
> The Art of Golemacy, the golem takes like 2  minutes to kill 1 mob idk feels too slow for me for the type of quest it is.

.go xyz -8021.480000 -2235.550000 133.748000 0 5.197960

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
