### ISSUE TITLE
NO DEAD BODY ON MINIMAP DONT KNOW WHERE TO GO TO GET THE BODY

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5752]
> NO DEAD BODY ON MINIMAP DONT KNOW WHERE TO GO TO GET THE BODY

.go xyz 1677.350000 -5366.490000 73.612200 0 5.403410

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
