### ISSUE TITLE
Mages don't seem to have their base melee crit values from agili...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5756]
> Mages don't seem to have their base melee crit values from agility. my 33 agility says I should have 4.91% but the melee sheet says 0. My weapon skill is maxed.

.go xyz 1881.570000 -4547.430000 28.504500 1 6.097000

**Comment by Shadownflame** [comment]
This seems to be a boosting side effect, the numbers on your sheet don't update until you relog.
