### ISSUE TITLE
the fires keep bugging out on drakki sometimes when we stand in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5759]
> the fires keep bugging out on drakki sometimes when we stand in the safe zone the area damage is ticking anyway for a good 2k damage every 3seconds even though we should be protected

.go xyz 95.075100 -303.862000 63.134600 229 4.712380

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/873
