### ISSUE TITLE
Vendor npc "Joshua Maclure" is selling alcaholic drinks for no m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5761]
> Vendor npc "Joshua Maclure" is selling alcaholic drinks for no money.

.go xyz -10006.400000 64.439300 34.842500 0 3.201750

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/3da4349c-9e90-43d0-92a5-5b70e22d6e13)

**Comment by Shadownflame** [comment]
Affects every vendor who sells alcohol, item issue. Items already reported i.e. https://github.com/Project-Epoch/bugtracker/issues/1447
