### ISSUE TITLE
Tainted Vitriol are only supposed to be gotten from mining in fe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5765]
> Tainted Vitriol are only supposed to be gotten from mining in felwood while having the cenarion beacon in your inventory, but i'm getting it from all thorium nodes in the world

.go xyz 2140.860000 -1502.250000 71.699000 0 3.219250

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1581
