### ISSUE TITLE
Switching between 2H and 1H+shield does not work correctly if th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5770]
> Switching between 2H and 1H+shield does not work correctly if this is done with a stance change. macro:
#showtooltip Spell Reflection
/cast Defensive Stance
/cast Spell Reflection
/equip Dal'Rend's Sacred Charge
/equip Draconian Deflector
The 1H weapon + shield is equiped and the stance is changed on the first click. However, the shield gets then removed so that you have to click the macro again.
This only happens when the stance is changed. Without stance changing it works.
HUGE Warri PvP BUG:o

.go xyz 1570.890000 -4423.090000 6.881290 1 0.545806

**Comment by Shadownflame** [comment]
I can't reproduce this. Macro does exactly what it should, shield doesn't get randomly removed.
