### ISSUE TITLE
Hey! i cant ress. did a UBRS before and logged out while i was d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5771]
> Hey! i cant ress. did a UBRS before and logged out while i was dead. did try run in inside again but i cant enter. did try make a group a try again but wont work. now im running to thorium point and standing were the spirit healer should be but its now visible for me. i have try the auto-unstuck but no luck with that aswell.

.go xyz -7575.500000 -1308.820000 284.669000 0 5.574730

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8292
