### ISSUE TITLE
Quest Forsaken Looters seems like it has a strange number of mob...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5781]
> Quest Forsaken Looters seems like it has a strange number of mobs to kill, it asks for 5 seekers 5 herbalists and 10 thugs. but there are only 6 thug spawns in the whole area.

.go xyz 3775.450000 -138.774000 1.266540 1 0.689639

**Comment by Bennylavaa** [comment]
there are only 6 but I dont see this as a problem seeing there are tons of mobs in this same area to kill while waiting for respawns. Will make this as intended can reopen if we need to address.
