### ISSUE TITLE
Quest Brightwater Lake for Rogues has the Quest Header 'Brightwa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5782]
> Quest Brightwater Lake for Rogues has the Quest Header 'Brightwater Lake' when it should have the Header 'Rogue' as it is a class quest.

.go xyz 9790.410000 945.916000 1308.780000 1 4.378990

**Comment by Shadownflame** [comment]
There is no quest "Brightwater Lake" in the game.
