### ISSUE TITLE
The breath meter started, and i'm not underwater...i'm slightly ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5786]
> The breath meter started, and i'm not underwater...i'm slightly near water though but definitely on ground.

.go xyz -1481.200000 2680.190000 77.371900 1 6.115080

**Comment by zana244** [comment]
Confirmed on internal, breathing starts when you are on the ground.

**Comment by kaytotes** [comment]
Ancient core bug that has a bounty. Workaround, jump to reset breath bar. Downgrading.

**Comment by sogladev** [comment]
fixed with https://github.com/Project-Epoch/TrinityCore/commit/dfd2d80bfbbd6626dcb2b153fa3b7e7708d3bfd8
