### ISSUE TITLE
Enchant Cloak - Resistance +3, does not work on Aspirant's Cloak...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5789]
> Enchant Cloak - Resistance +3, does not work on Aspirant's Cloak of Magic Accuracy.
Error: character says, "I can't use that.

.go xyz 1613.400000 -4394.880000 10.273700 1 2.358160

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4420
