### ISSUE TITLE
Warrior. If i have rage for heroic strike (15+ rage) in out of c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5791]
> Warrior. If i have rage for heroic strike (15+ rage) in out of combat, after press ability "heroic stkire" i get 1-2 rage for 0.5 secs.
For examle:
i have 20 rage - press HS - i have 21-22 rage

.go xyz -6272.040000 291.745000 382.094000 0 4.245280

**Comment by zana244** [comment]
WTF. Confirmed on internal? Spamming heroic strike / cleave makes you lose rage slower??
Also, it seems Anger Management talent works without speccing into it?

Rage seems a bit wonky, not sure if you need to spam the strikes first to induce the strange rage decaying.

**Comment by kaytotes** [comment]
https://github.com/user-attachments/assets/d82bd3db-a3cd-4cd9-854e-9109608b87d1

Can not replicate on internal any more. Various changes to power regen and spells since this was first reported and confirmed.
