### ISSUE TITLE
At my location, there is an oil spill that is under the water. I...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5793]
> At my location, there is an oil spill that is under the water. I don't have coords unfortunately but hopefully this bug  shows it :)

.go xyz -7139.950000 -4927.340000 -3.438500 1 3.982760

**Comment by zana244** [comment]
#2234 Not really a bug but I guess oil floats in wow too? :)

**Comment by Bennylavaa** [comment]
going to close this one and put in with the nodes same sort of fix.
