### ISSUE TITLE
Got 5 stacks of Mountain's Might and unleashed SoM, then used So...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5800]
> Got 5 stacks of Mountain's Might and unleashed SoM, then used SoC to continue fighting, when Mountain's Might was getting low, I switched to SoM but Judgement was no longer available to use.

.go xyz -8130.130000 -1266.920000 137.111000 0 2.395780

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2993 probably same issue, should be fixed since last update
