### ISSUE TITLE
in dual spec learn window, NPC still mentions Glyphs

"Dual Spec...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5801]
> in dual spec learn window, NPC still mentions Glyphs

"Dual Specialization allows you to keep two active Class Specializations, Talent, and Glyph sets

.go xyz 1980.490000 -4800.780000 55.797500 1 4.196320

**Comment by Shadownflame** [comment]
Non issue, cosmetic glyphs do exist, or will, on Epoch.
