### ISSUE TITLE
Dark Iron Slaver - (5844)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#581]
> Net only lasts 1 sec
`.go xyz -6527.040000 -1350.150000 208.890000 0 2.001190`

> Seems not to drop the quest related Item "Slaver's Record" from the quest "Do Slavers Keep Records?
`.go xyz -6849.600000 -1368.140000 170.456000 0 4.195290`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
