### ISSUE TITLE
Priest - Dual talents:
When having Lightwell talent in Holy, the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5810]
> Priest - Dual talents:
When having Lightwell talent in Holy, then respecing to Shadow, Lightwell rank 2 and 3 stays in spellbook (even without the talent active).

.go xyz -8834.160000 636.328000 94.447300 0 0.513305

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7244
