### ISSUE TITLE
Seal of Vengeance doesn't seem to be in a good spot. 

5 stacks ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5812]
> Seal of Vengeance doesn't seem to be in a good spot. 

5 stacks of seal of vengeance does about 33% less damage than my seal of righteous swings on a weapon that swings faster than the tick rate.( I have no talents in improve righteous)

There is no on hit procs for additional damage at max stacks.

Stacks clear on judgement.

Judging the seal does about 40% of the damage of if you just let the dot tick off.

.go xyz 2915.130000 -823.637000 160.327000 0 3.490660

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2991
