### ISSUE TITLE
Ringo doesnt let me hand in my quest.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5819]
> Ringo doesnt let me hand in my quest.

.go xyz -7196.500000 -1388.010000 -231.667000 1 1.811860

**Comment by Shadownflame** [comment]
Might be related to https://github.com/Project-Epoch/bugtracker/issues/7733

**Comment by Bennylavaa** [comment]
@Shadownflame see comment I left on 7733 it is most likely related. I am going to dupe this seeing if a player starts the event and leaved him passed out or logs out he will not be interactible.
