### ISSUE TITLE
Inferno Elemental - (5852)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#582]
> I can cast serpent sting on this. Elements should be immune to poison, aren't they?
`.go xyz -6723.290000 -1003.550000 241.730000 0 3.283290`

> Not all Fire Elementals in Searing Gorge drop the items for "Fit for a King" quest. e.g. Inferno Elementals
`.go xyz -6944.730000 -1235.030000 144.382000 0 1.324570`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2268
