### ISSUE TITLE
Im able to accept the quest Venomhide Eggs, withouit doing the P...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5820]
> Im able to accept the quest Venomhide Eggs, withouit doing the Prerequisite quest. also, i cant actually loot the eggs required for the quest.

.go xyz -7525.540000 -1900.850000 -275.737000 1 3.759700

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
