### ISSUE TITLE
realm time is doing wonky stuff. Local time is 11:06 and realm t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5822]
> realm time is doing wonky stuff. Local time is 11:06 and realm time is 09:54

Im in CET, so the hour difference is normal,

but the 12 minutes seem weird

.go xyz 2547.510000 -2893.750000 160.350000 1 1.807720

**Comment by Shadownflame** [comment]
Local time is showing your own device's time setting. This person hasn't set their clock right.
