### ISSUE TITLE
The quest Kyle's gone misssing. You feed the dog but dont get th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5832]
> The quest Kyle's gone misssing. You feed the dog but dont get the completion credit

.go xyz -2356.380000 -447.680000 -6.302940 1 0.581332

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/05fe8110-fd72-40f6-b224-1b3a15ced93d)
