### ISSUE TITLE
the brotherhood of thieves quest dosent work right you cant do c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5841]
> the brotherhood of thieves quest dosent work right you cant do close range combat as a hunter not sure if it is that way with all charcters or not.

.go xyz -8957.530000 -277.363000 74.759900 0 4.226990

**Comment by zana244** [comment]
level 1 hunter can kite level 4 mobs easily, GG.
should work better now that water interactions have been improved.
