### ISSUE TITLE
The mage, at the moment of going invisible (after 5 seconds), re...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5842]
> The mage, at the moment of going invisible (after 5 seconds), removes the invisibility buff from other mage (or mages?) within a radius of approximately 100 meters.

.go xyz 6691.160000 -4669.570000 721.611000 1 3.085790

**Comment by zana244** [comment]
Tested on internal with Shadownflame, ability works as intended. You are able to see other invisible people if you are invisible, the buff does not get removed.
