### ISSUE TITLE
GCDs are slightly off for mage, extra half-second on arcane expl

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5849]
> GCDs are slightly off for mage, extra half-second on arcane expl

.go xyz -8829.100000 641.701000 94.411900 0 1.617620

**Comment by Shadownflame** [comment]
Don't think this is a mage or Arcane Explosion issue. It feels like the old private server GCD bug that affects most instant casts and basically triggers some kind of a failed cast if you time the spell wrong due to latency/fast spam. More info needed.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6618
