### ISSUE TITLE
Just encountered a Blood of Heroes in the plaguelands guarded by...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5860]
> Just encountered a Blood of Heroes in the plaguelands guarded by two Fallen Hero elite mobs, these mobs shouldn't spawn before someone has tried to loot the blood and should despawn again once it has been taken or left.

.go xyz 1763.880000 -1834.310000 69.205300 0 6.179300

**Comment by zana244** [comment]
#932
