### ISSUE TITLE
The Wall of Flame ability used by Scinti <Stoker of the Flames> ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5861]
> The Wall of Flame ability used by Scinti <Stoker of the Flames> in the deadmines works as a physical attack, you can parry it, I do not know if that is intended or if it should be a spell, but it looks like it should be a spell.

.go xyz -663.686000 141.773000 -102.010000 725 4.872650

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5040
