### ISSUE TITLE
When in the Wetlands on the small boat that takes you from South...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5863]
> When in the Wetlands on the small boat that takes you from Southshore to the Wetlands, I used the spell "Teleport: Stormwind". The expected behavior is that I end up inside the Wizard's Sanctum in Stormwind.

The unexpected behavior I encountered instead was that I ended up under the world outside of Stormwind.

.go xyz -9015.280000 883.660000 29.621400 0 2.250000

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8201
