### ISSUE TITLE
I'm convinced at this point that Mother Tessa for quest Wanted: ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5868]
> I'm convinced at this point that Mother Tessa for quest Wanted: Mother Tessa doesn't actually respawn at all. if it does, it's respawn is over 24 hours

.go xyz -5239.630000 -3275.560000 295.036000 0 3.191560

**Comment by Bennylavaa** [comment]
has a 5 min respawn.
