### ISSUE TITLE
During taming beast quest my boar got stuck in a tree. Can't aba...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5872]
> During taming beast quest my boar got stuck in a tree. Can't abandon him - he is displayed as dead and also prevents from taming next pet in the chain

.go xyz 749.325000 -5025.540000 9.222450 1 5.733920

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
