### ISSUE TITLE
I have found a hole in the world at Tol Barad, it is on the left...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5877]
> I have found a hole in the world at Tol Barad, it is on the left-hand side of the short cave corridor where you land from the flightmaster at Tol Barad and can be accessed by climbing the rocks that creates the cave opening.

.go xyz -4621.170000 -919.027000 502.004000 0 4.222140

**Comment by zana244** [comment]
#7871 can only assume it's the same spot.
