### ISSUE TITLE
Cthun voice elwynn away from the creepy kids house. Was fishing ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5893]
> Cthun voice elwynn away from the creepy kids house. Was fishing in Crystalsong and got it

.go xyz -9437.850000 -78.169700 58.120000 0 4.200220

**Comment by Bennylavaa** [comment]
At 7:00am server time, the children will spawn and leave the house, running all the way to the [Valley of Heroes](https://wowpedia.fandom.com/wiki/Valley_of_Heroes) in Stormwind City, then to Goldshire, up the road toward [Northshire Abbey](https://wowpedia.fandom.com/wiki/Northshire_Abbey) to where the river meets [Mirror Lake](https://wowpedia.fandom.com/wiki/Mirror_Lake), and back to their house. They go up to the second floor and stay in a circular formation, and each time they reach a destination, they stop for approximately ten minutes to shift and move around, pointing in different directions.

Cameron is always in the middle, while Dana is always in the front. When they stand still, the children orbit around Cameron. Once the children finish their rounds at around 7:40am, they return to their room once again. Spooky music and sounds and voices plays, and the children despawn at 8:00pm. The sounds include a [banshee](https://wowpedia.fandom.com/wiki/Banshee) scream, a [ghoul](https://wowpedia.fandom.com/wiki/Ghoul) call, [C'Thun](https://wowpedia.fandom.com/wiki/C%27Thun) saying "You... will... DIE!" and "Death is close". In the grass to the southwest of the house, two tiny skulls can be found.
