### ISSUE TITLE
Adept's Elixir - Increases Critical Strike raiting by 24. This w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5901]
> Adept's Elixir - Increases Critical Strike raiting by 24. This was TBC value (strike raiting), should be converted to crit %.

.go xyz 42.722000 -3863.290000 75.559800 1 3.169720

**Comment by Shadownflame** [comment]
The elixir itself is a TBC one that won't be in the game on live.
