### ISSUE TITLE
fishing followup: problem seems to exists when recasting before ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5902]
> fishing followup: problem seems to exists when recasting before previous fishing cast has ended. i.e. if i cast quickly after not looting or casting quickly after looting, the problem appears. i dont believe it is a lag issue but a timing issue: previous cast should end before the next cast is made

.go xyz 3348.570000 1067.440000 1.001840 1 2.198520

**Comment by Bennylavaa** [comment]
if they are talking about the bobber lingering this is normal its also a good anti botting measure.
