### ISSUE TITLE
fishing pole casting animation very erratic at low levels. perha...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5903]
> fishing pole casting animation very erratic at low levels. perhaps at fishing levels much lower than required fishing level for the zone.  once fishing is leveled up a bit it seems to normalize. 

detected on 2 chars: one in Ratchet and another at Zoram'gar Outpost

.go xyz 3374.190000 1071.720000 0.687646 1 1.633810

**Comment by Bennylavaa** [comment]
cannot reproduce this
