### ISSUE TITLE
chen's empty keg, the barrens,  orc hunter...
I collected 5 plai...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5904]
> chen's empty keg, the barrens,  orc hunter...
I collected 5 plainstrider kineys for the quest and pur them in the bank. when i kill  plainstriders they still drop kidneys and should not

.go xyz -227.181000 -2078.710000 95.359800 1 5.782350

**Comment by zana244** [comment]
could not reproduce on internal, possibly solved by vmangos loot update.
