### ISSUE TITLE
Orc hunter: orgrimmar...when completing Training the Beast quest...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5905]
> Orc hunter: orgrimmar...when completing Training the Beast quest I did not recieve the beast training skill in spellbook

.go xyz 2105.760000 -4622.460000 58.439400 1 0.720006

**Comment by zana244** [comment]
intended, due to wotlk client pet doesn't have vanilla/tbc pet learning capabilities. the talents replace the beast training ability.
