### ISSUE TITLE
Chromie is nowhere to found in the Ruins of Andorhal. Nor Araj. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5912]
> Chromie is nowhere to found in the Ruins of Andorhal. Nor Araj. Nothing tells me that I should be looking for them somewhere else. And I have for example a quest telling me, that Chromie is in the north western part of the Ruins of Andorhal (quest name: A Strange Historian). Also I have quests telling me, that Araj is to be found in the center of Andorhal, but he is not there (quest names: Alas, Andorhal; Araj's Scarab).

.go xyz 1381.160000 -1300.840000 70.299300 0 4.448010

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2107
