### ISSUE TITLE
The Art of Golemancy" not working. Tried killing scorpids, worgs...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5913]
> The Art of Golemancy" not working. Tried killing scorpids, worgs, orcs, drakes, dwarves, like almost anything, but nothing will progress this quest, while I'm with the golem.

.go xyz -8020.870000 -2235.860000 133.749000 0 0.383845

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
