### ISSUE TITLE
Do Slavers Keep Records?" quest - killed like 20+ Dark Iron Salv...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5916]
> Do Slavers Keep Records?" quest - killed like 20+ Dark Iron Salvers, no drop. And the tooltip in the bottom right corner doesn't shows me, that they would drop the item, although the quest text tells it very specificly that I need to kill those. The tooltip is working for other custom quests though

.go xyz -6711.120000 -1371.580000 211.595000 0 3.840460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
