### ISSUE TITLE
Sometimes my pet seems to stuck. Must be some pathing issue. Cur...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5919]
> Sometimes my pet seems to stuck. Must be some pathing issue. Currently I'm in Feralas inside The Writhing Deep.

.go xyz -5358.110000 299.918000 22.392800 1 4.229840

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
