### ISSUE TITLE
Heartrazor - (5934)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#592]
> This creature patrols a route neccesary for the escort quest Homeward Bound, and is too strong to reliably solo. Please adjust the place where this creature spawns.
`.go xyz -5150.820000 -1198.760000 52.571700 1 2.088470`

> no loot too
`.go xyz -5192.850000 -1187.440000 45.862100 1 3.791770`

**Comment by zana244** [comment]
based. loot solved by vmangos update
