### ISSUE TITLE
Item: Crudely-written Log
Location: Winterspring
Issue: This ite...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5922]
> Item: Crudely-written Log
Location: Winterspring
Issue: This item drops off the high cheif i belive of rhe East furbolg camp in winterspring. It begins a quest but when i use the book to get the quest it says I dont meet the requirements for the quest.

.go xyz 1626.280000 -4424.240000 14.249700 1 2.586290

**Comment by zana244** [comment]
#1602
