### ISSUE TITLE
NPC: Marius Hedrin
Location: Winterspring, Everlook Inn
Issue: T...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5923]
> NPC: Marius Hedrin
Location: Winterspring, Everlook Inn
Issue: This could be a client issue, but on my screen she has a night elf model but has a human male skin stretched acrost the nightelf features!? it is very humerous to look at but clearly incorrect.

.go xyz 6691.940000 -4663.010000 721.583000 1 2.400420

**Comment by zana244** [comment]
#1378
