### ISSUE TITLE
Minor issue
Quest: The Fizz
The quest text describes him giving ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5924]
> Minor issue
Quest: The Fizz
The quest text describes him giving you a device coverd in buttons and asks you to get hit by lightning breath 8 times to charge it. I thought there was a bug because there was no such quest item in my bag. The quest gave me credit for geting hit by lightning breath, but might want to consider adding some sort of quest item or altering the text of the quest alitte :)

.go xyz 6424.210000 -4844.950000 716.373000 1 2.365200

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7599
