### ISSUE TITLE
Minor Issue
Quest: Root of the Issue
This quest is properly mark...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5925]
> Minor Issue
Quest: Root of the Issue
This quest is properly marked as a Dungeon quest but is incorrectly catagorized as a Burning Steppes quest instead of a Blackrock Depths quest.

.go xyz -8049.130000 -2287.340000 133.280000 0 5.817750

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5415
