### ISSUE TITLE
Quest: A Little Help From My Friends
Zone: Ungoro Crater
NPC: Ri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5927]
> Quest: A Little Help From My Friends
Zone: Ungoro Crater
NPC: Ringo

Issue: It appears if somone starts this escort quest but dosent finish it when the NPC passes out. the passed out npc never despawns which means the starting quest NPC never respawns to complete the previous quest Lost!

.go xyz -6877.590000 -1093.580000 -274.893000 1 0.811299

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7733
