### ISSUE TITLE
warlock's summons does not follow me properly. Sometimes they "d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5936]
> warlock's summons does not follow me properly. Sometimes they "don't know" how to follow, how to find the way when you jump from a wall or something and just dissapear,

.go xyz -5787.850000 -2634.190000 322.975000 0 3.703970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
