### ISSUE TITLE
lvl 12 in Dun Morogh. These Carts that provide fast free travell...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5937]
> lvl 12 in Dun Morogh. These Carts that provide fast free travelling in starting areas are too fast to catch em. You can get in only if you stay on the road and click in the right momemt. Maybe it is good to make distance from which you can get in bigger.

.go xyz -5504.950000 -1013.890000 393.089000 0 0.640061

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6859
