### ISSUE TITLE
The ` button does not save when set on keybind.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5973]
> The ` button does not save when set on keybind.

.go xyz 9870.570000 879.919000 1308.930000 1 5.081770

**Comment by Shadownflame** [comment]
Sounds like some keyboard shenanigans, I don't even have such a key.

**Comment by Bennylavaa** [comment]
everyone should have the ` key its the same one for ~ usually next to the number 1

also tested it on my end and it binds just fine, sounds like the person that reported this wasnt reloading the ui or closing the client by logging out and quitting the game for it to properly write to the wtf folder.
