### ISSUE TITLE
Baradin Hold retaliation mechanics on every mob and the last bos...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5975]
> Baradin Hold retaliation mechanics on every mob and the last boss and his two adds is very unfun to play into.  Especially in a melee-heavy group.  Can't imagine running this in anything less than Pre-raid bis or raid gear.

.go xyz 73.217000 -387.644000 -7.776130 731 0.140713

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1254
