### ISSUE TITLE
Hello! Solid Chest, or any chests in game 100% must contain at l...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5976]
> Hello! Solid Chest, or any chests in game 100% must contain at least one green item or/and recipe. Sometmes more than one green, sometimes blue + green. But green or green reciept is 100%. I loot around 15 chests and not found even one green item, just few reciepts.

.go xyz -69.521600 -4174.210000 119.955000 0 3.268230

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249
