### ISSUE TITLE
Firemane Scalebane in Dustwallow Marshed "The Den of Flame" cons...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5989]
> Firemane Scalebane in Dustwallow Marshed "The Den of Flame" constantly casts "Fire Shield" when in fight.

.go xyz -4388.190000 -2928.380000 24.641800 1 1.102600

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8051
