### ISSUE TITLE
Several poisons are reported as "Junks" for rogues. Specifically...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5994]
> Several poisons are reported as "Junks" for rogues. Specifically, Mind-numbing Poison III (which cannot be used), Crippling Poison II and Mind-numbing Poison I

.go xyz -4638.300000 -1132.090000 506.701000 0 3.208590

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6687
