### ISSUE TITLE
The tauren racial knowledge (perhaps all racial knowledge in gen...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5997]
> The tauren racial knowledge (perhaps all racial knowledge in general?) doesn't seemt to swap properly. I play a night elf druid and having changed to Tauren knowledge, I'm still benefting from the night elf Touch of Elune passive instead of the Tauren Endurance passive. But I can also use the tauren stun ability instead of Shadowmeld...

.go xyz 9698.800000 2574.310000 1335.680000 1 5.569980

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2953
