### ISSUE TITLE
Azuremyst & Bloodmyst Isles from TBC still appear on the Kalimdo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#5999]
> Azuremyst & Bloodmyst Isles from TBC still appear on the Kalimdor flightpath map.

.go xyz 8642.180000 842.317000 23.276700 1 4.539060

**Comment by Shadownflame** [comment]
There is already a confirmed issue on this by ktotes, i'll merge them. https://github.com/Project-Epoch/bugtracker/issues/8266
