### ISSUE TITLE
Twilight Hammer Ambassadors in Emperor room in BRD bug out when ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6002]
> Twilight Hammer Ambassadors in Emperor room in BRD bug out when they run down to defend him. They are invulnerable and don't participate in combat. They get you stuckin combat.

.go xyz 1379.540000 -740.902000 -92.721700 736 4.849880

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095 related

**Comment by Shadownflame** [comment]
NPC ID 8915

![WoWScrnShot_070724_225441](https://github.com/Project-Epoch/bugtracker/assets/172074323/33f74293-1740-4447-a118-844ac4746c6f)

**Comment by kaytotes** [comment]
Next deploy.
