### ISSUE TITLE
Hazzas & Morphaz still do not spawn in Sunken Temple. The recent...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6005]
> Hazzas & Morphaz still do not spawn in Sunken Temple. The recent patch yesterday claimed to have fixed this bug, but we just did a full clear of the entire dungeon once again and they failed to appear.

.go xyz -659.735000 69.022500 -90.833600 109 4.729290

**Comment by zana244** [comment]
#8310
