### ISSUE TITLE
With all four altars of blood in use in Sunken Temple, the Avata...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6008]
> With all four altars of blood in use in Sunken Temple, the Avatar of Hakkar encounter fails to begin.

.go xyz -632.171000 93.413800 -90.856100 109 3.286310

**Comment by zana244** [comment]
#8310

**Comment by kaytotes** [comment]
I strongly suspect they just misunderstand how this works. You still need the normal means to spawn him eg the egg but once spawned you give him blood. Tested many times since instance rework and all fine.
