### ISSUE TITLE
Flightpath from Swamp of Sorrows to Stormwind (Alliance) has you...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6011]
> Flightpath from Swamp of Sorrows to Stormwind (Alliance) has you fly through the terrain of the world.

.go xyz -9387.660000 -2199.610000 71.438400 0 0.701729

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
