### ISSUE TITLE
The Ancient Batteries for the quest at Noonshade Ruins in Tanari...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6016]
> The Ancient Batteries for the quest at Noonshade Ruins in Tanaris are bugged and respawn insanely slowly. I saw one in a half hour period.

.go xyz -7020.610000 -4466.890000 9.281760 1 3.082610

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
