### ISSUE TITLE
The quest "Wild Tulip" in Booty Bay has a diary book called "Alw...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6019]
> The quest "Wild Tulip" in Booty Bay has a diary book called "Always Yours" with a typo. On the second page the sentence reads "We made it so Plunder Isle though." Presumably, the dev meant to type "to" instead of "so" to make it "We made it to Plunder Isle though.

.go xyz -14395.800000 419.012000 7.773050 0 2.651860

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
