### ISSUE TITLE
Shadowsworn Thug - (6005)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#602]
> Missing the tooltip info about looting quest item "Bundle of Cultists Writings" (id 63326).

Same for Cultist and Adept.
`.go xyz -11548.800000 -3349.570000 15.747200 0 1.515070`

> Like other enemies they insta kick casts, and have no cd on kick
`.go xyz -11330.600000 -3429.910000 7.668620 0 1.204560`

**Comment by Bennylavaa** [comment]
that is a addon that does the tooltips...
