### ISSUE TITLE
After   taking "Anatomy of the Afterlife"quest in the Sepulcher,...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6022]
> After   taking "Anatomy of the Afterlife"quest in the Sepulcher, I would become an abomination but I did not have his skills on my skill bar. I am a hunter with a pet, and I'm not sure if that is the reason why. The person I ran it with (a druid) did not have issues. Also, I did not get credit for the kill in a group after attempting it twice.

.go xyz 522.583000 1647.350000 125.664000 0 1.364930

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5670
