### ISSUE TITLE
Just learned Eagle Eye and Eyes of the Beast, and even though I ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6023]
> Just learned Eagle Eye and Eyes of the Beast, and even though I know them, I am unable to cast them. When attempting to cast, I get a "The spell is not available to you" message on screen.

.go xyz 10109.000000 2475.090000 1317.200000 1 4.020120

**Comment by Shadownflame** [comment]
Beta settings
