### ISSUE TITLE
According to WoW Bestiary, Sonesplinter geomancers should have f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6025]
> According to WoW Bestiary, Sonesplinter geomancers should have flame strike ability. Certainly, it seems weird for them to hve just flame ward.

.go xyz -5656.410000 -3900.010000 323.449000 0 5.215280

**Comment by Shadownflame** [comment]
npc=1165
spell=11829

**Comment by Bennylavaa** [comment]
https://www.youtube.com/watch?v=lrsgUV1BN_I

classic they only cast flame ward.
