### ISSUE TITLE
I previously reported stonesplinter shamans don't have abilities...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6027]
> I previously reported stonesplinter shamans don't have abilities. As it turns out they do have the healing wave listed in WoW Bestiary. However, they don't self-cast it, which also seems like a problem.

.go xyz -4944.610000 -3445.430000 311.748000 0 5.061680

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6028
