### ISSUE TITLE
Curse of Tongues lasts 30 seconds in PvP. Way too long. In patch...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6033]
> Curse of Tongues lasts 30 seconds in PvP. Way too long. In patch 2.1 it was reduced to 12 seconds.

.go xyz 1354.080000 -4423.350000 27.840800 1 0.269353

**Comment by zana244** [comment]
Confirmed while dueling on internal.
https://wowpedia.fandom.com/wiki/Curse_of_Tongues
