### ISSUE TITLE
After completing the Learn to Ride in Elwynn Forest quests, one ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6034]
> After completing the Learn to Ride in Elwynn Forest quests, one of the quests were left in my quest log. It says to return the pamphlet to Randal Hunter, but he does not have any quest interaction, just the riding skill trainer menu.

.go xyz -9441.960000 -1388.620000 46.913300 0 5.443950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3196
