### ISSUE TITLE
Hunter pets in-combat movement speed is not normalized, but base...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6036]
> Hunter pets in-combat movement speed is not normalized, but based on the pre-tamed beast movement speed. I've encountered speeds from a -15% run speed cat (Snow Leopard from Dun Morogh) up to a +43% run speed cat (Moonstalker from Darkshore).

I hope you can normalize this out, since it seems that on every other point Epoch has opted for the normalized pets approach.

.go xyz 5359.480000 282.084000 26.788900 1 6.277420

**Comment by zana244** [comment]
Confirmed on beta 3 and internal. As far as I'm aware, the base speed of all pets should be 114 or 115%, regardless of their initial movement speed as NPCs.
