### ISSUE TITLE
Earthgrab Totem - (6066)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#604]
> Totem does melee attacks.
`.go xyz -8925.000000 -2327.410000 9.816730 1 5.080460`

> Melees the target rather than casting the intended spell.
`.go xyz -8871.280000 -2207.990000 8.903230 1 2.612960`

**Comment by zana244** [comment]
Solved on internal. Same NPC can have multiple totems active.
#554
