### ISSUE TITLE
Charge sent me through the world...again.  A solution similar to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6042]
> Charge sent me through the world...again.  A solution similar to Turtle WoW's REALLY needs to be implemented: Teleport me to the z-coordinate closest to where I began falling if I hit the bottom of the world.

.go xyz -7744.790000 -2152.280000 -4257.580000 0 4.233810

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6681
