### ISSUE TITLE
The quest Silithid Scramble is unbelievably slow to complete, to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6045]
> The quest Silithid Scramble is unbelievably slow to complete, to the point where it is entirely not worth doing.  This is because, as best I can tell, the Centipaar Tunnelers have all of two spawn points in the entire quest area.  Half of the Centipaar Swarmers should be replaced with Tunnelers for this quest to make any sense at all.

.go xyz -6952.200000 -4744.330000 9.141770 1 4.932230

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
