### ISSUE TITLE
The quest Water Co. Saviour's Filter Parts seem to only spawn in...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6046]
> The quest Water Co. Saviour's Filter Parts seem to only spawn in two locations, and even then these two individual parts spawn on a slow timer.  Something seems to be causing the rest of the parts to not spawn at all.

.go xyz -7297.960000 -4230.280000 13.803400 1 5.031590

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
