### ISSUE TITLE
I had a player targeted, who had just died due to being attacked...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6047]
> I had a player targeted, who had just died due to being attacked by guards in Gadgetzan.  The player in question was a Dwarf Shaman.  He used his self-resurrection ability, and upon popping back up, my character's autoattack was activated, causing me to strike the Shaman.  The guards then attacked and killed me (very understandable under the circumstances).  In no way should my character's autoattack be activated in such circumstances.

.go xyz -7202.740000 -3906.650000 9.290690 1 1.823290

**Comment by Bennylavaa** [comment]
sounds like a left click was done while dead this is intended if they were pvp flagged
