### ISSUE TITLE
For the quest The Perfect Fuel, the Ancient Batteries do not see...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6048]
> For the quest The Perfect Fuel, the Ancient Batteries do not seem to be spawning anywhere in the Noonshade Ruins.

.go xyz -9461.280000 -4202.310000 123.163000 1 3.427070

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
