### ISSUE TITLE
Quest "Advanced Alchemt" from the Scholomance Academy quests is ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6063]
> Quest "Advanced Alchemt" from the Scholomance Academy quests is listed in the Quest Log tool as in Elwynn Forest when it's actually located in Western Plaguelands

.go xyz 1744.650000 -1692.810000 59.887300 0 4.889440

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8300
