### ISSUE TITLE
Sandfury Executioner being Mind Controlled still allowed for pla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6065]
> Sandfury Executioner being Mind Controlled still allowed for players who were melee attacking the mob to continue to attack when it should have been seen as an ally

.go xyz 1895.200000 1266.400000 42.923100 209 2.945920

**Comment by Bennylavaa** [comment]
needs at least two people to test

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8273
