### ISSUE TITLE
Quest "Those Unrecovered", paladin class quest, I believe, is no...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6067]
> Quest "Those Unrecovered", paladin class quest, I believe, is not working - I can not turn the quest in. Can not interract with Patrick Mills.

.go xyz 2374.810000 -5964.720000 10.042300 1 6.209230

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2293
