### ISSUE TITLE
Warlock talent "Demon Portal" - If demon portal summons a copy o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6071]
> Warlock talent "Demon Portal" - If demon portal summons a copy of a demon you have already summoned as a pet, your pet stops attacking a mob and runs back,

.go xyz 2051.560000 -4649.410000 55.663600 1 5.758200

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3000
