### ISSUE TITLE
I'm able to craft Fel Iron Plate Gloves (Blacksmithing), but the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6074]
> I'm able to craft Fel Iron Plate Gloves (Blacksmithing), but they require level 61 to use and Fel Iron Bar.

.go xyz 10345.100000 837.932000 1325.920000 1 6.034030

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1689
