### ISSUE TITLE
not sure there should be mobs at the entrace of the tol barad. y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6082]
> not sure there should be mobs at the entrace of the tol barad. you run out and die.

.go xyz -2307.070000 57.619000 30.738700 0 0.027200

**Comment by zana244** [comment]
Actually a pretty valid concern!! Maybe similar to RFK, make the entrance/exit corridor a bit longer so that you don't aggro the mobs as soon as you zone out.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5941
