### ISSUE TITLE
Dark Whisper mobs in the quest The Earth Mother Provides are all...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6095]
> Dark Whisper mobs in the quest The Earth Mother Provides are all categorized as rare mobs and have a substantial amount of health and deal a lot of damage for a non-elite quest.

is this a bug?

.go xyz -813.156000 -1173.650000 151.795000 1 5.407090

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7585
