### ISSUE TITLE
Force of nature (treants) guardian pets have similar issue as de...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6100]
> Force of nature (treants) guardian pets have similar issue as demon portal - they are not willing to attack on their own, when the druid prompts them to attack by landing a spell, they mostly do, but sometimes only 2 out of 3... one treant is often lost in the textures and only pops up if you move around. Overall you never get the full amount of attacks you expect of them

.go xyz -8798.190000 351.820000 101.020000 0 4.587820

**Comment by Shadownflame** [comment]
Resolved with the new treant update. They have a pet bar and are fully controllable.
