### ISSUE TITLE
Demon Portal minions dont have the brain capacity (AI) to go beh...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6104]
> Demon Portal minions dont have the brain capacity (AI) to go behind their target. They will attack from whichever side of the target you summon them and dont adjust if the target turns or moves. This means if they happen to land in front, about 15% of their attacks are getting parried and there is nothing you can do about it

.go xyz 2148.670000 -4632.450000 50.752300 1 0.451004

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3000
