### ISSUE TITLE
Demon Portal imp spawns are using some rank1 version of Firebolt...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6105]
> Demon Portal imp spawns are using some rank1 version of Firebolt which only hits for 30 damage. Max level imp damage should be way higher

.go xyz 2130.500000 -4645.710000 49.035100 1 3.730040

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3000
