### ISSUE TITLE
The orc racial knowledge quest disappeared from my log sometime ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6123]
> The orc racial knowledge quest disappeared from my log sometime after I left Jaina and went to Swamp of Sorrows. I went back to Jaina and can no longer obtain the quest.

.go xyz 9764.800000 2524.500000 1322.130000 1 3.268770

**Comment by Bennylavaa** [comment]
they most likely were on the next part and didnt read what they were turning in
