### ISSUE TITLE
I can use demon skin and fel armor at the same time and i dont b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6124]
> I can use demon skin and fel armor at the same time and i dont believe it is supposed to?

.go xyz -574.992000 -4242.440000 38.100100 1 1.485190

**Comment by Shadownflame** [comment]
I can confirm these two buffs stack right now. Demon Skin is however the low lvl version of Demon armor, so this is not a huge issue, it grants very little stats.
Rank 1 spell ID 687
Rank 2 spell ID 696

**Comment by Shadownflame** [comment]
The two spells no longer stack.
