### ISSUE TITLE
hi been fishing here in azshara and i noticed i get 1 out of 5 n...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6128]
> hi been fishing here in azshara and i noticed i get 1 out of 5 nothing, not even fish escaped or something gray, have 300 fishing nat pagles rod and 75 lure on it so i am at 400 fishing

.go xyz 4139.000000 -7670.110000 1.271890 1 3.573840

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6901
