### ISSUE TITLE
Empowered Arcane Missiles drops the Arcane Blast stacks if you m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6135]
> Empowered Arcane Missiles drops the Arcane Blast stacks if you move-cancel and don't finish casting Arcane Missiles.

.go xyz 2102.380000 -4659.870000 47.264000 1 5.745850

**Comment by Shadownflame** [comment]
I can confirm this is happening but I'm not entirely sure it's wrong behaviour. Some research needed.

**Comment by Shadownflame** [comment]
This is still happening. Missiles doesn't even benefit from the stacks anymore, so it's a little weird that they still consume them at all. With the stacks now synergizing with barrage instead, it would make sense if only barrage consumed them.
