### ISSUE TITLE
i hit the dummy once i got combat for 1 minute

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6136]
> i hit the dummy once i got combat for 1 minute

.go xyz 1984.850000 -4693.430000 24.353900 1 2.869850

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6800

**Comment by Shadownflame** [comment]
Dummies properly leave combat with player after 15sec now.
