### ISSUE TITLE
Innkeeper Janene - (6272)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#615]
> For quest - Escaping Airheart - the reward for such a hard quest was pitiful ... elite mobs that absolutely SMACK, it kinda needs 3 people to do, and only 2.5k xp quest reward + no item
`.go xyz -3618.300000 -4468.150000 14.246000 1 5.331720`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7228
