### ISSUE TITLE
Millhouse's loot cache doesnt despawn and keeps dropping loot.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6154]
> Millhouse's loot cache doesnt despawn and keeps dropping loot.

.go xyz 157.673000 -220.723000 -7.776340 731 4.696540

**Comment by Bennylavaa** [comment]
ah ok, it respawns 5 minutes after looting.

**Comment by kaytotes** [comment]
Fixed in next release so setting to testing now.

**Comment by Shadownflame** [comment]
Doesn't respawn after 5mins anymore.
