### ISSUE TITLE
Q "escaping Airheart" is undoable because escorting npc is not e...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6155]
> Q "escaping Airheart" is undoable because escorting npc is not elite in an elite zone. So, she gets killed very easily. Also player can not heal her and enemy guard npcs have retaliation abillity which kill q giver almost instantly. :)

.go xyz -2866.150000 -2401.810000 211.276000 1 2.592700

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7228
