### ISSUE TITLE
Quest "Reclaiming the Eggs" in Hinterlands isnt working. I cant ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6157]
> Quest "Reclaiming the Eggs" in Hinterlands isnt working. I cant click on the egg objects. :)

.go xyz -244.527000 -3060.620000 130.487000 0 1.620910

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
