### ISSUE TITLE
the poison debuff still makes me able to do Venomhide Poison deb...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6158]
> the poison debuff still makes me able to do Venomhide Poison debuff even when I no longer have the debuff

.go xyz -7099.180000 -2125.850000 -272.054000 1 4.181830

**Comment by Shadownflame** [comment]
The poison lasts only 30sec but the weapon enhancement it applies lasts 5mins. Intended.
![WoWScrnShot_102124_081258](https://github.com/user-attachments/assets/6766a819-656c-41ac-bb7a-92d7bf1b4879)
