### ISSUE TITLE
Hello,

another Pet-related Bug. The Scorpid does not use its po...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6169]
> Hello,

another Pet-related Bug. The Scorpid does not use its poison when already 1 stack applied. So it never gets past its 1 stack.
You can however do it manually and get it stacking.

Cheers

.go xyz -7305.220000 -3501.950000 9.617590 1 5.878570

**Comment by zana244** [comment]
#2844
