### ISSUE TITLE
Seal twisting is not functioning properly by giving the second S...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6172]
> Seal twisting is not functioning properly by giving the second SoR hit after properly seal twisting. the normal weapon swing procs both SoR and SoC however the SoC proc is not benefitting from the twisted seal when you twist OUT of command. in TBC a proper seal twist resulted in a single weapon swing and SoC proc and two SoR or seal of blood etc.. procs.

.go xyz 520.827000 -261.057000 152.285000 0 4.660100

**Comment by zana244** [comment]
#2813
