### ISSUE TITLE
Thunderhead Stagwing - (6377)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#618]
> Group aggros with Mistwing Rogues. Not sure if intended behavior or not.
`.go xyz 2612.590000 -5066.140000 119.467000 1 2.158470`

> Damage on these might be a little overtuned. Even with 63 nature resist, they hit like a truck.
`.go xyz 2583.070000 -4934.930000 135.394000 1 5.242990`

> I've killed a few dozen of these and Undamaged Hippogryph Feathers have not dropped when WoWhead says it's a roughly 40% chance.
`.go xyz 2664.680000 -4988.830000 127.350000 1 2.335630`

> These mobs don't drop the "Undamaged Hippogryph Feather" they are supposed to at the 37% drop rate listed on WoWhead.
`.go xyz 4154.340000 -5329.040000 110.702000 1 0.131967`

**Comment by Bennylavaa** [comment]
see the below, that quest needs to be removed, there is a old beta version and a newer version on the npc 
In WoW Classis 1.13+ these feathers are not need as they are for the master quest which no longer requires these. At least you can still vendor them.
