### ISSUE TITLE
sometimes when shifting out of feral forms. your action bar will...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6184]
> sometimes when shifting out of feral forms. your action bar will show that u can shift back into any druid form and ur action bar will remain in the shapeshifted form, as in still having bear/cat etc abilities.

.go xyz -2916.810000 -326.211000 57.552300 1 2.611490

**Comment by Shadownflame** [comment]
Works fine to me, gotta be addon issue.
