### ISSUE TITLE
mixology" does not scale with the 2% crit portion of the mongoos...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6187]
> mixology" does not scale with the 2% crit portion of the mongoose elixir. This may be a bug, unless Mixology only effects stat increases and spell damage effects.

.go xyz -2925.190000 -260.273000 53.062100 1 4.653470

**Comment by Shadownflame** [comment]
I believe this is because on vanilla stats Hit and Crit chance stats can only scale in 1% increments. 25% of that 2% crit is only half percent crit, which gets rounded down to 0. Not sure if it's possible to change the behavior for this alone @Bunnyblock2

**Comment by ghost** [comment]
Your assumption is correct, its rounding down to 0. There's not really anything we can do about this its working as intended going off of classic logic
