### ISSUE TITLE
Lifebloom's final heal hits for the exact same amount even if th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6188]
> Lifebloom's final heal hits for the exact same amount even if the stacks are different. Lifebloom's final big tick should heal perportional to the stack amounts. 1 stack and 3 stacks shouldnt both hit for like 700 on the final heal. <3

.go xyz 6961.430000 -4568.650000 718.808000 1 5.366760

**Comment by Shadownflame** [comment]
This is the intended behavior for TBC.
