### ISSUE TITLE
Thunderhead Skystormer - (6378)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#619]
> These mobs do not drop Undamaged Hyppogryph Feathers for quest A Meeting with the Master. I can't complete the quest and get back to the Tower.
`.go xyz 4826.390000 -6015.890000 95.561500 1 4.463080`

> FFS the fact I had to look on discord to see that you don't even need to kill these anymore is so dumb. Fix this shit
`.go xyz 4435.880000 -5972.530000 98.388500 1 2.116000`

> MAKE THE DROP RATE INCREASE FUCK THESE HIPPOGRYPHS
`.go xyz 4705.420000 -6439.450000 112.700000 1 3.733920`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2400
