### ISSUE TITLE
It took me 1 hour of farming mobs to finish "Samophlange Manual"...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6205]
> It took me 1 hour of farming mobs to finish "Samophlange Manual" quest in Barrens. Not sure if bug or not, but that is ridiculously low drop rate.

.go xyz 1193.660000 -3596.460000 83.605700 1 3.649890

**Comment by zana244** [comment]
seems solved with vmangos loot update. I managed to get 5/5 just by grinding to the dude which you have to kill in the cave, so I imagine the drop rate got improved.
