### ISSUE TITLE
Probably already ticketed, but there are a lot of mobs / things,...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6225]
> Probably already ticketed, but there are a lot of mobs / things, that keep you infight in BRD. For example the barrel boss in the bar has 2 mobs, who are not attackable and bug out after his death keeping you infight. Also the room of Bael'Gar seems to put you infight keeping you in that state, and the mobs in the emperor room are about 80% bugged, being not even targetable.

.go xyz -8811.560000 609.597000 95.637100 0 5.362880

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095
