### ISSUE TITLE
as far as i experienced there are no dark iron nodes so far to m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6226]
> as far as i experienced there are no dark iron nodes so far to mine. I was stealthing through BRD, went to Searing Gorge, Burning Steps multiple times and there were none.

.go xyz -6795.590000 -1002.620000 247.222000 0 2.365050

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295
