### ISSUE TITLE
Lorekeeper Polkelt in Scholomance has a kind of "special" abilit...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6227]
> Lorekeeper Polkelt in Scholomance has a kind of "special" ability: Volatile Infection.
He will cast it on a random player and after 0.034s it ticks multiple times in the same time stamps until the player is dead.

22:43:29.007 Volatile Infection appllied on Player X
22:43:29.041 VI hits him for 935
22:43:29.041 VI hits him for 740
22:43:29.041 VI hits him for 1085
22:43:29.041 VI hits him for 1137
(from CombatLog)

So you cant do anything. Is this intended?

.go xyz -8822.780000 622.103000 94.070400 0 5.392570

**Comment by zana244** [comment]
Confirmed on internal, insta kill.

**Comment by Shadownflame** [comment]
Resolved.
