### ISSUE TITLE
I recently made a bug report regarding stacking debuffs from ope...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6230]
> I recently made a bug report regarding stacking debuffs from open world mobs. I just recognized, that it seems to be a thing regarding the mobs level. So if the mobs have different levels but the same debuff, it has different ranks, making the debuffs able to stack.

.go xyz 1804.630000 -2242.870000 61.800000 0 5.245040

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6231
