### ISSUE TITLE
dont know if this is considered a "bug", but I recognized that m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6233]
> dont know if this is considered a "bug", but I recognized that material spawns (herbs, ores) seem to have a fixed spawn cd, if you run around for example in Searing Gorge and you completed the route there wont spawn new herbs for a fixed time. since this is a small populated server in beta it seems fine, but I guess with a higher population this could lead to spawn camping meta (happened in twow, too). Maybe just something to think about. Maybe a dynamic spawn rate would help (if possible)

.go xyz -3518.220000 -1185.720000 88.392700 0 0.089450

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295
