### ISSUE TITLE
The mobs coming in with Hurley Blackbreath in BRD at the tavern ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6240]
> The mobs coming in with Hurley Blackbreath in BRD at the tavern are bugged and keep you infight after killing the boss, they are not targetable

.go xyz 903.373000 -143.887000 -49.757500 736 3.538160

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/839
