### ISSUE TITLE
Storm, Earth, Wind and Fire Quest Part 5 in Ungoro: The totem do...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6241]
> Storm, Earth, Wind and Fire Quest Part 5 in Ungoro: The totem doesnt weak the Stone Guardians, they have a debuff but stay strong

.go xyz -7089.800000 -2310.950000 -267.707000 1 6.092330

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2322
