### ISSUE TITLE
Regarding "The Perfect Container" quest in Tanaris, there are ba...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6244]
> Regarding "The Perfect Container" quest in Tanaris, there are barely any Car Parts and the respawn takes very long. Maybe Im just blind, but i only found 3 spots around the Cleanup Crew Area

.go xyz -7039.720000 -3559.780000 10.391800 1 1.311420

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
