### ISSUE TITLE
The quest "The Art of Golemancy" in the Burning Steppes doesnt w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6249]
> The quest "The Art of Golemancy" in the Burning Steppes doesnt work properly, mob kill count does not go up while killing mobs with the golem

.go xyz -8021.170000 -2238.750000 133.745000 0 6.249490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
