### ISSUE TITLE
I completed the quest "A Taste of Flame" and turned it in with t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6250]
> I completed the quest "A Taste of Flame" and turned it in with the Skin of Dragon from the Searing Gorge. Now I cannot take the followup quest for Bael'Gar. With my other character there hasnt been a problem to pick up the follow. Maybe the NPC has some kind of cooldown, where he is unable to give the quest for some reason?

.go xyz -7647.890000 -3047.480000 131.053000 0 2.416800

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/831
