### ISSUE TITLE
Quest "The Perfect Fuel" in Tanaris: The Ancient Batteries at No...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6262]
> Quest "The Perfect Fuel" in Tanaris: The Ancient Batteries at Nonshade Ruins doesn't spawn at all. Did this quest already 2 times, there everything was fine but now there are no quest items here for like 20 minutes straight

.go xyz -6933.740000 -4403.450000 11.871600 1 3.422060

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
