### ISSUE TITLE
nit: The quest "Stillwater Eels" has a few small syntax issues.
...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6268]
> nit: The quest "Stillwater Eels" has a few small syntax issues.

1st paragraph:
"we need to eat <name>" -> "we need to eat, <name>"

2nd paragraph:

tasy -> tasty
"fish me some eel" -> "fish me some eels"
"Bring it back" -> "Bring them back"
I`ll -> I'll

.go xyz 2285.890000 241.115000 34.245100 0 0.131965

**Comment by zana244** [comment]
#2181
