### ISSUE TITLE
Plated Stegodon - (6502)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#627]
> This mob is the target of a quest "The Un'Goro Hunt" The quest is mislabeled as Elwynn Forest
`.go xyz -7414.680000 -930.130000 -270.569000 1 1.847910`

> Once marked by skull or any other mark, the chat text for said mob is messed up.
`.go xyz -7367.010000 -547.026000 -274.725000 1 2.641610`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
