### ISSUE TITLE
When stealthing around mobs, they don't turn to look at you if y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6272]
> When stealthing around mobs, they don't turn to look at you if you get too close.

.go xyz 2039.950000 1852.440000 103.642000 0 4.736970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7344 related

**Comment by kaytotes** [comment]
I tested this a good amount on internal earlier going 1 - 10 on a rogue and they did this many times. Seems fixed.
