### ISSUE TITLE
The Rare spawn "Precipise" has way too much hp/damage for a norm...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6277]
> The Rare spawn "Precipise" has way too much hp/damage for a normal rare spawn

.go xyz -8626.570000 -523.456000 146.783000 0 2.304710

**Comment by Shadownflame** [comment]
I am inclined to confirm this. This mob seems to be balanced as a rare-elite, not a regular rare. The health value and the complex mechanics he uses at level 9 are not a characteristic of a simple rare mob. This might be intended as he is a fairly rewarding kill.
Devs have 2 options here:
1) Mark him as rare-elite if this is supposed to be group-content
2) Nerf his health and reduce the duration of his Water bubble dot (At level 9, no class can counter it as it's a magic effect). 
In comparison, the rare caster Fellicent's Shade has around 270 health at lvl 12. The damage they dish out is similar, but Precipise is 3 levels lower and as such, supposed to be weaker if balanced as a rare.

Note, Precipise's spells currently don't cost any mana and he is chain casting his water shield and water bubble without mercy. Water shield is also not possible to counter at lvl 9 (nobody can purge), which means not only this mob has elite health, he even takes half damage nearly all times.

**Comment by Shadownflame** [comment]
Nothing at all changed about this mob except his level was reduced from 9 to 6. Now his health and damage is even more ridiculous because it was too much for a lvl 9 rare and definitely too much for a lvl 6. He's still not marked as elite.

**Comment by Shadownflame** [comment]
Stats now match those of a rare and it can be soloed.
