### ISSUE TITLE
I'm at the blacksmith trainer and hovering over recipes and rece...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6281]
> I'm at the blacksmith trainer and hovering over recipes and receive an lua error:

Message: Interface\FrameXML\lualib_bundle.lua:2246: bad argument #1 to 'find' (string expected, got nil)
Time: 04/17/24 01:42:42
Count: 11
Stack: [C]: ?
Interface\FrameXML\lualib_bundle.lua:2246: in function <Interface\FrameXML\lualib_bundle.lua:2229>
...ns\project-epoch\mod-player-

.go xyz 1683.900000 285.766000 -61.631000 0 3.391030

**Comment by Bennylavaa** [comment]
this should be fixed now
