### ISSUE TITLE
Ravasaur Hunter - (6507)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#629]
> applies venom to itself
`.go xyz -7418.510000 -2079.720000 -272.043000 1 0.661318`

> venomhide poisoning stacks up on this npc and deals damage to instead of the player.
`.go xyz -7291.520000 -2048.530000 -270.831000 1 5.780530`

**Comment by Bennylavaa** [comment]
this creature doesnt use venmo
