### ISSUE TITLE
Health regeneration after combat is really fast, not sure if its...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6290]
> Health regeneration after combat is really fast, not sure if its supposed to be like this during Beta, but its really fast

.go xyz -8898.820000 -350.458000 71.416200 0 4.814740

**Comment by Shadownflame** [comment]
At low levels it's currently faster than intended, opposite results at high level. Regen is work in progress by Kaytotes.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3782
