### ISSUE TITLE
Logged out as a ghost over 12hours ago, came back - tried to res...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6294]
> Logged out as a ghost over 12hours ago, came back - tried to res at the dungeon portal (Baradin Hold) stuck as a ghost

.go xyz -2443.330000 35.576100 18.376000 0 0.700082

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
