### ISSUE TITLE
Lesser Dalaran Guardians appear to be taking damage from Druid's...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6297]
> Lesser Dalaran Guardians appear to be taking damage from Druid's Thorns while Greater Mana Shield is active - all other damage absorbed.

.go xyz 383.706000 128.589000 42.615900 0 0.741846

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/282
