### ISSUE TITLE
this guys should drop higher lockpicking level junkboxes than wo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6298]
> this guys should drop higher lockpicking level junkboxes than worn junkbox:
wastewanderer thief in tanaris

.go xyz -6921.710000 -4342.000000 11.592500 1 2.748850

**Comment by zana244** [comment]
https://www.wowhead.com/classic/npc=5616/wastewander-thief#pickpocketing
check again.
can also pick pocket it after vmangos update but quite low drop rate.
