### ISSUE TITLE
Bloodpetal Trapper - (6512)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#631]
> Drops Dinosaur Bone (is not supposed to do that).
`.go xyz -6717.400000 -600.645000 -270.641000 1 3.937050`

> are they supposed to drop dinosaur bones?
`.go xyz -6708.100000 -923.672000 -269.359000 1 3.335690`

> Their loottable shouldn't contain "Dinosaur Bone".
Drops "Dinosaur Bone" when killed.
`.go xyz -6571.750000 -912.572000 -272.222000 1 2.959420`

> Drops Dinosaur bones
`.go xyz -6574.440000 -988.922000 -270.500000 1 5.293060`

> Dropped Dinosaur bone?
`.go xyz -6591.720000 -974.616000 -271.482000 1 5.738540`

> These mobs are dropping the 'Dinosaur Bone' quest item. Pretty sure these are not dinosaurs.
`.go xyz -7010.410000 -982.197000 -272.217000 1 5.477730`

> Drops Dinosaur Bone for Roll the Bones quests, and I think it shouldn't be
`.go xyz -6491.320000 -957.866000 -274.662000 1 2.143310`

> they are dropping "Dinosaur Bone" quest item if you are on "Roll the Bones" quest and they are not supposed to be able to drop this item.
`.go xyz -6569.320000 -973.893000 -272.598000 1 0.319608`

**Comment by zana244** [comment]
solved with vmangos update.
