### ISSUE TITLE
In the objective text of the quest "Call of Earth" (dwarf versio...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6312]
> In the objective text of the quest "Call of Earth" (dwarf version), "2 bowls of mojo" is written in lowercase, while quest items should usually be capitalized at all times, like: "2 Bowls of Mojo

.go xyz -6114.770000 397.365000 395.541000 0 0.711902

**Comment by zana244** [comment]
#5500
