### ISSUE TITLE
When an enemy leashes due to distance and runs back to their ori...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6315]
> When an enemy leashes due to distance and runs back to their original spawn point, they sometimes get one parting strike against the target they are chasing, even if they're well outside melee range.

.go xyz 2271.360000 -355.473000 74.680000 0 4.971730

**Comment by zana244** [comment]
I think this was solved during beta 3
https://github.com/Project-Epoch/TrinityCore/commit/3324a583c19264df7033491d58e59a4eb28a6a03
