### ISSUE TITLE
The Shatterspear trolls are not attackable. They were back in va...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6316]
> The Shatterspear trolls are not attackable. They were back in vanilla, for Alliance, but now they're friendly.

.go xyz 1754.920000 -1631.050000 62.089800 0 3.374120

**Comment by Shadownflame** [comment]
This is custom change as these NPCs are subject to the troll racial swap quest chain now, which requires alliance to interact with these mobs.
