### ISSUE TITLE
Mobs pathfinding

Noticed when I AoE farmed as a mage: mobs will...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6318]
> Mobs pathfinding

Noticed when I AoE farmed as a mage: mobs will remember the last position your character was and will walk to that first, rather than their combat target's position.

Mobs should always find the shortest path towards their combat target.

.go xyz -8824.320000 642.515000 94.281400 0 2.161080

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
