### ISSUE TITLE
My character is not in combat, nor within melee range of anythin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6325]
> My character is not in combat, nor within melee range of anything to hit, yet he is trying to Auto Attack. When I proceed to get within melee range he does not attack. Reloading my UI has done nothing to fix it. According to World chat relogging fixes the issue. Thank you.

.go xyz -5319.460000 349.526000 396.068000 0 1.627460

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892
