### ISSUE TITLE
Paladins can cast 2 greater blessing buffs on the same person.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6326]
> Paladins can cast 2 greater blessing buffs on the same person.

.go xyz -7964.950000 -1697.850000 137.923000 0 4.690720

**Comment by Shadownflame** [comment]
GBOM, GBOW, and GBOK (spell ID 25782, 25894, 25898) are exclusive, but GBOSanct and GBOSalv (Spell ID 25899, 25895) stack with any of them and also with each other.
