### ISSUE TITLE
there is a hole near the entrance cave of tol  barad behind the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6334]
> there is a hole near the entrance cave of tol  barad behind the meeting stone.

.go xyz -2389.900000 180.257000 4.391660 0 1.606250

**Comment by zana244** [comment]
Confirmed on internal.
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/8e100592-23c8-4251-8668-0993c837cfe8)
If you jump forward in this spot you land in a small spot where you can go under the map texture.

**Comment by zana244** [comment]
#7871
