### ISSUE TITLE
As a Paladin, when taking the Holy Shield talent from the Protec...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6336]
> As a Paladin, when taking the Holy Shield talent from the Protection tree, the ability Holy Shield appears instead in the Retribution page of the spellbook.

This should be correctly appearing in the Protection page of the Paladin spellbook

.go xyz -6241.060000 343.873000 383.443000 0 1.812050

**Comment by zana244** [comment]
#2829
