### ISSUE TITLE
Feralas zone - mobs Grimtotem Raider, Grimtotem Naturalist, etc....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6338]
> Feralas zone - mobs Grimtotem Raider, Grimtotem Naturalist, etc.

Test Character - lvl 45 Gnome rogue with Master of Deception 3/5, Camoflage 4/5, using Pick Pocket ability

Issue - These mobs 100% detect my gnome rogue with a pick pocket success every time. For real. Knocked out of stealth while standing behind them, with them being lvl 43 to 45. Test it for yourself.

.go xyz -4281.850000 636.615000 64.598500 1 0.085555

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7344 related
