### ISSUE TITLE
lvl 42 wind serpent pet crits lvl 45 rogues in duals for 1000+ d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6351]
> lvl 42 wind serpent pet crits lvl 45 rogues in duals for 1000+ damage and a hunter (melee crits, not lightning breath)

.go xyz 1642.250000 -4405.020000 16.851800 1 0.009031

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2878
