### ISSUE TITLE
The "Keen Throwing Knfie" is still consumed on use,

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6356]
> The "Keen Throwing Knfie" is still consumed on use,

.go xyz -8947.530000 -108.654000 83.194300 0 1.921220

**Comment by Shadownflame** [comment]
Vendors still sell the old vanilla version of this item along with every other low lvl thrown it seems. The new, TBC IDs are present as well, but the old ones need removal:
![WoWScrnShot_072224_231501](https://github.com/user-attachments/assets/17d338a9-45bf-4d51-aea3-6305387975d2)
Item IDs 3107, 2946, 3131, 3135, 15326, 15327

**Comment by Shadownflame** [comment]
Note, the ones without stack do get consumed currently as well, lasting a single attack.

**Comment by ghost** [comment]
Fixed, there should be no old style throwing weapons left anywhere in the game
