### ISSUE TITLE
Can't make an omlette without... 
doing this quest and i can't c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6369]
> Can't make an omlette without... 
doing this quest and i can't click on the shadraspawn eggs, they are on the ground  and glowing but no hitbox to click on them

.go xyz -253.135000 -2885.540000 93.568900 0 1.296890

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8293
