### ISSUE TITLE
Wind Serpents don not go into melee when Lightning Breath is on ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6370]
> Wind Serpents don not go into melee when Lightning Breath is on automatic mode. The just stand there, wait for Focus and Lighning Breath again.

.go xyz -526.325000 -4273.350000 41.563800 1 3.293710

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5481
