### ISSUE TITLE
For the Quest "The Perfect Fuel" in Tanaris i have to gather 8 A...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6371]
> For the Quest "The Perfect Fuel" in Tanaris i have to gather 8 Ancient Batteries. There are none in the Noonshade Ruis as discribed in the Quest, or am i wrong about the Location?

.go xyz -7022.240000 -4413.220000 11.331200 1 0.658348

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
