### ISSUE TITLE
Tower of Azora,lvl 8 gray wulf at ressurection place, killing af...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6374]
> Tower of Azora,lvl 8 gray wulf at ressurection place, killing after get ressurected with low mana :)

.go xyz -9564.020000 -602.484000 58.313600 0 4.099430

**Comment by zana244** [comment]
holy moly this is based.
Wolf stalking GY for ress sick ppl :D

**Comment by kaytotes** [comment]
Blizzlike sniffed spawn with a wide wander radius.
