### ISSUE TITLE
Fish in a bucket quest is rewarding 55s per hand in.
Repeatable ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6377]
> Fish in a bucket quest is rewarding 55s per hand in.
Repeatable ? quest in Desolace Shadowspray village.

Might be a bit high of a gold reward.

.go xyz -1664.960000 3138.950000 24.789900 1 5.232160

**Comment by Bennylavaa** [comment]
blizlike
