### ISSUE TITLE
The quest "Freedom to Ruul" has a broken first ambush. I entered...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6380]
> The quest "Freedom to Ruul" has a broken first ambush. I entered the cave and 2 ambushes had already spawned before quest start so there were 6 furbolgs stacked in the same location. I managed to sneak past.

I started the escort and then when we got close, the realization that these were broken amush spawns when a third group spawn and all 9 melted the escort character.

.go xyz 3297.680000 -244.915000 124.695000 1 0.287363

**Comment by zana244** [comment]
#1009
