### ISSUE TITLE
Warbringer Constructs arent supposed tobe attackable until you u...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6399]
> Warbringer Constructs arent supposed tobe attackable until you unlock all the coffers

.go xyz 849.430000 -252.656000 -49.990700 736 4.876050

**Comment by Shadownflame** [comment]
Interesting. You get combat bug from unattackable constructs here https://github.com/Project-Epoch/bugtracker/issues/7534
Maybe the NPCs got swapped?

**Comment by Shadownflame** [comment]
This actually works as intended now. They aren't targetable until all doors are open, and they become targetable when the last door is open and Watchman spawns. Problem is they can be semi-engaged if you only open the dark coffer (they get in combat but remain untargetable) - this is reported elsewhere.
