### ISSUE TITLE
Sitting outside Ony me and a guildmate where going to duel but a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6402]
> Sitting outside Ony me and a guildmate where going to duel but after the countdown we were only able to auto attack each other. No other spells would work for either of us. After duel ended we could not enter another duel and kept getting "invalid target".

.go xyz -4680.130000 -3708.340000 46.643200 1 2.442470

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2967
