### ISSUE TITLE
Goretusks gain a damage increase when they do that stupid charge...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6411]
> Goretusks gain a damage increase when they do that stupid charge thing. It's only supposed to happen once in combat. They do it twice. I've taken two hits for 70+ damage in a row for a total of 140 hp which is half my health at level 13.

.go xyz -10093.400000 1526.310000 41.368300 0 4.473520

**Comment by zana244** [comment]
#75
