### ISSUE TITLE
Fishingat Sun Rock Retreat in Stone Talon Mtns.
Fishing skill is...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6412]
> Fishingat Sun Rock Retreat in Stone Talon Mtns.
Fishing skill is at 142 and have been fishing for about 10 minutes and all I am catching is greay loot items.

Equipped nightcrawlers for +50 fishing and still catching grey items.

.go xyz 919.016000 982.393000 104.107000 1 3.607990

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6852
