### ISSUE TITLE
Pterios, lvl 47 rare fish, seems kind of overpowered, not sure i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6413]
> Pterios, lvl 47 rare fish, seems kind of overpowered, not sure if intentional. Deals 4-5x the dmg of other fish and has 3x as much health and is not even an elite.

.go xyz 569.115000 -3535.090000 107.552000 0 4.430860

**Comment by zana244** [comment]
Could possibly mark as rare elite? And maybe reduce hp a bit, damage seemed fine.
