### ISSUE TITLE
Reclaiming the Eggs quest in the Hinterlands seems to be bugged....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6414]
> Reclaiming the Eggs quest in the Hinterlands seems to be bugged. The Gryphon eggs are not collectable.

.go xyz -365.155000 -2922.960000 75.162900 0 4.881570

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
