### ISSUE TITLE
The quest Water Co. Saviour; the Filter Ports are suggested to s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6420]
> The quest Water Co. Saviour; the Filter Ports are suggested to spawn below the dock (pier). However, checking  below the water from Steamwheedle all the way up to the pirate area, I was not able to find any of the quest items
I found some on another character, but so few that I could never complete the quest

.go xyz -6918.340000 -4920.550000 -3.769000 1 1.527350

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
