### ISSUE TITLE
Soulblaze and I testing pvp, dueled him got the world brawler de...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6432]
> Soulblaze and I testing pvp, dueled him got the world brawler debuff, became unable to duel within capital city despite both being alliance.

.go xyz 9969.880000 2225.510000 1329.780000 1 1.034330

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2967
