### ISSUE TITLE
While fighting ortorg (spelling maybe?) we had an interaction wi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6444]
> While fighting ortorg (spelling maybe?) we had an interaction with hunters pets being able to tank the boss for an obscen amount of time, seemed like they were not taking any damage from some of the atks and AOEs. I dont mean a small amount I mean 0

.go xyz 10311.300000 831.463000 1326.410000 1 4.245690

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1110
