### ISSUE TITLE
Gruff - (6583)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#645]
> This enemy is also incapable of hitting me even when I'm next to it. Only my pet can attack it. Otherwise it evade bugs.
`.go xyz -7829.220000 -870.803000 -266.451000 1 4.677060`

> This enemy seems unable to move to attack me directly and is evade bugging while spamming thunderclap. It won't move.
`.go xyz -7867.570000 -883.428000 -268.482000 1 0.197923`

> creature have 0 loot
`.go xyz -7714.690000 -959.128000 -271.910000 1 2.781410`

**Comment by zana244** [comment]
seems solved on internal? also drops loot.
