### ISSUE TITLE
Un'Goro Crater - Quest: Storm, Earth, Wind, and Fire.
 Yaluni's ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6450]
> Un'Goro Crater - Quest: Storm, Earth, Wind, and Fire.
 Yaluni's Totem can be used on corpses until complete the quest

.go xyz -6436.350000 -2041.660000 -242.649000 1 3.056200

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2321
