### ISSUE TITLE
Goretusks in Westfall have shadow resistance (my shadowbolt who'...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6451]
> Goretusks in Westfall have shadow resistance (my shadowbolt who's supposed to hit between 52 and 61, deals 35 damage, on average)

.go xyz -10908.700000 993.231000 36.293700 0 3.387360

**Comment by zana244** [comment]
Actually valid. 
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/e57eb15d-c2ac-42cf-90c2-31cfee4ed56c)

**Comment by zana244** [comment]
#75
