### ISSUE TITLE
Uhk'loc - (6585)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#647]
> This rare didn't drop anything of note.
`.go xyz -6300.890000 -1986.930000 -265.594000 1 5.792100`

> Did not drop a single gree/blue item
`.go xyz -6311.540000 -2004.790000 -260.925000 1 2.769380`

> no still rare sadness :(
`.go xyz -6294.570000 -2005.520000 -262.792000 1 0.443789`

**Comment by Bennylavaa** [comment]
fixed
