### ISSUE TITLE
At the WSG vendor for level 15 gear, there are no Rookie's Shoul...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6470]
> At the WSG vendor for level 15 gear, there are no Rookie's Shoulders, despite being in the set list. There are Rookie's Pads though.

.go xyz 1045.280000 -2108.820000 122.946000 1 1.090590

**Comment by Shadownflame** [comment]
Seems already fixed. It's pads on the set list too.
