### ISSUE TITLE
There's a lot of dots, spell casts, etc. from mobs I've encounte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6471]
> There's a lot of dots, spell casts, etc. from mobs I've encountered that just aren't registered. Not shown in my UI, not even in the combat log. Makes it really difficult to play the game at this level, even while fighting lower level mobs.

.go xyz 791.619000 -2541.390000 91.666700 1 2.860950

**Comment by Shadownflame** [comment]
Possibly related https://github.com/Project-Epoch/bugtracker/issues/6941

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6937
