### ISSUE TITLE
Some spells/debuffs in Tirisfal Glades don't show up on my chara...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6473]
> Some spells/debuffs in Tirisfal Glades don't show up on my character. Even preventing bandages/Rotten Rations without my knowledge.

.go xyz 1957.660000 -491.613000 34.525100 0 0.557079

**Comment by Shadownflame** [comment]
Possibly related https://github.com/Project-Epoch/bugtracker/issues/6941

**Comment by Shadownflame** [comment]
The Bleeding Horrors in this location have a spell called "Rancid Blood" which periodically reflects damage to you as you are DPSing. It has a visible green cloud around you, but it's not a debuff, and it cannot damage you unless you are hitting the enemy. Every actual debuff properly shows up. None if these even prevent bandaging, they're not DOTs.
![WoWScrnShot_072524_020151](https://github.com/user-attachments/assets/6e550c08-17c5-4d95-8820-b87eded5a716)
![WoWScrnShot_072524_020258](https://github.com/user-attachments/assets/61722679-c8e5-4568-82d0-5269539ef849)

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6937
