### ISSUE TITLE
For the quest The Perfect Fuel in tanaris west of steamwelde por...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6475]
> For the quest The Perfect Fuel in tanaris west of steamwelde port there are no ancient batterys to be collected for quest.

.go xyz -7233.830000 -4891.100000 0.563514 1 1.087630

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
