### ISSUE TITLE
If you swim along sections of  the bottom floor of Wavestrider B...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6478]
> If you swim along sections of  the bottom floor of Wavestrider Beach (Tanaris) you recover Breath, allowing you to currently never have to come up for air.

.go xyz -6735.210000 -4936.230000 -19.498000 1 0.145038

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8308
