### ISSUE TITLE
Killing some of the new horde NPCs in the Sepulcher will not PvP...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6480]
> Killing some of the new horde NPCs in the Sepulcher will not PvP-flag you.

.go xyz -340.927000 1191.720000 63.771200 0 2.899860

**Comment by zana244** [comment]
Confirmed on internal. Kor and Deathguard Kitsapell do not have horde pvp flags, unlike the rest of the NPCs in The Sepulcher.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8333
