### ISSUE TITLE
Zoning into Burndural (Wetlands) zones you out map-wise. Openein...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6486]
> Zoning into Burndural (Wetlands) zones you out map-wise. Openeing the map shows the continent map rather the zone map.

.go xyz -3899.590000 -1935.900000 148.610000 0 3.157530

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8298
