### ISSUE TITLE
Lev 44 Instant Poison unable to be applied (lev 45 character) ri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6493]
> Lev 44 Instant Poison unable to be applied (lev 45 character) right click on icon produces red text "Another action is in progress

.go xyz -7903.320000 -2801.880000 28.928600 1 5.829050

**Comment by Shadownflame** [comment]
Works fine on internal. Character must have been stuck casting something else. No info to pinpoint that.
