### ISSUE TITLE
Actually, the Tangy Clam Meat stacks fine. The Thick-Shelled cla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6497]
> Actually, the Tangy Clam Meat stacks fine. The Thick-Shelled clams erronesouly drop Clam Meat

.go xyz -1051.200000 -257.463000 8.369680 0 4.593010

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5248
