### ISSUE TITLE
Farming Thick Shell Clams for Iridescent Pearls. Clams frequentl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6499]
> Farming Thick Shell Clams for Iridescent Pearls. Clams frequently drop nothing. They should drop at least 1 Tangy Clam Meat everytime

.go xyz -1077.440000 -302.595000 0.476647 0 1.925640

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5248
