### ISSUE TITLE
one of the durotar tigers is unhittable

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6501]
> one of the durotar tigers is unhittable

.go xyz -995.324000 -5125.890000 -1.559890 1 3.878670

**Comment by zana244** [comment]
#8302

**Comment by Shadownflame** [comment]
This specific mob resets when you try to pull it from water (works fine if you walk onto the island)

**Comment by Shadownflame** [comment]
You can now properly engage this mob from the water. However, as it cannot swim, the player needs to leave the water to continue attacking afterwards, otherwise the mob resets.
