### ISSUE TITLE
I was in the upper marshes doing the dragonmaw questline in Burn...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6504]
> I was in the upper marshes doing the dragonmaw questline in Burndural. I died and when I released my spirit, It put me at the spirit healer in Sentinel Hill in westfall.

.go xyz -10546.900000 1197.240000 31.724100 0 1.844800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8298
