### ISSUE TITLE
Quest "Learn to Ride in Elwinn Forest" is broken, when I get to ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6508]
> Quest "Learn to Ride in Elwinn Forest" is broken, when I get to Randal he has nothing for me!

.go xyz -9442.050000 -1390.460000 46.856700 0 5.837350

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1723
