### ISSUE TITLE
Can't finish the quest "Reclaiming the Eggs" in the Hinterlands....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6511]
> Can't finish the quest "Reclaiming the Eggs" in the Hinterlands. Can't loot the eggs at all.

.go xyz -396.363000 -2887.320000 82.328900 0 0.171886

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
