### ISSUE TITLE
There are no deposit at all in the Drywhisker Gorge in Arathi Hi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6520]
> There are no deposit at all in the Drywhisker Gorge in Arathi Highlands and I can't complete the "Favor for Krazek" quest where I need 4 Lesser Bloodstone Ore.
Moreover a lot of deposit are bugged due to the new area The Blazzing Hills you created (this area is awesome btw, reminds me of the Elemental Plateau & stuff from TBC)

.go xyz -1936.460000 -3556.060000 148.930000 0 5.257800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1483
