### ISSUE TITLE
Ships are a mess. You can attack vertically through walls and ca...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6522]
> Ships are a mess. You can attack vertically through walls and can be aggroed through walls

.go xyz -14543.500000 113.783000 0.000722 0 3.367880

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5656

**Comment by Shadownflame** [comment]
I can't reproduce this as a widespread problem in the STV ships that are near the report location. The walls and floors properly give LOS.
There is however a visible gap in the stairs which is questionable, you can aggro/attack the deckhand underneath while going down the stairs as he is not LOS:
![WoWScrnShot_081624_015714](https://github.com/user-attachments/assets/8ede10b0-258c-47c0-b670-1d1d92c8d1c7)
I believe he should be LOS blocked despite the physical gap there.

**Comment by kaytotes** [comment]
Nothing we can do about that it's blizzard model data and we can't change params for just this ship.
