### ISSUE TITLE
Questioning Reethe quest poorly scripted in general. Skirmishers...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6531]
> Questioning Reethe quest poorly scripted in general. Skirmishers didn't move with the captain, one skirmisher stayed green and didn't become a targetable enemy  but kept following me, Reethe died before the encounter ended

.go xyz -3351.390000 -3191.980000 34.227400 1 2.097150

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8140
