### ISSUE TITLE
Quest Reagents for the Undercity Felhound Brains and Nether Wing...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6536]
> Quest Reagents for the Undercity Felhound Brains and Nether Wings dropped 100%, Doomwarder Blood does not

.go xyz -1800.340000 1820.600000 60.866100 1 5.726640

**Comment by zana244** [comment]
think vmangos update solved this, now all do not have 100% drop rate... this quest will be horrible :D (same as original alliance counterpart)
