### ISSUE TITLE
Attacking an elevated enemy will break your AA

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6537]
> Attacking an elevated enemy will break your AA

.go xyz -1699.050000 1938.410000 61.492600 1 1.518260

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892 related

**Comment by Bennylavaa** [comment]
I cant reproduce this exact case, but its linked to the other case.
