### ISSUE TITLE
Shadowsprey Orca can AA me but I can't AA it

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6538]
> Shadowsprey Orca can AA me but I can't AA it

.go xyz -1919.530000 3334.610000 -19.787400 1 5.817020

**Comment by Shadownflame** [comment]
Maybe related https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
I cannot reproduce this anymore. Perhaps the water pathing improvements solved this. Evading mobs can break your AA as per https://github.com/Project-Epoch/bugtracker/issues/7892 but these mobs have been fixed not to evade randomly when the player goes to the surface for water anymore.
