### ISSUE TITLE
For the quest Sacred Fire, the Incendia Agave spawns seem to be ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6549]
> For the quest Sacred Fire, the Incendia Agave spawns seem to be fixed and there's too few up at a time. The spawns don't seem to be cycling through all possible spots and take too long to respawn with too few active at a time

.go xyz -5061.710000 -2024.870000 -47.814200 1 2.091590

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2105
