### ISSUE TITLE
Antlered Coursers for the Stonetalon Quest Jin'Zil's Forest Magi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6551]
> Antlered Coursers for the Stonetalon Quest Jin'Zil's Forest Magic are supposed to have a 100% drop of two Courser Eyes. Just killed one and got nothing

.go xyz 1722.780000 789.974000 133.722000 1 5.878750

**Comment by Bennylavaa** [comment]
this is not true
