### ISSUE TITLE
Razormane Seers cancel their totems. Drop a searing then immedia...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6553]
> Razormane Seers cancel their totems. Drop a searing then immediately cancel it with a healing totem and vice versa

.go xyz -3871.080000 -1650.580000 91.689500 1 6.047890

**Comment by zana244** [comment]
https://youtu.be/wMwUbByb2C4
Taught by Kaytotes himself, blizzlike behaviour
