### ISSUE TITLE
Cannot turn in quest "The Corruption of the Jadefire." Quest say...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6555]
> Cannot turn in quest "The Corruption of the Jadefire." Quest says to turn the completed quest to NPC Eridan Bluewind in Felwood but the NPC doesn't even have a question mark above their head.

.go xyz 4006.550000 -1309.300000 254.497000 1 5.648490

**Comment by zana244** [comment]
#7895
