### ISSUE TITLE
Defias Dockworker - (6927)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#656]
> There are 3 of these in Jerod's Landing that are following the same path in almost the same location (overlapping), so it seems it has spawned 3 where it should be only one
`.go xyz -9991.930000 -105.746000 23.850400 0 5.931120`

**Comment by zana244** [comment]
Intended. pathing just a tiny bit janky but good enough.
https://www.youtube.com/watch?v=c6nD30EsSU4
