### ISSUE TITLE
executes sometimes dont deal damage, i hear the sound of the abi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6560]
> executes sometimes dont deal damage, i hear the sound of the ability and i lose the rage but i dont deal any damage from it, happens especially if i use it right after it becomes available

replicate by getting to execute range and spam execute, you will see it happen from time to time

.go xyz 1846.420000 -1734.170000 60.825000 1 5.789450

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2606
