### ISSUE TITLE
even though i dont have the bladestorm talent enabled, it random...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6561]
> even though i dont have the bladestorm talent enabled, it randomly procs. not sure if this is supposed to happen. im currently fighting wastewander mobs in tanaris if that means anything.

.go xyz -6892.720000 -4353.400000 15.275100 1 2.763260

**Comment by zana244** [comment]
I wish I had this problem. Most likely ravager weapon being used.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1921
