### ISSUE TITLE
for some reason can't autoattack underwater, but it appears to b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6565]
> for some reason can't autoattack underwater, but it appears to be random

.go xyz 477.862000 -4126.180000 112.092000 0 5.577870

**Comment by Shadownflame** [comment]
May be related https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
Same issue as https://github.com/Project-Epoch/bugtracker/issues/7892 evading mobs break your AA. These mobs have been fixed so that they no longer evade randomly (water mobs in general) so it won't happen unless you are dancing on the shore perimeter and trying to cheese them.
