### ISSUE TITLE
PvP vendor in Stormwind gives me mage gear as a Shadow Priest. S...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6569]
> PvP vendor in Stormwind gives me mage gear as a Shadow Priest. Set bonuses are all mage spells.

.go xyz -13930.000000 268.409000 15.649400 0 2.812070

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7977
