### ISSUE TITLE
When you jump into the lava pit in iron forge and die your chara...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6570]
> When you jump into the lava pit in iron forge and die your character still spawns in the lava pit making it impossible to resurrect. it doesn't take you to a spirit healer. am stuck.

.go xyz -4762.010000 -1086.870000 482.608000 0 3.985970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7296
