### ISSUE TITLE
Molten blast will only work to refresh the first Flame Shock use...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6574]
> Molten blast will only work to refresh the first Flame Shock used on a mob.

So if two shamans (A and B) cast flame shock, and then both Molten Blast, only the shaman who hit with Flame Shock first can refresh their Flame Shock. 

So if A hit first, B cannot refresh their Flame Shock with Molten Blast

.go xyz 27.291500 -3378.070000 104.642000 1 2.859710

**Comment by zana244** [comment]
#2646
