### ISSUE TITLE
Hello! Well, to make it fast. I didn't do the whole math but I m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6576]
> Hello! Well, to make it fast. I didn't do the whole math but I made a Tauren and UD Priest, and on the Tauren side, with the +5 Base Health Racial and +5 points in Enlightement, I only get 50 Health Points compare to the UD with no talent points invested. Cheers.

.go xyz -2917.390000 -253.598000 52.980000 1 0.142142

**Comment by Shadownflame** [comment]
Tauren racial was broken on beta. Resolved now.
