### ISSUE TITLE
hunter pets can infinitely tank Ortorg, they dont get any damage...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6583]
> hunter pets can infinitely tank Ortorg, they dont get any damage from lava slash or brutal strike thanks to their avoidance so a single healer is enough to keep them up... and they make enough threat to hold aggro. this is probably not intended

.go xyz 1559.530000 -4218.680000 45.463700 1 5.737340

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1110
