### ISSUE TITLE
If you die in Shatterspear village, you spawn in fucking Ashenva...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6585]
> If you die in Shatterspear village, you spawn in fucking Ashenvale Nightsong woods. How are you supposed to get back there from here?

.go xyz 2411.460000 -2950.620000 124.114000 1 0.597455

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2326
