### ISSUE TITLE
there arent enough herbs and mining nodes in the world... especi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6587]
> there arent enough herbs and mining nodes in the world... especially high lvl zones. It's an empty beta server and i can hardly pick up 4-5 nodes if i circle through a whole zone. Thats gonna be ass on live with crowd

.go xyz -6849.890000 996.373000 1.414220 1 4.311700

**Comment by Bennylavaa** [comment]
pooling issue related
