### ISSUE TITLE
Blackrock Sorcerer - (7026)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#659]
> Does not count towards Tired o' them Orcs!
`.go xyz -8135.820000 -1761.750000 133.118000 0 1.015520`

> i see theres loot but the button is gray and i cant click 
doesnt let to loot him
`.go xyz -8118.630000 -1546.940000 133.713000 0 1.630030`

> These are dropping silk cloth.
`.go xyz -8222.990000 -1746.640000 147.865000 0 5.633080`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2341
