### ISSUE TITLE
NPC pathing seems to have the same issue as pet pathing. The ene...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6590]
> NPC pathing seems to have the same issue as pet pathing. The enemies always run to your previous position when you are moving around swiftly, as though they have some 2-3 sec delay in checking where you are. This is especially spectacular when youre mounted, it takes ages to gather up enemies to AOE them because they keep randomly circling not towards me but to previous positions I ran through.

.go xyz 1818.570000 -1522.080000 59.389900 0 4.532570

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
