### ISSUE TITLE
NPC positions dont always reset properly after running out of le...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6591]
> NPC positions dont always reset properly after running out of leash range. Sometimes the NPCs "reset" to the position the top aggro player was at the time of the reset.

.go xyz -7949.890000 -5334.650000 0.520370 1 4.132030

**Comment by Shadownflame** [comment]
Only happens if the NPCs can't find a path back to their original spot, or inside dungeons if no players are present. Both reported elsewhere.
