### ISSUE TITLE
The captain's chest in tanaris is dropping nothing but gray rugs...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6592]
> The captain's chest in tanaris is dropping nothing but gray rugs. It's a prestigious chest to farm in Lost Rigger Cove usually as it requires a Captain's Key to open, and it's supposed to drop loads of goodies not just gray rugs. Right now it's not worth the effort to fight through the ship to find the chest.

.go xyz -7894.640000 -5370.300000 -1.618370 1 2.503310

**Comment by zana244** [comment]
Confirmed on internal. 3 times it gave only 3 gray items worth 2s each. A few days ago though it gave 1 journeyman backpack and a (useless) crafting recipe. Might be worth changing.

**Comment by zana244** [comment]
Solved on internal with loot update. Sometimes gives a lot of uncommon items.
