### ISSUE TITLE
Your extremely clever General Drakkisath mechanic doesn't actual...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6594]
> Your extremely clever General Drakkisath mechanic doesn't actually go away after the party wipes to it, meaning that if someone has been soulstoned, they're doomed to die to it anyway.

Also, you need to slow that cast down or speed up how quickly the Seal of Ascension takes effect. I used it at half his cast and the thing was too busy twirling around doing nothing that it got us all killed.

.go xyz -7496.170000 -1075.690000 264.870000 0 4.877850

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/873
