### ISSUE TITLE
As a shaman, my spells seem to do almost 2x the amount of damage...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6595]
> As a shaman, my spells seem to do almost 2x the amount of damage to the enemy rogue I've been dueling than to any NPCs I attack. Not sure if intentional, but she does have 17% PvP damage resistance too and takes the same 282 damage from my lightning shield whether she has her gear on or not.

.go xyz -13534.800000 -40.082300 39.106400 0 5.118360

**Comment by zana244** [comment]
Most likely cheat death bug.
#2878
