### ISSUE TITLE
Magma Totem hits for ~119 a tick, whereas my Searing Totem hits ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6596]
> Magma Totem hits for ~119 a tick, whereas my Searing Totem hits for ~64 a tick. The numbers on the AoE totem are crazy high and the numbers on the single target totem are pathetic by comparison.

.go xyz -13463.200000 90.963300 27.037400 0 4.390300

**Comment by zana244** [comment]
#8313 related
Also, magma totem costs a truckload of mana compared to searing totem so it's not that one sided.
