### ISSUE TITLE
Lesser Healing Wave does not proc Healing Way, but Healing Way s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6597]
> Lesser Healing Wave does not proc Healing Way, but Healing Way says "Your Healing Wave spells". May or may not be a bug, but should be more deliberately described if it doesn't affect Lesser Healing Wave.

.go xyz 3.664860 -112.744000 -8.462340 732 4.689620

**Comment by Shadownflame** [comment]
Never affected LHW.
