### ISSUE TITLE
Blackrock Slayer - (7027)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#660]
> Does not count towards Tired o' them Orcs
`.go xyz -8067.510000 -1926.960000 132.675000 0 1.421440`

> Didn't count toward quest "Tired o' them Orcs!" (killing 30 blackrock orcs)
`.go xyz -8084.080000 -1467.450000 132.249000 0 3.783000`

> Quest Tired o'them Orcs! - kill 30 orcs does not work, ive kill almost every time of them, noone is got in the quest comlition
`.go xyz -8084.950000 -1470.240000 132.326000 0 3.713670`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2341
