### ISSUE TITLE
5 second rule" not working correctly. it is using wrath style ma...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6602]
> 5 second rule" not working correctly. it is using wrath style mana regeneration (3 seconds "Casting" and then constant regen instead of ticks of mana every 2 seconds)

.go xyz -7545.630000 -3110.860000 17.881800 1 0.071358

**Comment by Shadownflame** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/8274
