### ISSUE TITLE
Mage's winter chill talent nerfed to 1%, not sure if it's wanted...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6603]
> Mage's winter chill talent nerfed to 1%, not sure if it's wanted behavior

.go xyz 1664.860000 1674.550000 120.530000 0 1.461970

**Comment by Shadownflame** [comment]
Confirmed, this spell is currently not TBC state, was forgotten on wrath as per Eredun. TBC state should be 2% per point. And only should give frost spell crit, currently gives every school.
