### ISSUE TITLE
The Young Forest Bear i tamed for the Hunter Quest has the same ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6609]
> The Young Forest Bear i tamed for the Hunter Quest has the same slow Movement Speed as the Prowler. And i noticed my Health-regeneration stops after taminga Beast. I was not in combat.

.go xyz -9615.170000 -293.264000 57.340700 0 1.271530

**Comment by zana244** [comment]
#6036
