### ISSUE TITLE
Blackrock Warlock - (7028)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#661]
> THe quest Tired o' them orcs! is not giving credit for kills. Finished The blazing hydra quest and I am still 0/30
`.go xyz -8232.580000 -1747.390000 148.583000 0 3.096300`

> This npc may slap a lil too hard, ouch!
`.go xyz -7684.650000 -1471.530000 140.755000 0 0.710903`

> These are dropping silk cloth.
`.go xyz -8245.240000 -1758.320000 145.935000 0 5.161830`

> Does not count towards "Tired o' them Orcs!
`.go xyz -7596.900000 -772.158000 190.834000 0 4.535900`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2341
