### ISSUE TITLE
The respawn rate of the Kobold Tunneler at Fargodeep Mine is way...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6614]
> The respawn rate of the Kobold Tunneler at Fargodeep Mine is way to high. Should at least be 2x long as it is now.

.go xyz -9866.130000 123.842000 32.136000 0 2.098830

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330
