### ISSUE TITLE
For some reason it is saying Rank 4 Divine Spirit is unavailable...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6617]
> For some reason it is saying Rank 4 Divine Spirit is unavailable to train even though I meet requirements (Level 60, Rank 3)

.go xyz -8542.730000 818.814000 106.521000 0 4.952060

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7658
