### ISSUE TITLE
Sometimes my GCD will be over and I can't cast spells because th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6618]
> Sometimes my GCD will be over and I can't cast spells because they're still on CD. Weird

.go xyz 2065.730000 -2997.200000 85.130500 0 5.396070

**Comment by Shadownflame** [comment]
There is some missing core support for latency/spell queueing from what I understand which causes some hiccups with GCD. Currently not fixable I was told, but I'll leave it hanging.

**Comment by Shadownflame** [comment]
400ms spell queue window implemented. Still wonky with high latency but it's as good as it'll get.
