### ISSUE TITLE
'The Art of Golemancy' quest in Burning Steppes is bugged, Stewa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6619]
> 'The Art of Golemancy' quest in Burning Steppes is bugged, Stewart is super weak and the enemies don't count for the quest

.go xyz -8000.470000 -2246.900000 131.808000 0 0.446679

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2348
