### ISSUE TITLE
Mobs still can and will cast and attack while running away in fear.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6624]
> Mobs still can and will cast and attack while running away in fear.

.go xyz -5648.590000 -3869.050000 321.284000 0 4.614250

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8252

**Comment by Shadownflame** [comment]
This issue still persists, most mobs flee mechanic stops after 2 steps.
