### ISSUE TITLE
Firegut Ogre Mage - (7034)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#663]
> wierd pathing
`.go xyz -7972.900000 -2437.700000 128.354000 0 5.336950`

> playing in team to do the ogres in burning steppes,  just looted dark iron scraps and fireguts but only on one teammember not for the 2,  in lower level both get quest items
`.go xyz -7869.440000 -2451.950000 135.331000 0 0.040560`

> Not doing much mage-ical things.
`.go xyz -7773.950000 -2482.600000 157.442000 0 1.743850`

> spamming text long after quest completed
`.go xyz -7987.020000 -2450.110000 132.304000 0 0.422339`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1994
