### ISSUE TITLE
Jaedenar Adepts (7115) are bugged. When you tag them they instan...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6631]
> Jaedenar Adepts (7115) are bugged. When you tag them they instantly blink, then depending on terrain you can't attack them until they move.

.go xyz 4810.690000 -525.216000 318.448000 1 4.996450

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/673
