### ISSUE TITLE
I don't know if this is a bug, but you have an absolutely ridicu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6634]
> I don't know if this is a bug, but you have an absolutely ridiculous amount of thorium veins in Un'Goro Crater.

.go xyz -7244.900000 -1467.450000 -228.490000 1 5.108950

**Comment by Bennylavaa** [comment]
18412 (Entry: 175404) - [Rich Thorium Vein X:-7220.000000 Y:-1476.000000 Z:-239.000000 MapId:1]  
18417 (Entry: 175404) - [Rich Thorium Vein X:-7210.000000 Y:-1486.000000 Z:-248.000000 MapId:1]  
39945 (Entry: 175404) - [Rich Thorium Vein X:-7247.479980 Y:-1466.810059 Z:-227.610001 MapId:1]  
17506 (Entry: 175404) - [Rich Thorium Vein X:-7246.509766 Y:-1459.930054 Z:-223.326004 MapId:1]

These are virtually on top of each other, also I am not seeing these in vmangos. I would check what epoch has against what vmangos has for spawn points for these nodes it seems like there are a lot more than normal.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8301
