### ISSUE TITLE
Reclaiming the Eggs in Hinterlands seems bugged. There are no Gr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6635]
> Reclaiming the Eggs in Hinterlands seems bugged. There are no Grphon Eggs in  Shandra'Alor,

.go xyz -460.107000 -2802.110000 103.825000 0 0.175647

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
