### ISSUE TITLE
deadmines fire boss in boat Scinti.
We dont take any damage of t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6639]
> deadmines fire boss in boat Scinti.
We dont take any damage of the fire wall  at lvl 45 nor do we see that he misses.

.go xyz -660.871000 154.171000 -103.542000 725 4.721090

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5040
