### ISSUE TITLE
In areas such as Stone Cairn Lake Murloc Camp there are multiple...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6641]
> In areas such as Stone Cairn Lake Murloc Camp there are multiple chest spawns but they are all up at the same time, i don't believe that's how it should work and only one should be up at a time

.go xyz -9271.170000 -1212.250000 70.784800 0 0.348281

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8221
