### ISSUE TITLE
The quest The Perfect Container has friendly Cleanup Crew at the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6652]
> The quest The Perfect Container has friendly Cleanup Crew at the crashsite. And there are no parts on the ground. Dont know what to do to progress here. Was trying to find their faction and click "at war" with them, but no faction is connected to them to achive this.

.go xyz -7045.600000 -3534.220000 15.377800 1 5.900390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
