### ISSUE TITLE
The quest Signs of Treachery?, starts from item Sealed Letter an...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6654]
> The quest Signs of Treachery?, starts from item Sealed Letter and ends at Nazeer Bloodpike cant be handed in. Nazeer does not have a questionmark and there's no option to hand in if u speak to him

.go xyz -3111.120000 -2831.990000 34.360400 1 1.869360

**Comment by zana244** [comment]
#1713
