### ISSUE TITLE
After completing The Black Shield, the questgiver Krog does not ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6655]
> After completing The Black Shield, the questgiver Krog does not give you the final part to go to Mosarn in Thunderbluff.

.go xyz -3147.040000 -2888.160000 34.131200 1 2.270690

**Comment by Bennylavaa** [comment]
There are other quests required to get this last quest in the chain most likely wasnt able to see this because the hoofprint quests was broken once that gets fixed this will work as intended. 

https://github.com/Project-Epoch/bugtracker/issues/2424
