### ISSUE TITLE
the quest Questioning Reethe for horde spawns a Theramore Skirmi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6656]
> the quest Questioning Reethe for horde spawns a Theramore Skirmisher that is friendly and follows you after you complete the quest.

.go xyz -3148.070000 -2976.720000 31.518100 1 1.678240

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8140
