### ISSUE TITLE
Quest: : Lost Rams

Mount Ram
Get to Ranch
Dismount

After dismo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6660]
> Quest: : Lost Rams

Mount Ram
Get to Ranch
Dismount

After dismounting you loose the pet bar on the action bar. Warlock

.go xyz -5601.460000 -1311.500000 410.967000 0 2.853610

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2177
