### ISSUE TITLE
Mage spell Arcane Missiles doesn't start to channelling if you m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6665]
> Mage spell Arcane Missiles doesn't start to channelling if you miss initial hit. Spell just cancels, consumes mana and doesn't shoot a single missle, even though hit or miss should could for each single missle and not channel itself.

.go xyz -7292.350000 -3653.700000 14.410900 1 5.651320

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5003
