### ISSUE TITLE
hey there
my Vampiric embrace Heals all the alliance players in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6667]
> hey there
my Vampiric embrace Heals all the alliance players in the group when inside dungeon but wont heal the Hordes
not sure if u are aware of this or intended

.go xyz 814.947000 -478.158000 -55.251300 349 1.105060

**Comment by Shadownflame** [comment]
Works fine as long as no one is PvP flagged. PvP issue open elsewhere.
