### ISSUE TITLE
Logging out in the carts in Elywyn has a chance to drop you thro...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6673]
> Logging out in the carts in Elywyn has a chance to drop you through the world when you log back in. Only got it to happen twice on two different characters. Might be location based or something. Hope this helps :)

.go xyz -9475.060000 65.318100 56.537200 0 5.029950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6736
