### ISSUE TITLE
I fell through the map when I used 'Charge' on a Kobold Laborer ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6681]
> I fell through the map when I used 'Charge' on a Kobold Laborer in Echo Ridge Mine...

.go xyz -8638.090000 -131.302000 -5409.260000 0 1.096070

**Comment by Shadownflame** [comment]
Mainly affects druids and warriors who can charge, but on top of pathing improvements, a generic failsafe is in demand against any instance of players falling under map and dying to it, as discussed with ktotes.
Related https://github.com/Project-Epoch/bugtracker/issues/6736

**Comment by Bennylavaa** [comment]
Having trouble reproducing but I know this can happen.

**Comment by Shadownflame** [comment]
Failsafe works stellar, can't even fall down if I deliberately teleport undermap.
