### ISSUE TITLE
The Elite Wandering Forest Walkers in Ferelas (Lower Wilds) whil...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6682]
> The Elite Wandering Forest Walkers in Ferelas (Lower Wilds) while Neutral, if attacked they will become hostile but will cast Regrowth on the attacking player opposed to casting regrowth on themselves.

.go xyz -4455.580000 -361.395000 38.221400 1 3.744940

**Comment by zana244** [comment]
#2979
