### ISSUE TITLE
mind numbing 2 and 3 and crippling poisons 2 are showing as junk...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6687]
> mind numbing 2 and 3 and crippling poisons 2 are showing as junk in the poison profession.  Both mindnumbing  are unable to be put of weapons

.go xyz -8808.450000 330.596000 102.235000 0 4.650630

**Comment by Shadownflame** [comment]
Item IDs 6951, 9186, 3776

**Comment by zana244** [comment]
#2584

**Comment by Shadownflame** [comment]
Mind numbing 2 is now a white junk instead of gray - still no poison properties.
Mind numbing 3 seems mostly fixed. I don't know why it has 100 charges?
Crippling poison II seems good now.
