### ISSUE TITLE
For the quest "Venomhide Eggs" in Ungoro I can see the eggs but ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6695]
> For the quest "Venomhide Eggs" in Ungoro I can see the eggs but they aren't lootable the pale yellow ones

.go xyz -7369.880000 -1955.390000 -270.404000 1 5.951010

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
