### ISSUE TITLE
Quest: Reclaiming the Eggs - Can't pick up eggs around Shadra'Al...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6696]
> Quest: Reclaiming the Eggs - Can't pick up eggs around Shadra'Alor in Hinterlands

.go xyz -399.052000 -2890.340000 84.941700 0 3.558430

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
