### ISSUE TITLE
I found a ooze covered gold vein in Durotar near Sen'jin Village...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6699]
> I found a ooze covered gold vein in Durotar near Sen'jin Village rock formations

.go xyz 384.030000 -4710.530000 15.228300 1 1.288940

**Comment by Bennylavaa** [comment]
Cords nowhere near and there are lots of rocks lol

**Comment by Bennylavaa** [comment]
:O I actually found it! Added to the node list
