### ISSUE TITLE
Inspiration (priest talent) does not proc on other than themselves

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6706]
> Inspiration (priest talent) does not proc on other than themselves

.go xyz 996.981000 -4437.930000 11.010800 1 5.679130

**Comment by zana244** [comment]
Confirmed on internal.

**Comment by kaytotes** [comment]
Next deploy

**Comment by Shadownflame** [comment]
Now procs on other friendly targets.
