### ISSUE TITLE
logout in capital cities should be instant, but i still wait 20 ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6709]
> logout in capital cities should be instant, but i still wait 20 sec for log out

.go xyz -8828.110000 619.382000 94.270100 0 5.515940

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6780

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4979
