### ISSUE TITLE
Jadefire Trickster - (7107)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#671]
> Got PvP flagged when using my Shadowfiend, got mind controlled and used a spell. Not sure it make sense to be PvP flagged when fighting a pet from my own faction.
`.go xyz 6359.560000 -742.565000 472.196000 1 4.592990`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3562
