### ISSUE TITLE
The quest reclaiming the eggs in hinterlands is what i need to c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6722]
> The quest reclaiming the eggs in hinterlands is what i need to complete to get my last 500 rep with aerie peak and i can't do it as you can't collect the eggs

.go xyz -4555.110000 1844.560000 90.136300 1 5.575300

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
