### ISSUE TITLE
The quest "Reclaiming the Eggs" in Hinterlands, doesn't seem to ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6723]
> The quest "Reclaiming the Eggs" in Hinterlands, doesn't seem to be allowing me to collect any of the eggs. I've searched it up and asked other people and they just click them easy as that but I can't

.go xyz -472.738000 -2903.060000 121.855000 0 1.011850

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
