### ISSUE TITLE
Hunter class quest tamed pets completely broke my character in w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6725]
> Hunter class quest tamed pets completely broke my character in weird ways. Stuck in combat with the first, fixed when released. Stuck in combat with the second, but can't melee, can't be seen as the one in proper combat (no xp or loot) and am still stuck like this even after release.

.go xyz 9912.420000 1182.920000 1307.950000 1 3.471410

**Comment by zana244** [comment]
#8321
