### ISSUE TITLE
For quest Waste Removal in Steamwheedle, the oil spill Northeast...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6727]
> For quest Waste Removal in Steamwheedle, the oil spill Northeast of town would not allow spill to be cleaned up

.go xyz -6717.570000 -4800.210000 0.642126 1 5.857370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2234
