### ISSUE TITLE
Dismissing pet is not giving Soul Shard back

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6728]
> Dismissing pet is not giving Soul Shard back

.go xyz -6929.150000 -4762.010000 10.029800 1 4.532420

**Comment by zana244** [comment]
confirmed on internal, but I am not sure if that is QoL that Epoch wanted to introduce or not?

**Comment by kaytotes** [comment]
As far as I'm aware this is intended right? You get your shards refunded when an action happens that makes you _unwillingly_ dismiss / unsummon a shard regeant demon.

Doing it yourself however is willing and so you lose it.

**Comment by Shadownflame** [comment]
Yep, death/dismiss is not supposed to give back anything.

PS: I can't even support introducing this. Shards are not being loaned to pets, they are meant to be consumed by summoning them. It's only a rip off if you weren't meant to lose your pet but it needs to despawn for transport.
