### ISSUE TITLE
(Inconsistent but recreateable)

When logging off or alt + f4-in...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6736]
> (Inconsistent but recreateable)

When logging off or alt + f4-ing on a cart in Elywnn Forest sometimes when logging back in you will fall throught the terrain to your death requiring you to resurrect at a GY

.go xyz -9489.350000 50.834200 57.987100 0 4.229340

**Comment by Bennylavaa** [comment]
was able to reproduce this on the first alt f4 while riding with Leia Swift around {map:0,x:-9623.845703,y:-610.928833,z:52.210491,o:4.567894}

**Comment by Shadownflame** [comment]
Marking this as critical because this will kill Soul of Irons if the server crashes or they aren't aware of the bug. Usually happens with zeppelins or boats on most servers, to the point some disabled falling damage for hardcores entirely.

**Comment by Shadownflame** [comment]
Failsafe works fine here too.

**Comment by aleksanderKopec** [comment]
Unfortunately, I don't think this is completely fixed, as it happened to me recently during the original launch weekend.

Logged off on a cart in Elwynn Forest, logged in a few hours later, fell through the world and died.

**Comment by Bennylavaa** [comment]
@aleksanderKopec I would test it again when the servers are back up, I assume all the lag was to blame for this.
