### ISSUE TITLE
A Reflection of Death:

I have the Combined Mirror Shards in my ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6739]
> A Reflection of Death:

I have the Combined Mirror Shards in my bags, but continuing to turn in this quest is disabled on the quest dialog.

.go xyz -4516.860000 1842.800000 93.318600 1 0.430547

**Comment by Shadownflame** [comment]
You have to talk to Trog and then the turn in works fine.
