### ISSUE TITLE
Jaedenar Darkweaver - (7118)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#674]
> When mobs are fleeing. They seem to be running little faster than normal.
`.go xyz 5086.090000 -486.961000 297.058000 1 5.244260`

**Comment by zana244** [comment]
Not sure if they are out of the ordinary. Seem to flee at about 15% hp, and the movement speed scales with the remaining HP... flees with about 70% speed. Instead of doing a Slow running animation they do a fast walking one.
