### ISSUE TITLE
Private Thorsen shows a yellow exclamation point above his head ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6742]
> Private Thorsen shows a yellow exclamation point above his head in the Rebel Camp. When right clicking on him, he doesn't have any quest to offer, he only states that "This is a dangerous place, Raciten. Be careful arounnd here.

.go xyz -11317.400000 -203.757000 75.366000 0 0.041574

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/117
