### ISSUE TITLE
Quest: Learn to Ride in Darn
Incorrectly states Jartsam is in th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6750]
> Quest: Learn to Ride in Darn
Incorrectly states Jartsam is in the Tradesmen's Terrace
He is located in the Cenarion Enclave

.go xyz 10126.500000 2531.040000 1323.100000 1 6.182600

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1723
