### ISSUE TITLE
Quest "Fit for a King" - The hemp felt a little too sparse. With...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6751]
> Quest "Fit for a King" - The hemp felt a little too sparse. With two people we had to Run back and forth between The Forgotten Coast and Mojache 3 times while visiting every body of water inbetween.

.go xyz -4695.840000 1723.580000 86.421200 1 5.043600

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7967
