### ISSUE TITLE
Very minor bug!
Step 1 - take Zenn's Bidding quest
Step 2 - kill...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6763]
> Very minor bug!
Step 1 - take Zenn's Bidding quest
Step 2 - kill webwood spider, pick up loot
Step 3 - Webwood Spider Silk quest item now in inventory, but quest still shows 0/3 Spider Silk progress
Step 4 - kill 2nd Webwood Spider, loot spider silk again, quest progress suddenly updates to 2/3 spider silk

.go xyz 9909.590000 721.738000 1309.880000 1 3.385200

**Comment by Shadownflame** [comment]
![WoWScrnShot_072524_231702](https://github.com/user-attachments/assets/febc87a7-0594-45ee-b854-a81deb513fb9)
