### ISSUE TITLE
In the quest The Perfect Container, the area described lacks the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6764]
> In the quest The Perfect Container, the area described lacks the Gnome Car Parts mentioned in the quest. Either the respawn timer on the objects is broken, or they're plain not there.

.go xyz -7545.350000 -3220.760000 26.496700 1 4.429950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
