### ISSUE TITLE
https://i.imgur.com/0wk5DCk.jpeg
This spot can spawn both green ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6785]
> https://i.imgur.com/0wk5DCk.jpeg
This spot can spawn both green and red crystals in ungoro

.go xyz -6294.100000 -1377.660000 -265.586000 1 2.923020

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8265
