### ISSUE TITLE
Flying a bat from the bulwark to sepulcher paths through the Dal...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6788]
> Flying a bat from the bulwark to sepulcher paths through the Dalaran bubble where you can see that nothing is there.

.go xyz 478.860000 1536.590000 131.318000 0 0.603619

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6744
https://github.com/Project-Epoch/bugtracker/issues/8077
