### ISSUE TITLE
Defias Cutpurse - (94)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#68]
> When aggrod then ran away from, after the NPC reset and I went to re-attack it I would get an error "You're too far away" constantly, had to un-target then re-target to fix issue.
`.go xyz -9097.610000 -11.676600 91.163500 0 2.148580`

> When mind controlled energy doesn't regen :P, maybe they never use backstab
`.go xyz -9143.710000 60.282800 77.015200 0 2.269030`

**Comment by Bennylavaa** [comment]
cannot reproduce this
