### ISSUE TITLE
Ferocitas the Dream Eater - (7234)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#680]
> killed twice, doesnt drop quest item :( 

Thanks
`.go xyz 9986.150000 324.727000 1316.550000 1 6.180870`

> doesnt drop the quest item
`.go xyz 10016.900000 289.362000 1322.560000 1 5.835970`

**Comment by zana244** [comment]
solvedo on internal. as a note... he drops a quest item which you have to open.
