### ISSUE TITLE
In combat without any enemies targeting me

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6800]
> In combat without any enemies targeting me

.go xyz -2826.560000 -2700.490000 37.340400 1 1.631990

**Comment by Shadownflame** [comment]
Redirecting here every random combat bug report.m except instance ones.

**Comment by Shadownflame** [comment]
Ok, this is not a combat bug. The guy probably aoe'd the egg sacs by mistake and because their nameplates are up in the high heavens, he couldn't tell:
![WoWScrnShot_072524_033626](https://github.com/user-attachments/assets/d5175c95-520c-43b0-a7fa-73e2e02b9165)
