### ISSUE TITLE
I got no rested status when hearthing to stormwind. logout takes...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6811]
> I got no rested status when hearthing to stormwind. logout takes 20s aswell so its not just visual

.go xyz -8599.570000 786.783000 102.187000 0 0.643437

**Comment by zana244** [comment]
Could not reproduce on internal.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6780
