### ISSUE TITLE
mr smites fire from canon deals no damage

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6815]
> mr smites fire from canon deals no damage

.go xyz -520.496000 110.842000 -109.446000 725 3.869570

**Comment by Shadownflame** [comment]
Mr. Smite (45066) in revamped Deadmines:
![WoWScrnShot_072524_032231](https://github.com/user-attachments/assets/2e0e8197-d74a-40b4-b792-9d06ef1cebc4)
The DOT (80961) currently deals no damage whatsoever. 
It is also stacking multiple times if more than 1 cannon shot lands in the same spot, which might be a problem when the damage is fixed. Might be impossible to escape on time if RNG is unfriendly. Should probably not stack up.

**Comment by kaytotes** [comment]
Next deploy.
