### ISSUE TITLE
Quest "Tips of Fire" in Tanaris give low amout of XP (470) for n...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6819]
> Quest "Tips of Fire" in Tanaris give low amout of XP (470) for nomral quest where you need to kill mobs to get loot

.go xyz -9533.740000 -3825.520000 72.491900 1 4.243220

**Comment by Kestrana** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/2253
