### ISSUE TITLE
Sandfury Guardian - (7268)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#682]
> Both Packs, usually attack, once you engage one pack
`.go xyz 1755.420000 1052.480000 48.033800 209 3.991820`

> scripting is off - these snakes dont pull together
`.go xyz 1763.620000 1046.530000 48.715400 209 4.987960`

> snakes not pulling together
`.go xyz 1759.820000 1060.110000 47.403900 209 4.686040`

**Comment by zana244** [comment]
#8262
