### ISSUE TITLE
Shaman talent Elemental Mastery does not expire upon the usage o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6828]
> Shaman talent Elemental Mastery does not expire upon the usage of Shock spells. Frost Shock, Earth Shock, Flame Shock, do not consume the Elemental Mastery charge. This results in the Shaman class being unintentionally capable of endlessly using auto critting free shock spells.

.go xyz -7001.720000 -3604.860000 241.960000 0 4.189560

**Comment by zana244** [comment]
Possibly old issue, works as intended on internal.
