### ISSUE TITLE
Witch Doctor Zum'rah - (7271)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#683]
> No loot
`.go xyz 1858.750000 1039.210000 8.876800 209 1.260160`

> no graves activated duaring boss fight no loot
`.go xyz 1910.760000 1014.530000 11.515500 209 0.368665`

> no loot
`.go xyz 1908.670000 1014.960000 11.515600 209 0.386602`

> Dropped no loot
`.go xyz 1912.010000 1015.220000 11.515600 209 1.851500`

> killed 3 times , still no loot
`.go xyz 1910.090000 1018.600000 11.515700 209 4.006360`

> No loot killed 2 times
`.go xyz 1907.520000 1015.190000 11.515600 209 5.818990`

> No loot dropped
`.go xyz 1910.000000 1014.380000 11.515600 209 1.062970`

> no loot drops and chest phased out
`.go xyz 1882.200000 1026.180000 8.876820 209 2.521910`

> No Loot
`.go xyz 1900.740000 1015.190000 12.216500 209 3.146300`

> Dropped no loot on death.
`.go xyz 1900.020000 1013.760000 12.161200 209 3.010130`

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/8115
