### ISSUE TITLE
Gahz'rilla - (7273)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#684]
> yo 49k hp wtf bro
`.go xyz 1667.640000 1152.960000 8.877120 209 6.261890`

> Gahz'rilla is spamming the knockback slam before players even land from the first one
`.go xyz 1656.890000 1185.190000 6.204220 209 0.386256`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7976
