### ISSUE TITLE
Sandfury Executioner - (7274)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#685]
> could be mind controlled. we just mced him the entire encounter, as we could somehow still damage him.  after he died, he did not drop the key for anyone
`.go xyz 1885.810000 1259.630000 39.174000 209 4.633800`

> if mind controlled, does not drop key
`.go xyz 1893.200000 1268.690000 42.014100 209 2.318940`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8273
