### ISSUE TITLE
The Pale Skinner weapon model doesn't properly rest in the hand ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6850]
> The Pale Skinner weapon model doesn't properly rest in the hand of the human male model - it's currently going through the palm of the hand

.go xyz -9517.270000 208.300000 56.780100 0 3.406860

**Comment by zana244** [comment]
Possibly attaching just a bit too high up the palm... really difficult to figure it out. Extremely minor and cosmetic bug. Also blizzlike item so I wouldn't really do anything...

**Comment by Bennylavaa** [comment]
this looks fine to me on ptr
