### ISSUE TITLE
In the quest "A Strange Historian" it might be an idea to change...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6851]
> In the quest "A Strange Historian" it might be an idea to change the quest text to describe Chromie's new location to being in South Andorhal rather than North West

.go xyz 1299.800000 -1481.300000 71.611700 0 3.461630

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2107
