### ISSUE TITLE
Another day, another seemingly bugged fishing quest (Eau De Parf...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6853]
> Another day, another seemingly bugged fishing quest (Eau De Parfish): interestingly, unlike previous dailies, I'm getting a lot of empty casts where a fish is caught and I right click and receive nothing (not even a 'your fish got away' message)--unsure if this has any bearing on anything, but I wouldn't be surprised if it was hitting the Fragrant Felfish in the loot roll but it's not being looted because it's not in game like the previous fishing daily objective.

.go xyz 6246.320000 -1099.520000 368.515000 1 4.596100

**Comment by Bennylavaa** [comment]
third cast and got this as well, this person has to have some patch or client issue.
