### ISSUE TITLE
Current fishing daily (Frozen Supplies) seems bugged: with 300 f...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6854]
> Current fishing daily (Frozen Supplies) seems bugged: with 300 fishing and a aquadynamic fish attractor I'm still not fishing up any of the quest objectives

.go xyz 6854.050000 -2387.280000 545.989000 1 3.565320

**Comment by Bennylavaa** [comment]
Cannot reproduce this either first few casts I fished some and without aquadynamic fish attractor
