### ISSUE TITLE
Do slavers keep records? = Quest. I think 50% drop chance of Sla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6858]
> Do slavers keep records? = Quest. I think 50% drop chance of Slaver's Recordings is incorrect. I killed more than 30 mobs and it still didn't drop.

.go xyz -6963.080000 -1717.270000 242.039000 0 3.624950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
