### ISSUE TITLE
Hello! Thanks for making this awesome server! Just wanted to giv...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6860]
> Hello! Thanks for making this awesome server! Just wanted to give feedback, since it's vanilla I really miss old quest text font, would be cool if you add it back (or make toggleable). Thank you!

.go xyz -8928.860000 -133.565000 82.273200 0 4.772080

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8139
