### ISSUE TITLE
The Map of the Eastern Kingdoms Doesn't match.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6863]
> The Map of the Eastern Kingdoms Doesn't match.

.go xyz -684.449000 -567.482000 25.074600 0 0.319044

**Comment by zana244** [comment]
I guess they mean the Northern tip of EK? quelthalas and the isle? EK zoomed in and EK + Kalimdor map? I imagine it's 3.3.5 client maps so no bug...
