### ISSUE TITLE
the "Waste Removal" quest has likely been reported often, but it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6874]
> the "Waste Removal" quest has likely been reported often, but it is not that certain schools are untouchable, but just have a VERY small interaction zone, you need to be exactly in the middle of it for it to work. it needs some upscaling

.go xyz -7367.070000 -4941.080000 -1.524180 1 5.674500

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2234
