### ISSUE TITLE
grunt report this as a bug, for grunt believes it is one: but th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6875]
> grunt report this as a bug, for grunt believes it is one: but there is no lootable objects in "noonshade ruins", related to the quest "The Perfect Fuel" and grunt forgot how to properly report a quest.

.go xyz -6942.500000 -4450.740000 9.592090 1 1.344580

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
