### ISSUE TITLE
when you start combat, and the npc leashes back instantly (a dif...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6877]
> when you start combat, and the npc leashes back instantly (a different bug), you automatically stop hitting the npc, even though your auto-attacks should be attacking. (as in, auto-attacks are active, the red circle around the targeted npc is blinking orange)

.go xyz -7033.840000 -4398.840000 9.583200 1 5.800970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892
