### ISSUE TITLE
This report is regarding the Un'Goro quest "The Legend of Aru-Ta...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6882]
> This report is regarding the Un'Goro quest "The Legend of Aru-Talis". I have to use Leakey's Core Driller in various places, however, the Ironstone Plateau does not seem to have an "area if intrest".

.go xyz -6875.550000 -2236.660000 -270.135000 1 0.169537

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
