### ISSUE TITLE
The Un'Goro quest "Venomhide Eggs" is not doable. It entails hav...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6883]
> The Un'Goro quest "Venomhide Eggs" is not doable. It entails having to collect 4 ravasaur eggs from their nests. They are described as having a "lighter colored shell", which I seem to have seen a number of times around the ravasaurs but cannot interact with them.

.go xyz -7756.360000 -2088.540000 -270.582000 1 3.228390

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
