### ISSUE TITLE
During the horde quest in Feralas called "A Strange Request" I h...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6887]
> During the horde quest in Feralas called "A Strange Request" I have to deliver a shrunken head to someone called Xerash Fireblade at the Lariss Pavilion. I have circled the area for a long time and am certain that this person simply does not spawn.

.go xyz -4120.840000 108.626000 75.801200 1 2.714150

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2075
