### ISSUE TITLE
Item "Rough Weightstone" tooltip says it lasts for 30 minutes ho...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6891]
> Item "Rough Weightstone" tooltip says it lasts for 30 minutes however the buff lasts for 60 minutes.

.go xyz -9648.740000 -658.237000 49.986100 0 4.722590

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1459
