### ISSUE TITLE
killed a bunch of beasts on 1 character, looted them and relogge...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6895]
> killed a bunch of beasts on 1 character, looted them and relogged to another character, then i skinned them with that second character, i got skill for skinning them but no leather. is that intended?

.go xyz 3547.160000 -4247.220000 103.739000 1 1.235480

**Comment by Bennylavaa** [comment]
this is normal, people can skin others npcs which have been fully looted and left.
