### ISSUE TITLE
Druids are only receiving .0308 crit per agi. It is supposed to ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6896]
> Druids are only receiving .0308 crit per agi. It is supposed to be .05 per agi. Unless of course youre doing custom stat weights then disregard.

Source:

https://wowwiki-archive.fandom.com/wiki/Critical_strike#Agility

.go xyz -8784.110000 360.683000 101.020000 0 0.237792

**Comment by Shadownflame** [comment]
There is something funky going on with stat calcs. Druids do get only 0.0305ish crit per agility from gear/buff, I can confirm this. However, their base value looks *way* too high:
![WoWScrnShot_072524_024043](https://github.com/user-attachments/assets/86cf9e3c-467f-463c-b1ca-cd816879a67f)

**Comment by Shadownflame** [comment]
Stats conversions rewritten by kaytotes to match TBC.
