### ISSUE TITLE
Quest - "Feathermoon Fishing"

Fished outside of feathermoon for...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6898]
> Quest - "Feathermoon Fishing"

Fished outside of feathermoon for a good 30 minutes with over 50 casts and did not catch the Marlin. Drop rate is very low or maybe non existant even.

.go xyz -8866.150000 651.367000 96.093000 0 3.604010

**Comment by Bennylavaa** [comment]
feathermoon is technically the sea and not water within Feralas this falls in line with blizlike.
