### ISSUE TITLE
Quest - "Murloc Mudkips" (fishing daily)

This quest may be brok...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6899]
> Quest - "Murloc Mudkips" (fishing daily)

This quest may be broken. Have been fishing in hillsbrad for 30 minutes without getting a single quest fish.

.go xyz -973.539000 -487.964000 3.151550 0 5.505810

**Comment by Bennylavaa** [comment]
not bugged they drop almost 80% of the time if I had to guess.
