### ISSUE TITLE
When fishing nothing happens after a click the moving bobber. Th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6901]
> When fishing nothing happens after a click the moving bobber. This may be a failed catch but there is no error given that says it failed.

.go xyz 4270.710000 -7443.340000 0.033557 1 3.322320

**Comment by Bennylavaa** [comment]
Confirmed, sometimes no loot but no error that fish has been missed, could be the vmangos loot Import issue.

**Comment by Shadownflame** [comment]
Might be some of the seasonal fish causing this?

**Comment by Bennylavaa** [comment]
This could be fixed a few updates ago will test it later.
