### ISSUE TITLE
Quest "The Plaguewood Cauldrons" does not work. When using the i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6903]
> Quest "The Plaguewood Cauldrons" does not work. When using the item "All-Purpose Neutralizing Agent" nothing happens after casting it near the cauldron.

.go xyz 2346.460000 -5131.580000 54.723400 0 3.311310

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7217
