### ISSUE TITLE
Quest "Advanced Alchemy" is labaled an Elywenn Forest quest inst...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6904]
> Quest "Advanced Alchemy" is labaled an Elywenn Forest quest instead of WPL

.go xyz 1006.910000 -2508.340000 58.640600 0 3.271160

**Comment by Bennylavaa** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/2305
