### ISSUE TITLE
Flight path from Marshals Refuge to Theramore has you fly throug...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6907]
> Flight path from Marshals Refuge to Theramore has you fly through walls/buildings in Steamwheedle Port.

.go xyz -3825.370000 -4516.580000 10.437200 1 0.827786

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3034 same issue since it's a connect flight from Un'goro through Gadgetzan
