### ISSUE TITLE
Tried selling back a level 45 pvp trinket (Emblem of Alacrity) a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6909]
> Tried selling back a level 45 pvp trinket (Emblem of Alacrity) and it got bugged in my bag. Its greyed out and i cant move it or equip it or delete it. Its just stuck there.

.go xyz 1458.890000 -1851.440000 125.736000 1 1.525920

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4745
