### ISSUE TITLE
Searing Totem V - (7400)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#691]
> AoE from mobs kills this totem?
`.go xyz 1303.970000 -1483.820000 71.601300 0 2.911920`

> Refuses to attack some mobs if you place it before the fight starts and pull the mob towards it. has to be recast when mob is in range.
`.go xyz 1455.130000 -1428.240000 75.615200 0 6.100920`

**Comment by ghost** [comment]
Cannot replicate either of these issues, presumably fixed in previous searing totem fix update.
