### ISSUE TITLE
The third part of "The Un'Goro Hunt" is catagorized as an Elwynn...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6910]
> The third part of "The Un'Goro Hunt" is catagorized as an Elwynn Forest quest. This is the part that requires the player to kill a Stegodon.

.go xyz -7328.750000 -1637.920000 -271.582000 1 1.718030

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2309
