### ISSUE TITLE
Do Slavers Keep Records?" may be bugged. Killed 50+ Dark Iron Sl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6912]
> Do Slavers Keep Records?" may be bugged. Killed 50+ Dark Iron Slavers in the Cauldron and the Slag Pits without seeing the records drop. If not bugged then a very low drop rate.

.go xyz -6515.140000 -1172.820000 309.394000 0 1.415090

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2288
