### ISSUE TITLE
I could not find any batteries after camping the noon shade ruin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6915]
> I could not find any batteries after camping the noon shade ruins for awhile. I think the spawns may be broken. This is for the quest "The Perfect Fuel".

.go xyz -7031.110000 -4542.370000 12.515500 1 2.163760

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
