### ISSUE TITLE
Inside ZF I was checking mob pathing to see if the paladin conse...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6917]
> Inside ZF I was checking mob pathing to see if the paladin consecrate aoe farm would work. It does not (unsurprising) but I did notice mobs were failing to return to their spawn locations and some just dissapeared all together. Seems like some sort of pathing issue when they try to return.

.go xyz -7189.180000 -3919.160000 19.392800 1 5.641580

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5602
