### ISSUE TITLE
My character's attack power is showing a permanent debuff of -47...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6920]
> My character's attack power is showing a permanent debuff of -47. 

I'm not sure what caused this but I dont recall seeing this prior to being hit by the Stonetalon Harpy's Curse of Recklessness

.go xyz -3349.740000 -2044.140000 96.526100 1 3.109640

**Comment by Shadownflame** [comment]
Definitely not the harpy COR. Cannot figure out based off the go xyz which creature's debuff did this.
