### ISSUE TITLE
Flight path from Tarren Mill to Sepulcher passes right through t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6921]
> Flight path from Tarren Mill to Sepulcher passes right through the Dalaran bubble.

.go xyz 276.160000 1346.450000 145.085000 0 1.628070

**Comment by Shadownflame** [comment]
Duplicate https://github.com/Project-Epoch/bugtracker/issues/8077
Related https://github.com/Project-Epoch/bugtracker/issues/6744
