### ISSUE TITLE
Zone: Barrens
Quest: Ignition

Quest text mentions that the supe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6922]
> Zone: Barrens
Quest: Ignition

Quest text mentions that the supervisor is in the control room but the mob patrols on the 2nd floor of the rig, outside of the room.

.go xyz 1063.720000 -3093.440000 80.236700 1 5.320010

**Comment by Shadownflame** [comment]
Blizzlike. The quest does not actually say he is in the control room, just tells you to "go up to the control room" because that's where he spawns.
