### ISSUE TITLE
General

This may be a major issue but it seems autoattack somet...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6923]
> General

This may be a major issue but it seems autoattack sometimes break. I've noticed it occur most often when the following scenario happened:
1- Place shaman totem near a mob.
2- Right click the mob to engage "auto-attack" at a distance.
3- Wait for the mob to aggro, run to and destroy the totem.
4- Attempt to reingage the mob through a spell.

Autoattack will then be broken with this specific mob until re-enabled on an other mob.

.go xyz -1589.870000 -3810.260000 21.613200 1 0.504616

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892
