### ISSUE TITLE
General Issue

Mobs will continue to use their abilities when ru...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6924]
> General Issue

Mobs will continue to use their abilities when running away. (Seen Quillboars stop their run to cast fireball and pirates stun while running away)

.go xyz -1613.360000 -3821.740000 14.730800 1 2.715540

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6624
