### ISSUE TITLE
Class: Shaman
Ability : Molten Blast

This ability should probab...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6925]
> Class: Shaman
Ability : Molten Blast

This ability should probably be unlocked after the acquisition of Flame Shock

.go xyz -972.243000 -4957.800000 2.895500 1 6.035910

**Comment by Hatson22** [comment]
Agreed. Levels 10-12 make more sense to me, but it's up to the devs.

**Comment by Shadownflame** [comment]
Rank1 is now learned at lvl 14.
