### ISSUE TITLE
Vicious Night Web Spider poison is not showing up as icon. Just ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6941]
> Vicious Night Web Spider poison is not showing up as icon. Just instantly causes destealth

.go xyz 2278.260000 -809.160000 69.988200 0 0.690578

**Comment by Shadownflame** [comment]
![WoWScrnShot_072524_015900](https://github.com/user-attachments/assets/9a62cfa8-30e9-438d-9e68-9e375722a37d)

Works fine here, figure it's some addon issue maybe some don't display it.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6937
