### ISSUE TITLE
Horde quest "CLUCK!" rewards nothing but 5xp. No egg.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6944]
> Horde quest "CLUCK!" rewards nothing but 5xp. No egg.

.go xyz 2226.680000 284.088000 35.187800 0 5.936220

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/296762b8-6d79-43dd-9f10-a7f4c8d87982)
Can't reproduce it leaves it on the ground. Most likely they are thinking of turtle wow where it gives it to you in the quest because trolls being mean and stealing peoples eggs.
