### ISSUE TITLE
using pre-raid gear i went to SM armory for fun.... and i seem t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6947]
> using pre-raid gear i went to SM armory for fun.... and i seem to be unhittable in bear or cat form from the front...... 36% dodge in bear 21% dodge in cat.... and even tho 0% parry, im parrying everything else it seems.

.go xyz 1818.110000 -427.091000 8.948840 189 3.102280

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6897
