### ISSUE TITLE
We have just completed a complete run of LBRS and we didnt get t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6957]
> We have just completed a complete run of LBRS and we didnt get the achievement, we killed Halycon & Gizrul but they didnt got counted for the achivement.

.go xyz -190.284000 -332.936000 64.424500 229 0.897761

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/46
