### ISSUE TITLE
as enhancement shaman, sometimes my off-hand dissapears during c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6962]
> as enhancement shaman, sometimes my off-hand dissapears during combat and it's not juist visual. It actually doesnt attack. but comes back if i sheathe.

.go xyz 2151.190000 -4632.830000 50.482200 1 0.964419

**Comment by Shadownflame** [comment]
I can't reproduce this. @Hatson22 ever experienced this?

**Comment by Hatson22** [comment]
Can't say I recall running into this.

**Comment by Shadownflame** [comment]
Sadly the report contains no info as to what weapons were equipped
