### ISSUE TITLE
Assisting Wizzle repair an airfighter, but there is no airfighte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6966]
> Assisting Wizzle repair an airfighter, but there is no airfighter to repair. I can still do the quest and finish it, but he is hitting on well thin air now.

.go xyz -4719.130000 -1682.970000 504.832000 0 2.411520

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2197
