### ISSUE TITLE
Upon receiving the quest "The Arcanaeum, Lady Lyrene says "I'll ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6973]
> Upon receiving the quest "The Arcanaeum, Lady Lyrene says "I'll have Marius make more scrolls but they'll cost you", which I think implies the FIRST scroll, the one you brought to her in the quest, is free. However, I didn't get any.

.go xyz 7893.250000 -4492.980000 705.464000 1 5.369590

**Comment by zana244** [comment]
The first one is for the quest, if you want more you pay... wording is fine.
