### ISSUE TITLE
In Wild Guardians (Moontouched Owlbeast part), the quest text sa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6978]
> In Wild Guardians (Moontouched Owlbeast part), the quest text says the mobs can be found in the North. However, while I didn't comb through the area, I'm pretty sure those have been replaced by the new nelf ruin area, and most/all moontouched owlbeasts can in fact be found in the South

.go xyz 6494.900000 -4845.710000 701.383000 1 0.560582

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6977
