### ISSUE TITLE
Storm Shadowhoof isn't in Everlook. He doesn't seem to be in Blo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6980]
> Storm Shadowhoof isn't in Everlook. He doesn't seem to be in Bloodvenom Falls either, where he was prior to patch 1.7. Consequently, several quests (Ursius of the Shardtooth, Brumeran of Chillwind, etc) cannot be completed.

For the record, he should be in Everlook. There's a reason why he was moved.

.go xyz 5412.520000 -646.785000 351.897000 1 0.635759

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7995
