### ISSUE TITLE
Salve via Hunting (and presumably the other profession-based ver...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6982]
> Salve via Hunting (and presumably the other profession-based versions), even the initial non-repeatable version, isn't available. If this is purposeful, then the flowers being there would be off

.go xyz 3945.200000 -1046.970000 245.902000 1 2.659300

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2089
