### ISSUE TITLE
Speak to Nafien quest cannot be completed, since Grazle is the l...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6984]
> Speak to Nafien quest cannot be completed, since Grazle is the location where Nafien would have been post-patch 1.9. In addition, Feathers for Nafien quest is obviously unobtainable because the quest-giver doesn't exist, but Feathers to Grazle didn't become available upon completing the non-repeatable Timbermaw Ally quest either.

.go xyz 6817.190000 -2083.240000 623.973000 1 0.342659

**Comment by zana244** [comment]
#950
