### ISSUE TITLE
Corrupted soul shards dropped off some mob in Un'goro. Should be...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6988]
> Corrupted soul shards dropped off some mob in Un'goro. Should be Felwood-only I reckon (and easy to check from DBs which mob that might be)

.go xyz -6784.170000 -2267.450000 -241.715000 1 0.852231

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1582
