### ISSUE TITLE
Winterfall Pathfinder - (7442)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#699]
> Faerie Fire ability (from this mob at least) does not prevent stealth.
It does successfully reduce armor though.
`.go xyz 6777.090000 -2610.080000 557.291000 1 0.281866`

> They apply Faerie Fire to you but you can still stealth even when the spell is applied
`.go xyz 6814.970000 -2547.710000 557.600000 1 4.749710`

> Their spell Faerie Fire is not preventing me from using prowl
`.go xyz 6787.120000 -2708.860000 558.735000 1 5.861590`

**Comment by zana244** [comment]
#2627
