### ISSUE TITLE
Readiness ability, final talent of survival tree, was found in m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6996]
> Readiness ability, final talent of survival tree, was found in marksman section of the spellbook. Additionally, Racial knowledge is sandwitched between MM and surv tabs, which seems weird

.go xyz 2088.480000 -4696.110000 40.297600 1 4.724690

**Comment by zana244** [comment]
Confirmed, most likely remnant of WoTLK where readiness is in MM tree.

**Comment by zana244** [comment]
#2839
