### ISSUE TITLE
I had previously made a report concerning Centipaar tunnelers di...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6997]
> I had previously made a report concerning Centipaar tunnelers disappearing, and speculated they might have... tunneling ability (but no script to pop up). Now I have a different hypothesis: I logged out in a location where I found one tunneler so as to kill it repeatedly, but upon relogging I saw a second one, and recollected seeing that spawn disappear when I entered the cave system... so perhaps their disappearance is related to entering a subzone they're in? (and logging there bypasses this)

.go xyz -7817.570000 -2594.610000 -48.450700 1 0.530856

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
