### ISSUE TITLE
Centipaar tunnelers, an objective for Silithid Scramble, have a ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#6998]
> Centipaar tunnelers, an objective for Silithid Scramble, have a habit of disappearing when approached. Several times I had a tunneler selected, approached it to shooting range, and it just disappeared from the view (in the way mobs usually disappear when server no longer updates the client about existence of the mob, like in phasing). I guess they have some "burrow" ability script, but no script for popping up and ambushing the player? Anyhow the quest is next to impossible to complete

.go xyz -8131.380000 -2769.280000 31.987500 1 0.318711

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
