### ISSUE TITLE
Riverpaw Taskmaster - (98)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#70]
> Hilariously cast lesser bloodlust on nearby gnolls that aren't even in combat with it.
`.go xyz -11013.600000 929.783000 36.678000 0 3.956320`

> Gave "Quick Bloodlust" to snake critter instead of himself.
`.go xyz -11140.400000 804.381000 34.743500 0 4.056710`

**Comment by Bennylavaa** [comment]
does cast lesser bloodlust on npcs around it.
