### ISSUE TITLE
In quest "Fit for a King", only "medium-level" beasts work, even...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7001]
> In quest "Fit for a King", only "medium-level" beasts work, even though the quest text says nothing about such quantification. It would really make if you could do the quest in the same time as Dental Records. Additionally, while channeling, targets are knocked prone visually, but they continue attacking while in this stun animation (also, is 8 second channel really necessary?).

.go xyz -4097.940000 2048.000000 86.039900 1 6.086240

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2267
