### ISSUE TITLE
In quest Tanaris Field Sampling, I cannot click any of the sampl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7005]
> In quest Tanaris Field Sampling, I cannot click any of the samples to test them (there should be Use: option). The quest appears uncompletable.

.go xyz -7154.540000 -3816.220000 8.417570 1 5.786010

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5665
