### ISSUE TITLE
Can't hand in "Signs of Treachery?" (certainly not to Nazeer BLo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7009]
> Can't hand in "Signs of Treachery?" (certainly not to Nazeer BLoodpike as the quest says) - which makes sense since it's 2.3 quest. Sealed letter probably shouldn't be dropping either.

.go xyz -3127.630000 -2856.180000 34.876100 1 0.957874

**Comment by zana244** [comment]
#1713
