### ISSUE TITLE
Perhaps Epoch is going for different conclusion in Shady Rest In...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7019]
> Perhaps Epoch is going for different conclusion in Shady Rest Inn chain than TBC did in 2.3 patch and the quest is consequently dropped, but I can't start suspicious hoofprints quest, which I checked was a part of vanilla version of the quest already,

.go xyz -3692.740000 -2538.780000 66.598400 1 5.234330

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2424
