### ISSUE TITLE
Mana shield mechanic from Karazhan on Lesser Dalaran Guardians i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7021]
> Mana shield mechanic from Karazhan on Lesser Dalaran Guardians is really really neat! However, don't you think the default ~3k mana is a bit much? I thought that for nonelites they felt heftier than they should, even with viper sting: what's a warrior, say, gonna do?

.go xyz 319.729000 139.862000 44.098500 0 5.674110

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/282
