### ISSUE TITLE
I had previously reported ferocious inspiration not triggering (...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7022]
> I had previously reported ferocious inspiration not triggering (at 1/3 talent ranks). I've relogged and it does work. However! While this would be far more difficult to debug, clearly the talent not being immediately active is a bug in its own right.

.go xyz 76.426400 -548.796000 144.057000 0 6.042860

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2905
