### ISSUE TITLE
In new quest "Pleading to Run" in Shadowprey Village, the drop r...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7028]
> In new quest "Pleading to Run" in Shadowprey Village, the drop rate of the quest items seems really low relative to frequency of the mobs, unless I had some oturageously bad luck. Okay, there's actually a dozen or so spawns (I checked from pserver databases), but I had to kill more mobs than there exists, and not everyone knows where to look so as to find the exact spawn locations. Doing the quest "normally" would, I reckon, be really awful.

.go xyz -1651.380000 3161.140000 23.918000 1 6.148890

**Comment by Shadownflame** [comment]
The drop rate seems fine.
