### ISSUE TITLE
Torek of Torek's Assault quest cannot be found at his usual spaw...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7034]
> Torek of Torek's Assault quest cannot be found at his usual spawn location. This may indicate the quest resetting improperly, supposing someone else did it before me.

.go xyz 1812.100000 -2155.610000 99.653700 1 6.057760

**Comment by Shadownflame** [comment]
Works fine. Spawn spot checks out, 3-4min for quest to complete, then 5min respawn.
