### ISSUE TITLE
Suffering Highborne - (7523)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#704]
> These are dropping the Frozen Ectoplasm for the .5 quest, Hunting Ectoplasm without the use of the quest item (Ectoplasmic Distiller)
`.go xyz 6522.510000 -4326.970000 673.706000 1 2.849020`

**Comment by zana244** [comment]
Solved on internal it seems, need to use distiller for frozen ecto to drop.
