### ISSUE TITLE
Think of the ANimals and waste Removal Quests in tanaris do not ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7042]
> Think of the ANimals and waste Removal Quests in tanaris do not grant group completeion it would be nice if they did.

.go xyz -7631.740000 -4930.130000 -2.002620 1 1.929230

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2233 https://github.com/Project-Epoch/bugtracker/issues/2234
