### ISSUE TITLE
Textures in Goldshire have gone white, I think the parts that ar...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7045]
> Textures in Goldshire have gone white, I think the parts that are supposed to be stone. Not sure if it's related but I just finished the custom quest that gives the green shoulders. It was fine before that.

.go xyz -9521.590000 137.336000 56.196600 0 1.870660

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3725
