### ISSUE TITLE
Leveling weaponskill is not correct. Just swapped to a 2h axe on...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7059]
> Leveling weaponskill is not correct. Just swapped to a 2h axe on my lvl 25 shaman and going from 0 and up takes crazy long. Killed 3 mobs now and only got 8 skill.......

.go xyz 1627.660000 -1952.320000 96.306700 1 5.336780

**Comment by Shadownflame** [comment]
2h was always a slog to skill up, but there indeed seem to be issues with the chance to level weapons. Work in progress by ktotes.

**Comment by Shadownflame** [comment]
Weapon skill up chance calculations reworked and is much closer to blizzlike now.
