### ISSUE TITLE
I killed with 2 characters the desertfox in tanaris and both tim...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7070]
> I killed with 2 characters the desertfox in tanaris and both times it kept making sounds after its death that didnt go away . only reloging fixed it or moving away from the place, as the sound was bound to the place it died both times and diminished when i went away

.go xyz -7266.810000 -3859.620000 12.641500 1 1.217730

**Comment by Shadownflame** [comment]
Corpse seems quiet now.
