### ISSUE TITLE
Unable to complete the quest "Reclaiming the Eggs" in the Hinter...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7075]
> Unable to complete the quest "Reclaiming the Eggs" in the Hinterlands due to not being able to interact with and loot the eggs on the ground.

.go xyz -407.030000 -2892.700000 84.511400 0 1.548680

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
