### ISSUE TITLE
in Mara Princess run. Rotgrip will trow you in the air and your ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7077]
> in Mara Princess run. Rotgrip will trow you in the air and your threat falss down and he attacks another player until tanks reach the water level and also the mountain guys on the way to Princess are bugged and cant move

.go xyz 2.438770 -164.149000 -197.692000 349 3.126530

**Comment by Shadownflame** [comment]
Seems already resolved. Rotgrip knocks you only a few yards upwards now and it's not enough to lose aggro. Primordial Behemoths reported elsewhere.
