### ISSUE TITLE
in Mara Princess run we we killed the Centaur Devotee firstand t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7078]
> in Mara Princess run we we killed the Centaur Devotee firstand the princess herself but she didnt drop any loot pls check out out and fix it .

.go xyz 34.735700 15.193900 -126.498000 349 2.109810

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6833
