### ISSUE TITLE
I as dead, so I ran back to the entrance of UBRS. But upon enter...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7080]
> I as dead, so I ran back to the entrance of UBRS. But upon entering, I'm still a ghost. I'm now death running inside the instance

.go xyz 86.948300 -280.282000 60.630600 229 1.924090

**Comment by Shadownflame** [comment]
Possibly related to https://github.com/Project-Epoch/bugtracker/issues/8292

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
