### ISSUE TITLE
in UBRS, after the first pull in Blackrock Stadium, there were n...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7082]
> in UBRS, after the first pull in Blackrock Stadium, there were no more groups coming out of the gates and we could not progress any further in the instance.

.go xyz 178.440000 -420.965000 110.472000 229 0.932274

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8012
