### ISSUE TITLE
Good Day. I'd like to inform you that the Wendigos by the Cave i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7084]
> Good Day. I'd like to inform you that the Wendigos by the Cave in Dun Morogh at Coords 42.22, 53.44 drops way to many armor pieces (espacially mail armor and some leather).

.go xyz -5350.310000 -27.858000 396.291000 0 0.117881

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1455
