### ISSUE TITLE
May be its not a bug but penance is clearly not a show spell its...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7089]
> May be its not a bug but penance is clearly not a show spell itself. However its usable in shadowform it should benefit from shadow weaving, can proc blackout, shoudlnt it generate a stack of shadow weaving then?

.go xyz -7078.340000 -3810.120000 8.600680 1 5.903770

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2987
