### ISSUE TITLE
Keeg Gibn the Ale & Wine vendor in Brewnall Village, Dun Morogh ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7090]
> Keeg Gibn the Ale & Wine vendor in Brewnall Village, Dun Morogh is giving away free alcohol. Get in while you can

.go xyz -5384.390000 303.284000 393.829000 0 3.528940

**Comment by zana244** [comment]
Hahahaha, not sure if intended!
Confirmed on internal.

**Comment by Shadownflame** [comment]
Not the NPC's issue, all alcohols are sold for free at any vendor. Items reported separately i.e. https://github.com/Project-Epoch/bugtracker/issues/1447
