### ISSUE TITLE
Goblin Engineer in Deadmines aggros whenm pulled with goblin bos...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7102]
> Goblin Engineer in Deadmines aggros whenm pulled with goblin boss but does not actually hit you. the golem he summons does not aggro you either.

only when you hit it back will it actually attack you

.go xyz -351.860000 236.349000 -103.928000 725 3.617460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/102
