### ISSUE TITLE
Think of The Animals
Puts you into combat - can only get out of ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7105]
> Think of The Animals
Puts you into combat - can only get out of combat like 40 yards from mob you triggered

also,if you remove shadow form,you cant reenter shadow form even if OOC. got to relog

.go xyz -7024.330000 -4855.300000 0.390162 1 5.128910

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2233
