### ISSUE TITLE
Healing Touch rank 3-7 should have a higher healing coeffecient....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7107]
> Healing Touch rank 3-7 should have a higher healing coeffecient. In classic any spells you learn above lvl 20 receive the higher +healing. However it seems like none of these spell ranks  are receiving any  bonus healing.

.go xyz -8802.280000 622.815000 96.776700 0 6.060600

**Comment by zana244** [comment]
#2600
