### ISSUE TITLE
Wmo portal between wind rider tower and its upper part is glitch...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7110]
> Wmo portal between wind rider tower and its upper part is glitching when you place the camera right on the stitch point. It was probably moved a bit or not baked after you made changes to Orgrimmar.

.go xyz 1668.720000 -4316.100000 59.229400 1 5.056370

**Comment by Shadownflame** [comment]
I think he probably means this but i'm not totally sure. Linking to other Org glitches https://github.com/Project-Epoch/bugtracker/issues/8006
![WoWScrnShot_081624_012947](https://github.com/user-attachments/assets/367c264a-7a35-4670-8e37-c44ca44eea00)
