### ISSUE TITLE
Fell through the ground in Razor Hill and died. I had exited the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7111]
> Fell through the ground in Razor Hill and died. I had exited the game while on the caravan after it stoped in razor Hill and when I got back in a fell through the ground.

.go xyz 322.108000 -4708.920000 -3843.060000 1 2.080320

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6736
