### ISSUE TITLE
The Gryphon eggs in Shadra'Alor for the quest Reclaiming the Egg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7112]
> The Gryphon eggs in Shadra'Alor for the quest Reclaiming the Eggs are not interactable with.

.go xyz -333.842000 -2913.290000 77.933500 0 6.110520

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
