### ISSUE TITLE
Had quite a few "Already Looted" messages when looting creatures...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7113]
> Had quite a few "Already Looted" messages when looting creatures. it only seems to be on cloth drops like linen or wool so far, possibly linked to Cloth Scavenging?

.go xyz -5176.430000 -1130.130000 43.789700 1 4.221910

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2942
