### ISSUE TITLE
Sometimes in melee, the player will stop attacking an enemy and ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7115]
> Sometimes in melee, the player will stop attacking an enemy and the "Too far away!" message will display. This can be fixed by re-targeting the enemy

.go xyz 2172.420000 -4606.310000 73.787100 0 0.510827

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7892
