### ISSUE TITLE
The quest Venomhide Eggs in Un'Goro Crater is bugged and the pla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7120]
> The quest Venomhide Eggs in Un'Goro Crater is bugged and the player cannot pick up the eggs

.go xyz -7454.740000 -1988.730000 -272.178000 1 1.794710

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
