### ISSUE TITLE
The in-game calendar lists the Kalu'ak Fishing Derby as occuring...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7129]
> The in-game calendar lists the Kalu'ak Fishing Derby as occuring every Saturday in Northrend, even though Northrend is not an accesible or playable continent.

.go xyz -9449.350000 -2260.730000 72.325100 0 0.089920

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8222
