### ISSUE TITLE
The quest "Learn to Ride in Elwynn Forrest" has the description ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7130]
> The quest "Learn to Ride in Elwynn Forrest" has the description to return to Stone Cairn Lake while tracked, even though the quest description in the quest log and quest NPC are located in Eastvale Logging Camp

.go xyz -9435.270000 -1376.770000 47.149500 0 3.584950

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1723
