### ISSUE TITLE
sacrificing voidwalker with mark of the wild fails to give shiel...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7138]
> sacrificing voidwalker with mark of the wild fails to give shield and removes motw from the warlock

.go xyz 328.256000 -1358.840000 37.391200 0 2.676560

**Comment by Shadownflame** [comment]
Cannot reproduce dispelling MOTW. The effect failing is likely due to the warlock gaining shadow resistance and the spell resisting, which is reported here https://github.com/Project-Epoch/bugtracker/issues/2790
