### ISSUE TITLE
In the Barrens doing Forgotten Pools quest. The trigger at the b...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7146]
> In the Barrens doing Forgotten Pools quest. The trigger at the bottom of the lake is bugged and won't let 'investigate' for the quest

.go xyz -1277.940000 -3011.900000 71.275000 1 5.958550

**Comment by zana244** [comment]
The .xyz is for the next quest in the series, The Stagnant Oasis (quest 877). For me both of them worked fine.
