### ISSUE TITLE
Location: At the Red Cloud Mesa starting point.

I cannot take o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7148]
> Location: At the Red Cloud Mesa starting point.

I cannot take on more than 1 objective at once. I got "The Hunt Begins", but not the one from Chief Hawkwind, even though there is an exclamation point over his head.

.go xyz -2878.630000 -223.231000 54.820800 1 1.224440

**Comment by zana244** [comment]
Could not reproduce? Could accept all quests.
