### ISSUE TITLE
Homing Robot OOX-17/TN - (7784)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#715]
> Seems to become 'inactive' if no one is nearby after the escort starts, meaning if unobserved it will never respawn and make it possible for part 1 of the escort to be turned in
`.go xyz -8437.530000 -4426.170000 9.606040 1 5.842690`

> all of the chicken escort quests do not share party wide quest completion credit
`.go xyz -8778.460000 -4364.190000 23.170200 1 0.316714`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2032
