### ISSUE TITLE
Quest: Gordunni Cobalt
Issue: Glowing blue spots do not appear t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7150]
> Quest: Gordunni Cobalt
Issue: Glowing blue spots do not appear to respawn.  I cleared them all and only got 10/12 of my quest cobalt and have not seen a single respawn to dig for more.

.go xyz -3962.310000 -152.569000 140.783000 1 6.068310

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8295
