### ISSUE TITLE
Zone - Dun Morogh. Mob - Zurka (lvl 10 Rare Troll by Iceflow lak...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7154]
> Zone - Dun Morogh. Mob - Zurka (lvl 10 Rare Troll by Iceflow lake).

Issue - Mob has 558 health. Please compare this health total to a lvl 12 dwarf shaman with 292 health, and the Rare lvl 12 Mob in Mulgore called Ghost Howl with 247 health.

I humbly submit that this lvl 10 mob has triple the amount of health it should most likely should have.

.go xyz -5233.450000 -95.702500 400.700000 0 4.436980

**Comment by zana244** [comment]
#1169
