### ISSUE TITLE
The design and wording for the quest "The Perfect Fuel" is terri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7159]
> The design and wording for the quest "The Perfect Fuel" is terrible. There is nothing indicative of interaction for it. I've been up and down the oil rig, under water, and on multiple of the floors. It is not a clear quest objective.

.go xyz -6563.870000 -4937.180000 -1.991820 1 2.382520

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
