### ISSUE TITLE
You can only have one Mana gem in your inventory, probably becau...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7161]
> You can only have one Mana gem in your inventory, probably because in TBC it becomes a single Gem with 3 charges, but you should be able to create more than one since they are a single charge. I would do this on longer fights like KT and c'thun, so i know you should be able to have more than one

.go xyz 1666.400000 1689.270000 120.719000 0 3.110530

**Comment by Shadownflame** [comment]
Resolved during beta.
