### ISSUE TITLE
Might want to double check fishing.  While I was out by Iceflow ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7170]
> Might want to double check fishing.  While I was out by Iceflow Lake (dwarf territories) leveling fishing, something happened that caused me to break fishing as if I moved merely by turning to the left and right in place, though that shouldn't happen.  Oddly fixed after hoping in the water and turning doesn't negate it.

.go xyz -5192.880000 2.129170 385.933000 0 1.795320

**Comment by Bennylavaa** [comment]
I cannot reproduce this
