### ISSUE TITLE
In BRD hall of crafting we are all stuck in combat

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7173]
> In BRD hall of crafting we are all stuck in combat

.go xyz 962.440000 -389.567000 -60.837700 736 3.968830

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7534
