### ISSUE TITLE
I am not sure if I am dumb or not, but the quest "Timbermaw ally...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7175]
> I am not sure if I am dumb or not, but the quest "Timbermaw ally" says the mobs are to "my west" - but none of those mobs are in the area. the "normal" mobs are still there

.go xyz 6785.410000 -2070.650000 622.674000 1 6.122620

**Comment by Bennylavaa** [comment]
fixed on ptr now
