### ISSUE TITLE
my pet cat is smaller than usual. Also the pet's pathing when se...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7179]
> my pet cat is smaller than usual. Also the pet's pathing when sending it in to attack is kind of broken. It'll spin in circles some times too.

.go xyz 10626.700000 1503.210000 1314.050000 1 5.904170

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
