### ISSUE TITLE
Mage Portal trainer in Stonard is missing

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7183]
> Mage Portal trainer in Stonard is missing

.go xyz -10452.200000 -3338.790000 20.181500 0 5.412590

**Comment by Shadownflame** [comment]
Confirmed, this was an oversight to my knowledge as the portal should be learnable on BC, however the NPC was Silvermoon affiliated which does not exist on Epoch. Suggest designing a new NPC to add for this purpose.

**Comment by Shadownflame** [comment]
NPC has been added. Unfortunately the croc quest mobs are on elite vanilla stats which makes the teleport quest incredibly difficult to solo for horde mages... there is a report open [here ](https://github.com/Project-Epoch/bugtracker/issues/7298)about that.
