### ISSUE TITLE
The Quest "Reclaiming the Eggs" seems to be bugged, I can't gath...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7186]
> The Quest "Reclaiming the Eggs" seems to be bugged, I can't gather any of the Gryphon Eggs around Shadra'Alor

.go xyz -402.616000 -2891.640000 86.513400 0 0.630769

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
