### ISSUE TITLE
Design: Dark Iron Scorpid - JC recipe - dropped off General Ange...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7189]
> Design: Dark Iron Scorpid - JC recipe - dropped off General Angerforge in BRD

.go xyz 835.715000 17.461500 -53.717000 736 6.041250

**Comment by zana244** [comment]
Could not get it in a few kills, I have to assume (for my sanity) that it was solved by VMangos Loot Update.
