### ISSUE TITLE
Centipaar Tunnellers need to be identified as Beasts like the Sa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7196]
> Centipaar Tunnellers need to be identified as Beasts like the Sandreavers so hunters can find them.

.go xyz -7919.150000 -2513.920000 10.740500 1 3.972230

**Comment by Shadownflame** [comment]
Probably related https://github.com/Project-Epoch/bugtracker/issues/7580

**Comment by Shadownflame** [comment]
Actually the opposite, none of the Centipaar should be classified as beasts. They are supposed to be Uncategorized.
