### ISSUE TITLE
Quest - Silithid Scramble

Low spawn rate for Centipaar Tunneler...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7197]
> Quest - Silithid Scramble

Low spawn rate for Centipaar Tunnelers... area filled with Sandreavers

.go xyz -7845.590000 -2612.020000 -51.016200 1 6.276710

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
