### ISSUE TITLE
Learn To Ride in Orgrimmar states: - Return to Kildar in Azshara...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7200]
> Learn To Ride in Orgrimmar states: - Return to Kildar in Azshara instead of Orgrimmar

.go xyz -7115.970000 -3806.550000 8.369880 1 3.886920

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1723
