### ISSUE TITLE
I have died and after logging out and back in a few hours later ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7201]
> I have died and after logging out and back in a few hours later I cannot retrieve my body in ZF.

.go xyz -6861.080000 -2959.170000 8.886250 1 4.429640

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8292 related
https://github.com/Project-Epoch/bugtracker/issues/6072 dupe
