### ISSUE TITLE
Two bugs with night elf racial: 1) touch of elune only affects m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7206]
> Two bugs with night elf racial: 1) touch of elune only affects main hand melee speed, not off-hand or ranged speeds; and 2) when switching out of the night elf racial the touch of elune buff stays, but will no longer follow the day/night cycle as far as I can tell.

.go xyz -4913.870000 -1148.440000 501.482000 0 3.106480

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2960
