### ISSUE TITLE
Follow up on earlier bug report regarding [Kill Command]:

I now...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7208]
> Follow up on earlier bug report regarding [Kill Command]:

I now have approximately 1 million damage in my recount damage logs. Neither me or my pet has registered any Kill Command damage. The only thing I have is 2 instances where Kill Command apparently evaded, but that's it.

So I definitely think Kill Command is broken at the moment.

.go xyz -7846.290000 -2653.850000 172.736000 0 3.032000

**Comment by zana244** [comment]
#2900
