### ISSUE TITLE
Kill Command doesn't seem to work at all. It triggers and can be...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7209]
> Kill Command doesn't seem to work at all. It triggers and can be cast as expected, but it doesn't seem like damage is every applied to the target. It shows up in the combat log as having been cast, but there's no entry with damage.

.go xyz 7485.440000 -4294.160000 652.459000 1 1.772260

**Comment by zana244** [comment]
#2900
