### ISSUE TITLE
This plague cauldron also does not work for the [The Plaguewood ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7216]
> This plague cauldron also does not work for the [The Plaguewood Cauldrons] quest. The [All-Purpose Neutralizing Agent] can be used, but nothing happens.

.go xyz 2717.390000 -5423.370000 161.564000 0 5.717560

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7217
