### ISSUE TITLE
The quest [The Plaguewood Cauldrons] does not progress when I us...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7217]
> The quest [The Plaguewood Cauldrons] does not progress when I use the [All-Purpose Neutralizing Agent] at this location. The item is used, but nothing happens with the quest. I do not know if this applies to the other plague cauldrons as well, since this is the first I've found.

.go xyz 2472.350000 -3730.740000 183.054000 0 5.847250

**Comment by Bennylavaa** [comment]
this works, they are trying to use the wrong cauldron that is not in the Plaguewoods
