### ISSUE TITLE
The Nafien and Grazle NPCs in Felwood have been merged/moved aro...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7222]
> The Nafien and Grazle NPCs in Felwood have been merged/moved around? Now only Grazle is present and he's standing where Grazle used to be, but he still has the [Speak to Nafien] quest, which seems impossible now.

.go xyz 3795.000000 -1320.670000 203.568000 1 3.491580

**Comment by zana244** [comment]
#950
