### ISSUE TITLE
I think doing the "Wanted: Doszurd" quest flagged me for PvP. I ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7224]
> I think doing the "Wanted: Doszurd" quest flagged me for PvP. I wasn't paying too much attention, so I guess it could have been something else, but I certainly didn't flag on purpose.

.go xyz -6974.580000 -4844.740000 8.019040 1 4.884160

**Comment by zana244** [comment]
#1233
