### ISSUE TITLE
Grouped chicken escort quests don't seem to work. They offer the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7225]
> Grouped chicken escort quests don't seem to work. They offer the "Player is starting quest" popup and the quest is accepted, but only the starting player seems to get credit when it's completed.

.go xyz -7017.140000 -4667.610000 10.772200 1 4.588290

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2032
https://github.com/Project-Epoch/bugtracker/issues/2043
