### ISSUE TITLE
Both the horde and alliance versions of "Escaping Airheart" esco...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7228]
> Both the horde and alliance versions of "Escaping Airheart" escort quest seems to be too hard. Tried twice with a 47 hunter and a 53 paladin. We could handle the mobs (only just) but failed at keeping the NPCs alive since they just had too little HP. The Fort Airheart area was low 40s elite mobs, so we expected the escort quests to be doable with just the two of us.

.go xyz -4842.710000 -861.577000 501.914000 0 3.591670

**Comment by Bennylavaa** [comment]
also has typo "We will morn the loss of Gerald in time too." should be "We will mourn the loss of Gerald in time too."

**Comment by Bennylavaa** [comment]
escort needs tweaking for both horde and alliance versions.
