### ISSUE TITLE
- All rank (lvl 45, so rank 1 to 3) heal players without needed ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7234]
> - All rank (lvl 45, so rank 1 to 3) heal players without needed to be in the same party or raid.
- screenshot of the proof on discord (grindplayer, 14:49)

.go xyz -6231.190000 332.347000 383.156000 0 5.046180

**Comment by Shadownflame** [comment]
Couldn't find any priest spell that would heal wrong targets.
