### ISSUE TITLE
A lost Warrior quest Jailor Eston is nowhere to be found. I look...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7242]
> A lost Warrior quest Jailor Eston is nowhere to be found. I looked all over the severs, inside the keep and outside, used Track humanoids, he wasn't there. 
His name is also Jailor Eston, there's a typo within quest objective calling him Jailer Eston.

.go xyz -474.540000 -1503.800000 87.577100 0 2.714760

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/1e726a2b-47e8-43bf-9317-b3e2f1b154e7)
He exists however there is a typo in quest ID 26389

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2208
