### ISSUE TITLE
At level 60 I did training of skills and then respecc'd my prima...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7244]
> At level 60 I did training of skills and then respecc'd my primary specialization.  I filled it in again (nearly full disc) and realized I still had light well as a spell, trained.  Lightwell is a trained spell in my OFFspec that I had not tampered with upon reaching 60.  

I have free lightwell spell as disc priest at 60 ;P

.go xyz -3590.450000 -4321.430000 7.176390 1 3.553510

**Comment by Shadownflame** [comment]
This issue still persists. You unlearn Lightwell (rank1) upon changing spec, but not rank2 or rank3

**Comment by kaytotes** [comment]
Next deploy.
