### ISSUE TITLE
For the Alliance Hinterland Quest: Reclaiming the Eggs, one cann...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7250]
> For the Alliance Hinterland Quest: Reclaiming the Eggs, one cannot loot the eggs (quest item) laden about the area called Shadra'Alor, where the quest says to search for them.

.go xyz -388.637000 -2958.700000 91.454800 0 1.098060

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
