### ISSUE TITLE
Winterspring Quest "A Little luck!  Quest NPC Witch Doctor MauÃ¡r...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7256]
> Winterspring Quest "A Little luck!  Quest NPC Witch Doctor MauÃ¡ri is not where it should be.

.go xyz 6725.060000 -4708.520000 722.182000 1 4.188870

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/869
