### ISSUE TITLE
Quest Azshara " A Meeting with the Master" the Undammaged Hippog...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7257]
> Quest Azshara " A Meeting with the Master" the Undammaged Hippogryph Feather 0/2 dosnÂ´t drop!

.go xyz 4111.070000 -5458.040000 109.381000 1 2.186300

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2400
