### ISSUE TITLE
i died on the way down the overlook cliffs. died kind of mid mou...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7262]
> i died on the way down the overlook cliffs. died kind of mid mountain. priest could cast rez but wasnt landing on me . twice

.go xyz 237.118000 -4093.970000 120.445000 0 3.847050

**Comment by Shadownflame** [comment]
Unfortunately the go xyz recorded is not on the mountainside to reproduce death spot, so completely useless.
