### ISSUE TITLE
we wipe on hydro in zf but we killed her. runback time too long ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7265]
> we wipe on hydro in zf but we killed her. runback time too long she despawned.

.go xyz 1681.920000 1177.940000 8.885770 209 2.283870

**Comment by zana244** [comment]
Possibly related #8245. 5 Min despawn time for corpses, bosses may need a bit higher timer tbh.
Tbh even ppl on wow classic complained about hydromancer hahaha
https://us.forums.blizzard.com/en/wow/t/boss-bodies-despawning/973288/2

**Comment by Shadownflame** [comment]
corpse despawns resolved
