### ISSUE TITLE
THere are no Filter Parts for "Water Co. Saviour" and also no Ba...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7270]
> THere are no Filter Parts for "Water Co. Saviour" and also no Batteries for "The Perfect Fuel" spawning anymore

.go xyz -7116.760000 -3972.070000 10.791400 1 2.087930

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
