### ISSUE TITLE
The Blackhoof Armaments fpr the Quest "Arms of the Grimtotems" i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7275]
> The Blackhoof Armaments fpr the Quest "Arms of the Grimtotems" in this village are not interactable

.go xyz -2469.570000 -3185.070000 33.619300 1 2.046650

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/3195
