### ISSUE TITLE
Hello !
i took the fly from sepulcher to the bulwark, while flyi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7283]
> Hello !
i took the fly from sepulcher to the bulwark, while flying, i went through the dalaran dome, empty inside :p

.go xyz 1740.510000 -723.103000 59.916800 0 6.275860

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/6744

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
