### ISSUE TITLE
in the smelting room if you face the outerwall from the guard ra...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7289]
> in the smelting room if you face the outerwall from the guard rail that separates the dwonstair from the furnace you can see your shadow under the bars of the guard rail. It is wrong environment behaviour i think

.go xyz -320.835000 285.934000 -70.488400 725 1.139740

**Comment by Shadownflame** [comment]
Yep, shadows are projected to a really weird spot from up here, it feels as though the game is not aware you're standing on the platform but treats you as if you were floating. No matter how deep into the platform you move, your shadows are projected to the ground faaaaaar below:
![WoWScrnShot_081624_012342](https://github.com/user-attachments/assets/9f73a2b2-b8ea-45c9-b27d-c9d3f38cc147)
Extremely minor issue but I guess it can throw some people off.

**Comment by kaytotes** [comment]
Blizzlike. Nothing we can do about this.
