### ISSUE TITLE
Hunter attack shows as axe and not bow. Minor but a little thing :)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7294]
> Hunter attack shows as axe and not bow. Minor but a little thing :)

.go xyz 1692.410000 1608.750000 124.684000 0 4.164530

**Comment by zana244** [comment]
Auto attack (general spellbook) is melee weapon icon and Auto Shot (marksmanship) is ranged weapon icon, everything works as intended.
