### ISSUE TITLE
Ironforge graveyard is broken

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7296]
> Ironforge graveyard is broken

.go xyz -4816.740000 -1144.300000 482.557000 0 0.113702

**Comment by zana244** [comment]
Dying in ironforge does not send you to a graveyard, but rather spawns you as a ghost directly on top of your corpse. Particularly problematic if you die in lava in the Great Forge.

**Comment by kaytotes** [comment]
Next deploy

**Comment by TetraDisaster0** [comment]
Fix appears to work according to this comment, it's been applied to the main branch. 
https://github.com/TrinityCore/TrinityCore/issues/30461
