### ISSUE TITLE
Young Goretusks constantly spam their rushing charge ability cau...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7299]
> Young Goretusks constantly spam their rushing charge ability causing all their melee attacks to deal extra damage instead of only casting it once when aggro'd like other mobs such as the Mangy and Elder Mountain Boars in Loch Modan

.go xyz -10155.200000 895.289000 37.964300 0 1.465090

**Comment by zana244** [comment]
#75
