### ISSUE TITLE
Prowler - (118)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#73]
> Pretty much every beast mob resets if I touch the water, not even going deep in the river, just by touching the water it INSTANTLY resets the fight
`.go xyz -9704.860000 -1042.280000 39.348200 0 5.004900`

> Leash range is kind of weird. Ran away once I got to a certain spot with another Prowler and a Bear...
`.go xyz -9708.120000 -1048.250000 39.772800 0 4.216450`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
