### ISSUE TITLE
Witch Doctor Uzer'i - (8115)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#730]
> The quest [Weapons of Spirit ] Cannot be picked up after completing [Natural Materials]
`.go xyz -4376.820000 267.405000 25.491300 1 1.470870`

> 'Weapons of Spirits' quest chain.
First quest have WRATH text, but works like in Vanilla(turnin in Orgrimmar)
The second have WRATH text and works like WRATH quest, but the thext on item from Vanilla
The rest works as it should
`.go xyz -4374.420000 265.985000 25.553200 1 2.092040`

**Comment by zana244** [comment]
#2075 
Need to do orgri turn in for Weapons of spirit
