### ISSUE TITLE
I have collected two ancient batteries for The Perfect Fuel and ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7303]
> I have collected two ancient batteries for The Perfect Fuel and have not seen any more spawn at Noonshade Ruins. I also did this quest a few days back and there were an abundance of them here.

.go xyz -6890.270000 -4365.020000 15.110000 1 2.717370

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
