### ISSUE TITLE
Touching the Filter parts for the quest "Water Co. Saviour" in T...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7306]
> Touching the Filter parts for the quest "Water Co. Saviour" in Tanaris near Steamwheedle Port takes a druid out of Aquatic Form.
Not interacting with it, just swimming against it ends the shapeshift

.go xyz -6877.010000 -4983.990000 -5.807010 1 0.622369

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
