### ISSUE TITLE
Gryphon Eggs fot the quest "Reclaiming the Eggs" in Hinterlands ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7308]
> Gryphon Eggs fot the quest "Reclaiming the Eggs" in Hinterlands can not be interacted with/picked up

.go xyz -439.348000 -2879.790000 85.613000 0 5.831170

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
