### ISSUE TITLE
pally blessings

one pally is able to buff me with both great bl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7317]
> pally blessings

one pally is able to buff me with both great blessing of wisdom and greater blessing of salv. Not sure why or of other combinations. They were undead paladin if it matters

.go xyz -2902.540000 -254.173000 55.195700 1 4.154970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6326
