### ISSUE TITLE
aru-talis site four

site four doesn't explicitly say aru-talis ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7318]
> aru-talis site four

site four doesn't explicitly say aru-talis site four unlike the other 3 sites once you enter the area.

I actually found this gave off a much more mysterious vibe when I came upon it. And absolutely loved it. 

I guess im suggesting to remove the other 3 location names.

.go xyz -8279.030000 -1149.470000 -179.645000 1 4.115590

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2317
