### ISSUE TITLE
soul mirror

if this is what I think it is that being a soulston...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7319]
> soul mirror

if this is what I think it is that being a soulstone wouldn't this be abused to soul stone an entire raid group? Maybe it would get fixed before it ever become "mandatory" like world buffs were in classic wow (players are silly like that) but I forsee the first raiding guild farming grombolar soulstones to beat the first difficult raiding content on the server. Which seems like cheating to me. Just my 2cents.

.go xyz -7961.920000 -1035.100000 -272.740000 1 0.589885

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/09cf00a7-f2a6-42e6-aab6-168f06c1fce9)
