### ISSUE TITLE
druid ability Rip

sometimes doesn't consume combo points yet is...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7320]
> druid ability Rip

sometimes doesn't consume combo points yet is still applied. Tried to find out how to reproduce but can't figure it out. I've seen it happen several times now that I've noticed in about 2 hours of play

.go xyz -7762.080000 -1670.300000 -271.639000 1 1.515120

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4077
