### ISSUE TITLE
quest: the southern pylon ungoro crater

the objective is comple...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7322]
> quest: the southern pylon ungoro crater

the objective is completed at a large distance away. Maybe make it so you have to be closer to the pylon itself

.go xyz -8126.670000 -1129.690000 -223.110000 1 4.981620

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2511
