### ISSUE TITLE
mage portal crossfaction

I took a stormwind portal as a horde t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7324]
> mage portal crossfaction

I took a stormwind portal as a horde toon from an alliance mage in dungeon group without thinking. Should defintely disable that lol

I think it's pretty funny. im stuck here with hearth on cd lol

.go xyz -8998.140000 861.254000 29.620600 0 2.250000

**Comment by Shadownflame** [comment]
As per Eredun this is not intended. Each faction should only be able to take portals to their own cities.
