### ISSUE TITLE
zul'farrak

the troll boss in the temple surrounded by the grave...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7325]
> zul'farrak

the troll boss in the temple surrounded by the graves didn't ressurect any mobs from inside the graves. I don't know if that's vanilla like or not but I think it should. 

I don't like how fast dungeons go these days with ppl going as fast as they can so I think things that slow it down are good.

.go xyz -4676.550000 1199.970000 110.921000 1 1.897420

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/683
