### ISSUE TITLE
Vampiric Touch

As a tauren druid the human priest's vampiric to...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7326]
> Vampiric Touch

As a tauren druid the human priest's vampiric touch didn't give me mana returns in zf dungeon

vampiric embraced worked though

.go xyz -5466.340000 -2518.320000 98.851800 1 1.397620

**Comment by Shadownflame** [comment]
Probably related https://github.com/Project-Epoch/bugtracker/issues/7577

**Comment by Shadownflame** [comment]
Works the same way as raid buffs, won't jump to pvp flagged targets, but works fine if everyone is PVE.
Both Vampiric Embrace and Vampiric Touch.
