### ISSUE TITLE
When you log out and back in while you have Presence of Mind act...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7336]
> When you log out and back in while you have Presence of Mind activated it makes the tooltip dissapear

.go xyz -7016.560000 -3383.680000 14.070900 1 6.176610

**Comment by Shadownflame** [comment]
Tooltip on action bar is fine after relog. Tooltip on buff is fine too. Tooltips in talent page and spellbook are fine as well. 
This must be an isolated UI issue.
