### ISSUE TITLE
Not sure if this is intended behavior, but as a prot pally, I am...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7338]
> Not sure if this is intended behavior, but as a prot pally, I am able to seal wisdom, then judge multiple targets - I do not lose my seal, and I am able to maintain judgements on multiple targets, I have successfully had judgement of wisdom concurrently running on 3 targets without any issues until they died. This is definitely not how the tooltip reads and it is not how any classic paladin I have used has functioned

.go xyz -337.014000 293.850000 -70.587500 725 0.684158

**Comment by Shadownflame** [comment]
Cannot reproduce Seal not being consumed by judgement. As for keeping up JOW on multiple targets, that is a normal mechanic. Your melee attacks refresh the duration so you can keep it rolling on as many as 10 targets even. You can only have 1 judgement effect active per paladin on your current target, that works fine, but does not stop you from judging multiple targets.
