### ISSUE TITLE
When you step on the ground at the top of Orgrimar's flight towe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7351]
> When you step on the ground at the top of Orgrimar's flight tower, he makes a strange noise and the character disappears for a few seconds until you move again.

.go xyz 1670.900000 -4330.610000 61.110000 1 1.283330

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8006
My character does vanish in this spot. Never seen this happen on another server, cannot be blizzlike:
![WoWScrnShot_081624_012108](https://github.com/user-attachments/assets/cd3ddf42-fb05-4128-8912-4a57a1c22ca4)
