### ISSUE TITLE
Omgorn the Lost - (8201)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#736]
> no loot
`.go xyz -8354.580000 -2787.060000 14.971500 1 4.010870`

> Rare dropped no green items.
`.go xyz -8413.390000 -2890.160000 9.484510 1 2.279550`

> Rare spawn dropping no loot
`.go xyz -8423.870000 -2890.730000 8.719770 1 3.401160`

> Pretty strong for a 50 rare. Couldn't kill as 49 pally with all CDs.
`.go xyz -8399.950000 -2904.520000 9.259350 1 3.286680`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249 related

**Comment by Shadownflame** [comment]
Fixed
