### ISSUE TITLE
In the quest "A Loa's Respect" in Anje'Watha, there is a spellin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7360]
> In the quest "A Loa's Respect" in Anje'Watha, there is a spelling error: Searing Roc's (possesive) should be Searing Rocs (plural) in the main quest text. The Quest Objective at the bottom has it spelled correctly.

.go xyz -9687.370000 -4137.500000 128.464000 1 2.819110

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/82f18dcd-76fa-4901-bfc7-c986ca81fa7f)

**Comment by Kestrana** [comment]
Fixed in PR https://github.com/Project-Epoch/epoch-core/pull/1514
