### ISSUE TITLE
I was farming the Timbermaw Hold reputation and noticed somethin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7366]
> I was farming the Timbermaw Hold reputation and noticed something:

Grazle is an npc who gives some quests that get you started with the rep farm. He was located south of Felwood in vanilla, but since Epoch uses the WotLK client, Grazle is now north of Felwood as he was moved there in patch 1.9 or so.

The problem is that hes using the spot of Nafien, another npc that he ventually tells you to talk to. So apparently Nafien is gone as I wasn't able to find her.

.go xyz 6643.920000 -2082.230000 591.313000 1 0.011570

**Comment by zana244** [comment]
#950
