### ISSUE TITLE
The perfect Fuel - quest in Tanaris at oil rig - I didnt manage ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7368]
> The perfect Fuel - quest in Tanaris at oil rig - I didnt manage to fing a valve to steal oil, probably missing or not visible

.go xyz -7130.140000 -4316.430000 9.064740 1 5.437480

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2229
