### ISSUE TITLE
Elite Dragonkin and drakes barely hit harder with melee attacks ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7371]
> Elite Dragonkin and drakes barely hit harder with melee attacks than normal mobs. Their ability damage seems fine however. 

The drakes also stop turning when casting their  breath, which makes the ability easily avoidable.

.go xyz -8046.780000 -2278.930000 132.178000 0 1.962760

**Comment by zana244** [comment]
#666
