### ISSUE TITLE
Can't interract with the Ogre Corpse after completing the Curios...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7375]
> Can't interract with the Ogre Corpse after completing the Curios Gordocc quest, also some of the Gorillas fall through the terrain after being given bananas.

.go xyz -3529.300000 2445.680000 56.617200 1 5.290260

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1828
https://github.com/Project-Epoch/bugtracker/issues/8294
