### ISSUE TITLE
The Quest Item for prime slime does not seem to do anything, but...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7378]
> The Quest Item for prime slime does not seem to do anything, but you get the quest item from killing the direglob, is this is the intended way to finish the quest, then it should be probably marked aas elite. Also the mob can be los cheesed and kited supper easily becaouse of the ranged long cast ability it has with no cd. It will never chase players if you move out of melee it seems.

.go xyz 353.528000 -3758.100000 107.276000 0 0.271978

**Comment by Shadownflame** [comment]
What quest item? There is nothing given with the quest.
