### ISSUE TITLE
Kregg Keelhaul - (8203)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#738]
> This rare didn't drop anything notable.
`.go xyz -8105.220000 -5304.810000 0.569734 1 1.855080`

> Didn't drop anything. :(
`.go xyz -8130.580000 -5207.550000 12.865000 1 0.492748`

> No items dropped
`.go xyz -8116.070000 -5265.350000 1.577120 1 4.835520`

**Comment by Bennylavaa** [comment]
fixed
