### ISSUE TITLE
Seems like that Centipaar Tunnelers are despawning after a few m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7380]
> Seems like that Centipaar Tunnelers are despawning after a few minutes, which makees finding and killing 6 for the quest Silithid Scramble extremely tedious, (Might be because its the same mob spawned during the original 'Gadgetzan Water Survey' quest were you need to investigate the vater, and using the quest item there also spawns 2 Tunnelers)

.go xyz -8053.400000 -2553.240000 -39.370400 1 5.944890

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
