### ISSUE TITLE
The Contagion rot disease you get from woodpaw mongrels stacks, ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7383]
> The Contagion rot disease you get from woodpaw mongrels stacks, double reducing attack speed, i think its just supposed to reapply and refresh its duration

.go xyz -4897.370000 473.217000 17.215200 1 0.691494

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2629
