### ISSUE TITLE
Not sure if intensed but Rogue stealth detection seems alittle h...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7386]
> Not sure if intensed but Rogue stealth detection seems alittle high, even at a distance they see you. Also if detected you can sometimes avoid being taken out of stealth by just walking away a short distance.

.go xyz -7986.400000 -5304.360000 1.916290 1 1.764700

**Comment by ghost** [comment]
Fixed in https://github.com/Project-Epoch/TrinityCore/pull/22
