### ISSUE TITLE
Soriid the Devourer - (8204)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#739]
> Dropped nothing at all
`.go xyz -7953.490000 -2560.690000 10.447800 1 5.902100`

> This rare dropped a single gray.
`.go xyz -7919.480000 -2563.310000 9.112780 1 2.008300`

> Didn't drop anything. Just like all the other rares in-game with no unique loot on them.
`.go xyz -7898.360000 -2578.290000 9.200650 1 4.022590`

> Dropped no loot upon kill.
`.go xyz -7928.360000 -2573.040000 8.850650 1 4.419280`

> Drops no loot
`.go xyz -7932.290000 -2577.390000 9.057490 1 0.919520`

> 0 loot from the rare
`.go xyz -7910.100000 -2560.880000 10.642900 1 2.144040`

> he drop no loot... sadness :(
`.go xyz -7941.320000 -2569.580000 8.996410 1 0.925401`

> no loot
`.go xyz -7940.710000 -2581.490000 9.099340 1 1.710930`

**Comment by Bennylavaa** [comment]
on purpose for beta
