### ISSUE TITLE
Tooltip for Improve Righteous fury does not update for protectio...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7393]
> Tooltip for Improve Righteous fury does not update for protection paladin

.go xyz -3795.530000 1840.510000 129.487000 1 3.948720

**Comment by ghost** [comment]
Can't replicate, the tooltip updates fine

**Comment by Shadownflame** [comment]
They probably mean the buff shown under portrait. Doesn't update for any spell with talents on 3.3.5.
