### ISSUE TITLE
Quest Cuergo's Gold - When clicking on the pirate flag, the host...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7399]
> Quest Cuergo's Gold - When clicking on the pirate flag, the hostile mobs spawn in the same place as the chest itself, and are stacked on top of each other. After 2 deaths, and when the chest and the hostile mobs despawn, the flag becomes unclickable, which means that player has to abandon the quest and regain all the map pieces to redo the quest.

.go xyz -10247.300000 -3982.340000 1.779660 1 3.073750

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2068
