### ISSUE TITLE
Longsnout - (119)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#74]
> These have an insane resist rate to Drain Soul even while im 3 levels above
`.go xyz -9853.690000 672.895000 36.844800 0 5.020020`

**Comment by Bennylavaa** [comment]
resists happen on my level 60 warlock as well.

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/75
Shadow resistant boars, what the heck.
