### ISSUE TITLE
Haarka the Ravenous - (8205)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#740]
> This rare didn't drop anything at all.
`.go xyz -9270.100000 -3891.830000 10.152000 1 6.235000`

> Did not drop any loot.
`.go xyz -9262.590000 -3889.740000 10.698200 1 3.705420`

> No loot on rare... sadness
`.go xyz -9265.140000 -3898.790000 10.077100 1 4.737800`

**Comment by Bennylavaa** [comment]
on purpose for beta
