### ISSUE TITLE
We just killed the Sentinel Archaedas in Uldaman unfortunately h...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7402]
> We just killed the Sentinel Archaedas in Uldaman unfortunately he wasn't lootable...
Great fight nontheless!

.go xyz 99.029400 272.353000 -51.779200 70 2.113690

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4158
