### ISSUE TITLE
AI pathing behavior for underwater murlocs at Crystal Lake in El...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7408]
> AI pathing behavior for underwater murlocs at Crystal Lake in Elwynn Forest is broken. Murlocs stand stationary on bottom of lake.

.go xyz -9489.510000 -209.000000 58.225000 0 4.703910

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
