### ISSUE TITLE
So I have a shitty logitech mouse that doubleclicks on left clic...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7413]
> So I have a shitty logitech mouse that doubleclicks on left click.
Upon character creation that doubleclick issue happened - which means sending out 2 left clicks in rapid succession faster than humanly possible.
This lead to the creation of two characters with the same name, in this case "Emina" and they are actually separate on my character select screen, despite sharing the same name.
I'm going to keep both of them without deleting so you can check out what happened in the database.

.go xyz -8949.950000 -132.493000 83.531200 0 0.000000

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/7a21981b-b121-4adf-912e-a29c602f9997)
This feels like it could cause some big issues with stuff like the mailing system

**Comment by kaytotes** [comment]
https://github.com/Project-Epoch/TrinityCore/commit/255568162f4329d630b212291d7b56e516f6834a

**Comment by T1ti** [comment]
official TC fix commit @kaytotes 
https://github.com/Grimdhex/TrinityCore/commit/49ab2bbe3883749594fe92a752e1d618c625d1b6
