### ISSUE TITLE
I resurreceted my party membe with Ancestral Spiritr in Gadgetza...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7422]
> I resurreceted my party membe with Ancestral Spiritr in Gadgetzan and the guards aggroed me and killed me

.go xyz -7195.140000 -3771.430000 8.623150 1 6.111950

**Comment by Shadownflame** [comment]
Sounds like somebody forgot rezzing can flag you.
Need to double check if rezzing an unflagged target may trigger the same response though.

**Comment by Bennylavaa** [comment]
did some tests today and it seemed fixed.
