### ISSUE TITLE
The Firemane Ashtail/Scout and Scalebane mobs seem extremely ove...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7429]
> The Firemane Ashtail/Scout and Scalebane mobs seem extremely overtuned, they are statted like elite mobs the same level with 5-6k hp and hitting for 300+ with auto attacks

.go xyz -4544.410000 -2984.990000 34.865200 1 0.260976

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7298
