### ISSUE TITLE
when swiftpaw is reseted he is walking / speed so really slow

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7438]
> when swiftpaw is reseted he is walking / speed so really slow

.go xyz -8842.290000 -329.380000 70.155800 0 1.156310

**Comment by Shadownflame** [comment]
Can't reproduce. He is a lvl 6 mob so his movement speed is generally less than that of players (lenient kiteable level range), and it doesn't change around.
