### ISSUE TITLE
Message: Interface\FrameXML\lualib_bundle.lua:1599: bad argument...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7440]
> Message: Interface\FrameXML\lualib_bundle.lua:1599: bad argument #1 to 'match' (string expected, got nil)
Time: 04/20/24 21:26:22
Count: 2
Stack: [C]: in function `match'
Interface\FrameXML\lualib_bundle.lua:1599: in function 

lua error when hovering over TargetFrame Res sickness icon

.go xyz -4731.700000 -3749.450000 55.233100 1 3.571210

**Comment by Bennylavaa** [comment]
cannot reproduce this with that debuff but I do this this time to time with spells from .lookup spell

but I think its a elvui issue and not a epoch issue.
