### ISSUE TITLE
The unitframes seem a bit big and clunky as well as the combat t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7453]
> The unitframes seem a bit big and clunky as well as the combat text which seems edgy clunky low res

.go xyz -7369.400000 -4370.080000 13.481800 1 5.460900

**Comment by Shadownflame** [comment]
Partial match https://github.com/Project-Epoch/bugtracker/issues/3265

**Comment by kaytotes** [comment]
Use uiScale...
