### ISSUE TITLE
I reported earlier wrongly that the quest starting item for the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7455]
> I reported earlier wrongly that the quest starting item for the quest

https://www.wowhead.com/classic/quest=637/sully-balloos-letter

is missing. It isnt, just have a very long respawn time.

.go xyz -849.180000 -547.319000 11.389300 0 2.467250

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7456
