### ISSUE TITLE
Shadow on the wall to the Cathedral Square is not working correk...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7457]
> Shadow on the wall to the Cathedral Square is not working correktly. Looking like black pattern

.go xyz -8688.250000 918.707000 101.596000 0 4.828180

**Comment by zana244** [comment]
I can't really see the issue? just dated graphics from 2004-2008 :D
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/01a32803-c255-441f-9c1f-30b4c517415a)
