### ISSUE TITLE
Trying to sell back items purchased at Warsong vendor will grey ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7462]
> Trying to sell back items purchased at Warsong vendor will grey them out, not sell them back, bug them within the inventory

.go xyz 1453.050000 -1848.910000 126.352000 1 4.788520

**Comment by zana244** [comment]
Confirmed, however they do not have any cost attached to them on internal...

**Comment by ghost** [comment]
Beta only bug, it is because they're refundable and have no cost. Won't exist on live as the items will have a price.
