### ISSUE TITLE
Equipment manager is fully bugged. Some saves randomly disappear...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7464]
> Equipment manager is fully bugged. Some saves randomly disappear. Switching to other Druid forms might trigger it?

.go xyz -142.942000 -111.337000 -31.438100 732 4.175190

**Comment by Shadownflame** [comment]
I can reproduce this on internal, although seems random rather than triggered by anything. I keep making equipment set saves and some just vanish after relog.

**Comment by Shadownflame** [comment]
Can't reproduce disappearance after last fix. If someone still finds issues, reopen.
