### ISSUE TITLE
Princess Theradras drop only 1 item, but must 2 like on blizz like

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7479]
> Princess Theradras drop only 1 item, but must 2 like on blizz like

.go xyz 11.792900 42.321900 -124.945000 349 4.751570

**Comment by Shadownflame** [comment]
Probably related https://github.com/Project-Epoch/bugtracker/issues/6833
The others didn't get any loot at all.

**Comment by Shadownflame** [comment]
Resolved.
