### ISSUE TITLE
Gnome Priest seems to get the wrong stats from levels. At lv45 g...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7483]
> Gnome Priest seems to get the wrong stats from levels. At lv45 gnome priest has Strength 80 Agility 63 Stamina 78 Intellect 35 Spirit 40. Compare to Undead Priest who has Strength 29 Agility 31 Stamina 41 Intellect 86 Spirit 96. Clearly the Gnome Priest is getting too much Strength, Agility, and Stamina while not getting enough Intellect and Spirit.

.go xyz -6242.770000 339.424000 382.949000 0 4.662130

**Comment by Shadownflame** [comment]
Already resolved.
