### ISSUE TITLE
Not sure if bug but we weren't allowed to resummon the hydra in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7492]
> Not sure if bug but we weren't allowed to resummon the hydra in ZF after wiping

.go xyz 1669.220000 1167.990000 9.325170 209 2.387610

**Comment by zana244** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8245
Shouldn't need to resummon her since she should not despawn.
