### ISSUE TITLE
secret of the circle quest statue does not spawn to turn in

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7504]
> secret of the circle quest statue does not spawn to turn in

.go xyz -323.582000 159.220000 -135.790000 109 3.761090

**Comment by zana244** [comment]
Confirmed on internal. Spawning (or maybe killing?) Atal'alarion should spawn a snake statue in the middle of the pool which should allow the quest to complete.

Someone also mentioned that two people inputting the word at the same time can spawn the boss multiple times -- worth investigating.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310
