### ISSUE TITLE
abandoning Quest: Caught! causes x15 Silk to also be removed fro...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7506]
> abandoning Quest: Caught! causes x15 Silk to also be removed from inventory

.go xyz -6764.980000 -1877.420000 244.495000 0 6.038770

**Comment by Bennylavaa** [comment]
couldn't reproduce this on ptr. Silk cloth stayed in my bag. Could be they had it in the bank which quests still track.
