### ISSUE TITLE
I do not have the Cenarion Beacon and I am picking up Tainted Vi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7511]
> I do not have the Cenarion Beacon and I am picking up Tainted Vitriol from mines all over the world. It should only be lootable in Felwood... unless this is intentional on this server?

.go xyz -6752.790000 -842.126000 252.315000 0 1.450560

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1581
