### ISSUE TITLE
For the quest "The Southern Pylon" in Un goro crater, it autocom...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7518]
> For the quest "The Southern Pylon" in Un goro crater, it autocompletes and the pylon isnt able to be clicked on to turn in the quest.

.go xyz -8042.910000 -1043.310000 -270.873000 1 1.574150

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2511
