### ISSUE TITLE
Slave Master Blackheart - (8283)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#752]
> lvl 50 rare hits 60 dmg to a lvl 47 prot paladin, i don't even take damage with seal of light. seems broken.
`.go xyz -6746.990000 -1247.660000 246.922000 0 5.048540`

> Dropped cloth and 1 silver, no uncommon loot.
`.go xyz -6751.690000 -1239.800000 246.874000 0 3.846410`

> drops nothing
`.go xyz -6628.100000 -1288.230000 264.792000 0 4.712610`

> No Green as Rare.
`.go xyz -6476.040000 -1356.690000 212.105000 0 3.465920`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8249

**Comment by Shadownflame** [comment]
Fixed
