### ISSUE TITLE
Dark Iron Taskmaster and Heavy War Golem in searing gorge will m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7521]
> Dark Iron Taskmaster and Heavy War Golem in searing gorge will melee me while im in stealth (does no damage) then they reset

.go xyz -6795.130000 -1072.430000 241.897000 0 4.019670

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7344 related
