### ISSUE TITLE
We killed Seeth'rei too fast and the next mob wont become hostile

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7524]
> We killed Seeth'rei too fast and the next mob wont become hostile

.go xyz 1278.920000 -259.144000 -78.212500 736 0.893750

**Comment by Shadownflame** [comment]
This fight is incredibly easy to break. Each NPC has a trigger around 15% health to call the next one and if you jump over it by landing big damage and the NPC dies from 16% > 0% within a second the trigger doesn't happen and you can't continue.

**Comment by kaytotes** [comment]
Next Deploy
