### ISSUE TITLE
constructs in brd by fineous are not targettable and put you in ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7534]
> constructs in brd by fineous are not targettable and put you in combat but just sit there

.go xyz 904.336000 -391.174000 -49.036600 736 2.006480

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095

**Comment by Shadownflame** [comment]
The patrolling constructs themselves cannot be aggroed, but aggroing any enemies near the ones standing around will put you in combat with at least one Warbringer construct who yells "Intruders!" 
![WoWScrnShot_070724_224921](https://github.com/Project-Epoch/bugtracker/assets/172074323/0a574c2d-6c53-40db-8ace-62b799a7db44)

**Comment by kaytotes** [comment]
Next Deploy
