### ISSUE TITLE
double bug type in arean after a reset

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7536]
> double bug type in arean after a reset

.go xyz 599.611000 -202.972000 -53.750600 736 4.976270

**Comment by Shadownflame** [comment]
BRD arena is not resetting properly. If you die/reset during the add waves, the adds won't despawn and will engage when you next try the encounter. Killing both waves of the adds then spawns two dwarven NPCs who will release one boss twice each, so you end up with 4 copies of the same boss. These duplicates also don't despawn if your party dies and the door remains closed, essentially bricking the instance if you can't kill them all.
![WoWScrnShot_093024_142932](https://github.com/user-attachments/assets/16cb3cb9-20cf-4235-8b9b-3b58fb189d68)
![WoWScrnShot_093024_142945](https://github.com/user-attachments/assets/aaf0cba4-1a9d-4bb0-b3cd-f17f6f565d6a)
![WoWScrnShot_093024_143016](https://github.com/user-attachments/assets/fc219e5e-d8c7-4f55-ab33-24a1f5cf2194)
