### ISSUE TITLE
The perfect fuel quest: ancient battery is slow to respawn we wa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7540]
> The perfect fuel quest: ancient battery is slow to respawn we waited like 10 minutes not even 1 respawned.. but sometime they do and some other times they dont idk..

.go xyz -6960.400000 -4425.320000 17.981800 1 1.641270

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
