### ISSUE TITLE
Magronos the Unyielding - (8297)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#755]
> no loot
`.go xyz -11611.300000 -2796.610000 3.431930 0 0.294141`

> Multiple of these spawned. I see 2
`.go xyz -11509.400000 -2747.270000 3.228920 0 3.140380`

> rare mob no loot
`.go xyz -11552.400000 -2752.310000 5.587190 0 2.073170`

**Comment by Bennylavaa** [comment]
Intended on beta not to spoil loot.
