### ISSUE TITLE
Flight path in The Harborage, Swamp of Sorrows registers as the ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7551]
> Flight path in The Harborage, Swamp of Sorrows registers as the Lakeshire flightpath

.go xyz -10103.000000 -2797.390000 61.075600 0 2.548900

**Comment by Shadownflame** [comment]
Note, this makes it impossible to target this flight point from other places.

**Comment by kaytotes** [comment]
Next deploy.
