### ISSUE TITLE
When Life Gives You... Berries? quest reward is missing strength...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7556]
> When Life Gives You... Berries? quest reward is missing strength. It has agility, stamina, mp5 or spirit or whatever, doesn't have strength. Unplayable. Anti-Warrior propaganda.

.go xyz -1811.790000 -4162.460000 9.650350 0 0.707471

**Comment by Bennylavaa** [comment]
This seems intended, not every quest and its rewards have to cater to every class in the game.
