### ISSUE TITLE
Cannot turn in animals to Paula Alestone in Blazing Hills. Canno...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7557]
> Cannot turn in animals to Paula Alestone in Blazing Hills. Cannot receive quest credit for turning in the animals into the stables

.go xyz -1820.580000 -4150.970000 9.895130 0 4.220510

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2279
