### ISSUE TITLE
Shardtooth E'ko is not lootable past 2 items. I'm not sure if it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7569]
> Shardtooth E'ko is not lootable past 2 items. I'm not sure if it's an autoloot bug or if something else is going on, but the item stays on the mob and cannot be looted, and displays the warning message "Already Looted".

.go xyz 7516.540000 -4699.640000 660.030000 1 3.463710

**Comment by zana244** [comment]
#8305
