### ISSUE TITLE
Magmus's statues in BRD (boss before Emperor) do not stop spitti...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7571]
> Magmus's statues in BRD (boss before Emperor) do not stop spitting fire, and will keep a group in combat even after his death. This is clearly not intended.

.go xyz 1384.950000 -708.988000 -92.114700 736 1.632130

**Comment by kaytotes** [comment]
Blizzlike that they continue after his dead.

Not blizzlike that they stick in combat.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095

**Comment by Shadownflame** [comment]
Resolved.
