### ISSUE TITLE
Twilight's Hammer Ambassadors seem to be bugged in that they won...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7572]
> Twilight's Hammer Ambassadors seem to be bugged in that they won't conduct combat when pulled like the other mobs in The Imperial Seat in BRD (Emperor's room).

.go xyz 1377.460000 -733.593000 -92.721700 736 4.639410

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6002
