### ISSUE TITLE
It seems to be that Rich Thorium Veins have been 1-tap nodes. Pl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7574]
> It seems to be that Rich Thorium Veins have been 1-tap nodes. Please investigate? This has happened to me for more than a few Rich Thorium nodes.

.go xyz 2401.170000 -2339.260000 50.380400 0 0.772081

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8068
