### ISSUE TITLE
For the quest The Perfect Fuel, there are no Ancient Batteries i...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7581]
> For the quest The Perfect Fuel, there are no Ancient Batteries in the Noonshade Ruins. Neither on the ground nor on the humanoids there. It does mention trolls but I don't see any in sight.

.go xyz -7360.710000 -4504.050000 9.882100 1 3.318230

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
