### ISSUE TITLE
For the quest "The Earth Mother Provides", the Dark Whispers are...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7585]
> For the quest "The Earth Mother Provides", the Dark Whispers are way overtuned. Nonelites that I should be able to solo quest, they have 19.4k health and do 500 damage per hit.

.go xyz -900.675000 -1149.800000 97.443700 1 2.666230

**Comment by Bennylavaa** [comment]
adding this info here seeing its semi related

mob "Dark Whisper" for quest "The Earth Mother Provides is listed as "rare", when it should be listed as "elite" or "rare elite" as it is a very strong elite mob for one person to fight. The quest overall seems way too difficult compared to other Racial Knowledge questlines.

from issue https://github.com/Project-Epoch/bugtracker/issues/3454
