### ISSUE TITLE
I am unable to progress in Aponi's Request. I talk to APoni Brig...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7586]
> I am unable to progress in Aponi's Request. I talk to APoni Brightmane, I can ask "Who is An'she?", and then after that the conversation is done. No progress on the quest.

.go xyz -1050.160000 -301.728000 159.030000 1 4.647050

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7711
