### ISSUE TITLE
Clack the Reaver - (8301)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#759]
> 2 at the same spot also lol, no loot again
`.go xyz -11410.700000 -2989.010000 -0.129108 0 4.391830`

> no loot on kill. is it a rare?
`.go xyz -11399.300000 -2973.360000 0.272206 0 3.343320`

> killed him 5 minutes ago, found him again. dupe spawn?
`.go xyz -11347.000000 -2977.300000 2.962520 0 0.080664`

**Comment by Bennylavaa** [comment]
Intended on beta not to spoil loot./

Cannot reproduce the double spawn.
