### ISSUE TITLE
Ferocious Bite damage does not align to the tooltip. The tooltip...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7594]
> Ferocious Bite damage does not align to the tooltip. The tooltip shows higher damage than what the ability actually does. They should be more aligned, either by increasing ferocious bite damage or reducing the values in the tooltip. Test details were shared in discord in the druid channel:

https://discord.com/channels/729423227373355040/996870826815131749/1226927569182527578

.go xyz 2115.880000 -4663.000000 45.883300 1 4.217600

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7461
