### ISSUE TITLE
Warmode reputation bonus is broken. It should be increasing repu...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7597]
> Warmode reputation bonus is broken. It should be increasing reputation gains according to the tooltip, but quest turnins and mob kills are awarding the standard amount of rep.

.go xyz 2255.650000 -5335.650000 85.775800 0 0.612945

**Comment by zana244** [comment]
Confirmed on internal. Possibly related to human rep racial, which also does not work.
The xp bonus works though.
#2820

**Comment by kaytotes** [comment]
Next Deploy
