### ISSUE TITLE
Deatheye - (8302)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#760]
> there are 2 of them spawned at the same time few yards from each other
`.go xyz -11180.500000 -2724.900000 14.613300 0 3.589650`

> This mob is spawning multiple times in the Blasted Lands as a rare spawn.
`.go xyz -10790.600000 -3016.790000 48.095300 0 5.971750`

> Rare mob no loot
`.go xyz -11107.900000 -2728.890000 13.547200 0 2.780750`

**Comment by kaytotes** [comment]
Reopening to check spawns

**Comment by Bennylavaa** [comment]
cannot reproduce the double spawn.
