### ISSUE TITLE
When using pounce on a mob, sometimes visually they will look li...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7601]
> When using pounce on a mob, sometimes visually they will look like they're turning the other way. But based on my ability to use Shred, their behind is still the original location. Visual should match the attack.

.go xyz 3314.200000 -4274.590000 159.140000 0 2.077030

**Comment by Shadownflame** [comment]
Seems to be generic issue with stuns.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7520
