### ISSUE TITLE
Contagion of Rot in WPL is stacking. I believe it should overwri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7605]
> Contagion of Rot in WPL is stacking. I believe it should overwrite, not double the debuff.

.go xyz 1647.020000 -1265.210000 69.527900 0 2.049650

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2629 related, same spell different mob

**Comment by zana244** [comment]
solved
