### ISSUE TITLE
On lifebloom, rank 1 should heal 675 when it blooms. However, in...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7608]
> On lifebloom, rank 1 should heal 675 when it blooms. However, instead of healing the target that it's cast on, it heals the druid who cast the spell. It also casts less than the tooltip. The bloom heal should heal the target it is cast on and it should match the amount on the tooltip (assuming no +heal).

.go xyz 1475.750000 -3675.510000 79.049100 0 3.119610

**Comment by Shadownflame** [comment]
Resolved on beta
