### ISSUE TITLE
Grunter - (8303)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#761]
> no loot rare
`.go xyz -11201.300000 -3216.070000 8.674600 0 5.111720`

> Skinned this boar and he gave light leather. Seems like a bug for a level 50 mob to give light leather.
`.go xyz -11207.600000 -3239.960000 10.160600 0 1.565680`

> Skinning him gave a light hide
`.go xyz -11326.400000 -3159.650000 7.115240 0 0.862739`

> Rare mob no loot
`.go xyz -11256.800000 -3158.070000 4.512350 0 4.366600`

**Comment by Bennylavaa** [comment]
fixed.
