### ISSUE TITLE
It looks like Gahz'rilla Fang does not proc while in bear form. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7611]
> It looks like Gahz'rilla Fang does not proc while in bear form. It should be giving me the thorns damage when it procs. Maybe all chance on hit procs are broken while in druid form? I've submitted similar bugs for other items/spells.

.go xyz 372.715000 -130.368000 -64.949000 736 3.448670

**Comment by Shadownflame** [comment]
Procs fine, it's just rather low chance (0.6 ppm or so)
