### ISSUE TITLE
There is a Call to Arms quest in Thrall's room, but I am unable ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7614]
> There is a Call to Arms quest in Thrall's room, but I am unable to pick it up. It should either let me interact with the billboard to accept the quest, or the quest should not be there.

.go xyz 1901.470000 -4149.630000 40.914100 1 3.502060

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8168 related
