### ISSUE TITLE
Traveling up the hut in The Drag where Jes'rimon is, I get some ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7615]
> Traveling up the hut in The Drag where Jes'rimon is, I get some weird UI behavior. The building disappears and I just see a blank landscape.

.go xyz 1954.780000 -4458.790000 54.692300 1 5.523670

**Comment by Shadownflame** [comment]
Similar to https://github.com/Project-Epoch/bugtracker/issues/8006 this is an area in Org that seems blizzlike,but might have been affected by the redesign of the city:
![WoWScrnShot_081624_011321](https://github.com/user-attachments/assets/a18d0bad-d8ec-4cc2-8977-441de6bb84a0)
My character also has the wrong lighting in random spots as if i was outside in the dark, when I have braziers next to me:
![WoWScrnShot_081624_011919](https://github.com/user-attachments/assets/56649888-0008-4eb7-ae17-2c953cfc5a6b)
Switches back if i take 2 steps forward:
![WoWScrnShot_081624_011917](https://github.com/user-attachments/assets/16c09678-a192-43d8-8b8d-3e6d550e4c17)
