### ISSUE TITLE
Mana Spring Totem is not showing on my buffs, I don't believe it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7617]
> Mana Spring Totem is not showing on my buffs, I don't believe it's giving me mana either. Perhaps it's not stacking with Blessing of Wisdom?

.go xyz 21.854100 -198.640000 -198.218000 349 4.780280

**Comment by Shadownflame** [comment]
Confirmed, Blessing of Wisdom currently blocks Mana spring from applying. This is wrath behavior, must be fixed to TBC state.

**Comment by Shadownflame** [comment]
The two spells now visually stack, but their effects do not. You only get the mp5 from wisdom

**Comment by Shadownflame** [comment]
Correction, both are correctly giving mp5, mana spring totem simply doesn't show up on the player panel's mp5 numbers anymore. It is a separate mana restore effect now same as Mana Tide and ticks on its own rhythm instead of being added to the player's innate mana ticks.
