### ISSUE TITLE
Casting an instant cast spell after a spell with > 1.5 second ca...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7622]
> Casting an instant cast spell after a spell with > 1.5 second cast time will not go off. I'll need to re-cast the instant spell after the second GCD window.

.go xyz 1331.610000 822.468000 8.907080 209 6.054000

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6618
