### ISSUE TITLE
I submitted a bug about Rejuvenation mana cost not being reduced...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7627]
> I submitted a bug about Rejuvenation mana cost not being reduced - it looks like it is reduced, but the tooltip still shows the full amount.

.go xyz 1537.240000 831.758000 8.891700 209 0.567840

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7752
