### ISSUE TITLE
I think Reclaiming the Eggs may be bugged for me. I can't seem t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7630]
> I think Reclaiming the Eggs may be bugged for me. I can't seem to find any gryphon eggs. This looks like a Blizz quest. I checked wowhead and in all the locations there doesn't seem to be any eggs.

.go xyz -400.666000 -2969.390000 100.291000 0 1.908670

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
