### ISSUE TITLE
When flying from Tanaris to Orgimmar, my character flies through...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7633]
> When flying from Tanaris to Orgimmar, my character flies through the new tower in Razor Hill. <3

.go xyz 1677.590000 -4315.710000 61.170000 1 2.861990

**Comment by Imperius5k** [comment]
confirmed that you do fly through the new tower

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
