### ISSUE TITLE
The call to arms quest after selecting warmode is unclickable.

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7634]
> The call to arms quest after selecting warmode is unclickable.

.go xyz -8490.960000 1115.140000 18.100100 0 5.781670

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/c5fbb78c-71b5-4820-ab9d-02ad661c8dd1)
Cannot reproduce

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8168 related
