### ISSUE TITLE
The Hinterlands quest Reclaiming the Eggs at Shadra'Alor isn't w...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7635]
> The Hinterlands quest Reclaiming the Eggs at Shadra'Alor isn't working, the eggs who were supposed to be here are not.

.go xyz -266.074000 -3032.880000 121.140000 0 3.009210

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
