### ISSUE TITLE
Rogue blind must be poison on vanilla wow. not a red debuff

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7647]
> Rogue blind must be poison on vanilla wow. not a red debuff

.go xyz -9117.360000 350.164000 93.709900 0 5.023750

**Comment by zana244** [comment]
[Patch 2.3.0] (2007-11-13): Blind is now a physical (no longer a poison) attack. [Reagent] requirement removed. Now shares the same diminish category as Cyclone and is now diminished in [PvE] as well as [PvP].
2.4.3 balance
