### ISSUE TITLE
deviate creeper in first little pond area in wailing caverns ent...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7648]
> deviate creeper in first little pond area in wailing caverns entrance won't die, instantly healing, also does not attack

.go xyz -704.346000 -2056.610000 65.490600 1 5.362860

**Comment by Imperius5k** [comment]
confirmed that it does heal when attacked, and wont really attack.

**Comment by Shadownflame** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by zana244** [comment]
Linking to creature issue.
#416
