### ISSUE TITLE
Patrick Mills - (8382)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#765]
> Pally quest Those Uncovered still bugged, cant hand in or talk to him with the dialogue option
`.go xyz 2375.220000 -5963.930000 9.948790 1 5.603330`

> Wont accept 'Those Unrecovered' paladin quest that has the cloak hand in
`.go xyz 2377.640000 -5962.940000 9.609730 1 4.594170`

> Can't give him the cloak for the Paladin quest Thost Unrecovered
`.go xyz 2375.430000 -5965.760000 10.099500 1 6.012150`

> This npc is completely broken, you can't accept his quest or continue the undead paladin quest through is dialogue options.
`.go xyz 2375.030000 -5967.380000 10.331800 1 1.323570`

**Comment by Shadownflame** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/2293
