### ISSUE TITLE
Shore shark in Tanaris has LOS issues. If you swim to the top of...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7654]
> Shore shark in Tanaris has LOS issues. If you swim to the top of the water you won't be able to attack it again.

.go xyz -7080.390000 -4904.260000 -1.404240 1 2.291550

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
Fixed.
