### ISSUE TITLE
The Perfect Fuel quest in Tanaris The batteries are not spawning...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7656]
> The Perfect Fuel quest in Tanaris The batteries are not spawning. I saw them yesterday so I know they are in the game. Spawn seems broken.

.go xyz -7130.740000 -4086.410000 10.989400 1 1.875490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
