### ISSUE TITLE
The floor of Undercity did not load when I entered the city. Now...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7657]
> The floor of Undercity did not load when I entered the city. Now I'm dead and can't rez.

.go xyz 1708.580000 164.883000 -2940.650000 0 1.813620

**Comment by Shadownflame** [comment]
I can tell from the go xyz that the problem is valid, but I have no means to reproduce this.

**Comment by Shadownflame** [comment]
As per ktotes, this issue cannot be server side. Person must reinstall corrupted client.
