### ISSUE TITLE
The Perfect Container quest
Parts spawned earlier but do not app...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7664]
> The Perfect Container quest
Parts spawned earlier but do not appear to be respawning.  There were only 5 on the ground for the quest's 6, and each time I come back none have respawned.

.go xyz -7052.580000 -3545.890000 20.298800 1 0.246814

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
