### ISSUE TITLE
At my current location in Gol'Bolar Quarry Mine a quest kinitec ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7668]
> At my current location in Gol'Bolar Quarry Mine a quest kinitec ore node and a copper ore node have exactly the same location and both were up at once.  If my location when submitting is not recorded, I'm in the big room with the frozen water, and am standing at the northern most point of that room.

.go xyz -5568.720000 -1799.490000 360.248000 0 0.163147

**Comment by Bennylavaa** [comment]
moved to the node tracker
