### ISSUE TITLE
The Npc "Southsea Freebooter", when it enters a fleeing state it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7672]
> The Npc "Southsea Freebooter", when it enters a fleeing state it runs a short distance and turns to fire a ranged attack. Then keeps doing that pattern. Usually when npc's are in a fleeing state they wont attack or cast spells at all until they're "done

.go xyz -7847.430000 -5136.970000 5.570410 1 3.156490

**Comment by zana244** [comment]
#8252

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6624
