### ISSUE TITLE
I just got disconnected after trying to open a Solid Chest at Lo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7677]
> I just got disconnected after trying to open a Solid Chest at Lost Rigger Cove in Tanaris. By the pirate ship at the end of the dock

.go xyz -7989.900000 -5404.830000 1.120870 1 4.270220

**Comment by Imperius5k** [comment]
i did not crash when opening the chest, may be a pc issue

**Comment by Shadownflame** [comment]
Seems random DC.
