### ISSUE TITLE
Witch Doctor Zum'Rah in ZF has zero loot in chest or on body. No...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7678]
> Witch Doctor Zum'Rah in ZF has zero loot in chest or on body. Not sure if intended

.go xyz 1852.780000 1041.020000 8.876850 209 1.572710

**Comment by Shadownflame** [comment]
Same issue as https://github.com/Project-Epoch/bugtracker/issues/8115
