### ISSUE TITLE
Frost Nova is resetting threat on mob, causes tank to lose mob

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7679]
> Frost Nova is resetting threat on mob, causes tank to lose mob

.go xyz 1599.820000 887.677000 9.040020 209 0.115207

**Comment by Shadownflame** [comment]
I think rooted mobs in certain circumstances might start hitting someone who is nearby if their highest aggro target is out of range. Most of them aren't that intelligent though. I cannot reproduce any kind of aggro shift happening with frost nova.
