### ISSUE TITLE
CRIPPLING POISON AND WOUND POISON CANCEL THEMSELFS OUT. TESTED O...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7680]
> CRIPPLING POISON AND WOUND POISON CANCEL THEMSELFS OUT. TESTED ON BOTH PVP PLAYER AND TARGET DUMMIES.

.go xyz 49.701600 -2725.620000 91.667100 1 1.116790

**Comment by zana244** [comment]
#2584
