### ISSUE TITLE
Quest "Reagants for the Undercity" contains a typo in the text: ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7687]
> Quest "Reagants for the Undercity" contains a typo in the text: it should be 'reagents'

.go xyz -1180.810000 -3413.340000 30.675600 0 6.112180

**Comment by zana244** [comment]
#2286 
Linking to quest issue.

**Comment by Kestrana** [comment]
Fixed in https://github.com/Project-Epoch/epoch-core/pull/1514
