### ISSUE TITLE
Most world chests currently don't contain any green gear. Please...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7689]
> Most world chests currently don't contain any green gear. Please make it so that they always have at least 1 piece of green armor/wep/misc. Same for rare enemies. Enchanters are currently royally fucked if they aren't running dungeons.

.go xyz 1485.080000 274.964000 -62.155400 0 4.071530

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249
