### ISSUE TITLE
There is a typo in quest text of "the lost warrior" custom escor...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7691]
> There is a typo in quest text of "the lost warrior" custom escort quest. Togthar says "seperated" instead of "separated"
There is no quest window at Krusk (quest end NPC) to write report in

.go xyz -558.627000 26.664300 48.046000 0 2.143250

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/f2dddd3a-34a2-4c39-997c-58fe335cec0a)
Confirmed in quest ID 26390
