### ISSUE TITLE
Pet pathing is dangerously bugged when soloing in elite hubs. Th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7692]
> Pet pathing is dangerously bugged when soloing in elite hubs. The damn voidwalker turns the corner for no reason when fighting an enemy still in the same room with us (its trying to get behind it or something but chooses to go on the other side of the wall), risking to pull loads of extras because it moves into a spot he is not supposed to.

.go xyz -386.895000 -1635.810000 52.582000 0 4.665130

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
