### ISSUE TITLE
I can't put my lvl 28 firestone on my lvl 20 WC staff which is B...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7693]
> I can't put my lvl 28 firestone on my lvl 20 WC staff which is BIS in this level bracket. This surely cannot be intended. It says target is too low level, but it's the best weapon to have in this bracket! Lower the level requirement otherwise this spell is dumpster value.

.go xyz 1840.130000 -4403.310000 3.942370 1 5.466810

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2618
