### ISSUE TITLE
my voidwalker got stuck inside the textures of stockades
when i ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7698]
> my voidwalker got stuck inside the textures of stockades
when i try to sacrifice it, it just evaded, but still give me the sac buff
had to dismiss resummon

.go xyz 140.092000 43.970600 -34.856200 34 6.023680

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2790
