### ISSUE TITLE
Avatar of Hakkar - (8443)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#770]
> Can be repeated. Also didn't drop essence for everyone.
`.go xyz -469.327000 271.484000 -90.430800 109 4.033890`

> Boss can be summoned multiple times.
`.go xyz -427.652000 280.058000 -90.827700 109 3.651800`

**Comment by zana244** [comment]
#8310

**Comment by Shadownflame** [comment]
Seems resolved.
