### ISSUE TITLE
Pet pathing issue:
When the pet is instructed to attack or follo...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7701]
> Pet pathing issue:
When the pet is instructed to attack or follow a target in distance and then the target moves, instead of going to the target, the pet goes first to the location where the target used to be when the attack/follow command was given and only then moves over to where the target actually is. Pet should be able to immediately pick up on target's altered location and change course without having to make a detour.

.go xyz -1975.020000 -3692.550000 14.763900 1 2.719010

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
