### ISSUE TITLE
Pet pathing issues: small obstacles like a little hill or the do...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7705]
> Pet pathing issues: small obstacles like a little hill or the docks of a ferry makes my pet stuck circling around trying to find a way off it so he stops following me. These small terrain bumps should not force the pet to path, since the player can just walk across it, he should simply follow owner and walk over it too.
Same problem when the character drops a small distance from a hill or ledge. pet should simply follow not run off 1 mile to find a path down.

.go xyz 621.011000 1158.760000 75.094300 0 1.576640

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
