### ISSUE TITLE
Duel fix:

Duelling opposite factions keeps debuff on you when y...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7706]
> Duel fix:

Duelling opposite factions keeps debuff on you when you lose.
If its a DoT, it ticks, when you at 1 hp. intant dead.
I suggest to make it so when you lose duel. All negative effects on you are gone.

.go xyz -7278.550000 -3811.990000 9.492400 1 1.783680

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4533
