### ISSUE TITLE
Quest bug: "Aponi's request"
This is the quest for horde to lear...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7711]
> Quest bug: "Aponi's request"
This is the quest for horde to learn the night elf racials. I cannot complete it at Aponi, in Thunderbluff. There's no follow up at this npc, just some unrelated dialog about An'she.

.go xyz -1049.800000 -300.382000 159.030000 1 3.972390

**Comment by Shadownflame** [comment]
Note, both tauren gods anshe and mushe are male and the quest text should refer to them as such.

**Comment by kaytotes** [comment]
Next deploy.
