### ISSUE TITLE
Dieing at the dancing troll village makes horde players (haven't...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7712]
> Dieing at the dancing troll village makes horde players (haven't tried alliance) respawn far off at a graveyard in Ashenvale with no way of getting back, have to take the ress sickness debuff.

.go xyz 7463.250000 -1560.670000 173.997000 1 4.051650

**Comment by Imperius5k** [comment]
confirmed that it does spawn you in ashenvale, however i do not know if this is intentional or not

**Comment by Shadownflame** [comment]
Already confirmed, linking to other report https://github.com/Project-Epoch/bugtracker/issues/2326
