### ISSUE TITLE
Quest bug: "Venomhide Eggs"
Quest in Ungoro Crater, appears it's...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7713]
> Quest bug: "Venomhide Eggs"
Quest in Ungoro Crater, appears it's not possible to loot and collect the item needed for this quest. I believe this is a repeatable quest that rewards horde players a mount, on retail.

.go xyz -7609.170000 -1961.440000 -271.129000 1 5.635490

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
