### ISSUE TITLE
Quest bug: "Silithid Scramble"
Quest from Tanaris, Noxious Lair....

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7715]
> Quest bug: "Silithid Scramble"
Quest from Tanaris, Noxious Lair. Only found 1 Centipaar Tunneler npc to kill for the 6 kills requiered.

.go xyz -9631.730000 -4132.520000 127.771000 1 2.564270

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
