### ISSUE TITLE
Quest bug: "Water Co. Saviour"
Missing quest items (Filter Parts...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7716]
> Quest bug: "Water Co. Saviour"
Missing quest items (Filter Parts) from location surrounding Steamwheedle Port.

.go xyz -7094.140000 -4883.830000 0.567850 1 1.639100

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
