### ISSUE TITLE
Pvp flagging, could easily be abused for griefing. Even when not...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7717]
> Pvp flagging, could easily be abused for griefing. Even when not flagged for pvp, doing any kind of aoe near a pvp flagged player automatically flags you for pvp. That is any kind of aoe, dmg or cc, doesnt matter.

.go xyz -7288.440000 -3976.740000 10.223700 1 4.355720

**Comment by Shadownflame** [comment]
Was resolved during beta.
