### ISSUE TITLE
not a bug, but using seal of righteousness not only deals more d...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7725]
> not a bug, but using seal of righteousness not only deals more damage than penitence but doesn't have the drawback of dealing damage to you, command deals less than all of these unless you get really luck with procs. Penitence needs better scaling, and at the very least commands judgement needs to deal the damage it deals on cc normally with maybe double crit chance on cc. Seal twisting costs too much mana and we need to drink each pull anyway. Aside; exorcism deals half dmg on other targets.

.go xyz 2111.640000 -4684.460000 43.291300 1 1.675960

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2936
