### ISSUE TITLE
COME OUT OF BG INTO NEUTRAL TOWN AND GUARD RAPE ME

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7757]
> COME OUT OF BG INTO NEUTRAL TOWN AND GUARD RAPE ME

.go xyz -7186.280000 -3840.810000 29.149300 1 1.076770

**Comment by Shadownflame** [comment]
Could not in any way reproduce this. Even if your dots remain on a person who ports out into the same town, the guards do not react.
