### ISSUE TITLE
totems can get healed for some unknown reason.
This is a horribl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7767]
> totems can get healed for some unknown reason.
This is a horrible bug for someone using a @mouseover macro. A few times i accidentally hovered over my totem and once wasted a heal on an ally and he died and we wiped,

.go xyz -7331.620000 -2420.140000 284.468000 0 3.509120

**Comment by zana244** [comment]
Confirmed on internal. If you target your totem, your heals get lost. Possibly the same if other classes try to heal the shaman's totem.

Later edit: Actually made a shaman on everlook fresh and on there (VMangos) if you cast a heal on your totem it lets you cast it and then it says Immune, however you still lose the mana. Maybe intended? Although on Epoch IIRC you don't see the finishing animation, nor an Immune.

**Comment by kaytotes** [comment]
Validated on Classic Era PTR. You _can_ heal totems it just displays as immune at the end.

https://github.com/Project-Epoch/bugtracker/assets/7526918/360fb24c-5f67-49eb-8a56-5dad2c7e3466

**Comment by kaytotes** [comment]
Closing in favour of https://github.com/Project-Epoch/bugtracker/issues/8325

The actual being able to heal isn't a bug it just doesn't display the immune correctly

**Comment by Shadownflame** [comment]
Interesting, I thought this was the same bug as the good old "totems are stealing away chain heal jumps" but it seems not. The totem is properly invalid target for AOE spells that autotarget, only the manual targeting works, which is, it seems, blizzlike.
You're supposed to use mouseover macros on the raid frames, not people's physical bodies lol.
