### ISSUE TITLE
Nature's Swiftness is very bugged. It ONLY works if you click it...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7768]
> Nature's Swiftness is very bugged. It ONLY works if you click it once and click a heal after it. If you click it twice, it'll count itself as a nature spell and spend itself on itself. If a pot/trinket/consumable is used while Nature's Swiftness' buff is active it will be consumed by all sorts of consumables and useables.

.go xyz -1566.130000 1854.910000 62.233300 1 5.739600

**Comment by Shadownflame** [comment]
Seems resolved.
