### ISSUE TITLE
Doomwarder mobs don't drop Doomwarder Blood for the quest Reagan...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7770]
> Doomwarder mobs don't drop Doomwarder Blood for the quest Reagants For The Undercity. On that note, isn't it spelled "Reagents"?

.go xyz -1647.680000 1838.650000 59.047300 1 0.205831

**Comment by zana244** [comment]
Seems to be the Horde counterpart for https://www.wowhead.com/classic/quest=1466/reagents-for-reclaimers-inc
Quest text specifies doomwarded captains, or lords.  Not a bug. Doomwarder captains indeed drop the blood, as well as Kaskk and Lord Azrethoc.
