### ISSUE TITLE
Clearcasting from Elemental Focus is not consumed by Molten Blas...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7771]
> Clearcasting from Elemental Focus is not consumed by Molten Blast, Shock nor Healing abilities.
Clearcasting says it reduces mana cost of healing abilities, but is not described that way on the talent itself.

.go xyz -587.728000 -939.363000 41.588100 0 3.317900

**Comment by zana244** [comment]
#2749
