### ISSUE TITLE
i tried to trade my best fiend and now we can never trade ever a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7798]
> i tried to trade my best fiend and now we can never trade ever again i'm realy scared idk whats going on how do i call 911

.go xyz -121.753000 2161.760000 155.679000 33 6.121430

**Comment by Shadownflame** [comment]
There is usually a bug on private servers when both players press trade simultaneously (the window has a bit of delay to pop up), and it results in an error showing 'target is busy' to both players. Like when two people dial each other's phone at the same time and both lines return occupied.
A simple relog fixes the issue normally.
I'm not 100% sure if this report refers to the same thing but it might be worth checking.

**Comment by Shadownflame** [comment]
Not happening here.
