### ISSUE TITLE
Maybell Maclure - (251)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#78]
> Takes too long to respawn
`.go xyz -10013.000000 40.820200 35.169600 0 4.599140`

**Comment by Bennylavaa** [comment]
.npc info says her respawn is 5 minutes which is totally blizlike. I also completed her quest chain where she goes invisible at the end and that looks like it is the issue it shouldn't use her respawn timer for that as 5 minutes is way too long.

**Comment by Shadownflame** [comment]
I'll set this to high prio as it is an early starting zone quest that will get a lot of people stuck on a crowded launch.
