### ISSUE TITLE
using rockbiter weapon while frost or fire enhancements are acti...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7802]
> using rockbiter weapon while frost or fire enhancements are active does nothing but still triggers gcd and uses your mana
switching between fire and frost however works fine, as does casting any of those over rockbiter

.go xyz -3570.370000 -1973.460000 117.833000 0 0.738857

**Comment by Shadownflame** [comment]
Related to https://github.com/Project-Epoch/bugtracker/issues/7823

**Comment by zana244** [comment]
Solved on internal.
