### ISSUE TITLE
My searing totem stopped working. It spawns but doesn't attack a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7803]
> My searing totem stopped working. It spawns but doesn't attack anything. It first occured a few days ago, thought the patch might address it, but it is still happening. i tried casting other fire totems, but to no avail, Fire nova works fine, but when i switch back to searing it just refuses to shoot. It only affects rank 2 from what we gathered.

.go xyz -3116.520000 -923.176000 3.961620 0 0.694183

**Comment by zana244** [comment]
#2591
