### ISSUE TITLE
Atal'alarion - (8580)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#781]
> Duplicates can be summoned if the word is simulaneously written by 2 or more players.
Also, does not spawn monument for quest upon death.
`.go xyz -467.990000 88.627900 -189.730000 109 1.796510`

> quest is begged, no quest item
`.go xyz -451.931000 94.620000 -189.730000 109 3.237870`

> Killing him didn't spawn the tablet need to complete "Secret of the Circle"
I don't see how to complete that quest otherwise.
`.go xyz -480.953000 92.516600 -189.730000 109 0.213979`

> Secret of the Corcle quest do not work after we make to all statues and collect it to word Raptor, boss came and we kill it, but quest do not complete
`.go xyz -428.104000 90.579700 -177.550000 109 3.299640`

> Secret of the Circle quest didnt work after changes with summon boss
`.go xyz -431.736000 95.807800 -179.767000 109 3.181050`

**Comment by zana244** [comment]
#7504

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310
