### ISSUE TITLE
Floating Peacebloom in Goldshire

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7816]
> Floating Peacebloom in Goldshire

.go xyz -9550.280000 116.418000 56.674800 0 0.605655

**Comment by Imperius5k** [comment]
im 90% theres no floating peacebloom, i looked for about 5 minutes, a second look could help but i did not see any floating peaceblooms.

**Comment by Bennylavaa** [comment]
211844 (Entry: 1618) - [Peacebloom X:-9549.509766 Y:116.517998 Z:59.036900 MapId:0]
