### ISSUE TITLE
When you took the teleport to tanaris the game crash, when i tri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7824]
> When you took the teleport to tanaris the game crash, when i trie to log the char the game crash again, so maybe the teleport to tanaris have problems

.go xyz -6233.080000 340.115000 383.260000 0 0.459461

**Comment by Imperius5k** [comment]
i teleported here both in the beta and just now a couple times and i never crashed once, perhaps it has to do with pc issues but ill leave it not confirmed until maybe more give it a try.

**Comment by Bennylavaa** [comment]
I cannot reproduce this either also on beta, I would say this was this users issue and not wide spread, also teleports are not something that will exist on launch so it should be fine to close.
