### ISSUE TITLE
reclaming the eggs

quest in hinterlands
gather 5 gryphon eggs

...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7825]
> reclaming the eggs

quest in hinterlands
gather 5 gryphon eggs

Problem: Cant find/click eggs (no sparkling effects on any eggs)
Unsure if the eggs are spawned (long respawn time) or just not there.

.go xyz -118.018000 -3266.230000 118.080000 0 6.256630

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
