### ISSUE TITLE
Tuarens at the great lift in the barrens are supposed to be peac...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7831]
> Tuarens at the great lift in the barrens are supposed to be peaceful

.go xyz -4670.690000 -1794.730000 -46.544700 1 5.682710

**Comment by Shadownflame** [comment]
Hmm, it's a matter of expansion. On vanilla the NPC would engage, later it was changed not to. To my knowledge all world state was reverted to Vanilla and as such this is intended.

**Comment by kaytotes** [comment]
Has never been friendly. 

https://www.wowhead.com/classic/npc=10079/brave-moonhorn
https://www.wowhead.com/wotlk/npc=10079/brave-moonhorn

Hostile to alliance until they were deleted in Cata.
