### ISSUE TITLE
Lightning Breath Rank 5 from Wind Serpent as Hunterpet:

Tooltip...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7844]
> Lightning Breath Rank 5 from Wind Serpent as Hunterpet:

Tooltip said it costs 50 Focus but now it costs 70 Focus.

.go xyz -4921.300000 -1149.910000 501.494000 0 2.073710

**Comment by zana244** [comment]
Could not reproduce on internal, spell consumes 50 focus, could cast 2 quickly one after another at 100 focus (waiting for GCD though).
