### ISSUE TITLE
Flightpath with the griffin to Tanaris Gadgezan, Griffin is Clip...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7845]
> Flightpath with the griffin to Tanaris Gadgezan, Griffin is Clipping trough the roofs of the new Steemweedle Port.

.go xyz -7223.970000 -3734.590000 8.390000 1 1.289160

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
