### ISSUE TITLE
inside SM Graveyard only spawns 1 Kingsblood but not a singel Gr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7846]
> inside SM Graveyard only spawns 1 Kingsblood but not a singel Grave Moss.

.go xyz 1789.630000 1306.570000 18.277300 189 4.688850

**Comment by Shadownflame** [comment]
I'm not 100% sure if this is the same pooling issue as https://github.com/Project-Epoch/bugtracker/issues/8295 because I can't see any herbs in GY, and Lord knows nobody picked them up on internal since the last restart. I can't even find the above mentioned Kingsblood though, so maybe...

**Comment by Shadownflame** [comment]
Situation is around 5 Kingsblood and 1x Grave moss now, not sure if these spawns are correct as I do recall it being mostly grave moss. Certainly an improvement though.

**Comment by Shadownflame** [comment]
Matches vmangos as per ktotes. As is.
