### ISSUE TITLE
Quest: Reclaiming the Eggs
Location: Hinterland / Shadra'Alor

C...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7849]
> Quest: Reclaiming the Eggs
Location: Hinterland / Shadra'Alor

Can't find any Gryphon Eggs in Shadra'Alor - i Guess they dont Spawn.

.go xyz -404.367000 -2892.870000 84.942900 0 3.766200

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
