### ISSUE TITLE
Morta'gya the Keeper - (8636)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#785]
> Stuck under temple
`.go xyz -280.698000 -3444.640000 187.641000 0 4.130810`

> This NPC and the other priest with the mallet of zul farrak tend to not reset properly if you jump down the sides of the temple. They sometimes even get stuck under the temple structure with no LOS to pull them out.
`.go xyz -98.118900 -3498.440000 121.786000 0 2.509560`

> won't return to the origin postion after leave battle
`.go xyz -268.840000 -3435.120000 186.765000 0 3.884440`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
