### ISSUE TITLE
Quest "A Lost Warrior" from Krusk in Tarren Mill. Quest objectiv...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7853]
> Quest "A Lost Warrior" from Krusk in Tarren Mill. Quest objective has a spelling error - "Dunrholde" instead of "Durnholde

.go xyz -40.915100 -953.724000 56.196400 0 4.387850

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/6f918370-4846-4a41-8c85-47d37c1ed692)
Confirmed Type in Quest ID 26388
