### ISSUE TITLE
The Evalcharr - (8660)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#786]
> Did not any greens or misc items. Noting.
`.go xyz 3267.340000 -4171.890000 104.912000 1 2.920060`

> rare mob dosent have any loot
`.go xyz 3144.180000 -4244.230000 100.272000 1 4.628610`

> no loot on kill
`.go xyz 3266.870000 -4411.680000 103.208000 1 2.690120`

**Comment by Bennylavaa** [comment]
has loot
