### ISSUE TITLE
Stromgarde NPCs (Troll Hunters and Defenders) sometimes clip thr...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7864]
> Stromgarde NPCs (Troll Hunters and Defenders) sometimes clip through the buildings, following their original pathing rather than taking into account the modified terrain.

.go xyz -1633.230000 -1609.300000 69.231200 0 2.475470

**Comment by Shadownflame** [comment]
Can't reproduce this. Their pathing must have been already corrected.
