### ISSUE TITLE
All mechanical chicken quests from Tanaris, Feralas and Hinterla...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7874]
> All mechanical chicken quests from Tanaris, Feralas and Hinterlands only count to the person that accepted the escort while in a party

.go xyz 486.005000 -3488.670000 106.509000 0 0.711641

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2032
