### ISSUE TITLE
Blessing of Light rank 1 is missing a casting animation for unde...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7878]
> Blessing of Light rank 1 is missing a casting animation for undead. Recasting it on the same target does not overwrite the original buff due to a more powerful buff being active error.

.go xyz 2129.500000 172.508000 39.219600 0 0.261099

**Comment by Shadownflame** [comment]
It has half of its casting animation now.
Light on caster's hands as she raises them - check
Visual on target - check
Light under caster's feet - missing

It's not a huge issue but it looks different from how you look when casting Kings or Wisdom. Note, blessing of might also missing the light from under your feet.

Also, it affects all three ranks of BOL: spell ID 19977, 19978, 19979 and all races, not only undead.

**Comment by ghost** [comment]
Fixed in https://github.com/Project-Epoch/epoch-core/pull/1494
