### ISSUE TITLE
Deviate Creepers (WC entrance) drop Crisp Spider Meat

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7880]
> Deviate Creepers (WC entrance) drop Crisp Spider Meat

.go xyz -742.061000 -2059.770000 70.326900 1 0.326272

**Comment by Imperius5k** [comment]
Confirmed ingame that they do infact drop crisp spider meat.

**Comment by Shadownflame** [comment]
Fixed with vmangos port it seems.
