### ISSUE TITLE
Shiv can't crit, the Talent Lethality increases crit damage though

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7882]
> Shiv can't crit, the Talent Lethality increases crit damage though

.go xyz 1775.220000 -4286.000000 7.292990 1 2.391440

**Comment by zana244** [comment]
A wowhead comment mentions in 2.1.3 that Shiv can crit, and based on the talent tooltip it should make sense.

Confirmed, Shiv does not crit on Epoch.
Shiv also consumes cold blood but still does no crit.
#2613

**Comment by Shadownflame** [comment]
Shiv can crit now and works fine with Lethality and Cold Blood.
