### ISSUE TITLE
killed rare Lord Captain Wyrmak in Swamp of Sorrows, no loot, sa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7883]
> killed rare Lord Captain Wyrmak in Swamp of Sorrows, no loot, same as all other rares i've killed, reporting this one since it was a level 45 elite with about 9k health :||

.go xyz -10620.000000 -4084.630000 22.835400 0 5.527040

**Comment by Imperius5k** [comment]
confirmed in game that it does drop no loot upon death

**Comment by Shadownflame** [comment]
Loot fixed.
