### ISSUE TITLE
Tried to do the quest Sunken Treasure in Blasted Lands. Repeated...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7897]
> Tried to do the quest Sunken Treasure in Blasted Lands. Repeatedly searched all of the underwater wrecks and didn't find the treasure. Must not be in the game yet

.go xyz -11870.400000 -3933.340000 -1.438160 0 4.068380

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8171
