### ISSUE TITLE
The quest "Tired o' them Orcs!" doesn't track the orc kills for ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7907]
> The quest "Tired o' them Orcs!" doesn't track the orc kills for the objective.

.go xyz -8108.990000 -1654.950000 135.496000 0 5.484630

**Comment by zana244** [comment]
Confirmed, no credit from any orcs.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2341
