### ISSUE TITLE
The quest "Turtle Power" spells the Lean Turtle Flanks as "Lean ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7914]
> The quest "Turtle Power" spells the Lean Turtle Flanks as "Lean Turtle Flank's". There's an extra apostrophe that is unneeded.

.go xyz 332.727000 -2140.510000 123.228000 0 0.173386

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2222
