### ISSUE TITLE
The gryphon eggs for the quest "Reclaiming the Eggs" in the Hint...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7915]
> The gryphon eggs for the quest "Reclaiming the Eggs" in the Hinterlands can't be clicked to pick them up.

.go xyz -377.310000 -2966.190000 105.212000 0 1.656070

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
