### ISSUE TITLE
Enchant Cloak - Resistance can't be applied to the PvP vendor cl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7918]
> Enchant Cloak - Resistance can't be applied to the PvP vendor cloaks (ex:Aspirant's Cloak of Magic Potency).

.go xyz -2963.510000 -1387.890000 18.464800 0 2.877430

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4420
