### ISSUE TITLE
The flight path from Nijel's Point to Gadgetzan flies me through...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7919]
> The flight path from Nijel's Point to Gadgetzan flies me through custom buildings in Steamwheedle Port (as a gnome, Gnomish Innovation, flying machine flight path).

.go xyz -7284.690000 -3823.700000 16.248600 1 1.050600

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
