### ISSUE TITLE
The flight path from Nijel's Point to Gadgetzan flies me through...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7920]
> The flight path from Nijel's Point to Gadgetzan flies me through the walls in Theramore when flying out of the city (as a gnome, Gnomish Innovation, flying machine flight path).

.go xyz -6296.000000 -5156.080000 10.360100 1 2.968460

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
