### ISSUE TITLE
Item "Emblem of Upturn" is triggered by any spell, including cra...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7921]
> Item "Emblem of Upturn" is triggered by any spell, including crafting spells such as craftin a bolt of cloth with Tailoring.

.go xyz -4840.620000 -860.420000 501.914000 0 1.907730

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
