### ISSUE TITLE
The quest "Boom! Boom! Boom" from Inabit Wedgefeet in Steamwheed...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7926]
> The quest "Boom! Boom! Boom" from Inabit Wedgefeet in Steamwheedle Port in Tanaris has no "in-progress" quest text and rewards no reputation with Gadgetzan unlike surrounding quests.

.go xyz -6889.280000 -4747.190000 11.533200 1 1.198050

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2237
