### ISSUE TITLE
Fire Rocs in Tanaris (levels ~43-44) drop low level items such a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7927]
> Fire Rocs in Tanaris (levels ~43-44) drop low level items such as Linen Cloth and Frayed Robes.

.go xyz -7645.130000 -3336.240000 63.060000 1 2.917070

**Comment by Imperius5k** [comment]
i killed about 10 of them and none dropped any of the items mentioned in the post above

**Comment by Shadownflame** [comment]
> i killed about 10 of them and none dropped any of the items mentioned in the post above

I think their drop chance might not be high, it's just part of their loot tables possibly. Whatever fix Kaytotes is gonna port should take care of these kind of bugs too.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/543
