### ISSUE TITLE
There are no "Ancient Battery" items to be collected at the Noon...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7928]
> There are no "Ancient Battery" items to be collected at the Noonshade Ruins in Tanaris for the quest "The Perfect Fuel".

.go xyz -6894.960000 -4347.050000 14.925300 1 3.753800

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2228
