### ISSUE TITLE
Shadowforge Senator - (8904)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#793]
> whole room bugged for us after 2 packs
`.go xyz 1383.860000 -792.953000 -92.722800 736 4.635410`

> event do not work
`.go xyz 1381.300000 -756.232000 -92.722900 736 4.964880`

> Event stop after 1 pack of mob
`.go xyz 1374.900000 -787.434000 -92.723200 736 2.089370`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095 related

**Comment by kaytotes** [comment]
Next Deploy.

**Comment by Bennylavaa** [comment]
looks good also neat.
