### ISSUE TITLE
my Emblem of Dominance is being proc'd by me making Heavy Magewa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7932]
> my Emblem of Dominance is being proc'd by me making Heavy Magewaeve Bandages... so im just doing first aid and I keep getting the buff over and over again.

.go xyz -1015.530000 -3507.600000 62.975300 0 5.953620

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8314
