### ISSUE TITLE
ROgue can't have Poison on Mainhand if they want to benefit from...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7936]
> ROgue can't have Poison on Mainhand if they want to benefit from Windfury. We should be able to have Enchant, poison and Windfury active.

.go xyz 3506.410000 -3314.170000 130.643000 329 0.020538

**Comment by Shadownflame** [comment]
This is not a bug. Devs may implement this change in the future based on suggestions.
