### ISSUE TITLE
Warbringer Construct - (8905)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#794]
> these shouldnt be active yet.   they have to be pulled with the mage boss
`.go xyz 861.441000 -299.140000 -49.935400 736 3.534350`

> They are active before anything has been done, and pull with the boss.
`.go xyz 837.398000 -321.096000 -50.663800 736 4.420630`

> These enemies start active instead of activating when all of the relic coffers are opened
`.go xyz 840.414000 -326.050000 -50.663800 736 3.983300`

> only 1 golem active all other - not
`.go xyz 919.811000 -390.722000 -49.899300 736 2.338190`

**Comment by Bennylavaa** [comment]
this seems resolved.
