### ISSUE TITLE
Warlock pet unsummons upon logging out and back in

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7941]
> Warlock pet unsummons upon logging out and back in

.go xyz -7347.030000 -3632.620000 10.061300 1 0.475946

**Comment by Shadownflame** [comment]
Yep, the pets aren't supposed to disappear on every relog. This is also a huge issue for disconnects/server crashes, as it leaves the warlock logging back with their pet gone. Blizzlike behavior is when you log out your last summoned pet is visible next to you on the character screen, and it spawns along with you when you next log in.

**Comment by Shadownflame** [comment]
Resolved, blessed be Kaytotes.
