### ISSUE TITLE
Warlock pets do not resummon after flight paths and hearthstones...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7942]
> Warlock pets do not resummon after flight paths and hearthstones (so far)

.go xyz -576.145000 -4244.230000 38.151200 1 1.067120

**Comment by Shadownflame** [comment]
Unfortunately this is the way it worked back in the day, you get the shard refunded and that's it.
Strongly suggest changing it to the modern implementation where pets would unsummon when you take a flight path and return upon landing. It would be a huge QoL improvement.
Hearthing probably shouldn't unsummon at all, but it.might be a vanilla vs classic thing.
