### ISSUE TITLE
Reclaiming The Egg in the Hinterlands does not work. Gryphon Egg...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7946]
> Reclaiming The Egg in the Hinterlands does not work. Gryphon Eggs are note interactable. https://www.wowhead.com/wotlk/quest=9475/reclaiming-the-eggs#comments

.go xyz -401.843000 -2886.460000 84.942800 0 5.033200

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
