### ISSUE TITLE
Venomhide Eggs, from the quest "Venomhide Eggs" are not interact...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7950]
> Venomhide Eggs, from the quest "Venomhide Eggs" are not interactable, nor do they have the sparkles to show they are interactable. The object is there, and I confirmed with wowhead they were the right thing to click.

.go xyz -7651.330000 -1724.430000 -272.037000 1 2.743440

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2165
