### ISSUE TITLE
Rogue Assassination talent "Improved Poisons" incorrectly changi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7954]
> Rogue Assassination talent "Improved Poisons" incorrectly changing poison duration on weapon. With 0 points, the durtation is 60 min. With 1 point applied, the total duration is reduced to 12 minutes (instead of a total of 72 minutes as it should). With 2 points, the duration is 24 minutes, 3 points 36 minutes, etc.

.go xyz -8752.260000 381.973000 101.056000 0 4.240320

**Comment by zana244** [comment]
Solved during beta 3
