### ISSUE TITLE
No Blood Fury Racial on Tauren from Orc Racial Knowledge

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7958]
> No Blood Fury Racial on Tauren from Orc Racial Knowledge

.go xyz 1611.230000 -4401.120000 10.707600 1 5.722010

**Comment by Shadownflame** [comment]
Huh, they are missing their version of Blood Fury indeed.

**Comment by Shadownflame** [comment]
Primal fury added and functions perfectly.
