### ISSUE TITLE
Twilight's Hammer Ambassador - (8915)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#797]
> keep infight but not attackable and do not attack
`.go xyz 1380.400000 -750.163000 -92.722900 736 4.732970`

> Not attackable?
`.go xyz 1384.920000 -733.371000 -92.721800 736 4.277980`

> bugged
`.go xyz 1380.570000 -747.643000 -92.723000 736 3.936400`

> invalid mob doesnt become active  and stands there when they rp run down
`.go xyz 1389.500000 -726.283000 -92.722100 736 4.634480`

> invalid mob just stands there after they run out.
`.go xyz 1382.210000 -708.437000 -92.076600 736 4.764080`

> Cannot be attacked and just stand there doing nothing.
`.go xyz 1381.950000 -738.952000 -92.722100 736 4.921270`

> standing in non combat
`.go xyz 1379.730000 -750.787000 -92.723200 736 4.877620`

> Bugged. Spawned, cant be attacked, wont attack back.
`.go xyz 1382.880000 -751.564000 -92.722900 736 5.497930`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6002
