### ISSUE TITLE
the mobs that spawn for Lards Lunch quest in hinterlands do not ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7971]
> the mobs that spawn for Lards Lunch quest in hinterlands do not despawn, i just got attacked by 20 mobs

.go xyz -40.385600 -4679.950000 7.492430 0 6.071340

**Comment by zana244** [comment]
They also do not give XP on internal, whereas on wow classic they do
https://www.youtube.com/watch?v=4MIryGPUkEE

I also think they should aggro on you as soon (or soon) as you open the basket, on epoch they leave you alone.

**Comment by Shadownflame** [comment]
I figure they won't give exp because they can be endlessly spawned. The lunchbox never goes away, which is good because people won't have to wait for a long respawn.
Their automatic aggro is fixed now and the mobs despawn after about 1minute.
