### ISSUE TITLE
sometimes i use a 5 point combo Rip, and my combo points stay on...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7972]
> sometimes i use a 5 point combo Rip, and my combo points stay on the mob. FeralDruid cat. Of the coast of Hinterlands 20:44

.go xyz -523.279000 -4698.160000 -1.797390 0 0.997605

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4077
