### ISSUE TITLE
lv 55 Blue priest PVP set "Vanta" with mage bonus

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7977]
> lv 55 Blue priest PVP set "Vanta" with mage bonus

.go xyz -8770.470000 403.000000 109.664000 0 5.459650

**Comment by Shadownflame** [comment]
Item IDs:
63600, 63601, 63602, 63603, 63604, 63605

**Comment by Shadownflame** [comment]
This was resolved
