### ISSUE TITLE
Ooze Covered Thorium Vein above ground on current position. Thes...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7984]
> Ooze Covered Thorium Vein above ground on current position. These are only supposed to be found within silithid hives.

I suspect this isn't actually misplaced, but a separate bug causes them to sometimes spawn on the surface instead of underground.

.go xyz -8087.530000 -1334.880000 -268.321000 1 4.544590

**Comment by Bennylavaa** [comment]
moved to the node tracker
