### ISSUE TITLE
No mining nodes are spawning in the cave at the top level of Jin...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7993]
> No mining nodes are spawning in the cave at the top level of Jintha'alor. I can't remember if this is vanilla behaviour or not, but you may want to double check this.

.go xyz -680.033000 -3747.810000 219.093000 0 6.205740

**Comment by Bennylavaa** [comment]
Nodes do not spawn in this cave in vanilla.
