### ISSUE TITLE
Many new quests given by troll NPCs in Revantusk Village are wri...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7994]
> Many new quests given by troll NPCs in Revantusk Village are written with a troll accent. Which in itself isn't bad, but is inconsistent when those same NPCs also offer vanilla quests where their dialog is perfectly normal. Could probably tone this down.

.go xyz -588.534000 -4553.470000 9.105860 0 2.002930

**Comment by Kestrana** [comment]
I only found an issue with "Prime Slime", which I corrected. Lard's Lost Beads actually needed more "ogre" but the other quests seemed fine to me. https://github.com/Project-Epoch/epoch-core/pull/1600
