### ISSUE TITLE
Demoralizing Shout from the Dunemaul Enforcer's in Tanaris reduc...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7998]
> Demoralizing Shout from the Dunemaul Enforcer's in Tanaris reduce melee attack power even after the debuff has ran out. Relogging resets attack power to normal values.

.go xyz -8527.370000 -2776.520000 11.402100 1 5.668160

**Comment by Shadownflame** [comment]
NPC ID=5472
Spell ID 89521 in game (custom)
Might affect other spell IDs too. To Reproduce this issue the test character must have some + attack power.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8338
