### ISSUE TITLE
I died in Gittermurk Mines. Group disbanded. I disconnected. Rel...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#7999]
> I died in Gittermurk Mines. Group disbanded. I disconnected. Relogged, walked into the instance, did not resurect. I have to go back to the graveyard

.go xyz 3.074910 -82.445600 -8.439160 732 4.764980

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8292

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6072
