### ISSUE TITLE
Windfury totem overrides personal flametong enchant. I don't thi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8000]
> Windfury totem overrides personal flametong enchant. I don't think that's the proper mechanic. Personal should override group totems.

.go xyz -155.771000 -156.779000 -32.778300 732 3.813870

**Comment by zana244** [comment]
Seems solved on internal. personal FT does not get overwritten by personal windfury totem (maybe by someone else's?).
