### ISSUE TITLE
Rotors on zep is not moving

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8005]
> Rotors on zep is not moving

.go xyz -12465.300000 212.619000 34.487600 0 4.115420

**Comment by zana244** [comment]
As far as I could tell, blizzlike behaviour. The rotors stop rotating a bit before landing, as the vehicle would theoretically use its built-up momentum.
https://www.youtube.com/watch?v=oFlKJi1jU4Y
