### ISSUE TITLE
Improved Shield Bash Protection Warrior talent makes Shield Slam...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8011]
> Improved Shield Bash Protection Warrior talent makes Shield Slam silence target when it should work only with Shield Bash

.go xyz 128.715000 -3160.870000 121.966000 0 4.339480

**Comment by Imperius5k** [comment]
confirmed that this is infact bugged and is silencing.

**Comment by Shadownflame** [comment]
Fix confirmed.
