### ISSUE TITLE
rend's event bugged, only the first wave spawn,

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8012]
> rend's event bugged, only the first wave spawn,

.go xyz 168.401000 -429.196000 110.863000 229 0.357418

**Comment by Shadownflame** [comment]
This seems to be a separate issue from Gyth bugging. I could not yet reproduce this, maybe it was fixed during the beta?

**Comment by Shadownflame** [comment]
This cannot be reproduced, probably fixed mid beta
