### ISSUE TITLE
The southern bridge that leads from Redridge into Duskwood - the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8016]
> The southern bridge that leads from Redridge into Duskwood - the lighting is bugged. I've provided a clip in the #generic-bugs channel.

The lighting changes instantly, like a light-switch, rather than a gradual shift in tone.  It's aesthetic mainly of course, but clearly not intended.

.go xyz -10460.200000 -1696.720000 81.582000 0 4.948090

**Comment by Shadownflame** [comment]
![WoWScrnShot_062324_233134](https://github.com/Project-Epoch/bugtracker/assets/172074323/a5549152-adf8-49cf-b7bc-ac5001faec01)
![WoWScrnShot_062324_233141](https://github.com/Project-Epoch/bugtracker/assets/172074323/b258a641-ea43-41ba-a957-6c91edd62723)
I guess it could use some polish but it's a really, really minor thing.

**Comment by zana244** [comment]
https://github.com/Project-Epoch/bugtracker/assets/50482785/b30fbe7c-c096-406c-a728-4da91de7e02c
Seems to have been solved on internal. You're at the wrong spot, this is the video they mentioned in discord.
Now there is a gradual smooth transition, well done!

**Comment by Shadownflame** [comment]
Oh wow, yeah, that's much worse.
