### ISSUE TITLE
Voidwalker Minion - (8996)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#803]
> These minions deal Shadowstrike damage, which causes their attacks to completely ignore Armor. Even at level 10, their attacks deal double the amount of damage of regular hostile mobs. This seems very overtuned.
`.go xyz 1452.010000 -4867.140000 12.385000 1 0.427064`

**Comment by zana244** [comment]
Not sure if intended, but way too based, this cave also has overtuned thugs.
Hits for 30-40.
https://www.wowhead.com/classic/npc=8996/voidwalker-minion#comments
"This little guy in Durotar - Skull Rock, is one of the top 5 killers in all of Hardcore Classic Wow. Be warned."
