### ISSUE TITLE
Sometimes Autoattack just doesnt do anything. You have it active...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8030]
> Sometimes Autoattack just doesnt do anything. You have it active (blinks active on the hotbar), you're standing in melee with the mob but nothing happens. If you stop autoattack and re-engage it(without moving or anything) it starts working correctly again

.go xyz -12702.700000 -468.196000 30.217400 0 4.136120

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6847
