### ISSUE TITLE
Zone: Tanaris
Quest: The one where you give an offering on the a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8044]
> Zone: Tanaris
Quest: The one where you give an offering on the altar to Gral east of Anje'Watha

Issues: Quest doesn't say that the altar is north along the beach rather than south. Item of offering to Gral remains in your inventory even after the quest ends.

.go xyz -9606.410000 -4161.600000 124.618000 1 6.182550

**Comment by Bennylavaa** [comment]
no idea what quest removing this for now
