### ISSUE TITLE
Zone: Tanaris
Quest: Silithid Scramble
Issue: Almost impossible ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8046]
> Zone: Tanaris
Quest: Silithid Scramble
Issue: Almost impossible to complete/Quest text sends you on impossible quest. You are asked to kill 6 Centipaar Tunnelers in The Noxious Lair underground. There are none there.

Centipaar Tunnelers only spawn 2 mobs during the Gadgetzan Water Surver quest using a dowsing widget in the pool of water at Sandsorrow Watch. So you'd need to dowse there 3 times in order to complete this quest.

.go xyz -7825.810000 -2575.320000 -43.322400 1 1.391830

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7580
