### ISSUE TITLE
Zone: Tanaris
Item: Captain's Key
Issue: Clicked on Captain's Ch...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8048]
> Zone: Tanaris
Item: Captain's Key
Issue: Clicked on Captain's Chest in Lost Rigger Cove. Key disappeared but chest didn't loot - nothing received.

.go xyz -7980.430000 -5491.430000 7.526370 1 5.366440

**Comment by Shadownflame** [comment]
Chest is just sometimes empty. https://github.com/Project-Epoch/bugtracker/issues/6592
