### ISSUE TITLE
Zone: Tanaris
Quest: Water Co. Saviour
Bug: No Filter Parts visi...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8049]
> Zone: Tanaris
Quest: Water Co. Saviour
Bug: No Filter Parts visible to find for the quest.

.go xyz -6858.710000 -4759.800000 9.779150 1 3.290900

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
