### ISSUE TITLE
Quest: The Manor, Ravenholdt
Zone: Hillsbrad Foothills

Issue: C...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8052]
> Quest: The Manor, Ravenholdt
Zone: Hillsbrad Foothills

Issue: Clicking on quest item spawns two copies of NPC Milton Beats.

.go xyz -0.334652 -1580.680000 203.794000 0 5.906210

**Comment by zana244** [comment]
Confirmed, it spawns 2.

**Comment by ghost** [comment]
I am unable to reproduce this on the PTR

**Comment by zana244** [comment]
Still managed to do this by just accepting the quest from the letter, walking up to the chest on internal and right clicking it.
Maybe it works differently on internal?
![image](https://github.com/user-attachments/assets/77bc2264-d254-4b2e-aca9-6c83d9f1194b)
Also, the NPCs do not aggro by default?

**Comment by Shadownflame** [comment]
Only spawns one Milton now, however, I got a female Milton? 
Is this a new inclusivity feature or the NPC random generates their skin?
I'm fairly sure he is supposed to be male.
![WoWScrnShot_120524_174418](https://github.com/user-attachments/assets/769fc518-d8d0-4b14-93fd-a26181cbaa3e)




The aggro issue seems fixed too, (s)he engages without mercy.

**Comment by kaytotes** [comment]
Not an us thing. Blizzard changed it some time between Vanilla and Wrath

**Comment by kaytotes** [comment]
Easy to put back if we want i guess

**Comment by Shadownflame** [comment]
Another issue seems to be (s)he takes way too long to despawn if not killed (and well, its not really designed to be killed). Logged back 40 minutes later, still guarding the chest.

**Comment by kaytotes** [comment]
Next Deploy.
