### ISSUE TITLE
Killing High chief Winterfall in winterspring, made me respawn a...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8056]
> Killing High chief Winterfall in winterspring, made me respawn all the way to alterac valley?????

.go xyz 440.753000 -1031.050000 111.369000 0 2.665660

**Comment by Imperius5k** [comment]
this only includes the coordinates to alteric valley and not the high chief winterfall therefore it may be tricky to test.

**Comment by zana244** [comment]
Confirmed on internal, dying in the cave (as far as I could tell?) teleports you to AV.
For High Chief Winterfall:
.go xyz 6721.530762 -5261.066895 778.356995 1
