### ISSUE TITLE
Silver Stream mine in Loch Modan does not contains any ore nodes

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8060]
> Silver Stream mine in Loch Modan does not contains any ore nodes

.go xyz -4853.200000 -2974.060000 321.530000 0 6.225860

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/385e5501-39c6-4d67-ad69-48e841cb2ae5)

**Comment by Bennylavaa** [comment]
second thought it could be due to this so will cross post https://github.com/Project-Epoch/bugtracker/issues/8295
