### ISSUE TITLE
I accidently closed to Bug Report for the Rite of Vision quest. ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8065]
> I accidently closed to Bug Report for the Rite of Vision quest. I wanted to point out that the spirit wolf you follow is just fast enough to outpace you at your swiftest and most direct path behind it. It lost it in the disance. Luckily I knew where to go. Should probably slow it down a touch if you haven't already.

.go xyz -2265.650000 -372.837000 -9.424130 1 2.865630

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2375
