### ISSUE TITLE
The lvl 55 PvP Paladin Plate Set has Shaman oriented Set Bonuses...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8067]
> The lvl 55 PvP Paladin Plate Set has Shaman oriented Set Bonuses, instead of Paladin Bonuses.

.go xyz -8770.360000 403.159000 109.665000 0 5.268790

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8054
