### ISSUE TITLE
A lot of Rich Thorium Veins only have 2 ore in them, although th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8068]
> A lot of Rich Thorium Veins only have 2 ore in them, although they should have at minimum 4! Until now, i never had 3 ores in a Rich Thorium Vein.

.go xyz -8224.760000 -1040.800000 -183.237000 1 4.990400

**Comment by Bennylavaa** [comment]
From what I have read in comments classic had a bug that allowed 6 taps whereas vanilla was usually 3-4 but sometimes there was a 2 tapper although rare. 

From what I can tell this is blizlike, however could be something we look into in the future. I believe turtle changed theirs to always be 4 taps.
