### ISSUE TITLE
Relogging during flight kicks you from every global chatchannel,...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8074]
> Relogging during flight kicks you from every global chatchannel, manuel rejoin was not possible. After restarting the client the channels where automatically joined again. Btw keep up the great work on the server! luv you guys!!!

.go xyz -3137.570000 -2844.320000 34.416100 1 6.120550

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4099
