### ISSUE TITLE
Flying from Tarren Mill to The Sepulcher you phrase right throug...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8077]
> Flying from Tarren Mill to The Sepulcher you phrase right through the Dalaran bubble and can see the empty shell inside. Quite an immersion breaker

.go xyz 478.860000 1536.590000 131.318000 0 0.603619

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/6744
Not sure if the flight pathing is intended to cut through at all.

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8307
