### ISSUE TITLE
Hello! Don't know if it is a bug, but the transition between nig...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8081]
> Hello! Don't know if it is a bug, but the transition between night and day is so sudden. One second it is day, and the next it is night, without evenings etc.. Don't know if it is intended but it feels not natural! Keep up the good work guys the server is phenomenal!

.go xyz -8722.280000 -99.469200 88.099300 0 5.950790

**Comment by Shadownflame** [comment]
Must have been already resolved. Evenings certainly exist and the transition is smooth as the sun slowly rises/sets.
