### ISSUE TITLE
Quest "The Fizz" in Winterspring, given out by Tanum refers to s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8084]
> Quest "The Fizz" in Winterspring, given out by Tanum refers to something called the Electro B.L.T.R. Device that you have to charge by chimera lightning breath. However, when accepting the quest, you don't recieve any items and when the chimaeras breathe lighting at you, nothing happens.

.go xyz 6398.940000 -4821.560000 725.218000 1 0.028643

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7599
