### ISSUE TITLE
In BRD two or Hurley's minions stay invulnerable and untargetabl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8085]
> In BRD two or Hurley's minions stay invulnerable and untargetable after the fight, until they redo the walk-in and only then become targetable

.go xyz 895.621000 -145.320000 -49.757400 736 4.351390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/839
