### ISSUE TITLE
In blackrock depths, in the big hall with many trash mobs and br...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8086]
> In blackrock depths, in the big hall with many trash mobs and braziers, before Magmus. There were no trashmobs!

.go xyz 1378.070000 -708.670000 -92.087600 736 1.723960

**Comment by Shadownflame** [comment]
Nonelite dwarves all missing except for the flamekeepers in the Lyceum
Fire elementals protecting the braziers missing too
