### ISSUE TITLE
In the sunken temple, two dragons that spawn in the center of th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8087]
> In the sunken temple, two dragons that spawn in the center of the main chamber despawn after we kill hakkar. (We have not kiled them just left them for later)

.go xyz -526.092000 92.937900 -91.167500 109 6.071970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8310
