### ISSUE TITLE
Doom'rel - (9039)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#809]
> can open the chest after you beat the event
`.go xyz 1258.580000 -253.278000 -78.219000 736 2.070540`

> no loot lootable at the 7 dwarf chest
`.go xyz 1264.220000 -252.962000 -78.219100 736 1.731580`

> no loot after killing
`.go xyz 1267.720000 -277.015000 -78.219200 736 0.477595`

> Chest is broken, can't loot
`.go xyz 1266.660000 -246.192000 -78.178300 736 1.798480`

> Boss fight bugged out halfway through the fight.  Only 3 of adds activated before it stopped working
`.go xyz 1266.860000 -251.560000 -78.218400 736 4.234760`

> stuck on this boss last add doesn't come to  attack us.
`.go xyz 1261.420000 -255.043000 -78.219100 736 5.386490`

> Chest cannot be opened after defeating
`.go xyz 1258.460000 -278.186000 -78.219200 736 5.309360`

> Dwarf council didnt drop loot
`.go xyz 1262.550000 -243.930000 -79.546900 736 5.305430`

> no loot
`.go xyz 1262.380000 -285.765000 -78.218500 736 4.321570`

> no loot second time
`.go xyz 1269.050000 -258.985000 -78.218700 736 2.049930`

> boss does not have loot and sometimes bugged that so we cannot progress after we kill Gloom'rel - there is 2 bosses left Hate'rel and Doom'rel - they lest green, we cannot kill it
`.go xyz 1265.480000 -244.638000 -78.644400 736 4.651800`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6142
