### ISSUE TITLE
One blackbreath crony in brd cant be attacked and keeps us in co...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8096]
> One blackbreath crony in brd cant be attacked and keeps us in combat

.go xyz 851.578000 -168.193000 -49.756000 736 3.862130

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095

**Comment by Bennylavaa** [comment]
This seems like it was fixed. I cannot reproduce this @Shadownflame

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/839
