### ISSUE TITLE
Multiple holdovers from TBC and WotLK in Engineering profession ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8101]
> Multiple holdovers from TBC and WotLK in Engineering profession such as the Flying Machine, Fell Iron Bombs, Fel Iron Casings, etc.

.go xyz -7144.700000 -3823.710000 8.477830 1 5.563740

**Comment by zana244** [comment]
You only get them if you boost from the beta goblins, they are not trainable.
