### ISSUE TITLE
Thorium Toolbox under the Engineering skill displays the tooltip...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8102]
> Thorium Toolbox under the Engineering skill displays the tooltip for Big Bag of Hides, a 24 Slot LW bag

.go xyz -7144.700000 -3823.710000 8.477830 1 5.563740

**Comment by ghost** [comment]
Duplicate of https://github.com/Project-Epoch/bugtracker/issues/1938
