### ISSUE TITLE
Leaving Warmode supposedly costs 75g, but no money is extracted ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8103]
> Leaving Warmode supposedly costs 75g, but no money is extracted after leaving.

.go xyz 1925.010000 -4192.590000 41.943000 1 1.889670

**Comment by Shadownflame** [comment]
As per Kaytotes, this is simply missing implementation.

**Comment by Bennylavaa** [comment]
level 10 it costs 1g
level 20 its 5g
level 30 its 20g
level 40 its 75g
level 50 its 100g
level 60 its 150g
