### ISSUE TITLE
I got the explore Silithus achievement just by flying to Valor's...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8104]
> I got the explore Silithus achievement just by flying to Valor's Rest. Also in the wind rider map Valor's Expedition says it's in Tanaris, but is actually in Silithus.

.go xyz -6357.280000 -254.065000 -2.392800 1 2.564390

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6989
