### ISSUE TITLE
After extensive testing I can confirm that there is an interacti...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8106]
> After extensive testing I can confirm that there is an interaction between spell damage and cheat death, where spell damage afflicted on the rogue is multiplied by the 33% chance to activate cheat death at a rate equal to eac talent point, up to 100% extra damage taken.

.go xyz -4668.790000 -3002.910000 36.908700 1 1.417920

**Comment by zana244** [comment]
#2878
