### ISSUE TITLE
Cat has far too much survivability somewhere. At level 45 with t...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8109]
> Cat has far too much survivability somewhere. At level 45 with talents but no buffs, not even my own MOTW or thorns, I can auto-attack a mob my level down to 0 and sometimes finish on over 90% HP. 

When played properly I can kill the same mob in 15 seconds and sometimes my health is 95% afterwards - I love the lack of druid downtime but this is probably too far, gotta narc on the other druids!

.go xyz -8657.740000 -3737.960000 23.035900 1 2.338100

**Comment by Shadownflame** [comment]
Not a bug report.
