### ISSUE TITLE
In Dun Morogh, at the event of the Mortar Team, the Mortar Team ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8111]
> In Dun Morogh, at the event of the Mortar Team, the Mortar Team Target Dummy is moving towards Angus and it would not reach him.

.go xyz -6017.210000 -223.217000 411.939000 0 1.260880

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/976
