### ISSUE TITLE
I died right after getting summoned at ZF summon stone

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8113]
> I died right after getting summoned at ZF summon stone

.go xyz 1212.670000 842.040000 8.933460 209 0.000000

**Comment by Shadownflame** [comment]
Might be related to https://github.com/Project-Epoch/bugtracker/issues/8201
Will need to see if accepting summons while on transport is capable of producing this bug too. (3 people required for test)

**Comment by Shadownflame** [comment]
Nope, summons dont produce the same issue.
