### ISSUE TITLE
Witch doctor Zum'rah in ZF doesnt drop loot

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8115]
> Witch doctor Zum'rah in ZF doesnt drop loot

.go xyz 1877.130000 1023.540000 8.876910 209 2.420230

**Comment by kaytotes** [comment]
Mob worked fine in previous betas, investigate.

**Comment by Shadownflame** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/8249
