### ISSUE TITLE
A Rogue's Deal" Quest not shown as completed for Tirisfal Lorewa...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8117]
> A Rogue's Deal" Quest not shown as completed for Tirisfal Lorewalker Achievement even when done.

.go xyz 2029.890000 151.695000 33.868500 0 3.342180

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/f67153de-b52c-4a64-9b74-2023b998d5de)
Works just fine, most likely they never did the followup quest with the same name
