### ISSUE TITLE
Check spawns in crypt, 4 enemies within same pull range so you c...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8118]
> Check spawns in crypt, 4 enemies within same pull range so you cannot enter crypt alone.

.go xyz 3042.360000 663.209000 77.345200 0 2.814000

**Comment by Shadownflame** [comment]
This is the intended vanilla behavior. The mobs got rearranged on wrath to facilitate soloing this quest, on vanilla you needed to separate the mobs yourself. I made a quick test case on internal to demonstrate how this quest was done back in the day and can confirm it works on Epoch just as well:

https://github.com/Project-Epoch/bugtracker/assets/172074323/9dd5ac8d-d5c3-4f87-a872-b1a6d6e11b43

I have not used anything else but what a lvl 14 has available (weak troll elixir from quest, 1 minor healing potion, and a +2 stamina food you can get from lvl 1 cooking), in completely white low lvl vendor gear. I don't even have keybinds setup so pure vanilla skill level. Classes like hunter/warlock can solo this quest as early as lvl 11-12, without a pet you need to be 13-14 to do it without corpse runs. With a corpse run you can skip the entire pull and just simply rez in the lower section of the crypt, which was also commonly used back in the day. Long live vanilla.
