### ISSUE TITLE
Flo (Raremob in Tirisfal, Brightwater Lake) cannot be hit with m...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8119]
> Flo (Raremob in Tirisfal, Brightwater Lake) cannot be hit with melee attacks. Always says I'm too far away. Hitting it with casts was possible. Not sure how hitbox behaves or where it is located compared to my character. Tried different heights in water, but didnt make it work.

.go xyz 2374.920000 35.175700 21.683500 0 5.890140

**Comment by zana244** [comment]
Could replicate on internal. First pull I actually managed to melee him, subsequent 2 pulls I could not, and he paths strangely to the surface of the water and back down to me...

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Shadownflame** [comment]
Seems fixed after water improvements.
