### ISSUE TITLE
Quest ''Melding of Influences'' The gargantuan ooze cant be inte...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8132]
> Quest ''Melding of Influences'' The gargantuan ooze cant be interacted with unless you alt+f4 first. if you then kill it, you cant loot it despite it having a loot-window. It then also despawns after 15 seconds.

.go xyz -8013.100000 -1598.310000 -271.242000 1 0.456668

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2099
