### ISSUE TITLE
Gordunni Scroll quest cant be picked up

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8135]
> Gordunni Scroll quest cant be picked up

.go xyz -4010.390000 -180.009000 140.125000 1 1.108660

**Comment by zana244** [comment]
Gordunni Scroll is not there on the realm, it is however at 
.go xyz -3955.370117 -156.740997 140.735992 1 0.383972

And you can pick it up and it respawns in around 5 seconds in the same spot every time.
