### ISSUE TITLE
Wanted ''Scorchmaw'' in Springsocket is not able to be picked up...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8139]
> Wanted ''Scorchmaw'' in Springsocket is not able to be picked up from the wanted board

.go xyz -6901.260000 -3876.360000 281.472000 0 3.716690

**Comment by ghost** [comment]
This is related to a module I believe, it works fine on my local with no modules enabled

**Comment by Shadownflame** [comment]
This still persists. There is a wanted post with a quest visually here, but cannot interact.
![WoWScrnShot_090524_000846](https://github.com/user-attachments/assets/f25d19f0-6889-43d1-ae7b-3ca4d77d5e26)

**Comment by Kestrana** [comment]
The quest giver didn't have a faction tag. I've fixed this and it should work now. https://github.com/Project-Epoch/epoch-core/pull/1600
