### ISSUE TITLE
Mind-numbing poison rank 2 is taggegd as ''Junk'' in the rogue's...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8142]
> Mind-numbing poison rank 2 is taggegd as ''Junk'' in the rogue's poison profession window

.go xyz 1808.010000 -4272.160000 7.097290 1 6.160030

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6687
