### ISSUE TITLE
Dustwind cave in durotar makes you discover lost rigger cove

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8145]
> Dustwind cave in durotar makes you discover lost rigger cove

.go xyz 892.365000 -4706.200000 25.355500 1 6.255600

**Comment by kaytotes** [comment]
Ancient issue across many cores with no known fix yet.

https://github.com/TrinityCore/TrinityCore/issues/19761
https://github.com/chromiecraft/chromiecraft/issues/30

**Comment by Shadownflame** [comment]
Probably related? https://github.com/Project-Epoch/bugtracker/issues/8056
If there is no fix that's gonna hurt those poor ghosts, damn.
