### ISSUE TITLE
Pagoo, the rare crab in Durotar, probably isnt intended to be sk...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8146]
> Pagoo, the rare crab in Durotar, probably isnt intended to be skinnable

.go xyz -117.080000 -5210.840000 0.065242 1 3.681530

**Comment by zana244** [comment]
Confirmed on internal, it is skinnable, which crabs usually aren't in WoW.

**Comment by Kestrana** [comment]
Removed skinning loot from Pagoo https://github.com/Project-Epoch/epoch-core/pull/1600
