### ISSUE TITLE
Eridan Bluewind - (9116)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#816]
> Can't turn in Linken's Memory to her. She's just stuck channeling a spell
`.go xyz 4007.070000 -1311.180000 254.497000 1 6.012030`

> You can take quests from her, she keeps casting an instant
`.go xyz 4006.880000 -1309.870000 254.497000 1 5.746450`

> Except if you change that on Epoch, this character should not be constantly casting something and should give a quest.
`.go xyz 4006.240000 -1310.010000 254.497000 1 5.682390`

> Npc bugged and can't be interacted with.
`.go xyz 3993.990000 -1300.540000 253.247000 1 5.724730`

> Seems to have bugged during hte Purified! quest, doesn't progress the quest. Abandoning didn't let me retake the quest.
`.go xyz 3992.470000 -1298.400000 252.668000 1 5.685400`

> Unable to hand in "Linken's Memory" to this NPC.
`.go xyz 4007.080000 -1309.650000 254.497000 1 5.647720`

> NPC is part of the Linken's Memory questline but will not interact in any way with the player. Should be able to turn in the quest Linken's Memory and give Silver Hearts.
`.go xyz 4007.380000 -1311.930000 254.497000 1 0.266178`

> Have quest "Flute of Xavaric" from item id 11668. Eridan has no interaction for this quest (same for Linken's Memory).
`.go xyz 4007.140000 -1309.800000 254.497000 1 5.737800`

> Have quest "Linken's Memory" but no interaction possible with Eridan Bluewind. When speacking to her I get the default dialog "The Emeraid Circle strives ...blablabla.. from this land.
`.go xyz 4006.340000 -1310.770000 254.497000 1 5.918430`

> She is casting and cannot continue Linken's Memory for me.
`.go xyz 4005.520000 -1309.250000 254.496000 1 5.608470`

> She buggs out at some point during one of her quests. She starts casting a spell and can't be interacted with anymore
`.go xyz 4524.090000 -822.845000 350.453000 1 0.225609`

> Can't turn in "Linken's memory" (id:3942)
`.go xyz 4006.230000 -1310.100000 254.497000 1 5.629820`

> The quest "Linken's Memory" cannot be turned to Eridan Bluewind when we reach that part. She seems to be stuck in an animation and im not sure if its related.
`.go xyz 4007.220000 -1311.680000 254.496000 1 0.494794`

> This NPC doesn't intereact  with the quest "Linken's Memory" And has been stuck in the purifying animation since she cleansed the Ironwood Flute.
`.go xyz 4006.080000 -1313.070000 254.497000 1 0.492354`

> Quest "Purified!" is bugged. The NPC just stands there stuck in an animation and the quest doesn't complete.
`.go xyz 4007.450000 -1309.710000 254.497000 1 5.652780`

> Flute of Xavaric quest cannot be turned in at this NPC upon completion.
`.go xyz 4007.020000 -1311.350000 254.497000 1 6.139980`

> This NPC does not complete the quest "Linken's Memory", despite the quest saying I have to talk to her.
`.go xyz 3998.130000 -1303.540000 254.792000 1 5.620260`

> Linken memory doesnt work ?
`.go xyz 3999.870000 -1305.510000 254.807000 1 2.570510`

> NPC is stuck after accepting "Purified", rendering her unable to give out any other quest and also breaking this one
`.go xyz 3994.580000 -1299.570000 253.242000 1 5.402920`

> is the endpoint for the quest "Linken's Memory" but does not have any text prompts.
`.go xyz 4006.980000 -1310.090000 254.496000 1 5.589960`

> Quest - Purified! - looks like you take that quest and it never ends. cannot speak again and mob looks like stuck witch animation
`.go xyz 4007.120000 -1310.030000 254.496000 1 5.822080`

> Cannot be interacted with for quests
`.go xyz 4006.380000 -1309.460000 254.496000 1 5.735180`

**Comment by zana244** [comment]
#7895
