### ISSUE TITLE
Larion - (9118)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#817]
> bro is just sitting behind a hill in Marshall Refuge waiting to body me. The heck is going on here?
`.go xyz -6262.150000 -1142.370000 -243.240000 1 0.600158`

**Comment by Bennylavaa** [comment]
Alliance is hostile toward Larion and Horde is hostile toward Muigin.

It's because Alliance members get a quest from Muigin to mess with Larion, and Horde members get a quest from Larion to mess with Muigin.
