### ISSUE TITLE
It appears as if the treasure for "sunken treasure" does not exist

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8171]
> It appears as if the treasure for "sunken treasure" does not exist

.go xyz -11926.200000 -3797.470000 53.396000 0 0.448284

**Comment by Bennylavaa** [comment]
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/5a8aaac2-b26b-4d33-8ce5-53f5813b91d3)
it deff exists
