### ISSUE TITLE
We killed Magmus but the door to Emp did not open in BRD lol

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8173]
> We killed Magmus but the door to Emp did not open in BRD lol

.go xyz 1381.150000 -707.665000 -92.056800 736 4.825670

**Comment by Bennylavaa** [comment]
am able to reproduce this on ptr

**Comment by Shadownflame** [comment]
This works on the correct custom BRD map (736). Teleporting to creature ID puts you to the old map where some bugs weren't fixed.
