### ISSUE TITLE
In Storm, Earth, Wind, and Fire, you can just drain the corpses ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8175]
> In Storm, Earth, Wind, and Fire, you can just drain the corpses of the air elementals over and over to complete the quest

.go xyz -8140.810000 -935.906000 -187.732000 1 4.087460

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2321
