### ISSUE TITLE
A quest 'A strange request' is wotlk version and want you to tal...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8195]
> A quest 'A strange request' is wotlk version and want you to talk with Xerash Fireblade, that is not existed in vanilla state. Cant find that mob there too.

.go xyz -4089.670000 92.906200 76.281000 1 2.272610

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2075
