### ISSUE TITLE
Hearthing on a boat will kill you

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8201]
> Hearthing on a boat will kill you

.go xyz -4845.960000 -1000.320000 -1600.760000 0 4.953810

**Comment by Shadownflame** [comment]
I managed to reproduce this. Hearthed on the boat from Wetlands to Theramore while it was already moving deep in the sea, and got ported a good 200 yards above my hearth spot at the human starting zone:

![WoWScrnShot_061824_143635](https://github.com/Project-Epoch/bugtracker/assets/172074323/3e3a3fe3-2b95-4dae-af00-4948bf66a928)

You can figure out what happened after.

**Comment by Shadownflame** [comment]
Happens on the Menethil >Southshore miniboat, too.
Zeppelins as well.

UPDATE: other types of teleports trigger this bug too
