### ISSUE TITLE
The new version of the Improved Drain Soul talent for Warlocks s...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8207]
> The new version of the Improved Drain Soul talent for Warlocks should increase the damage of Drain Soul by 30% at rank 2 of the talent. However, it does not increase the damage at all.

.go xyz 2112.630000 -4653.630000 47.281900 1 4.887310

**Comment by Shadownflame** [comment]
Spell ID 18372
Mana regen works fine now, but no damage given.
