### ISSUE TITLE
I feel like quest items for some new qustom quest at Tanaris bea...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8208]
> I feel like quest items for some new qustom quest at Tanaris beach do not respawn. ("The Perfect Fuel", "Water Co. saviour")

.go xyz -6540.150000 -4907.630000 -1.012000 1 6.201140

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2238
