### ISSUE TITLE
Dalaran Apprentice In Silverpine Forest do no social agrro, had ...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8215]
> Dalaran Apprentice In Silverpine Forest do no social agrro, had one run away and none of the others jumped in to help

.go xyz -30.837600 1366.050000 61.311800 0 5.318640

**Comment by zana244** [comment]
If they manage to flee, they will aggro eventually ... However, they more often than not start to immediately cast frostbolt after beginning to flee, exiting flee mode.
Not sure if there should be some proximity aggro, if you pull a humanoid past another, it should pull?
#8252

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6624

**Comment by Shadownflame** [comment]
This is still bugged even after the peer aggro improvements that work elsewhere. Their aggro ticks don't seem to happen while they are casting, so when they flee and pause near another mob, it won't aggro no matter how close they are (see screenshot). Only if you run them completely out of mana they will do their 'pulse' and aggro the nearby mob.
![WoWScrnShot_080124_234252](https://github.com/user-attachments/assets/15e550bf-4a30-4ecd-a1b1-9bef7cdf5486)

**Comment by Shadownflame** [comment]
Adding here that mobs attempt getting assist from dead peers. To be tested after ktotes deploys fix.

**Comment by Shadownflame** [comment]
Social aggro is now fine (if they make it to the nearest peer), dead peers are ignored, https://github.com/Project-Epoch/bugtracker/issues/6624 persists but that's not specific to this mob.
