### ISSUE TITLE
Bloodmyst island apear when you open flight map! dont know if th...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8226]
> Bloodmyst island apear when you open flight map! dont know if that is bug but just wanna let you know

.go xyz 6776.420000 791.262000 87.941100 1 2.814500

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5999

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8266
