### ISSUE TITLE
The Quest "Data Rescue" doesnt work proberly. The last machine o...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8229]
> The Quest "Data Rescue" doesnt work proberly. The last machine ofr the punchcards is not spawned.

.go xyz -691.179000 524.924000 -277.301000 90 2.888420

**Comment by zana244** [comment]
.go xyz -864.416016 394.924988 -316.428986 90 0.645772

Matrix Punchograph 3005-D is present there, and gives Prismatic Punch Card if you have the Red Punch Card
