### ISSUE TITLE
Lord Blackstone is doing way to much dmg for a 5 man dungeon. Fe...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8232]
> Lord Blackstone is doing way to much dmg for a 5 man dungeon. Feels like a wotlk boss, but players don't have WOTLK stats :D

.go xyz 157.416000 -238.595000 -7.777870 731 1.512710

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/1254
