### ISSUE TITLE
Mage Talent: Empowered Arcane Missiles. 

The Arcane Barrage aft...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8239]
> Mage Talent: Empowered Arcane Missiles. 

The Arcane Barrage after Arcane Missiles is doing less dmg instead of more dmg with stacks of Arcane Blast.

.go xyz -6656.530000 -1328.230000 244.687000 0 1.738770

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2917
