### ISSUE TITLE
Not enough Gnome Car Parts at the Quest The Perfect Container. O...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8242]
> Not enough Gnome Car Parts at the Quest The Perfect Container. Only 5 on ground, 6 needed. Respawn time is too long. Could be a horror if more than 1 player is doing the quest.

.go xyz -7048.790000 -3515.250000 20.395900 1 6.203970

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2230
