### ISSUE TITLE
Quest: Waste Removal
Item: Oil Absorber

The Oil Absorber doesn'...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8244]
> Quest: Waste Removal
Item: Oil Absorber

The Oil Absorber doesn't work correctly if you have a target that is not near the Oil Spill. Without target it works correctly.

.go xyz -7286.390000 -4906.660000 0.977475 1 4.937840

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2234
