### ISSUE TITLE
Ghazrilla in Zul'Farak despawned after a while

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8245]
> Ghazrilla in Zul'Farak despawned after a while

.go xyz -8826.890000 641.427000 94.332100 0 0.126164

**Comment by zana244** [comment]
Confirmed on internal, did not attack Ghaz'Rilla and she despawned in around 5 min after beating the gong. (stopwatch showed around 4:30 min and I started it when she became  attackable).

After some time the gong becomes re-interactible, but it does not spawn Gahzrilla again.

**Comment by kaytotes** [comment]
Next deploy.

**Comment by Shadownflame** [comment]
Looks stable now.

**Comment by Shadownflame** [comment]
Afraid my previous 20min test run wasn't sufficient.
30 minutes after Gahz is summoned the entire instance gets bricked and kicks you out (not even to the entrance but your hearth location), resetting completely. I really don't know who would ever need half an hour to clear this boss and for what reason, but it's not okay for something like this to randomly delete the instance ID and teleport the entire group to the other side of the planet.

100% new issue as gahz despawning after 5minutes never did this.

Note, this requires Gahz is engaged after spawning to reproduce.

**Comment by kaytotes** [comment]
It is impossible for these two things to be related. All that changed was the spawn time number.

**Comment by Shadownflame** [comment]
Yes Benny reported since that he had the same thing happening in Ony so it's most likely a more widespread issue than just ZF and it's pure coincidence that I had encountered it three times in a row after summoning Gahz.
Will have to open a separate issue but we aren't quite sure what causes these instance boots yet.
