### ISSUE TITLE
regular mobs and chests appear to not be dropping any green/unco...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8249]
> regular mobs and chests appear to not be dropping any green/uncommon at all. And for humanoid mobs, they seem be dropping grey weapons/armor at a 100% chance. The loot tables may be a bit bugged

.go xyz -5763.210000 -1215.860000 384.506000 0 0.785626

**Comment by Shadownflame** [comment]
This issue was prevalent on the beta. Waiting for vmangos port to be applied which will hopefully fix all of this.

**Comment by Shadownflame** [comment]
Fixed.
