### ISSUE TITLE
when looting Felix's box for the quest A Refugee's Quandary, the...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8250]
> when looting Felix's box for the quest A Refugee's Quandary, the quest tracker didn't update progress (that I had the box in my inventory ("1/1 Felix's Box') until I actually opened the quest log and clicked on the quest again

.go xyz -6481.140000 497.897000 385.848000 0 3.974170

**Comment by Bennylavaa** [comment]
This happens to all quests occasionally and I believe is a client problem.

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2076
