### ISSUE TITLE
Devouring ectoplasm near mad magglish in waling cavenrs entrance...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8261]
> Devouring ectoplasm near mad magglish in waling cavenrs entrance evades after 1 sec. seems to be stuck, but evades even when player is standing next to it.

.go xyz -677.422000 -2040.410000 66.640000 1 4.429930

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8302
