### ISSUE TITLE
Rogue's Mind-numbing Poison II is a grey junk. It cannot be used...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8264]
> Rogue's Mind-numbing Poison II is a grey junk. It cannot be used on weapons.

Mind-numbing Poison I is ok.

.go xyz 1810.860000 -4273.420000 7.053510 1 0.944779

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6687
