### ISSUE TITLE
RiverPaw Rampage part 2 quest has a typo, Slaugher instead of sl...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8271]
> RiverPaw Rampage part 2 quest has a typo, Slaugher instead of slaughter

.go xyz -9969.160000 1000.600000 31.467700 0 2.798130

**Comment by Bennylavaa** [comment]
You thought your work was done? Hardly...the gnolls have camps scattered all throughout the Eastern Kingdoms, and Westfall is no different. I appreciate the help you did earlier, but don't get too excited. The People's Militia does what needs to be done, and while the gnolls slaugher our citizens, we cannot stand idly by.

Go forth, south of the Gold Coast Quarry, and rid these lands of more gnolls. You will find camps where stronger members of their clan guard. I hope your up to the task, I'd hate to see you get killed.


Here are the typos:

"slaugher" should be "slaughter".
"your" should be "you're".

Quest ID 26709

Correction :

You thought your work was done? Hardly...the gnolls have camps scattered all throughout the Eastern Kingdoms, and Westfall is no different. I appreciate the help you did earlier, but don't get too excited. The People's Militia does what needs to be done, and while the gnolls slaughter our citizens, we cannot stand idly by.

Go forth, south of the Gold Coast Quarry, and rid these lands of more gnolls. You will find camps where stronger members of their clan guard. I hope you're up to the task, I'd hate to see you get killed.
