### ISSUE TITLE
Houndmaster Grebmar - (9319)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#828]
> Might be bugged - no dogs summon when he whistles aftter first one
`.go xyz 609.366000 -176.411000 -84.486800 736 4.808220`

> Boss's ability call hound is still broken in the middle of the fight
`.go xyz 589.959000 -188.029000 -84.490800 736 4.124820`

> not summoning dogs on every whistle... would be too op if it did.
`.go xyz 611.354000 -180.604000 -84.486800 736 2.325730`

> is not summoning dogs
`.go xyz 616.823000 -229.680000 -83.506400 736 1.909260`

**Comment by Bennylavaa** [comment]
BRD

**Comment by Bennylavaa** [comment]
still no doggies

**Comment by kaytotes** [comment]
The only bug here is that he's making the whistling sound. He is only meant to have 1 up at a time. I've tested that functionality and its working fine on the internal realm, once the previous one is dead he can try and spawn the next one. I have now properly fixed the whistle sound in next deploy.

**Comment by kaytotes** [comment]
Oh its his kill command thats doing it. Complete non issue. Closing.
