### ISSUE TITLE
Hinterlands Alliance Quest: Reclaiming Eggs.

Gyphon Eggs are un...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8280]
> Hinterlands Alliance Quest: Reclaiming Eggs.

Gyphon Eggs are unlootable

.go xyz -255.847000 -2809.340000 115.939000 0 2.472280

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2162
