### ISSUE TITLE
The Quest "Those Unrecovered" doesnt work, trying to give Patric...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8285]
> The Quest "Those Unrecovered" doesnt work, trying to give Patrick Mills Duke Lionheart's Cloak through the dialogue option doesnt do anything, clicking it does nothing.

.go xyz 2375.550000 -5964.450000 9.960220 1 5.775970

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2293
