### ISSUE TITLE
When riding a cart from goldshire to redridge the icon for the v...

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8290]
> When riding a cart from goldshire to redridge the icon for the vehicle im in doesn't resemble a cart, the positions on the image also do not match the positions my character moves to.

.go xyz -9654.730000 -1324.700000 47.269500 0 1.375120

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/4302
