### ISSUE TITLE
Instance ID Shenanigans

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8292]
> Instances will reset when they're complete empty.

> Upon dying in BRD we were sent to a new ID. we left the group and rejoined and were still stuck in a new ID

> wiped on magmus and brd reset

> All mobs respawned in ZF after a wipe

> Got put into a seperate instance after wiping on ZF

> The Glittermurk Mine reset the instance for half the group when we wiped. The people that walked back got put in a defiiferent instance.

> We've sent some people to summon outside. Upon return, we could not re-enter the same ID than our fellow teamate who was still inside (UBRS). We were just in front of Drak....so yeah, its was very sad.

> Got new dungen id when staying in same group after dining and reentering.

> Dungeon ID reset for 2 players in group, we ran out and whole dungeon was reset for everyone. RIP

> My group attempted Phalanx in the BRD Grim Guzzler. When we wiped, Araphal used Reincarnation and resurrected the group. Victoria and Leto had released by this point. Upon accepting the res, the pair found themselves in a completely separate, entirely uncleared instance of BRD. We had them leave group and log off then log back in. They found themselves in Undercity and made their way to the entrance, to find that respawns had occurred at the front and the mole does not work.

> if a party dies in an instane when they return to the instance the instance is reset automatcially happend on glittermusk mines and also deadmines today

> Drakkisath almost dead, party wipes, tank gets dc'd and is in a new version of the instance....rip attempts

> In deadmines boss/mobs respawned when we died on the iron clad boat.

> Player released after wipe. Was moved in to new instance. Could not zone in to same instance. All players had to run out and regroup.

> people died in BRD and came back to a diff instance than me

> Rezzed in ZF and entered a new instance

> Two of our group members died in BRD and when they got resurected they went to a seperate fresh instance while 3 of us remained in the instance we had been working on.

> UBRS mobs respawned after like an hour and we had to do it all over again

> We died in BRD, we all released spirit and the dungeon was completely resetted although we didnt do it manually, maybe a bug?

> our BRD randomly reset after a wipe... No idea why, it wasn't the first wipe, it was like the third one maybe.

> Stratholme keeps resetting

> Whenever anyone leaves the instance in BRD (whether by releasing after death, or disconnecting, or otherwise) they cannot rejoin the same instance ID. This ends the run, as wiping is a deathknell for the group. This has happened both times I've gone to BRD. Once we disbanded because of a server blip, and a warrior who released couldn't rejoin. The second, we wiped and entered into a brand new instance.

**Comment by kaytotes** [comment]
Next deploy to internal realm has experimental fixes for this. I estimate to consider it "done" we need to recreate the above with 2-3 people running a dungeon with .cheat god on with a total amount of time exceeding 24 hours. GM speed on, sprint through, whittle down health with .damage macros, switch off cheat god, let people die, release, etc. Manually resetting instance now and again. Over and over.

This time needs to be roughly tracked.

**Comment by Shadownflame** [comment]
Waiting for next fix attempt.

**Comment by Shadownflame** [comment]
Preliminary tests show great improvement in Stratholme ID saving after last update. Instance no longer hard resets after 2 hour but only trash starts respawning slowly. Hard reset now happens after 4hours, which is a switch ktotes can supposedly change around at will.
UBRS group test left to do.

**Comment by Shadownflame** [comment]
Group test shows party members no longer get separated at the 2hours mark either. Instance ID seems stable.
