### ISSUE TITLE
Expiring Pools

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8295]
There are many issues related to nodes stopping despawning, chests, quest objects etc. These are all related to pooling. Consider this the master issue that all others will be parented to then closed. We fix this we fix many.

Ref: https://github.com/TrinityCore/TrinityCore/issues/28524

**Comment by kaytotes** [comment]
Test Case 1

```
.setskill 186 450 450
.learn 2575
.add 2901
.go gameobject 2136907
```

Test Case 2

```
Add quest `The Perfect Fuel` stage 1.

.go xyz -6951.844238 -4344.445801 12.285729 1
```

**Comment by Bennylavaa** [comment]
@kaytotes In the case of The Perfect Fuel they are respawning very quickly maybe 2-3 minutes

as for the gameobject id you have us testing I am getting errors on that

**Comment by Bennylavaa** [comment]
as for the gameobject id you have us testing I am getting errors on that

**Comment by kaytotes** [comment]
Define errors

**Comment by Bennylavaa** [comment]
> Define errors

Says it doesn't exist

**Comment by kaytotes** [comment]
My bad, forgot to deploy the SQL changes.

**Comment by kaytotes** [comment]
Test case 1 passed.

**Comment by kaytotes** [comment]
Test case 2 passed.

Resolved.
