### ISSUE TITLE
Node Position Issues

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#8296]
Consider this a central housing for all cases where a chest such as a Herbalism or Mining node are spawning in the air / underground due to custom changes in an area. Any issues related to this should have their goxyz positions attached here.

**Comment by Bennylavaa** [comment]
213617 (Entry: 324) - [Small Thorium Vein X:-11685.599609 Y:-3412.330078 Z:18.409000 MapId:0]
211040 (Entry: 2040) - [Mithril Deposit X:-11487.599609 Y:-3406.520020 Z:18.856701 MapId:0]
210811 (Entry: 2040) - [Mithril Deposit X:-11540.000000 Y:-3400.000000 Z:16.723000 MapId:0]
206972 (Entry: 1734) - [Gold Vein X:-4014.750000 Y:1942.180054 Z:104.727997 MapId:1]
204942 (Entry: 1731) - [Copper Vein X:-9585.049805 Y:211.662994 Z:50.700401 MapId:0]
204178 (Entry: 1731) - [Copper Vein X:188.033997 Y:-4793.000000 Z:14.510000 MapId:1]
204161 (Entry: 1731) - [Copper Vein X:-9078.000000 Y:-3300.000000 Z:102.241997 MapId:0]
203925 (Entry: 1731) - [Copper Vein X:1119.910034 Y:-4494.000000 Z:20.438000 MapId:1]
206010 (Entry: 1619) - [Earthroot X:1118.069946 Y:-4499.000000 Z:20.327000 MapId:1]
204853 (Entry: 1731) - [Copper Vein X:-9654.490234 Y:-2022.859985 Z:57.119701 MapId:0]
204115 (Entry: 1731) - [Copper Vein X:945.301025 Y:-4123.000000 Z:-12.000000 MapId:1]
204732 (Entry: 1731) - [Copper Vein X:-111.012001 Y:-4599.000000 Z:54.067902 MapId:1]
214960 (Entry: 2047) - [Truesilver Deposit X:-6935.000000 Y:-3656.000000 Z:248.867004 MapId:0]
208750 (Entry: 1735) - [Iron Deposit X:-9500.000000 Y:-3765.000000 Z:24.558001 MapId:1]
211525 (Entry: 123848) - [Ooze Covered Thorium Vein X:-8088.000000 Y:-1336.000000 Z:-268.000000 MapId:1]
211519 (Entry: 123848) - [Ooze Covered Thorium Vein X:-6348.000000 Y:-916.000000 Z:-252.000000 MapId:1]
211055 (Entry: 2040) - [Mithril Deposit X:-11387.700195 Y:-3348.580078 Z:11.887900 MapId:0]
14685 (Entry: 73941) - [Ooze Covered Gold Vein X:-807.000000 Y:-4645.000000 Z:57.513000 MapId:1]
215028 (Entry: 2047) - [Truesilver Deposit X:-6741.000000 Y:837.820007 Z:17.914000 MapId:1]
5649 (Entry: 3764) - [Tin Vein X:-1300.000000 Y:-1728.000000 Z:101.238998 MapId:1]
206947 (Entry: 1734) - [Gold Vein X:1409.670044 Y:-1206.000000 Z:76.183998 MapId:0]
208653 (Entry: 1735) - [Iron Deposit X:-1348.000000 Y:-3465.000000 Z:51.903999 MapId:0]
208497 (Entry: 1735) - [Iron Deposit X:-1242.000000 Y:-3584.000000 Z:62.667000 MapId:0]
208938 (Entry: 1735) - [Iron Deposit X:-1227.000000 Y:-3603.000000 Z:60.835999 MapId:0]
210850 (Entry: 2040) - [Mithril Deposit X:-11336.000000 Y:-3429.000000 Z:10.118000 MapId:0]
208568 (Entry: 1735) - [Iron Deposit X:-1412.000000 Y:-3468.000000 Z:71.964996 MapId:0]
208875 (Entry: 1735) - [Iron Deposit X:-1379.000000 Y:-3496.000000 Z:56.838001 MapId:0]
215372 (Entry: 1623) - [Wild Steelbloom X:-1202.000000 Y:-3637.000000 Z:58.188999 MapId:0]
208645 (Entry: 1735) - [Iron Deposit X:-1209.000000 Y:-3639.000000 Z:63.201000 MapId:0]
215095 (Entry: 2047) - [Truesilver Deposit X:2213.860107 Y:-5194.000000 Z:55.063000 MapId:0]
74337 (Entry: 175404) - [Rich Thorium Vein X:2205.830078 Y:-5193.000000 Z:55.053001 MapId:0]
207115 (Entry: 176583) - [Golden Sansam X:-6952.000000 Y:982.588989 Z:9.148000 MapId:1]
214092 (Entry: 2045) - [Stranglekelp X:-12818.700195 Y:508.625000 Z:-5.338300 MapId:0]
206836 (Entry: 1734) - [Gold Vein X:1313.040039 Y:-1265.000000 Z:63.207001 MapId:0]
210785 (Entry: 2040) - [Mithril Deposit X:1582.449951 Y:-1523.000000 Z:61.443001 MapId:0]
208108 (Entry: 142145) - [Gromsblood X:-11751.000000 Y:-3302.000000 Z:5.639000 MapId:0]
201968 (Entry: 142141) - [Arthas' Tears X:1374.239990 Y:-1278.430054 Z:58.628502 MapId:0]
214450 (Entry: 142142) - [Sungrass X:-11209.000000 Y:-3315.330078 Z:8.702270 MapId:0]
215334 (Entry: 1623) - [Wild Steelbloom X:-1168.000000 Y:-3715.000000 Z:92.665001 MapId:0]
213350 (Entry: 324) - [Small Thorium Vein X:-7691.000000 Y:-2212.000000 Z:-256.000000 MapId:1]
205256 (Entry: 1731) - [Copper Vein X:-5567.069824 Y:-1799.280029 Z:360.231995 MapId:0]
208571 (Entry: 1735) - [Iron Deposit X:799.356018 Y:-412.000000 Z:139.593994 MapId:0]
20708 (Entry: 177929) - [Gaea Dirt Mound X:792.721008 Y:1487.819946 Z:-18.000000 MapId:1]
216877 (Entry: 1733) - [Silver Vein X:-1331.992432 Y:-3520.638672 Z:60.608105 MapId:0]
207807 (Entry: 2046) - [Goldthorn X:-1329.000000 Y:-3519.000000 Z:56.356499 MapId:0]
209018 (Entry: 1735) - [Iron Deposit X:-1164.859985 Y:-3734.620117 Z:109.443001 MapId:0]
208126 (Entry: 142145) - [Gromsblood X:-11706.200195 Y:-3102.489990 Z:14.500000 MapId:0]
15423 (Entry: 123309) - [Ooze Covered Truesilver Deposit X:-8131.000000 Y:-1141.000000 Z:-234.000000 MapId:1]
211093 (Entry: 2040) - [Mithril Deposit X:-12340.299805 Y:-1087.510010 Z:91.630699 MapId:0]
208878 (Entry: 1735) - [Iron Deposit X:-7079.000000 Y:-3712.000000 Z:274.813995 MapId:0] 
208630 (Entry: 1735) - [Iron Deposit X:-1274.000000 Y:-3564.000000 Z:60.707001 MapId:0]
208398 (Entry: 1735) - [Iron Deposit X:-1231.000000 Y:-3633.000000 Z:64.680000 MapId:0]
208587 (Entry: 1735) - [Iron Deposit X:-7179.000000 Y:-2729.000000 Z:265.907990 MapId:0]  
206906 (Entry: 1734) - [Gold Vein X:-9528.000000 Y:-3750.000000 Z:37.953999 MapId:1] 
206934 (Entry: 1734) - [Gold Vein X:-13434.000000 Y:-295.000000 Z:28.521000 MapId:0]  
214945 (Entry: 2047) - [Truesilver Deposit X:-13433.000000 Y:-300.000000 Z:15.024000 MapId:0]
213329 (Entry: 324) - [Small Thorium Vein X:-7275.000000 Y:-786.000000 Z:296.524994 MapId:0]
204174 (Entry: 1731) - [Copper Vein X:193.884995 Y:-4771.000000 Z:14.324000 MapId:1]
210858 (Entry: 2040) - [Mithril Deposit X:1270.119995 Y:-1308.000000 Z:68.228996 MapId:0]
211901 (Entry: 1618) - [Peacebloom X:-9582.879883 Y:16.643600 Z:60.107800 MapId:0] 
211844 (Entry: 1618) - [Peacebloom X:-9549.509766 Y:116.517998 Z:59.036900 MapId:0]
3032 (Entry: 3730) - [Bruiseweed X:-1665.000000 Y:-3177.000000 Z:99.856003 MapId:1] --overlap 
202906 (Entry: 1622) - [Bruiseweed X:-1665.000000 Y:-3177.000000 Z:99.856003 MapId:1] --overlap 
3538 (Entry: 3730) - [Bruiseweed X:-2087.000000 Y:-3654.000000 Z:68.425003 MapId:1]  
203366 (Entry: 1622) - [Bruiseweed X:-2087.000000 Y:-3654.000000 Z:68.425003 MapId:1]
214368 (Entry: 142142) - [Sungrass X:1450.260010 Y:-1706.900024 Z:69.475098 MapId:0]  
201979 (Entry: 142141) - [Arthas' Tears X:1543.400024 Y:-1647.880005 Z:69.248596 MapId:0]  
208125 (Entry: 142145) - [Gromsblood X:-11728.900391 Y:-3299.330078 Z:9.547970 MapId:0]  
202069 (Entry: 142143) - [Blindweed X:-6453.000000 Y:-1034.000000 Z:-275.000000 MapId:1] --overlap 
202070 (Entry: 142143) - [Blindweed X:-6453.000000 Y:-1034.000000 Z:-275.000000 MapId:1] --overlap 
215945 (Entry: 250173) - [Oil Spill X:-7143.726562 Y:-4931.044434 Z:-1.821261 MapId:1] 
200463 (Entry: 250042) - [Blood Petal Bush X:-9523.725586 Y:190.175171 Z:57.281353 MapId:0]

**Comment by zana244** [comment]
Found another:
208087 (Entry: 142145) - [Gromsblood X:-11695.000000 Y:-3092.000000 Z:20.205000 MapId:0]
210923 (Entry: 2040) - [Mithril Deposit X:-11723.000000 Y:-3135.000000 Z:8.749000 MapId:0]
205775 (Entry: 176584) - [Dreamfoil X:3680.389893 Y:-4469.000000 Z:119.658997 MapId:1]
211637 (Entry: 1618) - [Peacebloom X:-9142.000000 Y:-2509.000000 Z:118.872002 MapId:0]
211591 (Entry: 1618) - [Peacebloom X:-9165.000000 Y:-3037.000000 Z:96.545998 MapId:0]

**Comment by Shadownflame** [comment]
.go xyz -9495.820000 -3759.540000 26.217700 1 3.436450

**Comment by Shadownflame** [comment]
Floating nodes have been either removed or repositioned.
