### ISSUE TITLE
Burndural Zone ID

### ISSUE THREAD

**Issue by Bennylavaa** [Project-Epoch/bugtracker#8298]
Zone: Burndural
Parent ID: 4991

The parent ID should be 11 for wetlands shouldnt it? I noticed the world map doesnt work as it should when in Burndural

It looks like 4991 is Upper Marshes which has a parent ID of 11. I dont think the client handles that correctly so the fix would be to make Burndural's parent id 11. This should make the map work as it should, it should also fix the being teleported to westfall when dead shenanagans that I saw reported in discord a while back.

AreaTable.dbc

**Comment by Shadownflame** [comment]
Fixed.
