### ISSUE TITLE
Advanced Alchemy Chain

### ISSUE THREAD

**Issue by Bennylavaa** [Project-Epoch/bugtracker#8300]
### **Advanced Alchemy (27375):**
The quest is sorted under Elwynn Forest in the quest log, but it takes place in Western Plaguelands.

![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/2a74cb12-7b8d-437e-99b7-46b148476980)

### **Advanced Alchemy (27376):**
The quest says 'report to Proctor Blackwood' there is no Proctor Blackwood, it should read 'report to Proctor Philips' also the text tells you to go east but the npc is directly to the west.

![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/0b7f5604-f453-466f-a8ff-67fc9bba180c)

### **Advanced Alchemy (27377):**
This quest fails to mention that you need to hand it in back at Doctor Atwood, instead of the Proctor you were just protecting.
![image](https://github.com/Project-Epoch/bugtracker/assets/165105701/94f354a8-5a07-4cb0-a842-94ebd94b30e7)

**Comment by Shadownflame** [comment]
Quests now correctly sorted under WPL zone.
Hand-in information written into quest tracker on the right side and will not be added to the main text. Hopefully people find it (I didn't 🤣 )
