### ISSUE TITLE
Mining and Herb Nodes spawning stacked

### ISSUE THREAD

**Issue by Bennylavaa** [Project-Epoch/bugtracker#8301]
A collection of bugs reported where they talk about nodes all being spawned in clusters at one time. I think this might have something to do with pooling as well?

**Comment by Shadownflame** [comment]
Cannot confirm until pooling issue fixed. None of the nodes are ever up.

**Comment by Shadownflame** [comment]
Can confirm both the barrens tin vein spawns and the large cluster of rich thorium in Ungoro. There might be other similar spots but it doesn't look so widespread as to badly affect the economy or really bother people.

**Comment by Bennylavaa** [comment]
I do know the spawn points overlapping is normal but I dont think they should have both spawned at the same time. I could be wrong on this though.

**Comment by Shadownflame** [comment]
No change on the RTV spawns, unsure if @kaytotes wants to leave it as is?
The overlapping Tin veins seem to be resolved.

**Comment by Shadownflame** [comment]
Kaytotes likely found the cause for this and we might be seeing an improvement to spawn locations.

**Comment by Bennylavaa** [comment]
This seems fixed for now. At least I havent seen many like before. Reopen if you notice anything super weird.
