### ISSUE TITLE
Jergosh's Mind Control ability can hit multiple party members - Spell ID 80994

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8303]
Jergosh's custom ability is capable of taking (at least) 2 people under its control - we were testing with a duo, and the fight would reset every time he cast MC, as he grabbed both of us. No data if he can control more in a bigger group.

PS: most 5man mind control effects aren't cast at all if there is only 1 person in combat, as the tank is not an eligible target. This limitation also doesn't apply to Jergosh's spell. Might need consideration.

**Comment by Shadownflame** [comment]
Still hits both of us 
![WoWScrnShot_071824_015011](https://github.com/user-attachments/assets/dd4326af-0690-4c80-9527-78a94318e0a8)

**Comment by kaytotes** [comment]
Retest

**Comment by Imperius5k** [comment]
seems to be fixed to me after testing with shadown
