### ISSUE TITLE
Winterspring E'ko can be looted without Cache of Mau'ari

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8305]
Collection of issues regarding E'kos.

The E'kos can drop on Epoch without having the Cache of Mau'ari in your bag -- Confirmed on Beta 3 and Internal
Some people report having issues with "already looted" when trying to loot E'kos -- not able to confirm, may also be solved by solving Cache of Mau'ari first.

**Comment by kaytotes** [comment]
@zana244 Retest following loot upgrades

**Comment by zana244** [comment]
Seems to have been solved with the loot rework. Managed to make the E'kos drop only with cache in inventory, and could not drop otherwise (unless really low % drop rate...)
Also, you are not able to loot the E'ko if you delete your Cache of Mau'ari before looting, which is good (I think).
