### ISSUE TITLE
Fellicent's Shade - NPC ID 10358

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8311]
This rare's [Arcane Bolt](https://www.wowhead.com/classic/spell=13901/arcane-bolt) ability hits unusually hard (and it's not a weak spell to begin with). It's currently doing around 42-46 damage per cast, while on retail this spell damaged for 22-28.
See video time stamped from classic: https://youtu.be/2tG8ozowCFQ?t=19

**Comment by kaytotes** [comment]
Not a bug. Spell damage is set in the spell itself and this is blizzlike. Since this is a rare it gets buffed by 15%ish. Just a case of an already strong spell being given a minor (4 damageish) buff

**Comment by Shadownflame** [comment]
As per Eredun, there is a missing spell scaling implementation here due to TC core. The spell base value is correct in the dB but it should use a lower value than that due to the NPC lvl. Then that blizzlike value (which is around 22-28 on the video) should receive the 15% boost, which would put it at 25-32ish on Epoch.

**Comment by Shadownflame** [comment]
New scaling implementation brought her damage down to 35-44, which is a 10-12% lower average than earlier values. Dev decision is to keep this damage as it is more manageable now but still amply challenging. Confirmed on internal she is now soloable with any class at lvl 10 onwards.
