### ISSUE TITLE
Magma Totem has wrong damage values.

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8313]
https://www.wowhead.com/classic/spell=8190/magma-totem#see-also-ability
https://www.wowhead.com/tbc/spell=10586/magma-totem#see-also-ability
Classic/TBC vs Epoch tooltip values (and also ingame):
R1: 22 vs 38
R2: 37 vs 64
R3: 54 vs 94
R4: 75 vs 131

Scaling seems to be ... okay? 84 SP adds around 8 per tick

Later edit: I actually rechecked again, and magma totem is using the updated WOTLK Values, whereas Vanilla/TBC had lower base dmg. Could be possible for other spells too?
https://wowpedia.fandom.com/wiki/Patch_3.0.8#Shaman

**Comment by Shadownflame** [comment]
This seems like an oversight as nearly every spell was reverted to TBC. This should be using TBC values too, unless specified otherwise by the devs.

**Comment by Shadownflame** [comment]
Has TBC base dmg and TBC scaling (6.7%) now.
