### ISSUE TITLE
Odo the Blindwatcher - NPC ID 4279

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8317]
This boss in SFK doesn't use his [Howling Rage](https://www.wowhead.com/classic/spell=7481/howling-rage) ability.

**Comment by Shadownflame** [comment]
Issue persists.

**Comment by kaytotes** [comment]
I can't replicate this, no issues in db.

**Comment by kaytotes** [comment]
Seems to be internal only but i can't work out why
