### ISSUE TITLE
NPC's reset when entering water

### ISSUE THREAD

**Issue by Bennylavaa** [Project-Epoch/bugtracker#8319]
NPC's will reset when going from a non swimming state to a swimming state or vise versa.

**Comment by kaytotes** [comment]
The only generic bug in this come from https://github.com/Project-Epoch/bugtracker/issues/170 https://github.com/Project-Epoch/bugtracker/issues/258 which will be patched in next build.

Bears can't swim, wolves, can't swim, tigers can't swim. Essentially, not everything can swim so resetting is all they can do.

Isssues related to custom mobs eg the sharks and felstone brute are generally mob specific as they're using incorrect swimming flags I think.

Leaving this open but will close once i've fixed the specific custom creatures.

**Comment by Shadownflame** [comment]
New water behaviour is much more authentic, the mobs who can't swim now have a few seconds delay before they heal up and lose interest in you (they evade attacks during this time), same for the mobs who can't follow you to the land.
