### ISSUE TITLE
Hunter Taming Quests keep you in combat.

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8321]
Plethora of reports. After you tame a mob using the Taming Rod, you should not be kept in combat.
https://youtu.be/uHrhZaL43jA?feature=shared&t=10582

Linking all duplicates here, fairy certain it applies to the quests of all races.

Some people also mention their pet dying, but the frame is still there and they cannot dismiss it further, requiring a logout to fix.
Haven't managed to reproduce properly, although it did happen to me on internal when I used .tele ...
Maybe if the pet is too far away/dead dismiss it automatically.

**Comment by Shadownflame** [comment]
List of quest IDs affected (Taming the Beast):
6101,6064,6084,6088,6061,6062,6063,6082,6083,6085,6087,6102,26619,26621,26622,26627,26628,26629
List of item IDs affected (Taming Rod):
15908,15911,15913,15914,15915,15916,15917,15919,15920,15921,15922,15923,60955,60957,60943,60944,60945,60956

You can reproduce the pet frame bugging by simply pressing Stay and outranging the pet (it visually kills the pet but it's not actually dead)
![WoWScrnShot_072524_164643](https://github.com/user-attachments/assets/eefdbec5-dcbe-4c11-a4e7-5a3a41742c5d)

**Comment by ghost** [comment]
This is related to https://github.com/Project-Epoch/bugtracker/issues/2559

Generic issue with charm effects

**Comment by kaytotes** [comment]
@zana244 Does this need retesting now?

**Comment by kaytotes** [comment]
Made new low prio issue for the outranging: https://github.com/Project-Epoch/bugtracker/issues/8434

I've tested this across all hunter races on internal realm and can no longer replicate an issue. Closing.
