### ISSUE TITLE
Some custom NPCs still drop scourgestones.

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8323]
Going to add here the duplicate issues for NPCs which still drop Scourgestones even though they are not Scourge.

Tol Barad mobs
Blackstone Swashbuckler -- 46160
Blackstone Marauder -- 46159
Blackstone Corsair -- 46158

Adelbert Perry in Stormwind.

**Comment by kaytotes** [comment]
To the best of my knowledge this was resolved so slapping a retest label on it.
