### ISSUE TITLE
Master Looter can loot every quest item without being on the quest

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8326]
Killing enemies with ML loot setting allows the master looter to see and loot every possible quest item the NPC can drop without having the quests that are normally required to see/loot them.
Being able to see it might be intended (especially if someone in your group is on the quest), but looting them certainly isn't.

**Comment by kaytotes** [comment]
Next deploy.

**Comment by Shadownflame** [comment]
ML can now see possible quest items but cannot loot them.
