### ISSUE TITLE
Magmus doesn't drop any loot 50% of time

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8329]
npc=9938
Not sure if this was always the case and the vmangos port didn't catch it or a totally new issue
This boss is way too much effort to kill to have a high chance of not getting anything for it.

**Comment by kaytotes** [comment]
I can replicate the issue on internal realm. Can't replicate locally with same config settings. I suspect there might be something funky gone on with deploy so with next one I'll do a full clean and rebuild to see if the situation improves. Eyeballing the DB i can't see any particular reason why he wouldn't have a guaranteed drop.

**Comment by Shadownflame** [comment]
Issue still persists after last update.

**Comment by kaytotes** [comment]
Retest
