### ISSUE TITLE
Losing rage while queuing HS/Cleave/Maul skips over the next auto attack.

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8331]
If you have enough rage to queue HS/Cleave/Maul, but in the meantime you cast, say, a Hamstring or a Demoralising Roar, bringing you below the required rage to cast the HS/Cleave/Maul, the warr/druid will skip 1 auto attack. Normally the attack should go through.

Reproduce:
Pool 20 rage
In between swings:
Queue Heroic Strike
Cast Hamstring

**Comment by kaytotes** [comment]
Next Deploy

**Comment by Shadownflame** [comment]
Resolved
