### ISSUE TITLE
Quest Grab the Goods (26466) grammar errors

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8345]
"the companies second highest priority" > "the company's second highest priority"
"go collect the surviving cargo that is scattered around Playername" > "go collect the surviving cargo that is scattered around, Playername!"
"...by a damned ooze is ours and we need it back." > "...by a damned ooze is ours, and we need it back."

**Comment by Kestrana** [comment]
Corrected a lot in the whole chain such as zeppelin being misspelled and other grammatical issues. https://github.com/Project-Epoch/epoch-core/pull/1600
