### ISSUE TITLE
Felstone Fortress mobs don't seem to check tailor skill for Scavenging procs

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8349]
Dropping extra cloth with or without Tailoring.
NPC ID 46619 Felstone Acolyte
NPC ID 46620 Felstone Brute
NPC ID 46626 Felstone Warlock
NPC ID 46625 Felstone Rogue
NPC ID 46622 Felstone Merchant
NPC ID 46624 Felstone Outrider
NPC ID 46618 Etheldrin (rare)

+ Possibly every other custom ID in the area, list isn't full since it affects rares too

**Comment by zana244** [comment]
It might be the same for all custom ID NPCs?
Killed Ravenous Looter (45727) in Tanaris and had 2 separate stacks of mageweave cloth on 1 mob -- a stack of 1 and a stack of 2.

**Comment by kaytotes** [comment]
Fix deploying in next release
