### ISSUE TITLE
Call to Arms: Dustwallow Marsh

### ISSUE THREAD

**Issue by Bennylavaa** [Project-Epoch/bugtracker#8355]
![image](https://github.com/user-attachments/assets/a88d3c1f-28f2-4248-98f0-935d1fa1a984)
![image](https://github.com/user-attachments/assets/edfad3f4-9537-4eb0-b8c1-5c2f9bb9bbe3)

As alliance I can pick this up from the sign in theramore and the sign in brackenwall I don't think this is intended.

**Comment by kaytotes** [comment]
Won't fix without a very large amount of dev work. The boards are neutral, the quests are faction specific.
