### ISSUE TITLE
Arathandris Silversky - (9528)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#837]
> The quest for cenarion plant salve are not repeateble
`.go xyz 3826.850000 -1390.050000 204.459000 1 4.754630`

> Plant Salve quest are not repeatable
`.go xyz 3804.610000 -1467.950000 209.697000 1 4.848060`

> Salve not repeatable
`.go xyz 3802.850000 -1470.570000 210.081000 1 5.093720`

> The quests for [Corrupted Soul Shard]s and [Patch of Tainted Skin]s are supposed to be repeatable I think, but I was only ever able to hand each of them in once. The items keep dropping however, but there's no way to use them or get additional [Cenarion Plant Salve]...
`.go xyz 3805.400000 -1469.980000 210.233000 1 5.046810`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2089
