### ISSUE TITLE
Silithids are using the WotLK version of their infamous Silithid Pox disease

### ISSUE THREAD

**Issue by Hatson22** [Project-Epoch/bugtracker#8378]
Silithid Pox (a debuff a lot of silithids use) is using its WotLK version, which functions the same (scaling in % damage taken with the Silithid's level), but has 5 minute duration instead of 30 minutes.
Spell ID is the same across both TBC and WotLK: 8137

**Comment by kaytotes** [comment]
Dupe https://github.com/Project-Epoch/bugtracker/issues/2649
