### ISSUE TITLE
Elemental Overload (30681) proc issues

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8379]
It seems to proc correctly for Lightning bolt, but for Molten blast the chance feels closer to 5% than 20, it's extremely rare. 
Chain lightning behaves properly when used on multi target (20%ish proc against 3 targets), but produces some 5-6%ish proc chance when used on single target. Even if the proc chance is somehow split between the jumps, it should still give the full 20% chance when there are no jumps involved and the spell only hits one target.

**Comment by kaytotes** [comment]
There is no difference between spells.

**Comment by Shadownflame** [comment]
Seems to require 5/5 points in Fire And Lightning Mastery to reproduce the issue with Molten Blast.
With 1-4 points or no points in that talent, Molten blast properly procs Overload approx 20% of the time. Maxed to 5/5, I'm experiencing an average proc rate of 1.8% across my combined tests (total of 927 casts)

Chain lightning seems to be a blizzlike bug where the spell's proc chance is split between the 3 jumps even if there are no jumps. Blizz never fixed it, it's up to devs whether it gets amended here.

**Comment by Shadownflame** [comment]
Fresh test samples after recent shaman changes which swapped talent positions.

Test1 - without Fire and Lightning Mastery - 19 procs out of 81 casts 23.4% proc chance

Test 2 - with Fire and Lightning Mastery - 0 out of 153 casts (you do eventually get a proc every 200 attacks though)
