### ISSUE TITLE
Maybess Riverbreeze - (9529)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#838]
> Does not unlock Cenarion Salve quests after completing Cleansing Felwood quest.
`.go xyz 3941.680000 -1074.390000 254.581000 1 1.119280`

> Has no voice when clicked or interacted with.
`.go xyz 3943.410000 -1049.680000 245.831000 1 1.766140`

> doesnt exchange for cenarion salve
`.go xyz 3947.090000 -1050.610000 246.701000 1 1.870300`

> She does not give the trade-in quests for Cenarion Plant Salve
`.go xyz 3944.710000 -1050.300000 246.129000 1 1.598770`

> dont give saliva quests
`.go xyz 3978.480000 -1061.460000 262.123000 1 2.585440`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2089
