### ISSUE TITLE
Telling an Infernal to attack a target crashes the server

### ISSUE THREAD

**Issue by ghost** [Project-Epoch/bugtracker#8382]
Might also affect other creatures, as the issue seems to be generic, but I wasn't able to find any other creature that causes the crash.

**Comment by Shadownflame** [comment]
I am not having this issue on internal.

**Comment by Shadownflame** [comment]
I thought you were going to fix this on your local before pushing the update...
Yeah, you can reproduce it on internal now. Enable Immolation aura, send infernal on ranged target, and RIP server.
