### ISSUE TITLE
Blackbreath Crony - (9541)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#839]
> Stay hostile and keep in combat even after Boss is dead, but dont attack and keep you in combat, not attackable
`.go xyz 878.854000 -229.948000 -44.170700 736 0.213695`

> Two of these keep aggroing on others, keeping them stuck in combat. They do not attack at all.
`.go xyz 897.420000 -135.508000 -49.750800 736 3.939580`

> These get stuck in combat and are untargettable when starting the Hurley Blackbreath fight. Same with the boss.
`.go xyz 871.885000 -230.832000 -43.751700 736 1.879870`

> if you pull them into Ribbly's crony  they agro and become targetable solving the first bugg
`.go xyz 892.004000 -140.856000 -49.755600 736 4.130350`

> stuck in RP.  agroed but not targetable, forever in combat till death
`.go xyz 897.879000 -142.955000 -49.758200 736 6.057710`

> Bugs out and becomes non targetable and follows you if sapped immediately upon becoming hostile
`.go xyz 899.321000 -134.807000 -49.750000 736 4.971380`

> two of the adds in this fight, did not activate properly and are now following me around like pets. Combat stuck aswell.
`.go xyz 895.180000 -132.343000 -49.748100 736 5.699650`

> bugged, immortal
`.go xyz 898.947000 -148.907000 -49.758400 736 0.311573`

> Bugged out - not targettable - in combot
`.go xyz 844.353000 -219.545000 -43.674200 736 4.626170`

> Not turning hostile and keeping the party in combat
`.go xyz 897.489000 -142.927000 -49.756300 736 0.499519`

> 2 of the adds dont attack
`.go xyz 908.917000 -151.239000 -49.758400 736 2.567700`

> Not all of them become targetable and start atatcking when pulled.
`.go xyz 900.484000 -157.603000 -49.759600 736 1.887310`

> non combat
`.go xyz 901.468000 -152.154000 -49.759500 736 3.070090`

> Two of them bugged out, were non-interactable, but followed around the person that smashed open the barrels, as if they were in combat with them (but never actually attacked the person).
`.go xyz 901.283000 -137.223000 -49.752800 736 2.593510`

> Doesn't engage
`.go xyz 911.411000 -140.559000 -48.869500 736 3.122250`

> Mobs that stuck in combat
`.go xyz 904.332000 -151.267000 -49.757500 736 2.076130`

> these won't despawn and are just following our tank doing nothing but keeping us in combat
`.go xyz 905.660000 -145.760000 -49.757900 736 3.142650`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8095 related

**Comment by Shadownflame** [comment]
Happens exactly as pieced together from comments above:
Hurley and one crony becomes active after RP, 2 cronies remain unattackable, but attack you and keep you in combat:
![WoWScrnShot_070724_224225](https://github.com/Project-Epoch/bugtracker/assets/172074323/7fab0d3b-b7d3-4536-a43c-208ecd94d93b)
![WoWScrnShot_070724_224241](https://github.com/Project-Epoch/bugtracker/assets/172074323/d675d9ab-c74f-4f3c-820f-fdddd7b654d5)

Then follow you around even after Hurley dies until you pull them close enough to Ribbly and his cronies, at which point, off they go to have a bar fight:
![WoWScrnShot_070724_224317](https://github.com/Project-Epoch/bugtracker/assets/172074323/671ce542-ee53-44e2-b051-7041eca412e7)
After they obliterate the enemy crony, they leave combat and reset back to where they ended their RP with Hurley and unbug into attackable state:
![WoWScrnShot_070724_224327](https://github.com/Project-Epoch/bugtracker/assets/172074323/07bd71fd-24c5-4cd3-aff4-d4b33843ad61)

**Comment by kaytotes** [comment]
Next deploy
