### ISSUE TITLE
An Audience with The King (Quest 396) sends you to Variann

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8394]
Quest text, objective, and completion board needs adjustment as this quest is handed in with Lady Prestor on vanilla.

**Comment by zana244** [comment]
intended
https://www.wowhead.com/classic/quest=396/an-audience-with-the-king
#3163

**Comment by Shadownflame** [comment]
Oh wow, you're right, this quest intentionally fools you!
