### ISSUE TITLE
Casters can't benefit from Flametongue Totem when Windfury Totem is present

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8398]
With the current set up of their targeting priority, windfury is chosen for every class and spec, always, in a buffed environment.
Would be nice if there was a way for FT to reliably target at least clothies, or an easy way to pick between the two effects (having to remove every attack power buff isn't one). Whatever method is chosen needs to be clearly displayed in the buff tooltips so people are aware what criteria they need to meet in order to get their desired effect.

**Comment by T1ti** [comment]
Imo there are two options : 
- Whatever stat the player has the most between Spell damage and _bonus_ attack power.
- or between strength and intellect, This would work better at lower gear level when players don't have much spell power on gear.

**Comment by Shadownflame** [comment]
Bonus attack power is already the main issue, you get well over 500 AP from raid buffing, while gathering the same amount of spell power is really challenging.
Checking base stats would be a valid option, though it would also need to consider agility.

**Comment by Shadownflame** [comment]
New checking criteria returns windfury if STR or AGI > INT and flametongue if INT > STR or AGI
