### ISSUE TITLE
Feign death (spell ID 5384) never fails

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8402]
As of TBC this spell was still running on spell hit table and produced a good number of misses (displayed as resists on vanilla), particularly against higher level mobs than yourself.
On epoch this spell has 100% hit/success chance regardless of your level vs enemy level

**Comment by kaytotes** [comment]
Next Deploy

**Comment by Shadownflame** [comment]
Resists now happen and give a red message to warn the player.
