### ISSUE TITLE
Our Bodies Forsaken (26126) error in text

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8403]
Quest text says if you lose your Symbol, Rance Hartstolen in Undercity can provide a new one. It is not Rance, but Jake Hartstolen who provides this functionality, the quest giver. The functionality itself works properly, only the text is stating the wrong name.

**Comment by Kestrana** [comment]
Text fixed in https://github.com/Project-Epoch/epoch-core/pull/1600

**Comment by Bennylavaa** [comment]
looks like you meant 26216 its fixed
