### ISSUE TITLE
Item 64228 crashes the server when used

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8406]
Also refers to the wrong spell in description (cosmetic issue)

**Comment by Kestrana** [comment]
Item ID 64228 is Tough Hammer of the Boar. I think you have the wrong item ID. 
![image](https://github.com/user-attachments/assets/cd4794d6-dc71-4ca2-ae4b-f136ff93b1dc)

**Comment by ghost** [comment]
To clarify here, IDs can be different on our locals and the internal server. We do indeed need item names, otherwise we have to load up the internal server to find out what item this issue is referring to
