### ISSUE TITLE
Adrenaline rush stopped working

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8428]
Not sure which update broke this... 
It doesn't do anything, you regen the same 20 energy every 2sec while it's active
Spell ID 13750

**Comment by kaytotes** [comment]
Broke via the massive trinitycore upstream pull a while ago. Easy fix.

**Comment by kaytotes** [comment]
Next deploy but tested locally so closing.

https://github.com/user-attachments/assets/4d0d44d5-0f35-4dc4-9431-960276606bd7
