### ISSUE TITLE
Zapetta - (9566)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#843]
> He is unable to tell you where the zeppelin is at the moment
`.go xyz 2066.190000 287.936000 97.031400 0 1.735520`

> Npc does not answer on where is the zep question.
`.go xyz 2065.430000 287.033000 97.031500 0 1.388380`

**Comment by zana244** [comment]
Confirmed on internal, the gossip action does not work.

**Comment by zana244** [comment]
#8210
