### ISSUE TITLE
Explosive trap DoT scaling 

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8430]
Currently explosive trap scales 10% RAP on both the initial damage and each tick of the DoT portion. This seems to be wotlk behaviour, as spell tooltips and anecdotal reports suggest the spell didn't have scaling on its dot portion on TBC, only the initial damage. Patch notes from 3.3 suggest this was a blizz bug corrected during wotlk (worded "now properly scales" )
As epoch is aiming for tbc balance it would make sense to revert to the no-scaling tbc version, but it's entirely up to Dev choice. Using a custom scaling value is an option too (the wrath scaling is fairly powerful).

**Comment by kaytotes** [comment]
Next deploy.

**Comment by Shadownflame** [comment]
No longer scales with RAP on the dot part.
