### ISSUE TITLE
Not all hunter pet abilities should scale with RAP in TBC.

### ISSUE THREAD

**Issue by zana244** [Project-Epoch/bugtracker#8431]
Finally, a legit bug that buffs hunters for no reason...

From what I've researched, it seems that in TBC most hunter pet abilities do not scale at all with the RAP from the hunter, which is not the case on internal, where most likely there is some WotLK scaling still involved to buff all abilities...

Sources:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3124
https://github.com/watchyoursixx/hunter-tbc/issues/18
The first one has a few images of a spreadsheet hunters would use in TBC to sim their dps, and it shows the contributions of %inc damage an ability would get. Notably, Gore has no RAP contribution from the hunter, whereas lightning breath does.
The second one also confirms this, tested on TBC classic -- the guy is trustworthy, one of the main people of the classic hunter discord. This also provides clear information as to how each pet ability scales; apart from lightning breath / thunderstomp / Fire Breath (scaling with 5% of Spell Damage Bonus) and Scorpid Poison (2.6% of SPD per stack), the rest should have static damage.

As an example, on internal, a naked char with 231 RAP with a cat at lvl 60 with only the 25% damage modifier from happiness and  +10% from cat family has a 81 Claw average damage.
Equipping items to have 513 RAP leads to the same Claw dealing 115 average damage... this quickly increases with raid buffs etc.

It's interesting to note that the pet ability does not scale with the pet's AP --> casting blessing of might on it has no effect.

Unsure if pet abilities actually scale with anything else on internal.

**Comment by Shadownflame** [comment]
Numeric testing on internal shows an approx 10% of hunter RAP is directly converted into damage on claw, which is a magnitude higher scaling than wotlk had.

**Comment by kaytotes** [comment]
Next deploy.
