### ISSUE TITLE
Undermap failsafe hiccups 

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8433]
Master thread for cases where the system mistakenly triggers.

1) LBRS - minor
All the ledges in the upper part of the dungeon kick in the failsafe if you attempt to jump down, such as from here (it just drags you back where you were standing before the jump)
![WoWScrnShot_112924_013758](https://github.com/user-attachments/assets/12dcbdfa-740a-4f40-91da-e7e854eb4dab)

Repeatedly attempting to jump seems to override the failsafe and it eventually lets you fall. Should be still fixed of course but less gamebreaking.

2) UBRS - major
Same as the previous, if for any reason you'd be going downwards from any ledges you tend to get kicked back 2-3 times before the jump goes through. 
The difference is that in UBRS there are a number of enemy mobs who knock back and they're purposefully positioned around ledges and bridges as an added difficulty and you are fully intended to fly off into the abyss if you tank them in the wrong position. The failsafe currently cancels most such risk. Whether you get charged by a patrol while picking up the quest from Awbee or get tossed from the Drakkisath bridge, you port right back up with an oopsie.
![WoWScrnShot_112924_030034](https://github.com/user-attachments/assets/c0ee4a58-5fc0-40d1-9325-5809896582a4)
![WoWScrnShot_112924_025634](https://github.com/user-attachments/assets/b0c06d49-7dee-4b08-b28a-7b4ee67b3d2e)

3) Molten Span - major
Slow falling from UBRS to BRD not happening right now
![WoWScrnShot_112924_060956](https://github.com/user-attachments/assets/64a069ee-b90c-4d98-97b4-328b45afa4cf)

4) BRD - minor
Can't jump into the lava from this bridge. Not at all. Even 22 attempts later i'm still up here. (Has no ingame relevance to jump off here)
![WoWScrnShot_112924_061920](https://github.com/user-attachments/assets/cf04521f-4087-426d-9b36-e9f4ae427296)

Sometimes getting kicked back when jumping to Incendius but it usually lets you through
![WoWScrnShot_112924_062613](https://github.com/user-attachments/assets/d1bc2d01-25ff-4825-b269-2850b3548527)

Sometimes getting kicked back when jumping from here too, but it usually lets you through
![WoWScrnShot_112924_063213](https://github.com/user-attachments/assets/4cd14d8f-b191-45bf-b5b0-19346b2ce90f)

5) Blackfathom - minor
Can jump without slow fall but keep getting ported with slow fall.
![WoWScrnShot_112924_064549](https://github.com/user-attachments/assets/64275863-3aa8-4e46-83a5-1c30cd3ac5c1)

To be continued.

**Comment by kaytotes** [comment]
These are all sensible test cases thanks

**Comment by kaytotes** [comment]
Retest pls

**Comment by Shadownflame** [comment]
Resolved
