### ISSUE TITLE
Arei - (9598)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#844]
> Arei kept standing still after the confrontation with the 3 treants on the road, not updating the questlog at that point. I tried resummoning him with the flute and he talks like we finished the escort before.
`.go xyz 5986.950000 -1207.020000 378.947000 1 6.036570`

**Comment by Bennylavaa** [comment]
Seems to work fine for me, the only weird thing is if you talk to him while the escort is going on he will stand for a few minutes and then resume, that or you can pull a npc to him and start it back up quicker.
