### ISSUE TITLE
Gargantuan Ooze - (9621)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#846]
> He is unkillable, because he regenrates every 2sec 100% life.

But he does not reset the fight, or attack me. He just stands there and does nothing.
`.go xyz -7784.240000 -1508.090000 -267.040000 1 0.160403`

**Comment by Shadownflame** [comment]
related https://github.com/Project-Epoch/bugtracker/issues/8302

**Comment by Bennylavaa** [comment]
this is a duplicate for a quest, I couldnt reproduce this.
