### ISSUE TITLE
Ringo - (9999)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#856]
> not despawned
`.go xyz -7241.660000 -1430.050000 -232.459000 1 3.942270`

> This npc is here instead of in the volcano in the middle of the zone, also he's lying down for some reason.
`.go xyz -6155.620000 -1076.600000 -200.488000 1 0.768167`

> Wont let me take the next quest in the chain just stands here
`.go xyz -7198.640000 -1388.980000 -232.109000 1 0.238931`

> Someone failed the quest and he is sitting in the middle of nowhere
`.go xyz -6866.020000 -1078.100000 -274.434000 1 2.687990`

> A Little Help From My Friends - escort quest does not start after picking up. NPC will present lines, but does not move from spot.
`.go xyz -7200.320000 -1385.400000 -232.251000 1 5.893140`

> Sometimes bugs and will stop following
`.go xyz -6609.450000 -1420.260000 -270.828000 1 3.257000`

**Comment by Shadownflame** [comment]
Part related https://github.com/Project-Epoch/bugtracker/issues/7733
