### ISSUE TITLE
Deathmaw - (10077)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#858]
> rares drop no loot
`.go xyz -7668.890000 -2480.000000 139.715000 0 1.363420`

> This rare dropped nothing of note.
`.go xyz -7671.210000 -2483.050000 139.194000 0 1.474750`

> Did not drop a single item. No greens no misc items, no loot.
`.go xyz -7590.970000 -2663.150000 133.489000 0 4.224160`

> no loot rare mob
`.go xyz -8019.860000 -2818.830000 133.710000 0 4.218240`

**Comment by Bennylavaa** [comment]
fixed
