### ISSUE TITLE
Zerillis - (10082)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#860]
> Teleports back to his starting point when he reaches the end of his patrol
`.go xyz 1675.970000 906.575000 8.877630 209 1.820350`

> pathing below the floor
`.go xyz 1625.510000 920.968000 18.298100 209 1.189530`

> no loot on kill
`.go xyz 1636.090000 892.232000 9.078670 209 1.052340`

> After he patrols to the end of his path, he teleports back to the start instead of walking back.
`.go xyz 1682.930000 867.241000 8.879010 209 1.793830`

> dropped nothing
`.go xyz 1624.980000 876.632000 8.892350 209 3.443270`

**Comment by zana244** [comment]
Could not get him to teleport on internal? Loot issues solved.
