### ISSUE TITLE
High Justice Grimstone - (10096)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#861]
> agroed a horde rogue, now he is bugged and we are locked in the arena with no way out
`.go xyz 591.922000 -178.766000 -53.938500 736 5.913050`

> He started - for some reason - following our rogue, locking us in and not opening any doors.
`.go xyz 627.568000 -181.819000 -52.882300 736 0.520731`

> relogged, now he stands in the middle , doesn' follow anymore but event stays blocked
`.go xyz 598.801000 -176.279000 -53.844000 736 4.222120`

> tried to kill him not possible, tried freezing trap no luck, tried dismiss pet no luck, tried to log out doesn't work either. going to quit program and see what happens when i relog
`.go xyz 596.187000 -189.588000 -54.143800 736 2.257050`

> i did first part of arena and while skinning the thunder lizards this guy starts following me instead of giving the follow up on the arena , happend before now i got a dwarf pet :)
`.go xyz 593.691000 -182.494000 -54.147900 736 0.591993`

> did the first part of the event and now he is following me like a pet, second part of the event doesnt start
`.go xyz 599.664000 -186.700000 -54.106000 736 3.762120`

> He can aggro on a player and freeze the encouter
`.go xyz 608.594000 -192.019000 -53.835200 736 0.826933`

**Comment by Bennylavaa** [comment]
I couldnt repo this
