### ISSUE TITLE
Witch Doctor Mau'ari - (10307)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#869]
> Alliance hostile. Don't know if intentional, but this makes Alliance unable to use E'ko.
`.go xyz 6716.970000 -4707.800000 721.416000 1 4.729260`

> Unable to do the questline associated with this NPC, she is Hostile.
`.go xyz 6716.740000 -4664.750000 720.927000 1 4.739440`

> Hostile to the Alliance (only checked with active Warmode).
`.go xyz 6714.920000 -4695.300000 721.216000 1 5.091940`

> Hostile to alliance
`.go xyz 6721.920000 -4710.180000 721.975000 1 3.729810`

> hostile
`.go xyz 6719.990000 -4708.520000 721.747000 1 4.988470`

> I've the quest "A Little Luck" but can't interact with a horde npc.
`.go xyz 6716.760000 -4698.650000 721.248000 1 5.015950`

> This NPC should not be hostile towards Alliance
`.go xyz 6721.700000 -4708.590000 721.913000 1 5.039520`

> Horde aligned instead of neutral
`.go xyz 6715.980000 -4659.600000 721.188000 1 4.945270`

> Very cool adding her back, but she is hostile to alliance
`.go xyz 6718.920000 -4694.850000 721.453000 1 4.831910`

> The alliance can get the quest "A little luck" that requires you to talk to Witch Doctor Mau'ari. The problem is, the doctor is flagged for PVP and Horde. It either needs to be neutral or block the alliance from taking this quest.
`.go xyz 6720.730000 -4708.910000 721.833000 1 5.214640`

> Alliance can't intereact with this character even when we have the quest to talk to her.
`.go xyz 6714.820000 -4695.760000 721.227000 1 4.925920`

> This NPC is hostile to alliance. Should be friendly.
`.go xyz 6714.500000 -4697.130000 721.209000 1 5.022910`

> The quest [A Little Luck] wants me to speak to Witch Doctor Mau'ari, but she's hostile to me!
`.go xyz 6722.650000 -4709.210000 722.014000 1 4.619340`

> They are hostile to me and I can't turn in the "A Little Luck" quest.
`.go xyz 6714.620000 -4692.570000 721.261000 1 5.298710`

> Quest A Little Luck, can't talk to Witcher Doctor Mau'ari as alliance.
`.go xyz 6721.750000 -4708.320000 721.911000 1 4.986910`

**Comment by Bennylavaa** [comment]
fixed in Build 2553
