### ISSUE TITLE
Gyth - (10339)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#870]
> No loot dropped
`.go xyz 156.514000 -427.239000 110.472000 229 4.713540`

> was not spitting fire during the encounter on the lanes
`.go xyz 151.143000 -416.363000 110.472000 229 5.791600`

> loved this fight! gyth at the end felt soft though
`.go xyz 149.107000 -413.896000 110.472000 229 3.831770`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/7191
