### ISSUE TITLE
Tarantula - (442)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#88]
> Dont drop "crisp spider meat" which is required for the redridge quest "Redridge goulash
`.go xyz -9713.780000 -1809.480000 55.804400 0 4.618580`

> This feisty man attacked me whilst i was on a cart - this could potentially kill a low level player.
`.go xyz -9652.860000 -1474.150000 55.012800 0 1.493590`

**Comment by Bennylavaa** [comment]
they drop its just a lower % blizlike
