### ISSUE TITLE
Bile Spewer - (10416)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#880]
> Sometimes spawns excessive numbers of Bile Slimes and overwhelms parties with AOE damage. Beyond what others normally spawn in.
`.go xyz 4031.060000 -3462.300000 121.408000 329 0.552589`

> the amount of slimes spawned by these mobs is insane and bugged
`.go xyz 4036.400000 -3463.550000 121.385000 329 1.215630`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8297
