### ISSUE TITLE
Venom Belcher - (10417)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#881]
> Double Ramsein the Gorger spawn
`.go xyz 4003.680000 -3428.640000 120.507000 329 0.903494`

> too many poison
`.go xyz 4090.440000 -3393.330000 115.663000 329 2.002090`

> they spawn way too may bile slimes, like 5 at a time
`.go xyz 4097.230000 -3430.220000 116.978000 329 1.475610`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8297
