### ISSUE TITLE
Warchief Rend Blackhand - (10429)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#885]
> No loot from the boss chest
`.go xyz 153.979000 -428.101000 110.863000 229 5.309200`

> no loot after boss
`.go xyz 146.129000 -425.402000 110.472000 229 0.263784`

> No loot dropped
`.go xyz 156.514000 -427.239000 110.472000 229 4.713540`

> Glyth bugged and not coming down after rend dies
`.go xyz 179.014000 -431.975000 110.863000 229 4.986000`

> Chest did not contain loot
`.go xyz 149.028000 -428.818000 110.863000 229 3.776140`

> Stuck in combat.  Can't move forward in dungeon.
`.go xyz 186.318000 -421.851000 110.874000 229 4.927720`

> we kill warchief rend and dragon do not come to fight us
`.go xyz 153.120000 -432.185000 110.863000 229 6.251100`

> no loot in chest after boss
`.go xyz 140.665000 -420.234000 110.472000 229 0.109015`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8012
https://github.com/Project-Epoch/bugtracker/issues/5585
