### ISSUE TITLE
Young Goretusk - (454)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#89]
> all these piggies spam charge
`.go xyz -10115.700000 1683.640000 35.270900 0 1.533760`

> Charges over and over again dealing massive damage.
`.go xyz -10332.000000 1125.330000 36.468700 0 2.890580`

> These Boars permanent do the Charge attack with every single Attack
`.go xyz -10415.400000 1073.960000 48.870100 0 0.486491`

> Chain charging when in melee range for crazy dps lol ouch
`.go xyz -10466.900000 1143.390000 44.433300 0 5.901060`

> Keeps spamming the Charge ability ramping up DMG quite fast
`.go xyz -10449.600000 1184.760000 43.394500 0 0.613347`

> Keeps using his dash ability even though he is melee range next to you. Sometimes they bug and teleport behind you. And also they hit way too hard. I dont know if that last part is ok.
`.go xyz -10366.100000 1299.860000 39.737900 0 3.503460`

> They seem to uses their charge for every second attack even when they are already in melee
`.go xyz -10314.300000 1185.210000 39.524600 0 3.671210`

> spams charge constantly with seemingly no cooldown, and eve in melee range
`.go xyz -10420.000000 1082.540000 49.012000 0 5.530240`

> Spams charge resulting in enormous damage.
`.go xyz -9997.040000 1184.090000 42.367500 0 3.202530`

> When I was fighting the goretusk it was constantly using it's charge, dealing much more damage to me.
`.go xyz -10457.000000 1173.810000 45.354800 0 0.444286`

> These boars seem to repeatedly use rushing charge even when in melee range, is that intended?
`.go xyz -10163.400000 892.572000 37.173500 0 1.415520`

> Keeps on spamming his charge ability as well. Supposed to use before engaging in melee.
`.go xyz -10120.900000 1710.430000 33.458200 0 0.887641`

> spams "Rushing Charge
`.go xyz -10186.800000 912.687000 39.179000 0 0.650727`

> spams hoof every second
`.go xyz -9861.330000 1092.360000 34.239100 0 5.860170`

> The charge ability triggers constantly.
`.go xyz -10337.900000 1151.710000 35.924900 0 4.150240`

> He is doing too much damage due to constantly triggering one of his abillity.
`.go xyz -10330.500000 996.799000 35.645000 0 1.150970`

> Boar kept spamming its charge ability even when it was in close range.Was hitting very hard because of the extra damage that ability provides.
`.go xyz -9882.750000 1051.440000 34.220500 0 3.617340`

> Is this boar supposed to kill a 12 feral druid in bear form? just straight up...
`.go xyz -9884.260000 1056.250000 33.662400 0 4.915870`

> They charge always, almost insta killing you. Their charge is bugged.
`.go xyz -9837.690000 1310.630000 43.227600 0 3.085590`

> Charges everytime with no limit. Kills me so fast.
`.go xyz -10028.000000 1126.660000 41.752000 0 4.679030`

> Spams Rushing Charge like its other version in Westfall, far too quickly.
`.go xyz -10160.300000 898.739000 38.488700 0 1.034190`

> Keeps casting charge ability. Not sure of name
`.go xyz -10420.900000 1079.960000 49.548600 0 1.545570`

> When you kite any boar that has Charge, they spam it after everytime they hit you.
`.go xyz -10175.000000 910.622000 38.093200 0 3.320510`

> Boars constantly using abbilities without cooldown
`.go xyz -9853.710000 1086.950000 33.548500 0 3.824430`

> Frost nova causes it to keep casting it's charge attack leading to consecutive 66-99 damage hits. Three shotting squishy clothies
`.go xyz -10439.900000 1206.940000 48.257400 0 4.586210`

**Comment by zana244** [comment]
#75
