### ISSUE TITLE
Defias Rogue Wizard - (474)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#90]
> Doesn't use auto attack animation and doesn't use casting animation.

Combat log does not show damage or spell cast but im still losing health.
`.go xyz -9350.480000 521.935000 51.691600 0 0.960606`

> No attacking animation or effect. Are they hitting me with fireballs or something?
`.go xyz -9182.140000 -1002.530000 69.612600 0 5.895690`

**Comment by zana244** [comment]
Could not replicate on internal?
