### ISSUE TITLE
Urok Doomhowl - (10584)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#904]
> The speed of waves spawning during the event is way too fast
`.go xyz -24.063700 -376.552000 48.980800 229 3.015340`

> Mod that gives quest for that event boss do not come after we kill this boss
`.go xyz -28.735800 -371.800000 49.641700 229 3.843190`

> didnt despawn after a wipe
`.go xyz -14.752800 -397.274000 48.536900 229 2.310750`

**Comment by Shadownflame** [comment]
Related https://github.com/Project-Epoch/bugtracker/issues/5998
