### ISSUE TITLE
Urok Enforcer - (10601)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#905]
> Mages spawned way to fast
`.go xyz -25.929900 -400.874000 48.866100 229 0.835687`

> mobs spawning incredibly fast and hit like freight trains
`.go xyz -35.447000 -389.807000 48.764600 229 1.056690`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5998
