### ISSUE TITLE
Kobold Geomancer - (476)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#91]
> Doesnt chase after the player, if its out of LOS it just sits there combat bugging.
`.go xyz -9096.120000 -563.164000 62.435900 0 2.293370`

> no annimation when he casts a fireball
`.go xyz -9134.720000 -593.231000 57.621700 0 1.191220`

**Comment by zana244** [comment]
Could not replicate either of them on internal, his hands glow while casting fireball but obviously he does not have any other casting animation. Follows me fine if im out of LoS

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6937
