### ISSUE TITLE
Bile Slime - (10697)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#914]
> Don't despawn after each attempt on the Bile Spewer. have like 40 of them grouped up lmao.
`.go xyz 4084.660000 -3415.920000 116.085000 329 4.387970`

> Slimes stay after wipe also reallu hard if wipe
`.go xyz 4008.900000 -3454.230000 121.976000 329 0.919697`

> Instntly cast 3 og them and all of then got poison
`.go xyz 4092.960000 -3416.560000 116.302000 329 2.622170`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8297
