### ISSUE TITLE
Balnazzar - (10812)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#919]
> NO LOOT
`.go xyz 3420.210000 -3056.810000 136.498000 329 1.117170`

> No loot dropped
`.go xyz 3530.020000 -3059.370000 134.997000 329 5.802400`

> didnt give kill credit for achivment
`.go xyz 3446.340000 -3082.180000 135.002000 329 3.641070`

> no loot.   didnt reset HP when transforming
`.go xyz 3426.560000 -3060.400000 136.498000 329 1.937540`

> no loot
`.go xyz 3422.070000 -3061.120000 136.498000 329 3.411520`

> Dropped no loot.
`.go xyz 3428.780000 -3051.550000 136.498000 329 2.564760`

> Balnazzar doesn't drop loot
`.go xyz 3434.850000 -3055.360000 136.501000 329 2.079480`

> Still bugged. Does not heal during p2 and does not credit achievment or drop any loot.
`.go xyz 3422.440000 -3059.600000 136.498000 329 5.731790`

> Mob isn't lootable.
`.go xyz 3421.830000 -3049.490000 136.498000 329 0.039127`

> Drops not loot
`.go xyz 3427.930000 -3055.620000 136.498000 329 1.458750`

> no loot, and no achive
`.go xyz 3427.180000 -3062.210000 136.499000 329 3.309380`

> doesn't aoe stun after morph to dreadlord
doesn't reset hp after morphing
no loost after kill
`.go xyz 3422.990000 -3060.190000 136.498000 329 0.862236`

> has no loot
`.go xyz 3424.910000 -3062.210000 136.498000 329 0.971242`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/5380
