### ISSUE TITLE
Riverpaw Outrunner - (478)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#92]
> Hit multiples time, too fast ?
`.go xyz -9972.040000 588.787000 38.480300 0 4.294910`

**Comment by zana244** [comment]
Hmmm, it does seem like they do 1 or 2 extra attacks sometimes, however it seems to be intended since wowhead has thrash as ability.
https://www.wowhead.com/classic/npc=478/riverpaw-outrunner#abilities
