### ISSUE TITLE
Deathspeaker Selendre - (10827)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#922]
> This rare dropped only currency when killed.
`.go xyz 2470.250000 -3675.160000 178.188000 0 2.140240`

> This non-elite is WAY overtuned and drain lifes for like 900 a tick.
`.go xyz 2457.080000 -3696.720000 177.875000 0 4.588340`

> Incredible. This is the first old rare that doesn't have unique loot, that actually dropped a random green. Not sure if I got lucky, or if this is the only old world rare in the game that's not bugged.
`.go xyz 2687.210000 -5363.610000 157.605000 0 5.064360`

**Comment by Bennylavaa** [comment]
fixed
