### ISSUE TITLE
Ghost of the Past - (10940)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#930]
> These mobs dont go hostile instantly, allowing whomever looted to run off and leave the mobs for whomever comes later.
`.go xyz 1466.450000 -3703.500000 79.018400 0 5.520700`

> This enemy's Frost Armor buff is invisible
`.go xyz 1414.680000 -3664.570000 77.250200 0 1.831990`

> This mob is spawned before you enter the building at Darrowshire.
`.go xyz 1415.310000 -3676.360000 81.625500 0 2.174190`

> not despawn
`.go xyz 1474.570000 -3721.510000 80.514800 0 0.412176`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/2106
