### ISSUE TITLE
Captured Arko'narin - (11016)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#934]
> Quest work, nwm everything allright
`.go xyz 5003.400000 -438.335000 319.060000 1 4.854710`

> Mob does npt give quest at all. cannot start it after killing mobs around many times
`.go xyz 5004.130000 -440.723000 319.059000 1 0.018957`

> mob dont start quest line
`.go xyz 5004.160000 -441.155000 319.059000 1 0.167077`

**Comment by Bennylavaa** [comment]
you need to do the prequest first
