### ISSUE TITLE
Cauldron Lord Malvinious - (11077)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#939]
> 1 second respawn timer
`.go xyz 1846.510000 -1578.720000 58.923000 0 5.755690`

> Didn't drop a key for the cauldron
`.go xyz 1870.430000 -1558.820000 59.536800 0 5.248990`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330

**Comment by zana244** [comment]
He drops the key, but I'm not sure how he spawns. I always thought he was there, but it seems you need to kill the peeps around the cauldron to force him to spawn? Doesn't respawn instantly.
