### ISSUE TITLE
Lupos - (521)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#94]
> He dropped nothing, I really wish he dropped something
`.go xyz -10260.400000 55.646200 40.925400 0 4.555300`

> has no green loot
`.go xyz -10193.300000 -1075.180000 30.607700 0 1.723260`

> Lupos does shadow damage with auto attack (even as a tamed hunter pet). im pretty sure this was changed to physical at the end of vanilla
`.go xyz -10232.200000 73.398300 37.797500 0 1.569590`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8249

**Comment by Shadownflame** [comment]
Fixed.
