### ISSUE TITLE
Taragaman the Hungerer - (11520)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#948]
> humanoid instead of demon
`.go xyz -213.345000 156.297000 -21.329600 389 3.170440`

> this boss isn't classified as a demon.
`.go xyz -233.327000 154.595000 -18.862600 389 4.879450`

**Comment by zana244** [comment]
Same as bazzalan, wowhead has him as humanoid...
leaving as suggestion.
