### ISSUE TITLE
Mangy Wolf - (525)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#95]
> They spawn within the northeast section of Northshire Valley, roughly between the waterfall and the Defias mobs (I saw at least 2 spawns). To my knowledge these wolves have never spawned in Northshire Valley, only outside it. (Though with the introduction of the Swiftpaw quest, environmentally these wolves make sense here so perhaps this was an intentional change.)
`.go xyz -8850.110000 -422.758000 78.176000 0 5.207080`

> Instantly resets if I touch the river/water
`.go xyz -9460.970000 367.134000 49.120200 0 5.216710`

> Nearby Young Wolves do not aggro when this wolf is aggroed
`.go xyz -9276.450000 -26.425000 72.450600 0 1.886840`

> Stepping into the water while in combat with Mangy Wolf caused it to instantly reset/evade while in ranged combat
`.go xyz -9413.740000 171.566000 56.961700 0 1.950320`

**Comment by Bennylavaa** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8319
