### ISSUE TITLE
Grazle - (11554)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#950]
> 'Speak to Nafien' quest doesn't work since Nafien has been removed and Grazle relocated to where Nafien was.
`.go xyz 6816.640000 -2080.910000 623.839000 1 6.086280`

> Speak to Nafien" should this quest be removed? since Nafien should be where Grazle is, or if Nafien being moved somewhere else?
`.go xyz 6818.740000 -2085.370000 623.901000 1 0.185593`

> Gives the quest "Speak to Nafien" but it seems, on this server, Nafien is gone and Grazle stands in its place.
`.go xyz 6816.800000 -2080.010000 623.727000 1 0.591651`

> Grazle offers the quest Speak to Nafien, despite him not being in his position in southern felwood, and Grazle being up here instead of Nafien.
`.go xyz 6818.570000 -2083.180000 623.719000 1 5.554500`

> In that spot (Entrance to Timbermaw Hold from Felwood) must be furbolg Nafien, Grazzle should be south at the border with Ashenvale. Quest Speak to Nafien taken from Grazzle points to the same entrance, but there's no Nafien.
`.go xyz 6815.480000 -2080.540000 623.964000 1 0.136050`

> Gives a Quest to speak to Nafien while standing in his place.
`.go xyz 6819.300000 -2080.340000 623.420000 1 6.120480`

> Should be South of Felwood, and Nafien Should be in the North. Nafien is no where to be found.
`.go xyz 6818.820000 -2081.620000 623.563000 1 6.281780`

> quest deadwood of the north gives no xp
`.go xyz 6820.300000 -2083.100000 623.402000 1 0.292640`

> gives quest 'speak to nafien' in which place he stay, nafien do not exist
`.go xyz 6818.210000 -2083.160000 623.783000 1 5.763150`

**Comment by zana244** [comment]
Seems to have been fixed on internal.
