### ISSUE TITLE
Drysnap Crawler - (11562)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#953]
> This mob has both Frost Armor and Frost Shock to slow you down, even though it's a mob that's exclusively deep underwater. This causes cheap and unavoidable deaths by Drowning. Either only give it Frost Shock or Frost Armor, but not both.
`.go xyz -1961.870000 3306.930000 -1.653100 1 3.434110`

**Comment by Shadownflame** [comment]
https://youtu.be/SC6Rj-xXbmQ?t=2736 blizzlike
You're either supposed to pull them up to the surface or use underwater breathing buff.
