### ISSUE TITLE
Skeletal Fiend - (531)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#96]
> Does not have a death animation, just instantly transitions to a lying corpse.
`.go xyz -10494.100000 250.487000 31.474600 0 2.696150`

> death animation so fast it almost seems like they all teleport to a prone position
`.go xyz -10497.800000 219.049000 32.282800 0 0.446689`

**Comment by zana244** [comment]
Seems solved on internal. Can't reproduce.
