### ISSUE TITLE
Adon - (11706)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#963]
> Why is still here...ok, I accept he being here but change his eyes, he's a High Elf, not a Blood Elf.
`.go xyz 3360.640000 -4450.260000 127.642000 0 2.194560`

> BLOOD ELF SPOTTED
`.go xyz 3360.240000 -4445.760000 127.666000 0 5.813680`

**Comment by zana244** [comment]
I guess?
![image](https://github.com/Project-Epoch/bugtracker/assets/50482785/cf4b2006-716d-4a81-a465-641d4e2aea60)

**Comment by Shadownflame** [comment]
His eyes are blue, seems already fixed.
