### ISSUE TITLE
Putridus Shadowstalker - (11792)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#970]
> should be stealthed
`.go xyz 650.375000 -325.255000 -52.020500 349 4.611260`

> Not in stealth
`.go xyz 699.020000 -204.007000 -47.250700 349 5.690010`

**Comment by zana244** [comment]
in stealth on internal? although the visible range seems huge, but looking at some blizzlike videos kinda confirms it?
