### ISSUE TITLE
Rabine Saturna - (11801)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#972]
> talks about diremaul which doesnt exist
`.go xyz 7799.400000 -2575.610000 488.481000 1 3.039900`

**Comment by zana244** [comment]
DM exists, but indeed it will be changed a bit on epoch. Leaving issue open to keep track of NPC gossip,
think it starts the quest https://www.wowhead.com/classic/quest=5527/a-reliquary-of-purity (not on epoch)
