### ISSUE TITLE
Kaya Flathoof - (11856)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#974]
> FOR THE LOVE OF TALOS ADD MOVESPEED TO THOSE ESCORT FUKERS
`.go xyz -38.673700 -367.271000 -17.912200 1 4.197650`

**Comment by zana244** [comment]
haha

**Comment by Shadownflame** [comment]
Does this NPC suffer from the same bug as gilthares where she walks even when returning from combat?
