### ISSUE TITLE
Tortured Druid - (12178)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#986]
> RESPAWNS ARE TOO FAST. WITHIN A MINUTE
`.go xyz -7080.830000 304.339000 16.001100 1 0.875519`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/8330

**Comment by Bennylavaa** [comment]
5 min respawn time which is normal but these npcs are elite now so maybe that should be altered? Alternatively youll be here with a group so it should be fine. I am going to close the as a duplicate because its most likely is due to dynamic respawns.
