### ISSUE TITLE
Princess Theradras - (12201)

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/bugtracker#987]
> no loot
`.go xyz 10.403800 53.385400 -125.116000 349 0.934584`

> dropped no item loot, only deeprock salt
`.go xyz 53.761900 61.986300 -124.047000 349 3.474440`

> didnt drop loot a second run...
`.go xyz 37.792200 35.272900 -124.985000 349 5.619680`

> Princess Theradras dropped no loot
`.go xyz 10.832300 52.698100 -125.108000 349 1.481780`

> no loot twice in a row
`.go xyz 53.931400 52.506500 -124.266000 349 0.016365`

> F U NO LOOT D:
`.go xyz 13.077900 53.294700 -125.327000 349 0.663722`

> Didn't drop gear
`.go xyz 51.290900 129.399000 -131.156000 349 3.289310`

> Princess dropped no loot in a normal 5 man party
`.go xyz 51.888300 45.902000 -124.433000 349 1.280420`

> No treasure dropped from the boss
`.go xyz 44.224300 73.969500 -123.724000 349 1.607900`

> Dropped no loot.
`.go xyz 35.503000 42.754200 -125.258000 349 3.040300`

> no loot sadge
`.go xyz 48.706800 67.478700 -124.389000 349 5.591810`

> She did not drop any loot.
`.go xyz 54.128800 129.082000 -131.156000 349 1.208050`

**Comment by Shadownflame** [comment]
https://github.com/Project-Epoch/bugtracker/issues/6833
